### ISSUE TITLE
"An unknown exception has occured while uploading" is returned when repo contains an invalid routes.json file

### ISSUE THREAD

**Issue by brettneese** [Azure/static-web-apps#100]
Okay, so I did a silly. I committed an empty `routes.json,` in my assets directory somehow. Yes, I know. That went predictably bad, and I received far too many failed builds with a cryptic message:

```
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
An unknown exception has occured while uploading
```
I eventually found the problem, fixed the error, and now my builds work! But it'd be nice to catch this issue and provide better feedback. 

I replicated it [here](https://github.com/brettneese/my-first-static-app/actions/runs/174222205) (with an empty routes.json) and [here](https://github.com/brettneese/my-first-static-app/actions/runs/174222771) (with an invalid routes.json). 

Also this is super pedantic, and not sure if I should create a separate issue, but "occured" is misspelled in this error message. I'm not sure exactly where this code is (or even if it's public) or I'd send in a PR to fix it. ;-)

**Comment by miwebst** [comment]
Thanks for catching this :) we will get both problems fixed soon!

**Comment by miwebst** [comment]
Hi @brettneese, both of these should be fixed now. Please let us know if you run into further issues
