### ISSUE TITLE
Redirect containing @ symbol is escaped

### ISSUE THREAD

**Issue by matkoch** [Azure/static-web-apps#1007]
**Describe the bug**

Redirects containing a `@` symbol are converted to `%40`.

Add an entry in `staticwebapps.config.json`:

```
{
  "routes": [
    {
      "route": "/mastodon",
      "redirect": "https://dotnet.social/@nuke",
      "statusCode": 302
    }
  ]
}
```

**Expected behavior**

No escaping is applied to the provided URL.

**Additional context**

Mastodon doesn't accept the escaped URL.

**Comment by matkoch** [comment]
I could be argued, but on the other hand I expect the redirect to point to the URL I specified, and not something else

**Comment by zunderscore** [comment]
While I agree that other platforms could handle URLs better, I also agree that the service should not be URL encoding what we enter for redirect values without us explicitly telling it to. In other words, our redirect URLs should function exactly as we have written them.

Even if this one piece/instance of software were to change and handle encoding better, what about others? As we find more and more sites that also don't automatically decode URL paths, would we be expected to speak to the owner of every single one of them? That seems a little unrealistic when this could potentially be resolved from this side, I think.

**Comment by matkoch** [comment]
@annikel  Reason?
