### ISSUE TITLE
Authentication Loop With Custom Domain Configured

### ISSUE THREAD

**Issue by jtracey93** [Azure/static-web-apps#101]
Hi, 

So I think I may have found a bug. My static web app has Azure AD Auth enabled and this is enforced via a routes.json file. All works fine when using the default URL/Domain Name. However when I configure a custom domain for my static web app, it gets stuck in a redirection loop.

After one loop, if I stop and access the custom domain again, I gain access as expected. It's like the reply URL doesn't head back to the custom domain name. But once I've been through one Azure AD auth loop I have got the required token and I gain access to my site.

Happy to repro via teams (MSFT FTE - CSA in the UK)

Thanks 

Jack

**Comment by marcpiechura** [comment]
@jtracey93 I've the same issue, did you found a solution in the meantime? 

Thanks.

**Comment by jtracey93** [comment]
Afraid not, yet! The PG team have asked for some details though from me which I have provided so I'd think they are looking into it.

**Comment by marcpiechura** [comment]
FYI it works now for me, I‘ve change my routes to require global authorization via route /* and I’m now using a custom role instead of the default „authenticated“, but I‘m not sure if either of those fixed it or the Azure Team fixed it.

**Comment by miwebst** [comment]
We rolled out a fix for this, let us know if you run into any further problems!

**Comment by jtracey93** [comment]
Thanks just got around to testing and all working! 👍
