### ISSUE TITLE
/.auth/login/aadb2c endpoint causes a browser error

### ISSUE THREAD

**Issue by noontz** [Azure/static-web-apps#1010]
Trying to log in with B2C on the /.auth/login/aadb2c endpoint results in a browser error:

**_Refused to execute script from 'https://\<domain>.[azurestaticapps.net/.auth/login/aadb2c](http://azurestaticapps.net/.auth/login/aadb2c)' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled._**

The SWA is a vanilla SPA (with managed API) on a standard Sku

**To Reproduce**
1. Follow the [Configure authentication in an Azure Static Web App by using Azure AD B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-azure-static-app) documentation
2. Follow [step 4](https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-azure-static-app#step-4-check-the-azure-static-web-app)

**Expected behavior**
A B2B user flow experience and authenticated redirect to the SWA

**Device info (if applicable):**
 - Browser [chrome, edge]
 - Version [newest]

**Additional context**
Here is my staticwebapp.config.json:

- The header entries is a (failed) attempt to fix the issue
- I tried to remove the header entries and navigationFallback, but that resulted in a 404

```{
  "routes": [
    {
      "route": "/.auth/login/aadb2c",
      "allowedRoles": [
        "authenticated",
        "anonymous"
      ],
      "headers": {
        "Content-Type": "application/javascript"
      }
    },
    {
      "route": "/*",
      "allowedRoles": [
        "authenticated"
      ]
    }
  ],
  "globalHeaders": {
    "Content-Type": "application/javascript"
  },
  "responseOverrides": {
    "401": {
      "statusCode": 302,
      "redirect": "/.auth/login/aadb2c"
    }
  },
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": [
      "/content/*.{png,jpg,gif}"
    ]
  },
  "auth": {
    "identityProviders": {
      "customOpenIdConnectProviders": {
        "aadb2c": {
          "registration": {
            "clientIdSettingName": "AADB2C_PROVIDER_CLIENT_ID",
            "clientCredential": {
              "clientSecretSettingName": "AADB2C_PROVIDER_CLIENT_SECRET"
            },
            "openIdConnectConfiguration": {
              "wellKnownOpenIdConfiguration": "https://<domain>.onmicrosoft.com.b2clogin.com/<domain>.onmicrosoft.com.onmicrosoft.com/B2C_1_SignIn/v2.0/.well-known/openid-configuration"
            }
          },
          "login": {
            "nameClaimType": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
            "scopes": [],
            "loginParameterNames": []
          }
        }
      }
    }
  }
}
```

**Comment by rodyvansambeek** [comment]
I think you should remove the "route": "/.auth/login/aadb2c". This route is available from the Static Web Apps environment. Try to delete the "globalHeaders" as well. That is not neccessary for the authentication mechanism.

**Comment by noontz** [comment]
> I think you should remove the "route": "/.auth/login/aadb2c". This route is available from the Static Web Apps environment. 

The reason I have the route in the first place is to avoid the:

**This page isn’t working
delightful-ground-0e6832b03.2.azurestaticapps.net redirected you too many times.**

I assume the SPA redirect to index.html i causing this, hence the appended route

> Try to delete the "globalHeaders" as well. That is not neccessary for the authentication mechanism.
As I write the globalHeaders where appended to try and solve the issue. Removing them has no effect on the issue

**Comment by rodyvansambeek** [comment]
Ok, let me share you a working staticwebapp.config.json which I use in a project and works fine, maybe you can try to copy it and see what fixes it?

```json
{
    "trailingSlash": "auto",
    "platform": {
        "apiRuntime": "dotnet-isolated:7.0"
    },
    "auth": {
        "identityProviders": {
            "customOpenIdConnectProviders": {
                "aadb2c": {
                    "registration": {
                        "clientIdSettingName": "AADB2C_PROVIDER_CLIENT_ID",
                        "clientCredential": {
                            "clientSecretSettingName": "AADB2C_PROVIDER_CLIENT_SECRET"
                        },
                      "openIdConnectConfiguration": {
                        "wellKnownOpenIdConfiguration": "https://customer.b2clogin.com/customer.onmicrosoft.com/B2C_1_si/v2.0/.well-known/openid-configuration"
                      }
                    },
                    "login": {
                        "nameClaimType": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
                        "scopes": [],
                        "loginParameterNames": []
                    }
                }
            }
        }
    },
    "routes": [
        {
            "route": "/*",
            "allowedRoles": [
                "authenticated"
            ]
        }
    ],
    "responseOverrides": {
        "401": {
            "statusCode": 302,
            "redirect": "/.auth/login/aadb2c"
        }
    },
    "navigationFallback": {
        "rewrite": "index.html",
        "exclude": [
            "/images/*.{svg,png,jpg,gif,webp}",
            "/css/*"
        ]
    }
}
```

**Comment by noontz** [comment]
Using an exact copy causes this error in my pipeline:

**Oryx has found build steps, but identified unsupported platform versions. Failing build.**

Omitting the platform property leaves me with the same redirect error as before

**Comment by mishapos** [comment]
@noontz From what I see, your staticwebapp.config.json still has the defaultHeaders for `content-type` and route rule for `route": "/.auth/login/aadb2c"`. Could you please remove these from your staticwebapp.config.json and try deploying again? 

For the supported platform versions for your API please see our documentation: https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#platform

**Comment by noontz** [comment]
@mishapos 

- Please read the initial issue description: _The header entries is a (failed) attempt to fix the issue_. Removing them makes no difference?
- Removing the route rule for /.auth/login/aadb2c will result in the before mentioned redirect error (to many redirects) which, I assume, would be the expected behaviour for a SPA?
- The deployment issue mentioned is related to the staticwebapp.config.json suggested by Rody. I have no problem with the API version?

**Comment by mishapos** [comment]
Hi @noontz I see also that your `wellKnownOpenIdConfiguration` may be a bit misconfigured. It should be formatted as `https://<TENANT_NAME>.b2clogin.com/<TENANT_NAME>.onmicrosoft.com...` but yours is `https://<domain>.onmicrosoft.com.b2clogin.com/<domain>.onmicrosoft.com.onmicrosoft.com/`. Could you please change it to remove the two extra `.onmicrosoft.com` and try deploying again?

**Comment by noontz** [comment]
@mishapos
The  `wellKnownOpenIdConfiguration` was definitely misconfigured! I can now reach the login redirect correctly. Thanks. I am now redirected to  https://´<domain´>/.auth/complete and recieve a 403 _We need an email address or a handle from your login service. To use this login, please update your account with the missing info_   But  this is a different issue. Thank you for spotting this. I will close this issue.
