### ISSUE TITLE
Support for Route Parameters in staticwebapp.config.json, similar to proxies.json

### ISSUE THREAD

**Issue by jmzagorski** [Azure/static-web-apps#1014]
**Is your feature request related to a problem? Please describe.**
We are using managed functions and were recently upgraded to version 4 automatically, which is great. Our issue was that we had a proxies.json file routing API requests from the static webapp to our azure API gateway. v4 of Azure Functions does not use the proxies.json file unless you set `AzureWebJobsFeatureFlags = EnableProxies`, but it isn't clear if you can set this in any of the configuration files such as the staticwebapp.config.json or the host.json because you cannot set it in the azure static webapp configuration in the portal. Based on that, it seems that you cannot use v4 Azure Functions with an azure webapp that uses proxies.json.

**Describe the solution you'd like**
Route parameters are allowed in the staticwebapp.config.json, for example (**note** i am not sure if it would be rewrite or redirect in the below example)

```json
{
    "routes": [
        {
            "route": "/api/{id}/entries",
            "methods": ["POST"],
            "rewrite": "%CONNECTIONSTRINGS__MAIN%/{id}/entries",
        }
    ]
}
```

**Describe alternatives you've considered**
We tried the example above, both with redirect and rewrite, and it did not work. We were trying to migrate the proxies.json file below to the staticwebapp.config.json

```json
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "main": {
            "matchCondition": {
                "methods": ["POST"],
                "route": "/api/{id}/entries"
            },
            "backendUri": "%CONNECTIONSTRINGS__MAIN%/{id}/entries"
        }
    }
}
```

The other alternative is to code the proxy logic in a managed function. However, that seems like a lot of boiler plate code that a few lines of configuration can handle based on the proxies.json file, which is why we went with this solution when setting up the app.

**Additional context**
The only workaround was to set the below property in our staticwebapp.config.json so that we would be locked into v3 of azure functions, which would then read our proxies.json file

```json
    "platform": {
        "apiRuntime": "node:12"
    },
```

related docs
https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net6-in-proc%2Cazure-cli%2Cwindows&pivots=programming-language-typescript

https://learn.microsoft.com/en-us/azure/azure-functions/legacy-proxies#re-enable-proxies-in-functions-v4x

**Comment by Bionic711** [comment]
Would this also include the ability to proxy paths to a different location? I am currently sitting at 450MB on the Standard Hosting plan and am seeking a way to offload my images (about 425MB of that are the images) to an Azure Storage Account.

Even being able to route a wildcarded path, such as: 

`
{
    "routes": [
        {
            "route": "/images/*",
            "methods": ["GET"],
            "rewrite": "%STORAGEACCOUNT_URL%",
        }
    ]
}
`
Is this similar to what you are trying to achieve with this request?

**Comment by jmzagorski** [comment]
@Bionic711 our use case is forwarding the request to our Azure API gateway, and the ability to add additional headers, such as API Gateway subscription key and Authorization API key.

**Comment by Reshmi-Sriram** [comment]
Hey all,
In order to enable proxies, you can add `SWA_ENABLE_PROXIES_MANAGED_FUNCTIONS` to `true` in your application settings,
We are working on adding this information to the documentation soon.

cc// @craigshoemaker

**Comment by jmzagorski** [comment]
@Reshmi-Sriram that is great. Does that mean we can remove the `"apiRuntime": "node:12"` in our staticwebapp.config.json file, which was the workaround.

**Comment by Reshmi-Sriram** [comment]
> @Reshmi-Sriram that is great. Does that mean we can remove the `"apiRuntime": "node:12"` in our staticwebapp.config.json file, which was the workaround.

Yes, that is correct. You can now use proxy support in v4 itself and thus use the newer node versions. Could you let us know if it works fine for you? Thanks!

**Comment by jmzagorski** [comment]
Hi @Reshmi-Sriram sorry for the delay. I had a weird experience adding this to our configuration. I added it to the configuration, and it saved successfully. However, when I try to add another variable such as `foo` = `bar`, I get a generic error messge 

> Updating application settings
> Failed to update application settings: An error has occurred.

**Comment by jmzagorski** [comment]
Sorry for the delayed response. I added that env variable to a new staticwebapp and it worked so I am not sure what the last error was about. I have not removed the `apiRunTime` configuration yet. I am trying to find some time to do that and then monitor the logs with app insights to ensure it works. I will plan to do this next week so we can close this issue.  Thanks for the support and waiting on me!

**Comment by jmzagorski** [comment]
Everything has been looking good. Thanks for the support!
