### ISSUE TITLE
Feature to deploy static Websites from Local Machine to Azure Static Web App

### ISSUE THREAD

**Issue by shaijut** [Azure/static-web-apps#102]
**Important Feature Request:**

**Current Functionality:** In Preview `Azure Static Web App` pulls files from `Github` repository and hosts the files in `Azure Static Web App`.

**Required Feature:** Provide a Option to deploy or upload static sites from Local Machine via `FTP`  or Visual  Studio Publish / VS Code to `Azure Static Web App`

**Comment by miwebst** [comment]
https://github.com/Azure/static-web-apps/issues/96

**Comment by anthonychu** [comment]
Item tracking VS Code https://github.com/microsoft/vscode-azurestaticwebapps/issues/265

Azure CLI #7

**Comment by RossMurr4y** [comment]
For those looking for a workaround in the meantime, I've documented a pretty straightforward approach here: https://github.com/Azure/static-web-apps/issues/96#issuecomment-841072249

**Comment by simonaco** [comment]
closing as duplicate
