### ISSUE TITLE
CORS issue with azurewebsites.net and azurestaticapps.net

### ISSUE THREAD

**Issue by jonnekleijer** [Azure/static-web-apps#1020]
The swagger ui endpoint does not load by default, because it cannot access the swagger.json when using azure functions as an API and use `Microsoft.Azure.WebJobs.Extensions.OpenApi`.

I believe [this](https://github.com/Azure/azure-functions-openapi-extension/issues/131) is a similar issue only reported at the OpenApi repo. 

**To Reproduce**
1. Create azure static web application.
2. Add api project using azure functions.
3. Add Microsoft.Azure.WebJobs.Extensions.OpenApi extension to introduce swagger endpoints (e.g. `api/swagger/ui` and `api/swagger.json`).

**Expected behavior**
Load ui based on swagger.json hosted on the azurestaticapps.net endpoint. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8200351/208997298-10ec4d08-e3ca-4c6f-bc44-aa409924589c.png)

**Additional context**
What it should be &rarr; https://abc.azurestaticapps.net/api/swagger.json
What it refers to &rarr; https://xyz.azurewebsites.net/api/swagger.json

When editting the url manually and refer to the correct json, it works nicely. 
It's hard to reproduce locally, as all the functions are hosted on localhost:7071.

**Comment by mishapos** [comment]
@jonnekleijer Could you please try adding your SWA domain as a custom base URL to the function settings as described here? https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi.md#configure-custom-base-urls

**Comment by jonnekleijer** [comment]
@mishapos I added it as a custom base urls for the server and it worked fine.
Thank you for your support!

**Comment by zawasp** [comment]
I tried with both "/api" and "abc.azurestaticapps.net/api" in the SWA configuration in Azure Portal. It now shows an empty page. Locally it works just fine, as well as if I set the correct url for the swagger.json in the Explore field. Any ideas @mishapos ?

**Comment by simonjstanford** [comment]
A newbie point For the next person that gets stuck on this - you need to override the DefaultOpenApiConfigurationOptions class in your project for reading the OpenApi__HostNames configuration settings to work. I had followed a guide and implemented the IOpenApiConfigurationOptions directly and was stuck.

See e.g. https://stackoverflow.com/questions/69391352/how-can-i-configure-the-swagger-ui-page-for-azure-functions-v3

**Comment by ScotteYx** [comment]
> @jonnekleijer Could you please try adding your SWA domain (abc.azurestaticapps.net/api) as a custom base URL to the function settings as described here? https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi.md#configure-custom-base-urls

Just saying a big thank you - added my domain url to my static web app configuration as "OpenApi__HostNames" and it got rid of the CORS error.
