### ISSUE TITLE
Failed to deploy the azure function

### ISSUE THREAD

**Issue by H-Ashrafi** [Azure/static-web-apps#1022]
I have a static website built with Hugo + TailwindCss hosted on a free plan on Azure Static Site. However I cannot deploy it to Azure when I include an `api` folder. The error message in Oryx logs is `Failed to deploy the azure function`. (I've attached the logs.txt)
**How I have set-up the repo:**
- Site uses Hugo and Tailwind 
- App build command in the workflows file is as follows (file is attached) 
```
app_build_command:  |
            npm install postcss postcss-cli tailwindcss
            npm install -D @tailwindcss/aspect-ratio
            npm install -D @tailwindcss/forms
            npm install -D @tailwindcss/typography
            npx tailwindcss init
            npx tailwindcss -i ./assets/styles/input.css -o ./assets/styles/main.css --minify
            hugo --minify 
```
- It's a private repo with a submodule for the theme
- the Api is written in `dotnet:6.0`
- I have added the `"platform": {"apiRuntime": "dotnet:6.0"}` in the `staticwebapp.config.json` (file attached.)
- The api works with `SWA cli` on my local machine. 
- The api works when I deploy it as an Azure function and link it to the static website as a `Bring your Own` function. For which I have to use a paid subscription. 💰 

[staticwebapp.config.json.txt](https://github.com/Azure/static-web-apps/files/10299852/staticwebapp.config.json.txt)
[logs.txt](https://github.com/Azure/static-web-apps/files/10299829/error.txt)
[Github_Action_yaml.txt](https://github.com/Azure/static-web-apps/files/10299848/Github_Action_yaml.txt)

**Comment by mishapos** [comment]
@H-Ashrafi Do you have any app settings in your api definition or your Static Web App that begin with `FUNCTION_` or `WEBSITE_` ? These are not allowed with the free, managed Azure Functions with Static Web Apps per these docs: https://learn.microsoft.com/en-us/azure/static-web-apps/apis-functions#constraints but are allowed when you link a Bring-Your-Own Function.

**Comment by H-Ashrafi** [comment]
Thanks @mishapos **that solved the problem. ** 
There were two env variables that Azure had created automatically when I built the static web app service. It'd be a massive time saver if the portal would delete those when an api got uploaded.
