### ISSUE TITLE
Failed to contact content server, stopping...

### ISSUE THREAD

**Issue by JohnYii** [Azure/static-web-apps#1023]
Failed to contact content server, stopping...
An unknown exception has occurred

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
##[error]Error: The process '/usr/bin/bash' failed with exit code 1
Finishing: AzureStaticWebApp

**Comment by craigomatic** [comment]
I see the same issue (as mentioned in #745). Was hoping I could get around this by using the [SWA CLI](https://azure.github.io/static-web-apps-cli/docs/cli/swa-deploy/), however I get the same error.

**Comment by okotta1** [comment]
Same issue. 
I tried to deploy locally using static web app cli, but it still keeps failing.

**Comment by ApurvGpt** [comment]
I am also facing this issue for last couple of days.

**Comment by jvmlet** [comment]
Same problem, please address ASAP

**Comment by hojovi** [comment]
Same here

**Comment by sjmcculloch** [comment]
Same here. I haven't changed anything on my side.

**Comment by tim-anderson-linksbridge** [comment]
Same here.

**Comment by trudyhood** [comment]
Same issue:
https://github.com/vpnhood/VpnHood.AccessServer.UI/actions/runs/3790125965/jobs/6445215368

**Comment by adam-javelin** [comment]
Same issue here.

**Comment by michaelpear** [comment]
Also experiencing same issue. Now December 28, 2022.

**Comment by sgollapudi77** [comment]
Hey @JohnYii , can you provide a little more context here, like the default hostname of the app, the region where it is deployed and all.

**Comment by okotta1** [comment]
same issue

**Comment by sgollapudi77** [comment]
Can someone provide more details like default hostname of the app, the region where it is deployed so that we can investigate this issue more thoroughly. TIA :)

**Comment by trudyhood** [comment]
@sgollapudi77 
 default hostname: mango-stone-052bcc91e.azurestaticapps.net
region: West US 2

**Comment by mishapos** [comment]
Hi, all, we've figured out the issue and fixed it. Could you please try running a deployment again and verifying that it goes through now?

**Comment by michaelpear** [comment]
Confirm that the issue is fixed in my pipeline.

Can you provide information on what the problem was? Also, is there any workaround should this occur in the future? This was a problem for several days and I'm sure many of us spent time investigating the issue and whether we had somehow introduced it.

**Comment by jvmlet** [comment]
@michaelpear totally  agree, such kind of outages of hosting services should be properly communicated, businesses are loosing $$$ after all....

**Comment by JohnYii** [comment]
Without changing anything on our side, publishing to AzureStatiWebApp and starts working again on December 28th 4 am pacific time. So the outage (unable to publish to Azure static web app) last for around 4 days (24th to 28th).

Thank you @mishapos for resolving everyone else jumping on reporting their issue to help escalate this. I am closing this issue

**Comment by cmydur** [comment]
same issues here for my deployment , DeploymentId: 9b7f6cf4-3e71-48ef-8ada-fcb2021f6b49
