### ISSUE TITLE
Azure Static Web Apps - failed to find content server error

### ISSUE THREAD

**Issue by tim-anderson-linksbridge** [Azure/static-web-apps#1026]
My azure static web app pipeline is failing as of today (we haven't done a build since before holiday) with the error:

Failed to contact content server, stopping...
An unknown exception has occurred

in the build and deploy step. 

I've tried a couple of re-tries and it's the same every time.

**Comment by adam-javelin** [comment]
![image](https://user-images.githubusercontent.com/79462674/209735974-f9df5bcd-3bd9-443f-a65f-c069feb19151.png)
Having the same issue.

**Comment by sgollapudi77** [comment]
Hey @adam-javelin , @tim-anderson-linksbridge we're tracking this issue at #1023 . Closing this as duplicate now. Please feel free to add more details in the parent issue.
