### ISSUE TITLE
Gatsby build fails 

### ISSUE THREAD

**Issue by nikita-seliverstov** [Azure/static-web-apps#103]
Hi, 

I tried to build this repo: https://github.com/Arvutiamblik/amblik.
netlify builds site well but using static web apps it fails. The log does't give usefull data

**Comment by miwebst** [comment]
This repository is private, can you provide details on what you see in the Github Action logs for the failed workflow run? 

Also not sure if you have seen this tutorial: https://docs.microsoft.com/en-us/azure/static-web-apps/publish-gatsby  - but this may help with configuration issues.

The other potential issue could be that a dependency is missing on our image and thus the builds fails.

**Comment by nikita-seliverstov** [comment]
I made repository public

**Comment by miwebst** [comment]
Thanks! @kichalla it looks like Oryx is failing to do detection: https://github.com/Arvutiamblik/amblik/runs/907088059?check_suite_focus=true can you take a look?

**Comment by miwebst** [comment]
Hi @nikita-seliverstov we have updated our version of Oryx, can you see if you are still running into this error?
