### ISSUE TITLE
Azure Static App giving intermittently 503

### ISSUE THREAD

**Issue by amitcogni** [Azure/static-web-apps#1032]
As we are using Azure Static Web App for hosting our react application. However since last few hours we are getting error -Failed to load resource: the server responded with a status of 503 () net::ERR_HTTP_RESPONSE_CODE_FAILURE.

In that we are using standard plan without any in build function api... and application is working perfectly till yesterday. 

Please suggest is there any issue Azure service or we are missing something.

**Comment by yeonjulee1005** [comment]
our project too!🤔
Our project is also based on Nuxt3.
All three projects distributed as static web apps have intermittent connection errors.

please reply:)

**Comment by jmsfilipe** [comment]
My guess is that it was related to this incident: https://app.azure.com/h/MM3V-HS8/2b366b

**Comment by amitcogni** [comment]
> https://app.azure.com/h/MM3V-HS8/2b366b

Thanks jmsfilipe

If possible request you to please share details around that.. Actually not able to see within my subscription.

Thanks in Advance.

**Comment by Reshmi-Sriram** [comment]
Marking this closed.

**Comment by bonanzaeducation** [comment]
Needs to be re-opened. We are experiencing the same issues today!

**Comment by hermantretteteig** [comment]
Experiencing the same issue today
