### ISSUE TITLE
Oryx Pipeline Timeout - deploying Next.js

### ISSUE THREAD

**Issue by camila-akqa** [Azure/static-web-apps#1035]
**Describe the bug**

Hope you can help us, we are trying to deploy a next.js solution to azure static web apps but our Azure pipelines stopped working since yesterday with an upload timeout.

![image](https://user-images.githubusercontent.com/67367750/211983175-2efd6ad7-5ee1-45a5-8b2d-b7ee6f6d9969.png)

 Our solution is building fine and as per logs it seems to have Finished Upload and failed Polling on deployment. 

I verified creating a new Static Web App and the results are similar, some times it works with no issue, and sometimes it fails. In azure I see that the status of the environment is "Uploading" and then after sometime (weight long time after the build failed) it changes to ready. 

![image](https://user-images.githubusercontent.com/67367750/211976239-b9793966-245e-44b0-8221-2b6b41b5e064.png)

This is an extract of the yml step that is failing:
![image](https://user-images.githubusercontent.com/67367750/211993599-2e1da07b-46ff-4cab-b4d0-24c2cad38242.png)

**Expected behavior**
The build files to upload to the static app every time the build is triggered .

**Comment by sachin-rathor** [comment]
Hi @camila-akqa,

Thanks for reaching out!

Could you share us the repo detail, Action runs, .yml file, default Hostname to investigate more on this?

**Comment by camila-akqa** [comment]
Hi Sachin

Thanks for your promptly response, I am attaching the yml file. I can't provide you access to the repo as it is private but I could try to share any further details required privately, what's your best contact?

Regards


--
Technical Lead  |  +61 3 9684 6427  |  AKQA, Level 11 380 St Kilda Road, Melbourne, 3004

**Comment by sachin-rathor** [comment]
You can send details on sachinrathor@microsoft.com

**Comment by camila-akqa** [comment]
Hi @sachin-rathor I am wondering if you have had a change to look into this further. Today again this started to fail during upload without much details:

![image](https://user-images.githubusercontent.com/67367750/213093773-1fb75099-cb7e-450a-b868-3b230b8bc459.png)

The difference this time is that it actually never get uploaded in Azure Static Web apps

![image](https://user-images.githubusercontent.com/67367750/213094722-168744f9-4666-47f2-b26e-6cd454a35a7b.png)

Please let me know if there is anything else I can do.

Thanks

**Comment by camila-akqa** [comment]
Hi @sachin-rathor last failed DeploymentId: b88058b8-3858-43a1-b44f-ef114ac94c05 , please let me know if you also want the full log :) thanks again for looking into this

**Comment by sachin-rathor** [comment]
Hi @camila-akqa,

On looking into your issue, we found that there was an error related to function host. Right now we could see that your app has been successfully deployed many times after the last failed deployment.

Did you make any code changes on your side after the last failure deployment? If yes, then it might be happening because of your code changes.

If not, would it be possible for you to share your repo with us to do further investigation.
Thanks!

**Comment by camila-akqa** [comment]
Hi @sachin-rathor 

I hope you can keep this issue open, I've just sent you an email with further details.

Thanks

**Comment by awariis** [comment]
Hello, I'm facing the same issue on nextjs 14.

**Comment by thomasgauvin** [comment]
I'm closing this issue as it was opened before our improved Next.js support. Refer to the improved Next.js support announcement https://github.com/Azure/static-web-apps/discussions/1428 and https://github.com/Azure/static-web-apps/issues/1427 for updated threads.
