### ISSUE TITLE
Build fails when duplicate (case-insensitive) file paths are found

### ISSUE THREAD

**Issue by Paruyrik** [Azure/static-web-apps#104]
Case-sensitive file paths are currently not supported. The conflicting paths detected are 'public/blog/README/index.html' and 'public/blog/Readme/index.html'.

**Comment by miwebst** [comment]
Edited the title a little so that others might find it easier. This is currently a limitation we are working on. We will update this issue when we have more information!

**Comment by timothyhalley** [comment]
Same issue here... --> Build / Deploy Log: (circa line 200)

Finished building function app with Oryx
Case-sensitive file paths are currently not supported. The conflicting paths detected are 'dist/tag/Development/index.html' and 'dist/tag/development/index.html'.

This is a simple GRIDSOME app build using AZ static web app and GIT actions to build for CI/CD with custom domain (no slots or anything - basic).

**Comment by miwebst** [comment]
We have a fix coming for this soon, will followup once it is out :)

**Comment by miwebst** [comment]
Do you mind retrying? This should be fixed now!
