### ISSUE TITLE
authentication with facebook not working

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#1040]
[https://www.streamingdiscovery.com/.auth/login/facebook](https://www.streamingdiscovery.com/.auth/login/facebook)

I've seen that there were several people complaining about the same error. I'm here just to add one more. all other authentication methods are working normally. 

note: the same error happened about a year ago and has been fixed.

**Comment by Bionic711** [comment]
I was just setting up facebook login for my static web app as well. I login to facebook to return to my site's /.auth/complete and the 403 page is displayed. Nothing in the /.auth/me page either. I was thinking it was just me but it appears we are not the only ones having these issues with facebook login. Twitter, AAD, and Google logins are working normally.

**Comment by Reshmi-Sriram** [comment]
Issue being tracked in #695 and #967 
Closing this one, feel free to comment in the others!
