### ISSUE TITLE
Support for NextJS Standalone output for static web app deployment

### ISSUE THREAD

**Issue by salikansari6** [Azure/static-web-apps#1042]
I was wondering if there is a provision for using the standalone output feature. Ref: [Output File Tracing
](https://nextjs.org/docs/advanced-features/output-file-tracing). As the node_modules generated by Next.js is of a hefty size and the static web apps deployment gives error that app size was too large. With help of standalone feature one can decrease this size down significantly and use the standalone folder independently as Next.js app. Kindly revert back on this

**Comment by Reshmi-Sriram** [comment]
Hi @salikansari6,
Static Web apps now supports `standalone` feature in Next.js. You can read more about the latest updates [here](https://github.com/Azure/static-web-apps/discussions/1066). Do let us know if this helps! Thanks!

**Comment by salikansari6** [comment]
Thank you so much for this! Will surely try this out

**Comment by Reshmi-Sriram** [comment]
Closing this issue. Feel free to continue the discussion in the common [threads](https://github.com/Azure/static-web-apps/discussions/1066) for same!
