### ISSUE TITLE
Can we make an Azure Static Web App using Blazor?

### ISSUE THREAD

**Issue by AshirwadSatapathi** [Azure/static-web-apps#105]
As static web apps allows to make web apps with so many javascript libraries, does it support Blazor under the hood or it's not supported as of yet?

**Comment by miwebst** [comment]
We are working on this support! Today you can use client-side Blazor support as it compiles into static assets.

**Comment by aaronpowell** [comment]
Here's an article on how to do it today by modifying the Actions: https://www.timheuer.com/blog/hosting-blazor-in-azure-static-web-apps/

**Comment by AshirwadSatapathi** [comment]
Thanks for sharing the article Aaron.

**Comment by Swimburger** [comment]
Not sure if this was possible when you originally asked this question, but Today you can also do this without modifying the Actions.
Not sure if officially supported, but it works out of the box, check out my how-to: https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-azure-static-web-apps

**Comment by rickvdbosch** [comment]
Announced at Ignite today: first class support for Blazor (and C# Functions) for Static Web Apps. Interesting links:

* [Blazor and C# APIs now supported in Azure Static Web Apps](https://azure.microsoft.com/en-us/updates/blazor-and-c-sharp-apis-now-supported-in-azure-static-web-apps/)  
* [Tutorial: Building a static web app with Blazor in Azure Static Web Apps](https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-blazor)
