### ISSUE TITLE
Next.js Hybrid deploy fails -  No matching Static Web App was found or the api key was invalid

### ISSUE THREAD

**Issue by DynamicsNinja** [Azure/static-web-apps#1055]
**Describe the bug**

I'm trying to deploy the Next.js app via a standard preset that is not modified and the error pops up when deploying.

The app is using APIs and is configured as PWA.

**The content server has rejected the request with: BadRequest
Reason: No matching Static Web App was found or the api key was invalid.**

What do I need to change to make it work?

[YAML FIle](https://github.com/Azure/static-web-apps/files/10488120/azure-static-web-apps-nice-pond-0767dc503.yml.txt)

**Comment by vivekjilla** [comment]
Hi @DynamicsNinja I don't see any issue with the workflow file you shared. 

Can you please also share the Action run logs where it failed, to get more context.

Can you also please check again that the secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_POND_0767DC503 exists for your repo and is not been modified.

**Comment by Wavesolid** [comment]
any answer for this issues yet? because I was facing this issue as well

**Comment by vivekjilla** [comment]
@Wavesolid Can you please share your workflow file and also the run logs to debug this further. Thanks!

**Comment by Wavesolid** [comment]
> @Wavesolid Can you please share your workflow file and also the run logs to debug this further. Thanks!

My issues was solved yesterday, I just updated my secret API token by reset `deployment token` from Azure Web Static Apps portal. Thank you for helping.

**Comment by sulabh-msft** [comment]
Glad @Wavesolid you are able to resolve the issue. Closing the issue.
