### ISSUE TITLE
Add SvelteKit preset to the Static Web App create flow

### ISSUE THREAD

**Issue by geoffrich** [Azure/static-web-apps#1057]
**Is your feature request related to a problem? Please describe.**
When creating a Static Web App via the VS Code extension, I have to choose "Custom" when building a [SvelteKit](https://kit.svelte.dev/) app and enter the following settings:

| property          | value          |
| ----------------- | -------------- |
| `app_location`    | `./`           |
| `api_location`    | `build/server` |
| `output_location` | `build/static` |

**Describe the solution you'd like**
SvelteKit is listed as a preconfigured build preset:

![image](https://user-images.githubusercontent.com/4992896/215288141-701ad8b0-b2db-4506-af4e-5308e4757ec8.png)

**Describe alternatives you've considered**
Continue to use the "Custom" option.

**Additional context**
I maintain the SvelteKit adapter for Azure SWA. Currently, I need to specify the build configuration in [my project's README](https://github.com/geoffrich/svelte-adapter-azure-swa#azure-configuration). I've had issues raised in the past where people have configured this incorrectly.

It would be great if SvelteKit could be a preset instead, so it is more likely to be set up properly. SvelteKit supports [zero-config deployments](https://kit.svelte.dev/docs/adapter-auto) to Azure SWA, so if you can create a SWA with a SvelteKit preset, no other setup will be needed.

**Comment by thomasgauvin** [comment]
Thanks geoffrich, I've added this ask to the vscode extension backlog

**Comment by thomasgauvin** [comment]
This has been completed by the VSCode extension team 🎉 https://github.com/microsoft/vscode-azurestaticwebapps/issues/789
