### ISSUE TITLE
App location not being found in workflow file.

### ISSUE THREAD

**Issue by Ritvik-Sapra** [Azure/static-web-apps#106]
I am trying to deploy a simple workflow file using azure static web apps. Everything is working fine except build and deploy which shows the following error and says app location not found. I have tried editing and commiting the changes in workflow file to try different paths, but literally nothing works.

![WhatsApp Image 2020-07-25 at 2 07 21 AM](https://user-images.githubusercontent.com/54613995/88433593-01a1ab80-ce1c-11ea-9400-677e9e32bdd7.jpeg)

**Comment by miwebst** [comment]
Do you mind sharing the repository structure? In general the app location is a reference to a directory not a particular file. If you would like to use the root of your repository you can specify "/"

**Comment by Ritvik-Sapra** [comment]
Yes, it worked but now it says it can not find build or build:azure node in package.json

**Comment by miwebst** [comment]
Yes if you have a package.json, Oryx will run either the build or build:azure npm run script. If you dont have one of these and want to run a different command when building your application you can use the app build command override. Take a look at the docs here: https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow#custom-build-commands

**Comment by Ritvik-Sapra** [comment]
This is the repo: https://github.com/akanksha99-rs/Navigate-The-Mars-Rover
I typed "build" in the package.json, but still it didn't work.
Locally, we run this app by typing `npm start` in the directory where server.js is located (main app).

**Comment by miwebst** [comment]
Looks like a cool project :) But yes this probably wont work since the project is configured to be a Node server. You can start hosting your static web files by adjusting your app location to be the Microsoft_FrontEnd folder, but for the backend/server api calls you will need to use a NodeJS Azure Function. You can find some documentation here: https://docs.microsoft.com/en-us/azure/static-web-apps/apis
