### ISSUE TITLE
East US 2 Static WebApps Production environment do not deploy

### ISSUE THREAD

**Issue by Bionic711** [Azure/static-web-apps#1069]
I have created 3 static web apps in East US 2. Each one has the same issue. It will deploy any number (up to max) preview stages, but Azure DevOps times out when attempting to deploy the production stage.

I started on this journey because of the authentication issues that were occurring as a result of this issue:
https://github.com/Azure/static-web-apps/issues/1061

**To Reproduce**
1. Run pipeline to deploy to dev
2. Deploy succeeds
3. Run pipeline to deploy to production
4. Deploy times out and fails

If possible, please provide the following information if relevant (do not include sensitive content):
[staticwebapp.pipeline.yaml.txt](https://github.com/Azure/static-web-apps/files/10713914/staticwebapp.pipeline.yaml.txt)
[staticwebapp.config.json.txt](https://github.com/Azure/static-web-apps/files/10713916/staticwebapp.config.json.txt)

**Expected behavior**
Static webapp should deploy to production stage and not time out

**Screenshots**

**Additional context**

**Comment by vivekjilla** [comment]
Hi @Bionic711 , Can you please share the static web app url and the deployment logs for failure runs. Thanks!

**Comment by Bionic711** [comment]
@vivekjilla 
[failedruns.txt](https://github.com/Azure/static-web-apps/files/10715310/failedruns.txt)
URL: https://polite-pond-0403eb30f.2.azurestaticapps.net

**Comment by Bionic711** [comment]
I deploy to "Central US" today with a brand new static webapp. Having the same issues deploying to production that I am in "East US 2". Dev deploys fine but production does not. Tried to deploy via the SWA CLI and it failed attempting to upload to production.

swa deploy --env production --resource-group rgname --app-name appname

**Comment by vivekjilla** [comment]
Hi @Bionic711 I see you're using BYOB as a backend for your SWA app, the issue seems to be related to certain combination of configuration here.

1. Can you please try a new site once deploying to production directly for the first time without creating a dev environment and see if works.
2. Also, just wanted to know if you're linking two BYOB backends: one for the production site and another for the dev stie. If yes, can you please explain the order of the steps followed to link these backends to your site. This will help us understand the issue better.

Thanks in advance and apologies for the inconvenience.

**Comment by Bionic711** [comment]
@vivekjilla 
1. My SWA CLI deployment from yesterday was to a portal created front-end fresh off creation. It did not have BYOB or anything attached to it yet.
The SWA CLI deployment is here: https://gentle-rock-0dc419110.2.azurestaticapps.net

2. Yes. Two different BYOB. This is interesting because this has been working for months (I started using SWA last August).
[sanitized-staticwebapp.json.txt](https://github.com/Azure/static-web-apps/files/10721314/sanitized-staticwebapp.json.txt)
First I deploy this ARM template. This deploys the production site, along with the BYOD for production and links them, as well as creates the DNS, etc.

Once that is completed, I deploy this ARM template:
[sanitized-functionapp.json.txt](https://github.com/Azure/static-web-apps/files/10721354/sanitized-functionapp.json.txt)

After it is deployed, I have to manually link the dev backend as I have not figured out how to do that with ARM templates yet.

**Comment by vivekjilla** [comment]
@Bionic711 
For 1. (gentle-rock-0dc419110) Can you provide the deployment logs. I'm seeing only client-side error saying, "Current directory cannot be identical to or contained within artifact folders.". Basically, running swa deploy from a folder outside the root folder of your app should help unblock here.

For 2. I see you're deploying a `linkedBackend` followed by `userProvidedFunctionApp`. We probably don't need to do both of them. Just the `linkedBackend` resource should be sufficient. I will check more on if this is causing some issue from our side.

Meanwhile, can you try deploying 1 fixing the client side error and see if it unblocks you. Thanks!

**Comment by Bionic711** [comment]
I was able to perform a SWA CLI deployment to the gentle-rock SWA based on your guidance to not deploy from the root location of the deployment and instead use the --app-location.

I have everything manually recreated and connected and am back to the same situation I was on Friday.

2 ongoing issues:
1. Deploying via the pipeline to production fails
2. Authentication in prod not working because the keyvault references @Microsoft.KeyVault(SecretUri=) do not work.

**Comment by vivekjilla** [comment]
@Bionic711 Thanks for the update.

So, for the deployment failing via pipeline, did you try removing the `userProvidedFunctionApps` resource in your ARM template and see if it worked. Please try with a new SWA app and see if it works. 

For the authentication not working because of keyvault references, Can you please check if the SWA identity has access permissions and other steps mentioned in these [docs](https://learn.microsoft.com/en-us/azure/static-web-apps/key-vault-secrets). And if it still doesn't work, can you please share the site name where this is happening so that I can look into this further.

Thank you!

**Comment by Bionic711** [comment]
Removing the ```userProvidedFunctionApps``` resource has allowed the first deployment to occur via the pipeline (without a dev environment created). https://calm-sky-0ef8fbf0f.2.azurestaticapps.net/

I created the dev environment via the pipeline by deploying it's branch.
I created the function app as described in my previous comment.
I manually attached the function app to dev environment in the SWA.
I deployed the dev API to dev function app.
I deployed the dev site to SWA preview environment.
I deployed the main API to main function app.
I deployed the main site to SWA production environment.

Deployment via ARM and the Pipeline are now working again.

As for the authentication. I followed the docs you provided. Manually added a System Assigned Managed Identity. Added that with Get Secrets permissions on the key vault. Site is returning 404 when attempting to access any of the 3 configured IdP (Microsoft, Google, Facebook). https://calm-sky-0ef8fbf0f.2.azurestaticapps.net

When I hardcode the values in dev (as is required) authentication works as expected.

**Comment by vivekjilla** [comment]
@Bionic711 I see you have raised a support ticket as well for this. Let me know where do you want to continue this discussion further, here or the support ticket.

Sharing the current observations:
1. Initially the calls to keyvault were failing with access denied errors, but now we're seeing "KeyVaultSecretResolutionError: secret not found" errors
2. Also looks like the app_id does not seem to be added to app settings.

Can you please double check if the app settings are added correctly and exist in the keyvault as well. for example `FACEBOOK_CLIENT_ID` vs `FACEBOOK-CLIENT-ID`
And if possible, can you also share the `Staticwebapp.config.json` file where your custom auth configuration info is present.

TIA!

**Comment by Bionic711** [comment]
I prefer to continue it here so that mayhap some other users stumble upon this and help themselves.

1. This is probably because I originally only had a UAMI attached and had to add the system-assigned. (I am hoping SWA will support UAMI access to keyvault in the future similar to AS and FA).

I fixed the Facebook settings in the ARM parameters for the keyvault call file for production ```FACEBOOK-CLIENT-ID``` and ```FACEBOOK-CLIENT-SECRET``` to ```FACEBOOK-APP-ID``` and ```FACEBOOK-APP-SECRET```. I also verified the AAD and Google values are correct and populated all the way through.

With the Facebook corrections, all three are "working" on production (I am not going to add the autoconfig site name to the redirect URLs). YAY! 

Why is it that since one was not working correctly they all were failing?

**Comment by vivekjilla** [comment]
Thanks a lot for the update @Bionic711 . Glad that everything is working now. 

> Why is it that since one was not working correctly they all were failing?

This seems to be related to some optimizations on our side where we mark the auth configuration is invalid if we see some invalid settings. Will bring this back to the team and see if we can improve this experience further.  

Closing this issue as it's resolved. Please feel free to reach out in case of further queries etc.
