### ISSUE TITLE
Facebook authentication results in 403 at /.auth/complete

### ISSUE THREAD

**Issue by Bionic711** [Azure/static-web-apps#1073]
Implemented Facebook Authentication as dictated here:
https://learn.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=facebook%2Cinvitations

However, facebook authentication fails at the /.auth/complete#_=_ page with a 403.

Per the Facebook Dev tools, all authentications are occurring successfully.

It appears the actual FB authentication is successful, but it is failing somewhere back in the SWA. Compare to a google or aad login which have a 200 on the /.auth/complete page.

**To Reproduce**
1. Navigate to https://thedollsplace.com/.auth/login/facebook
2. Login with your facebook account
3. See error at /.auth/complete of a 403

**Expected behavior**
Facebook users are logged in.

**Screenshots**
![fb_auth_failure_swa](https://user-images.githubusercontent.com/13358952/218823841-33a1bedc-562e-4654-95f8-fcbec2bcc2ad.png)

**Device info (if applicable):**
 - Windows/Android
 - Edge, Chrome, Firefox

**Additional context**
The issue occurs regardless of whether the configurations for Facebook are using app config or key vault references.
I have custom roles implemented via a function app at api/getRoles that works for Google and AAD auth.

**Comment by vivekjilla** [comment]
@Bionic711 just to share an update, it seems like we're not receiving any user details from the facebook endpoint based on initial look. Will check further on this. Can you please also share the har trace if possible, just to see if I missed anything and check once if any config/access is missing from your facebook app.

Also I tried reaching the https://developers.facebook.com/ to test out this flow once, but the site seems unreachable. Not sure if this issue is related.

**Comment by Bionic711** [comment]
@vivekjilla Do you have a secure way for me to share the HAR trace? I am not comfortable putting it on the public issue. I can share a OneDrive link of it to your user email address? I will share a ZIP with you and include the Facebook configuration I am using via Screenshots.

I do not believe there are any misconfigurations (very similar to the AAD and Google versions) but I am only human.

**Comment by Bionic711** [comment]
Support request ID | 230215004000424

**Comment by vivekjilla** [comment]
Thanks for the details via support ticket @Bionic711 
I think, there are two ways to solve this:

1. Add `email` scopes to start receiving the email id, as below.

```diff
{
  "auth": {
    "identityProviders": {
      "facebook": {
        "registration": {
          "appIdSettingName": "FACEBOOK_APP_ID",
          "appSecretSettingName": "FACEBOOK_APP_SECRET"
        },
+      "login": {
+         "scopes":["email"]
+       }    
      }
    }
  }
}
```

2. Change the claim we are checking for to get user details, by adding userDetailsClaim pointing to `nameidentifier`, as below.
This is useful in case someone doesn't have a valid email id as well.

```diff
{
  "auth": {
    "identityProviders": {
      "facebook": {
        "registration": {
          "appIdSettingName": "FACEBOOK_APP_ID",
          "appSecretSettingName": "FACEBOOK_APP_SECRET"
        },
+       "userDetailsClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"
      }
    }
  }
}
```

Please try this out and let me know if it helps. Thanks!

**Comment by Bionic711** [comment]
@vivekjilla That works! The major difference is that it puts the facebook user id in the userdetailsclaim rather than the email address. Twitter, Google, and AAD all place the email address in that field. I tried using the email (fb auth succeeded but resulted in 403 at the SWA). Using ```"userDetailsClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"``` claim resulted in me getting what I needed.

Thank you again!!!

**Comment by vivekjilla** [comment]
Awesome. Glad it got resolved. Thanks for the update!
