### ISSUE TITLE
Custom CNAME

### ISSUE THREAD

**Issue by vmsilvamolina** [Azure/static-web-apps#109]
You need a CNAME to add a custom domain to the Azure Static Web App service, but now we only can use the WWW.

How about the companies that have taken the WWW record? or have specific requirements (apps or solutions) with different names?

**Comment by miwebst** [comment]
So WWW is not required, it can be any subdomain (i.e. blog.customdomain.net or example.customdomain.net or www.customdomain.net) I believe we are updating the docs around this (@craigshoemaker). 

What is not supported right now is APEX domains (i.e. customdomain.net) and we are working on this!

**Comment by vmsilvamolina** [comment]
Yes, you're right. I misinterpreted the reference example: now I validate with another value and it's ok!

The information in the panel is not entirely clear (at least for me it was not XD), it can change to the following:

"To add a custom domain, first configure a CNAME **like the following** record with your DNS provider."

**Comment by miwebst** [comment]
Ah i see, similar to this issue? https://github.com/Azure/static-web-apps/issues/87
