### ISSUE TITLE
Static Web App Build Details section missing in Azure Portal

### ISSUE THREAD

**Issue by dummy-andra** [Azure/static-web-apps#1095]
**Description:**
When attempting to create a new Static Web App from the Azure Portal using the 'Microsoft.Web/staticSites' resource type, the Build Details section is missing from the creation process. This makes it impossible to configure build settings for the app, resulting in the app being stuck in the "WaitforBuild" state indefinitely.

**Steps to reproduce:**
1. Log in to the Azure Portal
2. Click on the "Create a resource" button
3. Search for "Static Web App" and select the "Static Web App" resource type
4. Fill in the required fields for Basics, Tags, and Review + create
5. Notice that the Build Details section is missing, leaving no options to configure the build settings for the app
6. Proceed with the creation process and wait for the app to be deployed

Notice that the app is stuck in the "WaitforBuild" state indefinitely

**Expected behavior:**
The Static Web App creation process should include the Build Details section, allowing users to configure build settings for their app and preventing the app from being stuck in the "WaitforBuild" state.
![image](https://user-images.githubusercontent.com/37038210/223379966-1f683129-abd1-4b52-9942-600dbf03702e.png)

**Actual behavior:**
The Build Details section is missing from the Static Web App creation process in the Azure Portal, making it impossible to configure build settings and causing apps to be stuck in the "WaitforBuild" state.
![image](https://user-images.githubusercontent.com/37038210/223379881-38230594-ea67-4f23-bdaa-9410b5ff7d32.png)

**Additional information:**
This issue can be worked around by creating the Static Web App via the Azure CLI or REST API, which includes the Build Details section in the creation process. However, this option should be available in Portal too, since in Preview was.

**Comment by thomasgauvin** [comment]
Hi @dummy-andra, this is not the expected Portal experience. Can you share the Portal link you are using, or any details that could help reproduce this? I am unable to access such a Create blade for Static Web Apps

**Comment by dummy-andra** [comment]
Here are the steps in screenshots. 

![image](https://user-images.githubusercontent.com/37038210/223662151-b9694224-2ea6-4275-b965-0b3ed85a16d4.png)
![image](https://user-images.githubusercontent.com/37038210/223662184-a2b4f4d3-5a81-454f-a46c-592ce47f56bd.png)
![image](https://user-images.githubusercontent.com/37038210/223662220-533a0475-7571-44dc-b35b-22623d790707.png)

Portal Link: https://portal.azure.com/#create/Microsoft.StaticApp

Should I open a MS support ticket? The behavior is reproducing on different tenants/accounts across multiple subscriptions.

**Comment by thomasgauvin** [comment]
Can you scroll to the bottom of the `Basics` tab and take a screenshot? I am trying to understand if the Portal section for build details is not being rendered fully. This is what the bottom of the page should look like: 
![image](https://user-images.githubusercontent.com/35609369/223889675-f55631b5-aecb-458d-abb1-bb585e1baccd.png)

**Comment by dummy-andra** [comment]
The botom of the window page for Basic tab is at the `Review and Create`  see screenshot added at step3
![image](https://user-images.githubusercontent.com/37038210/223957965-188befbc-6516-42d5-a2e2-2cb3212857cb.png)

**Comment by dummy-andra** [comment]
I will record a video in 1-2h for more clarity.
