### ISSUE TITLE
Provide working sample of NextJs Hybrid App

### ISSUE THREAD

**Issue by nad-au** [Azure/static-web-apps#1103]
**Is your feature request related to a problem? Please describe.**
I'm trying to follow the example in https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid but our infra is provsioned through automation so I'm unable to follow all the manual steps.

**Describe the solution you'd like**
A working example of a NextJs Hybrid App as per https://github.com/staticwebdev/nextjs-starter

**Describe alternatives you've considered**
I've tried adapting the starter app https://github.com/staticwebdev/nextjs-starter but there's additional flags and settings required in pipeline and config scripts which are unclear - and this would only be revealed if manual steps are performed.

**Additional context**
I'm unable to deploy a hybrid app. I get a number of errors. The latest is:
```
Oryx has determined that the app build artifacts are in the '.next' directory. If this is incorrect please specify the app artifact location.
Finished building app with Oryx
Failed to find a default file in the app artifacts folder (.next). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

It would be most helpful to see a working example app and pipeline scripts to avoid a lot of the guesswork.

Thank you

**Comment by thomasgauvin** [comment]
This has now been completed in https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid
