### ISSUE TITLE
Case sensitivity issues with URLs and Routes.json

### ISSUE THREAD

**Issue by clairernovotny** [Azure/static-web-apps#111]
I have a static site with content at `/news`. Many old unfixable links point to `/News` and that returns a 404.

When I put this in the routes.json returns too many redirects, so that feature does not seem to be case sensitive.

```json
{      "route": "/News",
      "serve": "/news",
      "statusCode": 301
}
```

This is a critical blocker as we are unable to get the links resolved.

**Comment by mkarmark** [comment]
Hi @clairernovotny, thanks for bringing this issue to our attention! We have deployed a fix to this issue, and your route should now work on your static web app.
