### ISSUE TITLE
Deploy fails: wrong folder is picked for deployment?

### ISSUE THREAD

**Issue by oarchambault** [Azure/static-web-apps#1127]
**Describe the bug**
Hello, I am trying to setup a **GitHub Action** to build and deploy my React front-end app to Azure Static Web Apps. My front-end app source folder is not at the root of my repository, but in a subfolder, let's say at 'src/web/'.

Building the app happens in a previous step and seems to be working correctly, the build output is in 'src/web/dist'.

I then use Azure/static-web-apps-deploy@v1 to only deploy and skip the build part.
Those are my parameters:
```
azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
action: "upload"
app_location: "src/web/dist"
output_location: ""
skip_app_build: true
```

But then I get the following logs and error:
```
App Directory Location: 'src/web/' was found.
Looking for event info
Skipping step to build /github/workspace/src/web with Oryx
No Api directory specified. Azure Functions will not be created.
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
The content server has rejected the request with: BadRequest
Reason: The size of the app content was too large. The limit for this Static Web App is 262144000 bytes. For a higher app size limit, consider upgrading to the Standard plan.
```

But my output folder (src/web/dist) size is around 250kb, so it seems like it is trying to deploy the whole parent folder (src/web) which is over 180mb. The log line _'App Directory Location: 'src/web/' was found.'_ points that way too.

The GitHub repository is not public, but here's a workflow file which is almost identical to the real one, with just some folder names changed and comments removed.
[workflow.yml.txt](https://github.com/Azure/static-web-apps/files/11112479/workflow.yml.txt)

I do not have a staticwebapp.config.json file.

As I am still trying to setup this workflow, so I expect at least a different error message.

Thank you!

**Comment by vivekjilla** [comment]
@oarchambault in the attached workflow file, I see an environment variable APP_LOCATION pointing to `src/web/`. I think this environment variables is taking precedence. I think all those three env variables can be removed from the workflow file as we're passing them as the parameters. 

Can you please try it and let us know if it works. Thanks!

**Comment by oarchambault** [comment]
@vivekjilla That fixed it, thank you very much! 
Do you know if this behaviour is documented? As a newbie using GitHub Actions it would have been nice to know.
Cheers!

**Comment by AliBdeir** [comment]
I'm having this same exact issue, except it only happens when the workflow is run on a PR being opened.
