### ISSUE TITLE
Timeout on build and deploy

### ISSUE THREAD

**Issue by adiazcan** [Azure/static-web-apps#113]
Hi, 

I have a large site with gatsby and lot of images. 

When I try to deploy using GitHub Actions, I always have a timeout problem with Oryx

**Oryx has timed out while building app, the current limit is 900 seconds. Failing build.**

Is there any way to increase 900 seconds limit timeout? It's not enough for my site buiding.

**Comment by miwebst** [comment]
Hi @adiazcan, we put this limit here to avoid build errors resulting in extra Github Action costs (private/org repos). Can you answer 2 quick questions?

1. Locally how long does it take to build your application? Is 900+ seconds expected?
2. How large is the application once built? We currently have a 100 MB limit and I'd expect you may hit that if your site is especially large.

**Comment by adiazcan** [comment]
Hi @miwebst 

We are working to migrate our web magazine from SharePoint to Gatsby http://www.compartimoss.com/ 

1. It tooks about 30 minutes to build, we have more than 9000 images and more than 400 static html pages and gatsby has to generate all the thumbnails and pages.
2. Our application has 43,4 MB 

How can we publish it?

**Comment by miwebst** [comment]
I see! Ok in that case we probably want to keep this safety for other cases but add a workflow configuration so you can adjust it if your build takes longer. We will plan something for this and get back to you. Sadly right now there isn't a quick workaround

**Comment by adiazcan** [comment]
Ok, let me know If I can help/test this new version

**Comment by adiazcan** [comment]
Hi @miwebst 

any plan to support more minutes on build? or can we deploy directly without build?

**Comment by miwebst** [comment]
So we actually just added a configuration that you can add to the build and deploy step of your workflow step. Here is an example:

        app_location: 'app' # App source code path
        api_location: 'api' # Api source code path - optional
        app_artifact_location: 'build' # Built app content directory - optional
        build_timeout_in_minutes: 15

You may see an error saying there is an unrecognized input, that is just because we havent added it to our official GitHub Action and docs yet.

Valid values for the build timeout are 1 - 1440 minutes (although GitHub Actions may timeout before then)

**Comment by adiazcan** [comment]
@miwebst with build_timeout param my site compiled but I found another problem that you mentioned early, I have more than 4000 files on my site. exactly I have 13229 files, so the Github Action fail for this reason. 

Any way to avoid this problem?

**Comment by miwebst** [comment]
Ah I was afraid of this, yes we currently are limiting the number of files during preview to 4k files. I'm surprised that you are running into this limit and not the 100 MB limit. In either case, we currently will reject this application. These limits are in part a way for us to judge the needs of the community and we will be evaluating them as we head for general availability.

**Comment by adiazcan** [comment]
ok, we'll move to another service because we want to go live on one or two weeks

**Comment by miwebst** [comment]
Sorry to hear that, we will be changing these limits as we get to GA, I appreciate you trying out the product though!

**Comment by adiazcan** [comment]
Hi @miwebst 

any plan for GA? Do you have any date? Can we see the GA limits?

I want to try again with this service and our site.

**Comment by miwebst** [comment]
@anthonychu can probably provide better answers on GA date. As for limits, I wont publish anything right now but we will be able to support 13k files at that time.

**Comment by anthonychu** [comment]
Best date we can provide right now is the first half of this year.

**Comment by loganmarshall1** [comment]
Hi @anthonychu hope you're having a great weekend!

do you know when  `build_timeout_in_minutes: 15` will be GA? I just tried to set it to 30 and Oryx build timed out after 15 min.  Is there an updated version number of the AzureDevops Pipeline Task?

`Starting: AzureStaticWebApp
==============================================================================
Task         : Deploy Azure Static Web App
Description  : [PREVIEW] Build and deploy an Azure Static Web App
Version      : 0.187.2
Author       : Microsoft Corporation
Help         : https://aka.ms/swadocs
==============================================================================`

`Oryx has timed out while building app, the current limit is 15 minutes. Failing build.`

**Comment by anthonychu** [comment]
It should be available after the updated task is rolled out. A member of the Azure DevOps team chimed in on https://github.com/Azure/static-web-apps/issues/642#issuecomment-985804112 with the release progress.

**Comment by loganmarshall1** [comment]
> It should be available after the updated task is rolled out. A member of the Azure DevOps team chimed in on https://github.com/Azure/static-web-apps/issues/642#issuecomment-985804112 with the release progress.

Thanks dude! Super happy, greatful & excited! You rock!

**Comment by anthonychu** [comment]
The updated task should be available now. Also added this parameter to the docs:

https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#extend-build-timeout

**Comment by loganmarshall1** [comment]
> The updated task should be available now. Also added this parameter to the docs:
> 
> 
> 
> https://docs.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#extend-build-timeout

Perfect thank you. Yes I got it working on all of my apps. I had to set it to 45 minutes :). Thanks!!

**Comment by rhutchison** [comment]
Unexpected input(s) 'build_timeout_in_minutes', valid inputs are ['entryPoint', 'args', 'action', 'app_location', 'azure_static_web_apps_api_token', 'api_build_command', 'api_location', 'app_artifact_location', 'output_location', 'app_build_command', 'repo_token', 'routes_location', 'skip_app_build', 'config_file_location', 'skip_api_build', 'production_branch', 'deployment_environment', 'is_static_export']

https://github.com/Azure/static-web-apps-deploy/blob/v1/action.yml

Am I missing something?
