### ISSUE TITLE
Build and Deploy Internal Server Error

### ISSUE THREAD

**Issue by orteez** [Azure/static-web-apps#1131]
Running a deployment is getting an internal server error:

`The content server has rejected the request with: InternalServerError`

DeploymentId: 71d5a028-391f-4f96-961c-f6403cbb94f2

Building with Vue 3.0.0 and node engine 16.13.1

**To Reproduce**
1. Merge pull request
2. go to deployment job
3. View Build and Deploy tab

**Expected behavior**
Pipeline to run successfully. Issue only started today. Yesterday deployments succeeded.

**Comment by devrony** [comment]
Same here.  Additional message:  ##[error]Reason: An unexpected error has occurred. Please ensure your deployment token is properly set and try again later.

We are deploying to a Static Web App using DevOps Release Pipeline. Working yesterday.  We reset our "Deployment Token" on the Static Web App and updated our CD to use that new value. Still same issue.

**Comment by devrony** [comment]
It's possible this is an internal issue with DevOps.  From our prior deployments, the step it's failing on is trying to access the /working_dir/ directory and the process can't access the content.  

This was the next step in line that worked on prior build:
2023-04-06T17:19:13.9035924Z Skipping step to build /working_dir/_ota-court-web/courtweb/web with Oryx

**Comment by jsloan-ARI** [comment]
Same issue here. Running a Static Web App with React that was working perfectly fine and suddenly running into the same error message when running the pipeline: 

Reason: An unexpected error has occurred. Please ensure your deployment token is properly set and try again later.

We created a new Static Web App resource and got the exact same issue when deploying to that one. Suspecting an Azure issue.

**Comment by Christoba** [comment]
Same issue. All SWAs across multiple subscriptions. Also unable to reset deployment token.

**Comment by isaiahscheel** [comment]
Same issue. Unable to reset deploy token either through the Azure portal like it says I should be able to here: https://learn.microsoft.com/en-us/azure/static-web-apps/deployment-token-management

**Comment by itsxallwater** [comment]
Would love to get an official weigh in on this as it is quickly becoming a production blocking problem and I'd rather not go back to running SWAs out of storage blobs.

**Comment by mstinglin** [comment]
It is back on guys

**Comment by orteez** [comment]
> It is back on guys

Confirming that it's working for us too. Any info on why it was down for over two hours would be great...

**Comment by devrony** [comment]
Confirmed. Working again.

**Comment by isaiahscheel** [comment]
Yep looking good from our pipeline again as well.

**Comment by verso-patrick** [comment]
getting this now again for no reason: 

![Image](https://github.com/user-attachments/assets/5c214147-eeba-4672-9d9c-e42c2e8a70d7)

**Comment by liramzarrouk** [comment]
Also getting this message for now for no reason...

**Comment by listen3000** [comment]
@darena-patrick @liramzarrouk did you find a solution?

**Comment by smartinworld** [comment]
@listen3000 did YOU find a solution?? :)
