### ISSUE TITLE
nextjs ssr experiencing cold start ( > 5 sec)

### ISSUE THREAD

**Issue by doorman02** [Azure/static-web-apps#1144]
**Describe the bug**

I am deploying a NextJs app with ssr and the first call to getServerSideProps takes > 5 seconds even after removing all logic from it. After the inital call it loads much faster. But if idle for some time it will trigger another cold start. Is this related to the cold start of the ssr server? If this is the case, would it possible to configure it to be always on or to keep it warm?

**To Reproduce**
Create NextJs app with ssr.

**Expected behavior**
The app should load faster on the inital call to getServerSideProps

**Device info (if applicable):**
 - OS: MacOs, iOS
 - Browser Chrome
 - Version latest

**Comment by thomasgauvin** [comment]
Hi @doorman02, we hear your feedback. We're actually tracking all feedback related to NextJS here: https://github.com/Azure/static-web-apps/discussions/1066

We've been working to improve our support for NextJS and reduce cold starts. We'll be providing updates in that thread when they come along.

**Comment by thomasgauvin** [comment]
Hi @doorman02, we've shipped significant improvements to our Next.js support on Static Web Apps, here's the announcement: https://github.com/Azure/static-web-apps/discussions/1428

Notably, cold starts are drastically reduced! Closing this thread, try out our improved Next.js support and let us know how it goes in #1428!

**Comment by doorman02** [comment]
Hi @thomasgauvin thanks for the update. Do you know what was the cause for the cold start issue?

**Comment by KMDgit** [comment]
This issue is still present. I'm getting sometimes +5 s to load a simple page of 46B.
<img width="1030" alt="Screenshot 2024-09-16 at 10 43 56 AM" src="https://github.com/user-attachments/assets/3171368c-6139-4315-a534-f998f42bf65e">

**Comment by KMDgit** [comment]
You have to reopen this issue @thomasgauvin. It's really annoying.
