### ISSUE TITLE
How to redirect or rewrite by different user agent?

### ISSUE THREAD

**Issue by gyhyfj** [Azure/static-web-apps#1150]
If there is `rewrite` rule in config file, for prerended page, like:
```json
{
  "routes": [
    {
      "route": "/",
      "rewrite": "/index.html"
    }
  ],
}
```
If I just want this page for PC device, and I need to redirect to another website for Mobile device, by different user agent.
Then I have to rediret on client side after user loading this html file, because this rewrite rule will stop request accessing my server middleware. 

Could it be possiable to config the redirect or rewrite by ua in `staticwebapp.config.json`?

**Comment by thomasgauvin** [comment]
Hi @gyhyfj, this is not possible at this time with Static Web Apps. This thread provides more context regarding why this isn't an option today https://github.com/Azure/static-web-apps/issues/196.
