### ISSUE TITLE
swa Failed to fetch functions for your app.  

### ISSUE THREAD

**Issue by eodeg** [Azure/static-web-apps#1153]
Static web is not able to connect to Azure Function.

Getting the following message in Application Insights in the Azure Portal.

"Failed to fetch functions for your app."

**Comment by donniegraham** [comment]
We are experiencing the same issue. It came back up but it's down again.... this seems to be a re-occurring problem :(

**Comment by eodeg** [comment]
We have also experienced the same issue a couple of times in the last year.

**Comment by mishapos** [comment]
Same issue as #1154
