### ISSUE TITLE
Connect Azure Front Door to Static Web App with Private Link

### ISSUE THREAD

**Issue by tobiasdiez** [Azure/static-web-apps#1158]
**Is your feature request related to a problem? Please describe.**
Currently, the setup of a static web app behind a front door is quite involved: https://learn.microsoft.com/en-us/azure/static-web-apps/front-door-manual#update-static-web-app-configuration

**Describe the solution you'd like**
A similar solution as for App Services: https://learn.microsoft.com/en-us/azure/frontdoor/standard-premium/how-to-enable-private-link-web-app

**Comment by thomasgauvin** [comment]
I see you thumbs up'ed my answer, I'll close this issue, feel free to reopen!
