### ISSUE TITLE
JavaScript error on custom domain blade; cannot generate TXT to verify my domain

### ISSUE THREAD

**Issue by RayDeanTech** [Azure/static-web-apps#1159]
**Describe the bug**

I am following the "[Set up a custom domain in Azure Static Web Apps](https://learn.microsoft.com/en-us/azure/static-web-apps/custom-domain-external)" instruction set.  I'm trying to verify ownership of the domain, as instructed.  But, the code I'm supposed to copy for the TXT record is never generated, and JavaScript errors are dumped to the console. 

**To Reproduce**
1. Under a static web app project, got to Custom Domains
2. Click Add, then choose 'Custom domain on other DNS'
3. Put in your domain name:  "domain.tech"  WITHOUT the subdomain, as per the instructions (my domain ends in a .tech; JS error dumped to console after pressing next)
4. Press the Generate Code button... you're supposed to wait, but mine is never generated.  Instead, JavaScript errors are dumped to the console.

**Expected behavior**
I had expected to see a code that I could copy and paste as a TXT record for my registrar.

**Screenshots**
![image](https://user-images.githubusercontent.com/21373144/236629474-0ac28c3c-3c44-40f1-8fd9-d14ed9c19e09.png)

![image](https://user-images.githubusercontent.com/21373144/236629507-411c9577-8a7e-4d52-a76f-46c46f6484aa.png)

**Device info (if applicable):**
 - I have used both Brave and Firefox.

**Additional context**
I have also tried this with a different static app, and got the same results.  I was only able to finish the first part of the instructions: adding the "www", and that part was verified by Azure.  I just need to get to part 2 & 3 of the instructions:  generated the TXT code, and setting up an Alias.

**Comment by gizim79** [comment]
I have the exact same issue. Hopefully a temporary thing.

**Comment by blackpatton17** [comment]
What kind of internship student is doing this awful work? Even my assistant can use ChatGPT to make a better one. Hold on... Maybe this is really a Chatpgt master piece.

**Comment by mariussm** [comment]
This issue is also present when doing things in PowerShell, either using Azure CLI or Azure PowerShell Module.

**Comment by andymarsden** [comment]
Can confirm the exact same issue above - tried multiple domains and static apps. Same custom blade issue error in console.

**Comment by johnpeeke** [comment]
Issue seems to be resolved.

**Comment by RayDeanTech** [comment]
I can confirm that I'm now able to generate the special code for my TXT record -- no errors dumped to browser console.  After I complete the entire process, I I'll close this out.
