### ISSUE TITLE
in portal, "Functions" tab displays "No results."

### ISSUE THREAD

**Issue by dcollien** [Azure/static-web-apps#116]
"Functions" tab displays "No results."
then 10-20 seconds later, the functions listing loads.

**Comment by miwebst** [comment]
This is most likely due to Functions host cold starting. I expect that if you hit the function app and then go to the Portal (after previously not visiting it via Portal) then it would be much more responsive.

**Comment by dcollien** [comment]
Would it be possible to make it say "loading" while it's loading, instead of "No results."

**Comment by anthonychu** [comment]
Thanks. This is good feedback. @takyyon @ehamai

**Comment by thomasgauvin** [comment]
This seems to have been fixed with changes to the SWA API blade
