### ISSUE TITLE
Oryx has failed to build the solution.

### ISSUE THREAD

**Issue by dev-dev-7** [Azure/static-web-apps#1166]
Getting below error! 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

![image](https://github.com/Azure/static-web-apps/assets/78405874/356b0623-2b63-453e-ab83-315394474e24)

**Comment by deven-gqc** [comment]
Even I am experiencing the same problem.

**Comment by dev-dev-7** [comment]
Bro it will fix by doing “CI=false react-script build “(remove all warnings from react app) . Build successful.

**Comment by deven-gqc** [comment]
Where should I add this line? `CI=false react-script build `

**Comment by dev-dev-7** [comment]
![Uploading image.jpg…]()

**Comment by deven-gqc** [comment]
Unfortunately, the image is not visible.

**Comment by deven-gqc** [comment]
@dev-dev-7 I was able to fix the issue. Thanks a lot!

**Comment by mhassanrahman** [comment]
Anyone having the issue, you have to add `CI=false ` in package.json against the build tag.

![Screenshot 2024-06-07 025207](https://github.com/Azure/static-web-apps/assets/14047513/9d0f09a7-85f3-49fe-9178-c2dd73a49c77)
