### ISSUE TITLE
Issue regression: Environment variables no longer applied in preview environments

### ISSUE THREAD

**Issue by binkiesjoris** [Azure/static-web-apps#1178]
Issue #914 seems to have regressed, when deploying new preview environments through the 'AzureStaticWebApp@0' task on devops, environment variables are again no longer applied to the preview environments and we have to manually update the variables after deployment for them to be applied to the server.

All information regarding the issue can be found in the original linked issue.

**Comment by sig9** [comment]
came here to say the same thing. 
Could you put in a functional test please. 
- For new PR environments, A redeployment or change to env vars should not be required for new environments to have their app settings.

**Comment by binkiesjoris** [comment]
I have received a response from azure support that the issue has been flagged by the backend team and should be fixed in the next release (ETA not precisely known), so it should be fixed again sometime in the near future!

**Comment by rdpolarity** [comment]
Just got around to testing out this issue again on a different project and I can confirm that the issue has certainly regressed.
Context: I wrote the original issue #914.
Hopefully this get resolve permanently this time round.

**Comment by thomasgauvin** [comment]
Thanks for reporting everyone, we're looking into this

**Comment by thomasgauvin** [comment]
Update, this issue has been fixed, app settings are now propagated to the managed Azure Function correctly for preview environments! Closing this issue

**Comment by binkiesjoris** [comment]
Hi @thomasgauvin thanks for the updates! I can confirm the issue is resolved. I had opened a support issue for this, but that ticket got closed already once they forwarded the message to the developers.
