### ISSUE TITLE
Oryx Build detects hugo but has an error and on the first attempt

### ISSUE THREAD

**Issue by BohrenAn** [Azure/static-web-apps#1183]
Hi i've seen lately that the Build Pipeline has some errors and need to reinstall hugo to sucessfully build.
Anything that can be done here?

---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230501.1, Commit: 58513374525ab2977af68fc5b3c344d32858d8af, ReleaseTagName: 20230501.1

Build Operation ID: 39264c745f03ee76
OS Type           : bullseye
Image Type        : jamstack

Detecting platforms...
Detected following platforms:
  hugo: 0.96.0
Version '0.96.0' of platform 'hugo' is not installed. Generating script to install it...
Detected the following frameworks: hugo

+++ dirname /opt/tmp/images/build/installHugo.sh
++ cd /opt/tmp/images/build
++ pwd
+ __CURRENT_DIR=/opt/tmp/images/build
+ source /opt/tmp/images/build/../../build/__hugoConstants.sh
++ VERSION=0.96.0
++ PLATFORM_NAME=hugo
++ INSTALLED_HUGO_VERSIONS_DIR=/opt/hugo
++ INSTALLATION_URL_FORMAT=https://github.com/gohugoio/hugo/releases/download/v#VERSION#/#TAR_FILE#
++ TAR_FILE_NAME_FORMAT=hugo_extended_#VERSION#_Linux-64bit.tar.gz
++ TOML_FILE_NAME=config.toml
++ YAML_FILE_NAME=config.yaml
++ YML_FILE_NAME=config.yml
++ JSON_FILE_NAME=config.json
++ CONFIG_FOLDER_NAME=config
++ sed s/#VERSION#/0.96.0/g
++ echo hugo_extended_#VERSION#_Linux-64bit.tar.gz
+ fileName=hugo_extended_0.96.0_Linux-64bit.tar.gz
++ sed s/#VERSION#/0.96.0/g
Source directory     : /working_dir/blog.icewolf.ch
++ echo https://github.com/gohugoio/hugo/releases/download/v#VERSION#/#TAR_FILE#
+ url=https://github.com/gohugoio/hugo/releases/download/v0.96.0/#TAR_FILE#
++ sed s/#TAR_FILE#/hugo_extended_0.96.0_Linux-64bit.tar.gz/g
Destination directory: /931fd894-1001-4965-9531-21499ab433a5-swa-oryx/app

retry 0
++ echo https://github.com/gohugoio/hugo/releases/download/v0.96.0/#TAR_FILE#
+ url=https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Linux-64bit.tar.gz
+ request='curl -fsSLO --compressed https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Linux-64bit.tar.gz'
+ /opt/tmp/images/retry.sh 'curl -fsSLO --compressed https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Linux-64bit.tar.gz'
+ installationDir=/opt/hugo/0.96.0
+ mkdir -p /opt/hugo/0.96.0
+ tar -xzf hugo_extended_0.96.0_Linux-64bit.tar.gz -C /opt/hugo/0.96.0
+ rm hugo_extended_0.96.0_Linux-64bit.tar.gz
+ ln -s /opt/hugo/0.96.0 /opt/hugo/lts

Downloading and extracting hugo version 0.96.0 to /opt/hugo/0.96.0...
Downloaded in 1 sec(s).
Extracting contents...
Done in 1 sec(s).

Regards
Andres

**Comment by thomasgauvin** [comment]
Hi @BohrenAn, it seems that the Hugo app is building correctly, correct? The `Version '0.96.0' of platform 'hugo' is not installed. Generating script to install it...` line is happening because Go has been extracted from the base Oryx image to improve download speeds

**Comment by BohrenAn** [comment]
Maybe i am just irritated that it is printed in red
![image](https://github.com/Azure/static-web-apps/assets/45082822/834a9f2e-3ad6-4c80-bc24-88e0d3b49e26)

**Comment by thomasgauvin** [comment]
Ok thanks for the feedback, I'll bring it up with our eng team to print yellow/warning instead

**Comment by BohrenAn** [comment]
Thanks @thomasgauvin that would be nice

**Comment by BohrenAn** [comment]
Any updates here?

**Comment by thomasgauvin** [comment]
No update at this time, we had another fix for Oryx that took priority but we still have this on our backlog

**Comment by BohrenAn** [comment]
Hi All,

It seems like this has now been fixed and the issue can be closed now
![image](https://github.com/Azure/static-web-apps/assets/45082822/e1668962-130c-4677-885e-240023538d9d)

Thanks and Regards
Andres

**Comment by BohrenAn** [comment]
I am closing here
