### ISSUE TITLE
Azure Static Web Apps support for Next.js app directory

### ISSUE THREAD

**Issue by RenMen** [Azure/static-web-apps#1185]
I have an Nextjs app directory application with Next-auth as authentication middleware(Azure B2C Ad). Everything is working as expected in localhost as well as Vercel but not on Azure static web app.  Seems azure not yet ready for nextjs app directory  or I am missing some thing.

**Comment by thomasgauvin** [comment]
Hi RenMen, can you indicate what specifically is breaking in your app directory Next13 app?

**Comment by RenMen** [comment]
Hello Thomas,
Thank you for your response.
I am not not able to sign-in using next-auth. appreciate if you can visit
my website https://lemon-desert-0ee8eaf10.3.azurestaticapps.net and try to
sign in.
But the same code if I upload to vercel (https://p-access.vercel.app)
everything is working fine.
I iterate, this is an app using NextJS 13 App directory

Regards

Ren

**Comment by RenMen** [comment]
> Hi RenMen, can you indicate what specifically is breaking in your app directory Next13 app? We're aware that some of the features such as RSC are not working as intended, we're working to fix those is issues

**Comment by RenMen** [comment]
> Is there any time frame when nextjs app directory SSR will be ready for production?

**Comment by RenMen** [comment]
> Hi RenMen, can you indicate what specifically is breaking in your app directory Next13 app? We're aware that some of the features such as RSC are not working as intended, we're working to fix those issues

**Comment by RenMen** [comment]
Is there any time frame when nextjs app directory SSR will be ready for production?

**Comment by RenMen** [comment]
> Hi RenMen, can you indicate what specifically is breaking in your app directory Next13 app? We're aware that some of the features such as RSC are not working as intended, we're working to fix those issues

Is there any time frame when nextjs app directory SSR will be ready for production?

**Comment by RenMen** [comment]
> We're working on a few fixes for Next 13 app directory that should enable this in the coming months, I will keep this thread updated.

Any updates ?

**Comment by wesleycoder** [comment]
Bumping this.
It's frustrating, there's been months already and no updates about this, not from vercel nor from azure.

**Comment by diveddie** [comment]
@thomasgauvin, I appreciate the work on Static Web Apps. This is a huge jump forward for all of our clients using Azure. Is there a testing or UAT group that we could join? If not, can we gain early access?

We are starting a large migration from a desktop app to Azure, and we'd love to begin with App Router but are prepared to fall back to the Page Router. I am happy to be a guinea pig and provide feedback if your team is open to it.

**Comment by hrc7505** [comment]
ISR(revalidate) is not working 

`next: 13.3.0`

```
- task: AzureStaticWebApp@0
    inputs:
      is_static_export: false
      azure_static_web_apps_api_token: $(WEB-DEPLOYMENT_TOKEN)
      production_branch: main
```

**Comment by symeus-sgs** [comment]
@thomasgauvin can you please provide an update on when you think this will be available? Many thanks.

**Comment by thomasgauvin** [comment]
We are preparing to test these changes over the coming month, Feb-March timeframe

**Comment by thomasgauvin** [comment]
Hi @symeus-sgs @tomhendra @yannbolliger @Minot1 @AkselHSkaar @kimkanu @Qualizorg @VJFC @diveddie! We've recently shipped major improvements to our Next.js support on Static Web Apps! Check out the announcement for full details: https://github.com/Azure/static-web-apps/discussions/1428 Significantly, support for App Router, RSC, Server Actions are all present. Let us know how it goes in the thread of #1428!
