### ISSUE TITLE
Per-Environment database connections

### ISSUE THREAD

**Issue by AesonFord** [Azure/static-web-apps#1195]
**Is your feature request related to a problem? Please describe.**
Having different environments available is excellent, but dev environments create no value if they are pointed to the production database

**Describe the solution you'd like**
Database connections should be configurable per environment

**Describe alternatives you've considered**
I currently have a separate SWA for each environment

**Comment by thomasgauvin** [comment]
Currently, this is an option in the Portal in the database connections tab, you can select an independent database for each environment. Can you help me better understand how you are encountering this scenario?

**Comment by AesonFord** [comment]
I was looking around the portal and didn't see the option, so that's on me. Sorry about that
