### ISSUE TITLE
Custom Sub-Domains

### ISSUE THREAD

**Issue by johnnliu** [Azure/static-web-apps#12]
Want ability to use subdomains:

docs.johnliu.net

currently the custom domains settings only validates www.

this is strange since AzureFunctions or Static Site both supported subdomains.

**Comment by miwebst** [comment]
This sounds like a DNS issue. Have you tried creating a CNAME from docs.johnliu.net to the name of your static web app?

Static Web Apps supports more than just the www subdomain.

**Comment by johnnliu** [comment]
Hi, you are right, I might have done it wrong last time and mistyped my cname or something, it's working as I expect today sorry!
