### ISSUE TITLE
The default out of the box Next.JS app deployed to Static Web App does not work

### ISSUE THREAD

**Issue by abhijit-me** [Azure/static-web-apps#1207]
I created the default Next.JS app using the following command and the below settings.

npx create-next-app@latest ./

Typescript - Y
ESLint - N
Tailwind - Y
Src - N
App - Y

Next version is 13.4.5 and React version is 18.2.0

I created a Static Web App with the default settings for Next.JS.

I have the following lines in the yml file.

      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "" # Built app content directory - optional
      app_build_command: 'npm run build'
      api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'

App runs fine locally and shows the default Next.JS page but I always get a blank page when I browse to the static web app. What am I missing?

**Comment by ChezMose** [comment]
If it helps:  
Next v13.4.2 does work.  
Next v13.4.6 and later do not (500 error).

**Comment by adamalfredsson** [comment]
> NextJS defaults to app dir, and Next 13 currently has some issues on Static Web Apps. We're working on a fix and will be updating you all here in the next couple of months.

Should this not be documented, [here](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#unsupported-features-in-preview) for example?

**Comment by thomasgauvin** [comment]
@adamalfredsson, we're investigating the scope of support, because it seems that some support issues is related to Next itself. Some features work on certain versions but not others as @ChezMose pointed out.

**Comment by tmaasen** [comment]
@thomasgauvin any updates on the issues causing swa not to work with Nextjs 13?
