### ISSUE TITLE
Next ISR support seems incomplete: revalidation does not occur in the background

### ISSUE THREAD

**Issue by psegalen** [Azure/static-web-apps#1208]
**Describe the bug**

I have a NextJS app hosted in a Static Web App, its output is configured as "standalone" and most of my pages have getStaticProps and getStaticPaths. I have configured ISR with a "revalidate" prop set to 600 for the getStaticProps and a "fallback" prop set to "blocking" for the getStaticPaths.
My goal is to pre-render every page at build time and have Next re-render each page if it's a new one or if its cache is more than 10 minutes old.
Everything works as intended excepted that when a page cache expires, the browser triggers a re-render which is blocking, some pages call an API which can call another API, the whole process can take up to 5 seconds, that means every 10 minutes there is a browser taking 5 seconds to get the page.
Did I miss something? Is there a piece of configuration to explicitly use in the Github Action YAML file?

**To Reproduce**
1. Create a NextJS app which requests an API taking some seconds to respond
2. Create a page with a short revalidation delay
3. Deploy it to a SWA as standalone (see config below)
4. Wait for the revalidation delay and try to request the page with your browser: your browser will be blocked the time the API responds (instead of getting the stale page while NextJS launches a revalidation in the background)

My next.config.js is the following:
```
const nextConfig = {
  reactStrictMode: true,
  images: {
    unoptimized: true,
  },
  output: "standalone",
};
```

**Expected behavior**
[The NextJS ISR doc](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration) states that a request triggering a regeneration should not be blocked, it should get the cache version and trigger the regeneration in the background.

**Comment by psegalen** [comment]
More information about this: when I run the standalone server locally, ISR is behaving like it should, an example: if I kill my local API, revalidation fails but I'm still getting the cached version of the page in my browser whereas in my Static Web App I get Next's 500 error when doing the same test which means when it's hosted in SWA it simply ignores how ISR should behave...
Is there a parameter I'm missing?

**Comment by psegalen** [comment]
One more piece of information: even modifying the `revalidation` prop on our problematic pages to something really long (6 hours) doesn't seem to have the desired effect, these pages still block requests every ~ 10 minutes... Really odd!

**Comment by thomasgauvin** [comment]
@psegalen we recently rolled out major improvements to our Next.js support, check out the announcement for full details: #1428.
ISR/on-demand cache revalidation is now supported, try it out and let us know how it goes in #1428! Closing this issue
