### ISSUE TITLE
ISR not working on Next 13 with /app folder (App Router)

### ISSUE THREAD

**Issue by zecka** [Azure/static-web-apps#1209]
## Description
Page with ISR on /app-router return an error 500. Same page on /pages folder work well

probably related to #1185 

## src/pages/random.tsx
```tsx
const RandomPage = ({ beer }: any) => {
  return <div>Random beer: {beer}</div>;
};
export async function getStaticProps() {
  const res = await fetch('https://api.punkapi.com/v2/beers/random');
  const beers = await res.json();
  const beer = beers[0].name;
  return {
    props: {
      beer,
    },
    revalidate: 10,
  };
}

export default RandomPage;
```

- Then go to http://yourapp.azurestaticapps.net/random
- Refresh the page after 10 sec and everything work well

## src/app/random-app/page.tsx
```tsx
const RandomBeer = async () => {
  const resBeer = await fetch('https://api.punkapi.com/v2/beers/random', {
    next: { revalidate: 10 },
  });
  const beers = await resBeer.json();
  const beer = beers[0].name;
  return <div>{beer}</div>;
};
export default RandomBeer ;

```
- Then go to http://yourapp.azurestaticapps.net/random-page
- Got error 500

<details>
  <summary>I also try `export const revalidate = 10;` , but doesn't work too</summary>

  ```tsx
export const revalidate = 10;
const RandomApp = async () => {
    const resBeer = await fetch('https://api.punkapi.com/v2/beers/random');
    const beers = await resBeer.json();
    const beer = beers[0].name;
    return <div>{beer}</div>;
};
export default RandomApp;
  ```
</details>

<details>
  <summary>Same page without revalidate is well display but of course never rerender</summary>

  ```tsx
const RandomApp = async () => {
    const resBeer = await fetch('https://api.punkapi.com/v2/beers/random');
    const beers = await resBeer.json();
    const beer = beers[0].name;
    return <div>{beer}</div>;
};
export default RandomApp;
  ```
</details>

**Comment by thomasgauvin** [comment]
Hi @zecka, we're working on some fixes to support Next 13. Expect an update in the next few months.

**Comment by zecka** [comment]
Got it thank's i'll will use page router instead app router.

**Comment by JarFrank** [comment]
ISR is very useful feature. I have the same issue.

**Comment by erikahumadakandc** [comment]
Hey 👋 @thomasgauvin , Any updates on this? Thanks!

**Comment by hrc7505** [comment]
I am facing similar issue

**Comment by zecka** [comment]
It seems that there is an update on this https://github.com/Azure/static-web-apps/discussions/1428
