### ISSUE TITLE
Problems updating app settings in portal

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#121]
@medhatelmasry Ran into a couple of issues while configuring app settings in the portal. I've run into this as well.

Recording here: https://youtu.be/zU1GeIUx9TY?t=1919

* Added 5 items, but only 4 appeared to have saved
* Save button is greyed out sometimes when there are outstanding changes to save

**Comment by medhatelmasry** [comment]
Thanks Anthony.

Regards,
Medhat Elmasry


*Be Kind, Be Calm, Be Safe*

**Comment by anthonychu** [comment]
@ehamai @takyyon Could you please take a quick look at this?

**Comment by takyyon** [comment]
Taking a look at this

**Comment by takyyon** [comment]
Closing this since a fix has been pushed and it is live now.
