### ISSUE TITLE
Yet again unable to debug an Angular App in VS Code

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/static-web-apps#1211]
Describe the bug

Upgraded the swa cli to the latest version and the VS Code is current too. Open an Angular app to debug it but the debugger does not launch the chrome on port 4280.

To Reproduce
Please see above.

Expected behavior
VS Code should launch the angular app and attach it to Chrome for debugging.

Screenshots
This is what logged on the debug console:

> Note: Using the "preview" debug extension
2
crbug/1173575, non-JS module files deprecated.

Device info (if applicable):

OS: macOS - ARM architecture - Windows 11 x64
Browser: Chrome
Version: The latest
Additional context
n/a
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by fiveisprime** [comment]
What version of node are you on and can you share your launch config?

**Comment by Arash-Sabet** [comment]
Not sure how but the things started working,
