### ISSUE TITLE
Azure Static Web App - random long response time issue (up to 10 seconds) cold start

### ISSUE THREAD

**Issue by denysbilozor** [Azure/static-web-apps#1215]
I have created Azure static web app with NextJS (test empty project)
https://calm-tree-034d0f210.3.azurestaticapps.net/

Sometimes it works super fast, but sometimes the server response time is 10-12 seconds?
What could be an issue?

![image](https://github.com/Azure/static-web-apps/assets/6359094/4e6e4373-a9d4-4ac5-b718-74dd52f47320)
![image](https://github.com/Azure/static-web-apps/assets/6359094/fcfeb98d-ab8a-46aa-b04c-71fc458d8672)

Azure Plan Standard
![image](https://github.com/Azure/static-web-apps/assets/6359094/b5fc0316-23c0-4d75-b7e7-3ea730c574eb)

**Comment by omer-repo** [comment]
I have same problem today in my all static web apps. What is the problem exactly and is there anything that we can do?

![stat](https://i.imgur.com/nzF8dVJ.png)

**Comment by TomEversdijk** [comment]
@omer-repo: There currently is an issue as you can see on the azure status page. https://azure.status.microsoft/en-gb/status

![Screenshot 2023-08-04 at 16 21 44](https://github.com/Azure/static-web-apps/assets/14876230/4b858a35-6285-4bd6-8348-392b8fc22c0d)

**Comment by thomasgauvin** [comment]
Closing this issue as it has been resolved. For updated info on Next.js support on Static Web Apps, check out #1428
