### ISSUE TITLE
Build fails deploying a Vue.js application to SWA

### ISSUE THREAD

**Issue by jochenkirstaetter** [Azure/static-web-apps#123]
Hi,

Recently I tried to deploy an existing Vue.js application to SWA however it fails during the build process in regards to the `fibers` dev dependency which cannot be compiled and used to complete the build. The application itself is currently hosted and operational using App Services (with production and staging slots). I would like to shift this static web app to SWA if possible.

The public repository is located here:
https://github.com/mscraftsman/mscc-jobs

API Functions are not part of the front-end project as we have an API site already running on Azure VM due to .NET Framework and legacy dependencies.

Build logs shall be informative to report the fibers related problem straight away.

Kind let me know if further details are needed and how we can improve the code base to have a successful build during deployment as SWA.

Thanks, JoKi

**Comment by miwebst** [comment]
Hi @jochenkirstaetter,

Thanks for bringing this to our attention! Looking through the logs and doing a little searching it seems like we may be missing some of the dependencies for building the fibers package. 

@kichalla can you take a look at these logs and see if there is anything we can do from the Oryx side.

**Comment by jochenkirstaetter** [comment]
Hi @miwebst 

Thanks for looking into it. Yes, that is causing the build to fail.

Meanwhile, I removed the `fibers` devDependency and run `npm update` on the repository. This way it builds and deploys as expected. The website runs now, and I'm playing with other options, like custom domain, HTTP headers, etc.

Thanks, JoKi

**Comment by miwebst** [comment]
Awesome happy to hear that! Let us know if you run into an other issues. I'll follow up with @kichalla to see if we can figure out whats going on with fibers.

**Comment by kichalla** [comment]
Hi @jochenkirstaetter, thanks for your repo link. I just now investigated the issue after checking out the commit `f322d0bad8e46724a24f90228421d2705f3762f1` (this was before you removed the `fibers` dependency) and was able to reproduce the issue that you were seeing.
Based on the log output it suggested to install some pre-reqs but they were already present in the docker image, so I tried doing `npm install` of your app in the official Node 12 image `node:12` to see if it reproduces and got errors. I later tried again after updating the `fibers` version to `5.0.0` and this time it worked in both the official `node:12` and with `oryx` (which SWA uses).

Curious, with which version of node were you able to successfully use `fibers`? For example, I noticed that your app builds fine when Node version 10 is used.

**Summary:** You can use two options from what I am seeing:
1. Update the `fibers` dependency to `5.0.0` or above
2. Use Node version `10` (I have not tested if it works with other versions too). You can explicitly specify a node version to be used by either using the `engines` field in package.json or by setting the environment variable called `NODE_VERSION` (for example: NODE_VERSION=10)

**Comment by jochenkirstaetter** [comment]
Hi @kichalla 

Thanks for the analysis.
I'm not too deep into the development of the front-end code however running the CI/CD chain.

So far I haven't noticed any drawbacks of removing the fibers dev dependency, and the code base is working perfectly.
If, for whatever reason, the `fibers` package is going to be needed, we are going to opt-in for your suggestion #1, and upgrade the code base completely to match latest Node version and recent npm packages.

IIRC, I had it running on Node 13.x on my local machine and didn't observe anything similar.

Anyways, let's close this issue.

Thank you so much for your time and analysis.

Best regards, JoKi
