### ISSUE TITLE
Unable to deploy Vite React app with TypeScript (node 18) API

### ISSUE THREAD

**Issue by andrew-goldie** [Azure/static-web-apps#1233]
Build of the static app and the API seems to finish OK, but then packaging artefacts for deploy of the managed Azure function fails with the error as attached.

The API function is a very simple contact-us handler than uses the mailjet node library. I have successfully deployed the site previously - the only changes being to the front-end React app and no changes to the API.

I am using v4 Azure functions and targeting node 18 runtime.

![image](https://github.com/Azure/static-web-apps/assets/29654110/a8d0b868-9db8-4d08-80e5-2e30e7e3fb54)

**Comment by andrew-goldie** [comment]
Seems like the error messages are not related to the core problem which was a TypeScript build failure due to my own bug. Closing as no longer an issue.

**Comment by CCisGG** [comment]
Hi may I ask what is your output location? I explicitly set it to "build" folder but azure always detect it as "/" and says not found index.html. I thought it was a React specific issue

**Comment by andrew-goldie** [comment]
For a vite-based React app the application root is / and the default output location is /dist
