### ISSUE TITLE
Routes are not built on Next 13

### ISSUE THREAD

**Issue by Abbbdab** [Azure/static-web-apps#1236]
We have a Next 13 app running Next 13.4.2. We are using Azure repo and Azure build pipeline to build the app. 
There are currently two issues, the deployment fails because of the size, which I have tried to circumvent by removing cached files as mentioned in [issue #1034 ](https://github.com/Azure/static-web-apps/issues/1034).

The second thing I noticed is the pages are not generated, as per the screenshot attached. 
<img width="648" alt="Screenshot 2023-07-31 at 8 26 59 pm" src="https://github.com/Azure/static-web-apps/assets/25984969/2d996c81-463f-4aba-b13d-7db42873d6ff">

I have tried everything, and currently have exhausted all the options.

**Comment by thomasgauvin** [comment]
@Abbbdab, for the size limitation, I'm glad you were able to resolve it with that issue, alternatively, we recommend enabling standalone https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#enable-standalone-feature

Your application pages not being built seems like this may be a NextJS-related issue. Is the issue also happening when you build locally? If so, perhaps there is a NextJS config that is preventing static page generation, and instead resulting in some type dynamic page generation

**Comment by anish-dev-127** [comment]
same issue not able to deploy nextjs 13.4 with appRouter. deployment failed every time. please give me solution

**Comment by thomasgauvin** [comment]
Hi folks! This issue is now resolved with our improvements to Next.js support on Static Web Apps, with support for Next.js 13 & 14 and further features. I'll be closing this thread, please try out the newest improvements and let us know how it goes in the announcement thread: https://github.com/Azure/static-web-apps/discussions/1428
