### ISSUE TITLE
Deploy of gridsome fails with images in LFS

### ISSUE THREAD

**Issue by CHH** [Azure/static-web-apps#124]
Hi, I'm trying to deploy a Gridsome site and I'm getting this error in the Github Action:

```
$ gridsome build
Gridsome v0.7.19

Initializing plugins...
Load sources - 0.1s
Create GraphQL schema - 0.14s
Create pages and templates - 0.06s
Error: Failed to process image src/images/TouchIcon.png. Input buffer contains unsupported image format
    at ImageProcessQueue.preProcess (/bin/staticsites/ss-oryx/app-int/node_modules/gridsome/lib/app/queue/ImageProcessQueue.js:81:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by h2xd** [comment]
@CHH Why did you closed the issue, I'm running into the same error and would kindly ask you: **How did you fixed this issue?**

Greets, Andrej :)

**Comment by CHH** [comment]
@h2xd Hi Andrej, I closed this because it was an error on my part and no bug with Azure Static Web Apps. I fixed this simply by adding `lfs: true` to the `checkout` Action in the GitHub Workflow file. 

Hope this helps, Christoph :)

**Comment by h2xd** [comment]
@CHH Thanks Christoph! Same issue in my side, just found it. :D

Cheers, Andrej
