### ISSUE TITLE
Module not found: Error: Can't resolve 'react-router-dom' in '/github/workspace/src'

### ISSUE THREAD

**Issue by dsevenx** [Azure/static-web-apps#1248]
**Describe the bug**

I have a react APP - build with yarn. I get in the "github actions this":
Running 'yarn run build'...

yarn run v1.22.15
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'react-router-dom' in '/github/workspace/src'

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

**To Reproduce**
commit a file (like readme.txt) to 
https://github.com/dsevenx/cubewm
and go to github actions

OR 

create local from the scratch :

npx create-react-app cubewm
cd cubewm
yarn install
yarn upgrade react@latest
sudo yarn add react-bootstrap bootstrap
sudo yarn add react-image-gallery
yarn run start

-> this all to a  git-Repo and make with an azure-static-web a resource

**Expected behavior**

succesful build

**Screenshots**
look in the github actions

**Device info (if applicable):**
local on MAC OS everything is fine

**Additional context**

**Comment by dsevenx** [comment]
Problem is solved, when i install  "react-router-dom --save" - it does not matter yarn or npm.

Sad is that the problem does not occur local.

**Comment by seba-campo** [comment]
Thanks, it was useful for my project too!
