### ISSUE TITLE
Warning message when repository uses LFS

### ISSUE THREAD

**Issue by CHH** [Azure/static-web-apps#125]
Hi, I'm using Git-LFS for the images in a project and the generated Github workflow didn't work out of the box. 

It would be helpful to generate a warning message in the build log when LFS objects are present, but the repository wasn't checked out with `lfs: true`.

**Comment by miwebst** [comment]
Hi @CHH ,

Thanks for bringing this to our attention! We can look at how to make this experience better. What was the resulting behavior in this case? Were certain files missing?

**Comment by CHH** [comment]
Thanks for the reply @miwebst! 

My static site generator (Gridsome) threw a very weird error related to image processing, which turned out hard to debug. First I thought it was an issue with the NPM package `sharp`, but then I remembered a similar issue with Netlify. Then I enabled `lfs: true` in the checkout action and everything worked.

**Comment by miwebst** [comment]
Makes sense; we can take a look to see if there is anything we can do to make this experience better!
