### ISSUE TITLE
Next.js rewrite no longer working on swa since v13.4.13

### ISSUE THREAD

**Issue by bertrand-riviere** [Azure/static-web-apps#1261]
**Describe the bug**

The rewrite is broken since Next.js v13.4.13 (both using next.config.js and middleware.js).
Using Next.js v13.4.12 the rewrite works as expected.

**To Reproduce**

I have created a minimal repo to reproduce the issue https://github.com/bertrand-riviere/nextjs-swa-rewrite-bug
The app is deployed as a swa: https://orange-water-06ec3c503.3.azurestaticapps.net

**Expected behavior**

The rewrite to work: for instance browsing https://orange-water-06ec3c503.3.azurestaticapps.net/page-a should display "Page B" (just like in https://orange-water-06ec3c503.3.azurestaticapps.net/page-b).

**Additional context**

I use the App Router.

**Comment by sebastian-worcay** [comment]
Same problem here. Results in the middleware not working for me as well. For example rewriting for internationalization in middleware.

**Comment by bertrand-riviere** [comment]
Hello,
Any news on this bug?
Btw, I have tested the latest NextJs version (1.5.2) and it still does not work

**Comment by sebastian-worcay** [comment]
Same here, rechecked on 13.5.4 and still an issue.

**Comment by MadHabber** [comment]
This is also broken under Azure Web Apps within a Docker Node 18 container. The Next JS project had a "revert to a revert" around the router right before 13.4.13 was deployed. I am guessing it is in their code. =(

**Comment by bertrand-riviere** [comment]
> This is also broken under Azure Web Apps within a Docker Node 18 container. The Next JS project had a "revert to a revert" around the router right before 13.4.13 was deployed. I am guessing it is in their code. =(

Well, could be... but in this case I don't get why it would work locally, on Vercel, etc...

**Comment by TheOriginalBD** [comment]
This bug persists in Next JS 14.0.3.
As previously mentioned the rewrites still work locally and on Vercel but not on Azure SWA.

**Comment by IanIsFluent** [comment]
I'm seeing my rewrites not work in an Azure Static Web App running Next 14.0.2. Has this bug been noticed by Microsoft, yet?

**Comment by rduque1** [comment]
Same problem here

**Comment by thomasgauvin** [comment]
Hi folks! This issue is now resolved with our improvements to Next.js support on Static Web Apps, with support for Next.js 13 & 14 and further features. I'll be closing this thread, please try out the newest improvements and let us know how it goes in the announcement thread: https://github.com/Azure/static-web-apps/discussions/1428
