### ISSUE TITLE
After successfully creating Static Web App, workflow reports an error: "Platform 'dotnet' version '8.0' is unsupported."

### ISSUE THREAD

**Issue by v-reinawang** [Azure/static-web-apps#1273]
**Azure DevOps work item**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1885646

**TESTCASES AFFECTED**
Publish to Azure Static Web Apps

**Platform**
- [x] Windows
- [ ] Linux
- [ ] Mac

**INSTALL STEP**
1. Clean machine: Win11 x64 22h2 ENU 
2. Install Dev17.8 Preview 3, Preview channel

      - Web workload
      - Includes SDK 8.0.100-rc.1.23455.8

**REPRO STEPS**
1. File > New> Project > Blazor WebAssembly App > Next > .NET 8.0 > Create
2. Right click Solution > Create Git Repository > GitHub, Verify your GitHub account your GitHub > Create and Push
4. Right click project > Publish > Azure > Azure Static Web Apps > Click 'Create new', will open [portal](https://ms.portal.azure.com/#create/Microsoft.StaticApp) and then create a Static Web App as follow:
    ![image](https://github.com/Azure/static-web-apps/assets/109339894/bf70c703-29f6-466c-b979-cf37a13ddbd0)

    Repository select the repo just created and update the App location to the name of the project that was created
    ![image](https://github.com/Azure/static-web-apps/assets/109339894/3abaa405-84be-4523-b776-1f1c01a04ead)

5. After successful creation, click Go to resource, clicking on the sentence below will open the GitHub
    ![image](https://github.com/Azure/static-web-apps/assets/109339894/addd1fa7-b1f2-44ca-961c-b6cf4a4f72c0)

6. After a while, it will be displayed that the creation of workflow runs failed with error
    ![image](https://github.com/Azure/static-web-apps/assets/109339894/7e588ee0-509c-4869-9b01-f9b7de5c52f6)

7. Click on this workflow file, then click Build and Deploy Job
    ![image](https://github.com/Azure/static-web-apps/assets/109339894/b3400480-a47e-4d3c-a676-8c8ecd1a16b7)

**ACTUAL**
It will be displayed that the creation of workflow runs failed with error:
Error: Platform 'dotnet' version '8.0' is unsupported. Supported versions: 3.1.10, 3.1.11, 3.1.12, 3.1.13, 3.1.15, 3.1.17, 3.1.18, 3.1.21, 3.1.23, 3.1.25, 3.1.26, 3.1.28, 3.1.29, 3.1.31, 3.1.32, 6.0.0-preview.1.21102.12, 6.0.0-preview.2.21154.6, 6.0.0-preview.3.21201.4, 6.0.0-preview.4.21253.7, 6.0.0-preview.5.21301.5, 6.0.0-preview.6.21352.12, 6.0.0-preview.7.21377.19, 6.0.0-rc.1.21451.13, 6.0.0-rc.2.21480.5, 6.0.0, 6.0.3, 6.0.5, 6.0.6, 6.0.8, 6.0.9, 6.0.11, 6.0.12, 6.0.13, 6.0.14, 6.0.15, 6.0.16, 6.0.18, 6.0.19, 6.0.20, 6.0.21, 7.0.0-preview.1.22076.8, 7.0.0-preview.5.22301.12, 7.0.0-preview.6.22324.4, 7.0.0-preview.7.22375.6, 7.0.0-rc.1.22426.10, 7.0.0-rc.2.22472.3, 7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.0.4, 7.0.5, 7.0.7, 7.0.8, 7.0.9, 7.0.10, 1.0.16

---End of Oryx build logs---
Oryx has found build steps, but identified unsupported platform versions. Failing build.
![image](https://github.com/Azure/static-web-apps/assets/109339894/7bc99d24-fd83-4c50-97db-c75f3738efe6)

**EXPECTED**
Platform 'dotnet' version '8.0' is supported.

**Comment by balachir** [comment]
We now have a bug in VS to track this - [Bug 1885646](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1885646): [WebToolsE2E] [SWA] After successfully creating Static Web App, workflow reports an error: "Platform 'dotnet' version '8.0' is unsupported." and Antonio is following up with the Oryx team.

**Comment by v-reinawang** [comment]
Verify this issue is fixed, so close it.
