### ISSUE TITLE
Next.js with standalone - The size of the function content was too large. The limit for this Static Web App is 104857600 bytes.

### ISSUE THREAD

**Issue by mg-aceik** [Azure/static-web-apps#1274]
**Describe the bug**

Using Next.js with standalone - getting error `The size of the function content was too large. The limit for this Static Web App is 104857600 bytes.`

**To Reproduce**
See public repo and github action.
https://github.com/Aceik/XmCloud.PlaySummit/actions/runs/6168748518/job/16741759637

**Expected behavior**
Building locally shows that the .next/standalone folder is 71MB, well under the 100MB limit.

**Comment by alexrabin** [comment]
You may need to remove the nextjs cache after the build.

Replace your build command with:

```json
    "build": "next build && rm -rf ./.next/cache",
```

**Comment by thomasgauvin** [comment]
Hey folks! Next.js deployments now support app sizes up to 250 mb and can be further reduced by using standalone. See all details in our latest announcement: https://github.com/Azure/static-web-apps/discussions/1428

Closing this issue
