### ISSUE TITLE
/api should not be blocked in apps that don't have functions

### ISSUE THREAD

**Issue by mattetti** [Azure/static-web-apps#129]
I create a new Hugo static app that I deployed using ASWA and everything went well except that I can't access my API docs because they are under `/api/`. I don't have any functions so that's a bit of an unexpected behavior. Since I don't know how to fix this issue, I had to change the page to my API docs which isn't ideal.

**Comment by miwebst** [comment]
Hi @mattetti, totally agree. I will add something to our backlog to get this fixed!

**Comment by miwebst** [comment]
This should be fixed now! Please let us know if it is not.
