### ISSUE TITLE
Azure CLI support?

### ISSUE THREAD

**Issue by empz** [Azure/static-web-apps#13]
It would be great if a basic version of working with Static Web Apps would be included in some form in Azure CLI.

The GitHub requirement is a bit awkward. 
Ideally, we should be able to run a simple az cli command to push a folder into an Azure Static Web App. 
Also, a command to "promote" a specific deployment to production.

**Comment by dariagrigoriu** [comment]
Thank you for the feedback, we will update on Azure CLI progress.

**Comment by anganti** [comment]
Though we don’t have what you have exactly asked for (which is in progress to push a folder to deploy)

The CLI is released and can be downloaded through the official site: 
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-windows?view=azure-cli-latest&tabs=azure-cli

Documentation can be found here: https://docs.microsoft.com/en-us/cli/azure/staticwebapp?view=azure-cli-latest

**Comment by anthonychu** [comment]
Deploy from zip via CLI is tracked here: #7

**Comment by anthonychu** [comment]
Closing this in favor of #7. We don't currently have plans to support promoting between environment. Please create a new issue for it if it's still relevant. Thanks!
