### ISSUE TITLE
Renamed GitHub Project Name, Build and Deploy Now Failing

### ISSUE THREAD

**Issue by theonewolf** [Azure/static-web-apps#130]
I noticed in the past two days after we renamed our project on GitHub, our deploys are failing in the Workflow at stage "Build and Deploy" with the message:

```
The content server has rejected the request with: BadRequest
Reason: No matching static site was found or the api key was invalid.
```

1. Is there any method of updating our static web app configuration to the new GitHub URL?  If that is causing the issue.
2. Or, is there a way of regenerating our API token / key to make it valid again?
3. Or, do we need to delete our Azure Static Web App in the Azure portal, and remake it with the new GitHub repository?

**Comment by miwebst** [comment]
This is a known issue that we have a fix rolling out for, unfortunately it is not based on the actual api key but rather a problem with some of our metadata. The easiest (although this is painful right now) option is to just delete your static web app and the corresponding workflow file, then recreate it against this repository. No need to create a new repository.

In the future (once our fix is deployed), you will be able to safely change the name of the repo and if you were to hit this sort of issue, resetting the api key will fix this.

**Comment by theonewolf** [comment]
@miwebst thank you for the quick answer.  I will recreate today and let you know how it goes.

**Comment by theonewolf** [comment]
This worked!  Two painpoints:

1. We now have to re-auth users, regenerate invite URLs, and have them re-grant permissions to a new web app.
2. Extra painful because there is not user import feature yet I don't think with auto-email invites.

**Comment by miwebst** [comment]
Ouch, ya re-adding all the users would be painful. We need to improve this story. Thanks for reporting this!

**Comment by mrgenesis** [comment]
> This is a known issue that we have a fix rolling out for, unfortunately it is not based on the actual api key but rather a problem with some of our metadata. The easiest (although this is painful right now) option is to just delete your static web app and the corresponding workflow file, then recreate it against this repository. No need to create a new repository.
> 
> In the future (once our fix is deployed), you will be able to safely change the name of the repo and if you were to hit this sort of issue, resetting the api key will fix this.

My God! After hours searching... were only this? Thank you @miwebst.

**Comment by sinedied** [comment]
@miwebst Was there an update regarding this issue? Is it safe now to rename your project on GitHub?

**Comment by miwebst** [comment]
It is safe to do so, as long as you have either created the static web app since GA or rotated your deployment token then you should be good.

**Comment by Hub-Mo** [comment]
I still get this problem in 2025. creating a new SWA didnt help either :(
