### ISSUE TITLE
The content server has rejected the request with: InternalServerError

### ISSUE THREAD

**Issue by dindak** [Azure/static-web-apps#131]
Recently our SWA deployments have not been successful. We've retried 5 times today, and gave it some time to determine if it was temporary. Currently using `Azure/static-web-apps-deploy@v0.0.1-preview` in an action step.

Let me know if additional log snippets would help, if I should be contacting a different team, or if there is a potential issue with our SWA instance. Thanks!

20 minutes ago:
```
Finished building app with Oryx
Found and validated 'routes.json' within build artifacts folder.
Zipping App Artifacts
Done Zipping App Artifacts
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
The content server has rejected the request with: InternalServerError
Reason: An unexpected error has occurred. Please try again later.
```

7 days ago:
```
Finished building app with Oryx
Found and validated 'routes.json' within build artifacts folder.
Zipping App Artifacts
Done Zipping App Artifacts
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.2525046(s)
Status: InProgress. Time: 15.5339972(s)
Status: Succeeded. Time: 30.7615721(s)
Deployment Complete :)
```

**Comment by miwebst** [comment]
Hi @dindak, sorry to hear that y'all are running into issues! This is the right place to come to :) 

Can you share some of the information regarding your SWA instance so we can check out whats going on? If you can provide the region where this static web app is and the generated hostname that would be perfect - we will be adding an issue template soon.

**Comment by christiandornetto** [comment]
I have the exact same issue. Failed a build from a pull request and after correcting the error I cannot publish the application to the either the PR env or to the main env.

**Comment by christiandornetto** [comment]
Here's more:

When I try to browse the production url, it actually takes me to the pull request staging environment (which doesn't exist as you can see from the screenshot).

![image](https://user-images.githubusercontent.com/38754730/90402701-bcc60900-e097-11ea-9182-57cb21b33e3c.png)

**Comment by dindak** [comment]
> Hi @dindak, sorry to hear that y'all are running into issues! This is the right place to come to :)
> 
> Can you share some of the information regarding your SWA instance so we can check out whats going on? If you can provide the region where this static web app is and the generated hostname that would be perfect - we will be adding an issue template soon.

Thanks @miwebst !

Region: Central US
Hostname: https://jolly-mushroom-0be828310.azurestaticapps.net

@christiandornetto has a good lead, one of our recent pull requests failed to create a new staging environment. This was a PR deploy log from 4 days ago:

```
Finished building app with Oryx
Found and validated 'routes.json' within build artifacts folder.
Zipping App Artifacts
Done Zipping App Artifacts
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.2691926(s)
Status: InProgress. Time: 15.5148754(s)
Status: InProgress. Time: 30.8334313(s)
Status: InProgress. Time: 46.0713209(s)
Status: InProgress. Time: 61.278271(s)
Status: InProgress. Time: 76.579716(s)
Status: InProgress. Time: 91.827408(s)
Status: InProgress. Time: 107.0330159(s)
Status: InProgress. Time: 122.110046(s)
Status: InProgress. Time: 137.301288(s)
Status: InProgress. Time: 152.5596787(s)
Status: InProgress. Time: 167.82938(s)
Status: InProgress. Time: 183.7570035(s)
Status: InProgress. Time: 198.9128616(s)
Status: InProgress. Time: 214.2297953(s)
Status: InProgress. Time: 229.5430492(s)
Upload Timed Out. Unsure if deployment was successful or not.
```

**Comment by miwebst** [comment]
So this is actually being caused by new Github Action behavior: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ 

We will work to get this fixed, sorry for the inconvenience!

**Comment by dindak** [comment]
> So this is actually being caused by new Github Action behavior: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/ 
> 
> 
> 
> We will work to get this fixed, sorry for the inconvenience! 

Ah that makes sense, thanks! Is there any workaround at this time, or should I just try to recreate a new SWA instance - with fork PR builds turned off?

**Comment by miwebst** [comment]
We have a fix rolling out that will fix the bad environment issue but it will take a few weeks before that is live. If you dont mind you can get around this by recreating with a new SWA instance.

P.S. the initial bug that caused the bad staging environment is now fixed. You can access the secrets during a pull request from a fork.

**Comment by dindak** [comment]
The rolling fix resolved my existing swa issues. Thanks for the quick turnaround @miwebst!
