### ISSUE TITLE
Hybrid/Universal/Auto rendering for .NET 8 Blazor 

### ISSUE THREAD

**Issue by indcoder** [Azure/static-web-apps#1332]
**Is your feature request related to a problem? Please describe.**
With Blazor in .net 8, supporting auto render [SSR -> Client Interactivity ] , looking to SWA to support this renderinh

**Describe the solution you'd like**
Just like for [Next.js-React](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid) and [Nuxt.js-Vue](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nuxtjs), we are looking to support the same capability for Blazor that now supports these multiple modes. Since this will increase the site performance and SEO.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by thomasgauvin** [comment]
Hi @indcoder, Blazor supports WASM deployment to SWA, but auto-render require servers and deployments to App Service.
