### ISSUE TITLE
Blazor 8.0.100-rc.2.23502.2 works until I need the 'wasm-tools' workload & Blazor 8 release

### ISSUE THREAD

**Issue by michaelvolz** [Azure/static-web-apps#1334]
**Describe the bug**

Background: Some Safari versions seem to dislike the SIMD implementation of Blazor/WASM.

After inserting `<WasmEnableSIMD>false</WasmEnableSIMD>` into the `project.csproj` the `wasm-tools workload` is needed. The GitHub action now throws this error:

```
/opt/dotnet/8.0.100-rc.2.23502.2/sdk/8.0.100-rc.2.23502.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: wasm-tools [/github/workspace/redmuffin.Blazor.Static/redmuffin.Blazor.Static.csproj]
/opt/dotnet/8.0.100-rc.2.23502.2/sdk/8.0.100-rc.2.23502.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore 
```

**To Reproduce**
1. Create new Blazor (8.0.100-rc.2.23502.2) WebAssembly project
2. Insert `<WasmEnableSIMD>false</WasmEnableSIMD>` into the `project.csproj`
3. use GitHub Action to deploy to Azure Static WebApps

**Expected behavior**
GitHub Action deploying without error

**Additional context**
I tried different combinations from installing `dotnet 8.0.100-rc.2.23502.2` via `actions/setup-dotnet@v3` and `dotnet workload install wasm-tools` or `dotnet workload restore` before `Azure/static-web-apps-deploy@v1` without success.

**Comment by thomasgauvin** [comment]
Hi @michaelvolz, thanks for reporting this, we're looking into it. Based on preliminary research, this is caused by a bug in Oryx (the engine we use to build SWA projects), and we've communicated this to them. When they release a bug fix, we will fix this for SWA builds as well.

**Comment by DaleCam** [comment]
Please Note - the same issue applies also to adding:
`<RunAOTCompilation>true</RunAOTCompilation>` 
into the csproj being published.

**Comment by thomasgauvin** [comment]
@DaleCam we're working on the fix for this for Blazor & .NET 8, will keep this thread updated when it rolls out

**Comment by crazyfox55** [comment]
What is the work around for deploying with GitHub actions? 

Can I just use dotnet build, dotnet publish, ect? I'm not sure what the actual commands are. If you have a link to a tutorial that doesn't use the static-web-apps-deploy action that would be great.

**Comment by michaelvolz** [comment]
@crazyfox55 I haven't found a workaround. Still waiting.

Using the normal actions and on top a special action for uploading would be fantastic. Would give the most flexibility.

**Comment by DaleCam** [comment]
This seems to be fixed for me now! Thanks Guys!

**Comment by euhm** [comment]
Hey @DaleCam , what was the fix if I may ask? Still blocked at rolling out an app to older iOS devices.

Thanks!

**Comment by DaleCam** [comment]
Hi @euhm, I was deploying to an Azure Static Web App via Azure Devops. At some point the Deployer that Azure uses for Blazor Static Web Apps was updated, and the issue resolved for me. Now I can deploy without any issues within the Azure environment. I hope that helps. (I am using .NET 8.0.3)

**Comment by michaelvolz** [comment]
After a long hiatus, I can report that my problem also is resolved.
