### ISSUE TITLE
Oryx built the app folder but was unable to determine the location of the app artifacts. Please specify the app artifact location

### ISSUE THREAD

**Issue by 11SolutionsPvtLtd** [Azure/static-web-apps#1336]
**React App is failing to deploy**

**To Reproduce**
1. Go to 'https://github.com/11SolutionsPvtLtd/tf-website/actions/runs/6853282829/job/18633749827'
2. Click on 'Build and Deploy Job'
3. Scroll down to 'Oryx built the app folder but was unable to determine the location of the app artifacts. Please specify the app artifact location.'

[staticwebapp.config.json](https://github.com/Azure/static-web-apps/files/13338458/staticwebapp.config.json)
[yml.txt](https://github.com/Azure/static-web-apps/files/13338479/yml.txt)

**Expected behavior**
React App should be deployed in Azure Static Web App.

**Screenshots**
[logs_12.zip](https://github.com/Azure/static-web-apps/files/13338614/logs_12.zip)

**Device info (if applicable):**
NA

**Additional context**
NA

**Comment by thomasgauvin** [comment]
Hi, the GitHub repository you are sharing isn't available. Can you verify that you have the correct output location set in your GitHub Actions workflow file? https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions

**Comment by 11SolutionsPvtLtd** [comment]
Hi @thomasgauvin ,

I gave you the permission to our repository. I also verified the location and try to change and got the failure. I noticed 2 issues in logs which I shared in previous attachement.

a) There's node module dependency warning which shouldn't give this issue.
b) It's showing in the log that it's copying the build output in a location. And getting the failure when it's trying to read it again from that.

Please see below error.

Copying files to destination directory '/bin/staticsites/cd5e512e-d825-49d3-8c36-357fb0d0fa59-swa-oryx/app'...
Done in 11 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.
Copying .ostype to manifest output directory.

Done in 118 sec(s).


---End of Oryx build logs---
Try to validate location at: '/bin/staticsites/cd5e512e-d825-49d3-8c36-357fb0d0fa59-swa-oryx/app'.

Here, we have used mantinedev template.
https://github.com/mantinedev/vite-template
