### ISSUE TITLE
'deployment_token was not provided.' error when using Dependabot and pull-requests.

### ISSUE THREAD

**Issue by michaelvolz** [Azure/static-web-apps#1342]
**Describe the bug**

Building and deploying works when committing normally. 
But when Dependabot creates a new PR, the action fails with this error message:

```
deployment_token was not provided.
The deployment_token is required for deploying content. If you'd like to continue the run without deployment, add the configuration skip_deploy_on_missing_secrets set to true in your workflow file
An unknown exception has occurred

```

**To Reproduce**
1. Add Dependabot
2. Wait for outdated library to be updated
3. Look at the PR

**Expected behavior**
The PR should be valid, and the action should have successfully built but not deployed

**Additional context**
The deployment token works fine when committing new changes.

**Comment by Izzmo** [comment]
I think this is a duplicate, but yes this is frustrating.

**Comment by michaelvolz** [comment]
@Izzmo good info. Do you have any suggestions how to fix this, or is it not possible for me to do something?

**Comment by skystedt** [comment]
@michaelvolz You should be able to add the secrets to Dependabot
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#adding-a-repository-secret-for-dependabot

**Comment by michaelvolz** [comment]
@skystedt thank you!! That solved my problem! Good to know. This information should maybe make available somehow in the workflow.
