### ISSUE TITLE
Routing in Azure static web apps

### ISSUE THREAD

**Issue by MohammadBoushi** [Azure/static-web-apps#1345]
I want to configure the routing on the Azure static web app where my Angular app is deployed so that the following configuration works as expected.
My staticwebapp.config.json
```
`{
    "routes": [
        {
            "route": "/old-route/page/",
            "redirect": "/new-route/page/",
            "statusCode": 301
        },
        {
            "route": "/old-route/page/:filepath",
            "redirect": "/new-route/page/:filepath",
            "statusCode": 301
        },
        {
            "route": "/old-route/page/{id}",
            "redirect": "/new-route/page/{id}",
            "statusCode": 301
        },
        {
            "route": "/old-route/page/:path*.aspx",
            "redirect": "/new-route/page/:path",
            "statusCode": 301
        }
    ],
    "navigationFallback": {
        "rewrite": "/index.html",
        "exclude": [
            "*.{css,scss,png,gif,ico,jpg,svg}"
        ]
    } 
}`
```
The first one works as expected.
The second and third should be redirected to "/new-route/page/:filepath" with the filepath or ID. but nothing of them works as expected. The fourth one should be redirected to "/new-route/page/:path" without extension. but all are not working as expected except the first one.

is my configuration correct and is there any way to overcome this issue?

**Comment by rmihael** [comment]
Hi! Have you managed to make it work somehow?

**Comment by MohammadBoushi** [comment]
Hi @rmihael 

yes
