### ISSUE TITLE
After Build Finished:  Node version 20.9.0 is not supported. Please use one of the following versions 12, 14, 16, 18.   

### ISSUE THREAD

**Issue by SirRobin67** [Azure/static-web-apps#1349]
Failed after build of Azure static web service.  Not a lot of detail in the error.

---End of Oryx build logs---
Try to validate location at: '/bin/staticsites/0eb197a4-d222-477e-a851-c0c1c72645fb-swa-oryx/app/build'.
Finished building app with Oryx
Node version 20.9.0 is not supported. Please use one of the following versions 12, 14, 16, 18.

Additionally I searched the entire code base for >=20   It does not exist.

**Comment by tkhv** [comment]
To specify that your project should use Node.js 18, you can set the "engines" field in your package.json file like this:

```
"engines": {
  "node": "18.17.1"
},
```

**Comment by SirRobin67** [comment]
Thank You for the help. Greatly appreciated   

I did have the engines in the package.json but it was ignoring it because it was in the wrong section.   Just so anyone can benefit.  Here is a example of where it goes.

 "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "eslint": "^8",
    "eslint-config-next": "14.0.3"
  },
  "engines": {
    "node": "18.17.1"
  }
