### ISSUE TITLE
Angular SPA 404

### ISSUE THREAD

**Issue by Raisinpit** [Azure/static-web-apps#135]
I'm working on a SPA Angular app and I'm having an issue; when not on the base url a reload of the page(F5) results in a 404. 
Previously when hosting in blob storage I could set a flag to redirect to the index.html and this would resolve the issue. 
There doesn't seem to be a similar option for Static Web Apps.

**Comment by miwebst** [comment]
I imagine you have not added fallback routes, take a look at the docs here: https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api/6-exercise-fallback-routes?pivots=angular

**Comment by Raisinpit** [comment]
@miwebst I did not, once added it worked fine. Thanks for your help! I'll be adding it to our repositories.
