### ISSUE TITLE
Broken image, Next.js App

### ISSUE THREAD

**Issue by hamza-bm-sbg** [Azure/static-web-apps#1352]
Hello, I'm new to deploying in Azure and I could use some help

After deploying Next.js App to Azure swa, I found out that the images are broken.

![2023-11-27_135341](https://github.com/Azure/static-web-apps/assets/138494223/2ed7c924-3cbf-4e18-aeff-99b5bacf71f7)

I am using Image component of next/image and pointing to images in public folder like: src="/me.png"

I deployed the app by accessing the Azure portal, creating swa and linking it to the project github repo

**Configuration:*

- package.json:
 next: 14.0.3,
node: 18.17.1

- next.config.js:
 output: "standalone",
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "**.azurestaticapps.net",
      },
    ],
  },

**Comment by rbourdon** [comment]
Any more detail you can find in application insights? Have you tried Next.js 13.4.12? There are currently some major issues with versions after this in Azure SWA.

**Comment by hamza-bm-sbg** [comment]
> Any more detail you can find in application insights? Have you tried Next.js 13.4.12? There are currently some major issues with versions after this in Azure SWA.

I tried with Next.js 13.4 and had the same issue

**Comment by exaucae** [comment]
did you end up with a workaround, @hamza-bm-sbg ?

**Comment by MertHaddad** [comment]
related : https://github.com/vercel/next.js/issues/34310

any update? @hamza-bm-sbg

**Comment by hamza-bm-sbg** [comment]
Sorry for the late response, we moved our project on DigitalOcean and installed it on a Droplet and everything worked fine.

Hope someone else could find a solution for Azure SWA

**Comment by mukeysh-k** [comment]
any solution?

**Comment by julian-gallo-nexer** [comment]
I am having the same issue in NextJs 14.0.4, I have tried several ways as shown bellow but none of the have worked to fix broken images in Azure static web app 
```htmx
import logo from "@/public/assets/icons/aurora_icon.png";
import logo2 from "../../../public/assets/icons/aurora_icon.png";

<Image 
    src={logo} 
    alt="image" 
    width={80} 
    height={80} 
/>

<Image
    src={logo2}
    alt="image"
    width={80}
    height={80}
  />

  <Image
    src={"../../../public/assets/icons/aurora_icon.png"}
    alt="image"
    width={80}
    height={80}
  />

  <Image
    src={"@/public/assets/icons/aurora_icon.png"}
    alt="image"
    width={80}
    height={80}
  />

  <Image
    src={"/assets/icons/aurora_icon.png"}
    alt="image"
    width={80}
    height={80}
  />
```

**Comment by reneruiz** [comment]
We couldn't find any solutions so we ended up just shutting off the image optimization in `next.config.js`.

**Comment by Ali-Gator** [comment]
I think that is because `standalone` option.

Here is from [doc](https://nextjs.org/docs/pages/api-reference/next-config-js/output):

This will create a folder at .next/standalone which can then be deployed on its own without installing node_modules.

Additionally, a minimal server.js file is also output which can be used instead of next start. This minimal server does not copy the public or .next/static folders by default as these should ideally be handled by a CDN instead, although these folders can be copied to the standalone/public and standalone/.next/static folders manually, after which server.js file will serve these automatically.

So I guess it needs to copy the whole `public` folder to remote server after deploying.

**Comment by thomasgauvin** [comment]
Hey folks! We shipped major improvements to our Next.js support on Static Web Apps recently, announcement thread is #1428. This issue is now resolved, try it out and let us know how it goes in #1428! Closing this issue

**Comment by antony-jr** [comment]
If anyone wants a quick fix, just want to use static webapp (instead of a hybrid app), simply use **unoptimized next/image**. (in nextjs config, output: 'export')

```
 <Image unoptimized .../>
```

Profit :money_mouth_face: 

Source: https://nextjs.org/docs/pages/api-reference/components/image#unoptimized

**Comment by marcodali** [comment]
Solution link: https://github.com/vercel/next.js/issues/60161#issuecomment-2195324832
