### ISSUE TITLE
Deploy Fails for .NET 8 Azure Functions

### ISSUE THREAD

**Issue by scottkuhl** [Azure/static-web-apps#1353]
**Describe the bug**

After updating the Api project in a Blazor template from .NET 7 to .NET 8 the deploy fails.

**To Reproduce**
1. Create a new SWA project which will default to .NET 7.
2. Change the settings.json file to: 
    `"azureFunctions.deploySubpath": "Api/bin/Release/net8.0/publish",`
3. Change the Api.csproj file to:
```
    <TargetFramework>net8.0</TargetFramework>
...
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
```
4. Commit the changes to GitHub and let the action run and you will get this during the deploy:

```
Deployment Failed :(
Deployment Failure Reason: Failed to deploy the Azure Functions.
```

**Expected behavior**
The application deploys the Azure Functions running on .NET 8.

**Comment by thomasgauvin** [comment]
@scottkuhl, functions are working on some improvements to improve their deployments for .NET 8. Right now, as a temporary workaround, downgrading Microsoft.Azure.Functions.Worker.Sdk to 1.15.1 helps but still is flaky at times. Check out my repo with the temporary workaround https://github.com/thomasgauvin/BlazorOnSWA

We expect Functions to roll out these changes later this week, for deployments to go without a hitch regardless of Microsoft.Azure.Functions.Worker.Sdk version

**Comment by thomasgauvin** [comment]
Hey @scottkuhl, we rolled out some changes to Functions regions West US 2, East US 2, West Europe and East Asia. These regions have the fix in place, see this repo https://github.com/thomasgauvin/Blazor-SWA-demo/actions fix coming to Central US

**Comment by scottkuhl** [comment]
@thomasgauvin Thanks, my app is in Central US, so I will test the update when it gets there.

**Comment by thomasgauvin** [comment]
Excellent, thanks for the confirmation @scottkuhl!
