### ISSUE TITLE
How to make authentication work?

### ISSUE THREAD

**Issue by tdrjin** [Azure/static-web-apps#136]
I have a single page static web app built with vuejs (path being "/") and have successfully deployed it to azure static web. However, when trying to add authentication, it still takes me to the main page without asking me to log in. 

my route.json looks like this:
`{
    "routes": [
        {
            "route": "/",
            "allowedRoles": ["authenticated"]    
        },
        {
            "route": "/login/aad",
            "serve": "/.auth/login/aad"
        },
        {
            "route": "/.auth/login/twitter",
            "statusCode": "401"
        },
        {
            "route": "/.auth/login/facebook",
            "statusCode": "401"
        },
        {
            "route": "/.auth/login/google",
            "statusCode": "401"
        },
        {
            "serve": "/.auth/login/github",
            "statusCode": "401"
        }
    ]
}`

Can someone pls kindly advise what I have done wrong?

**Comment by miwebst** [comment]
This looks ok to me, did you mean to call it route.json? It should be routes.json.

**Comment by tdrjin** [comment]
Yea, that was the issue. Thanks for the help!
