### ISSUE TITLE
SSR not working properly with Next.js 13.5

### ISSUE THREAD

**Issue by DjilanMouhous** [Azure/static-web-apps#1365]
Since yesterday, my Next.js app no longer renders components generated through API calls during GitHub Actions build. Strangely, I can access the data correctly during the build, but it seems like the JSON, supposed to be created alongside static HTML, isn't generated. Initially using Next.js 13.4, builds started generating only 500 pages despite success, prompting a switch to Next.js 13.5. Now, I'm encountering issues with server-side components.

**Comment by thomasgauvin** [comment]
Hi @DjilanMouhous, our preview of hybrid rendering Next.js doesn't fully support Next.js versions 13 and above https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid If this is a limitation, I recommend using Azure App Service or another service with self-hosting

**Comment by DjilanMouhous** [comment]
> Hi @DjilanMouhous, our preview of hybrid rendering Next.js doesn't fully support Next.js versions 13 and above https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid If this is a limitation, I recommend using Azure App Service or another service with self-hosting.
> 
> We're hoping to iterate on our Next.js support in 2024.

Hi @thomasgauvin , thanks for the update. In that case, I'll explore Azure App Service for now. Appreciate your assistance!

**Comment by thomasgauvin** [comment]
@DjilanMouhous we just rolled out a significant improvement for Next.js on Azure Static Web Apps, check out the announcement and let us know how it goes! https://github.com/Azure/static-web-apps/discussions/1428 Closing this thread as this is now resolved as per the newest announcement
