### ISSUE TITLE
Start/Stop app

### ISSUE THREAD

**Issue by mikelhamer** [Azure/static-web-apps#137]
It would be nice to have the feature to start or stop an app from the CLI or web gui

**Comment by miwebst** [comment]
Is the idea behind this to prevent others from accessing the site until you are ready?

I believe a work around today would be to edit the routes.json file to block all routes, then when you are ready you can simply remove that rule or the routes.json altogether if you aren't using it today.

**Comment by mikelhamer** [comment]
Yes that would be the use case I had in mind. I hadn't thought of this.
Thanks!
