### ISSUE TITLE
Is it possible to restrict IP addresses for my static web app?

### ISSUE THREAD

**Issue by tdrjin** [Azure/static-web-apps#138]
I have a vuejs app and want to restrict the access to office IP only. Is there an easy way to do it? Many thanks.

**Comment by Freshinger-UX** [comment]
You can set it under the **webapp -->network -->access restrictions.**

**Comment by miwebst** [comment]
That is for Web Apps, but not for Static Web Apps :) 

There is currently no way to do this on Static Web Apps, I'll add a backlog item for this.

**Comment by Freshinger-UX** [comment]
Oh sorry
