### ISSUE TITLE
The content server has rejected the request with: BadRequest Reason: No matching Static Web App was found or the api key was invalid.

### ISSUE THREAD

**Issue by UtkarshArjariya** [Azure/static-web-apps#1384]
![image](https://github.com/Azure/static-web-apps/assets/103949787/cf627b79-86c8-4dec-a0e8-d610cb9ece84)
![image](https://github.com/Azure/static-web-apps/assets/103949787/1f2477ff-fe8a-4c53-ad53-af15f8cbe654)

 Unable to deploy CI/CD 2 and 3 in the above image

**Comment by thomasgauvin** [comment]
It seems that you were able to deploy successfully, do you still have this issue? https://github.com/UtkarshArjariya/My-portfolio-site/actions/runs/7430354998/job/20219945737

Can you verify that your environment variables are properly configured with your deployment token as a secret for your GitHub Actions? This is set automatically when creating your Static Web App from the Portal, but worth double checking.
