### ISSUE TITLE
No support for UK Region

### ISSUE THREAD

**Issue by sebastianrogers** [Azure/static-web-apps#1389]
I have a need for a web site based in the UK, for governance the data cannot leave the UK, I can use an Azure Function and Azure SQL Service to hold the data in the UK but cannot create the Static Web App in either UK South or UK West.

Will Static Web Apps become available in the UK?

**Comment by thomasgauvin** [comment]
Hi Sebastian, Static Web Apps is a global service. Only the managed functions and staging environments are localized. You could ensure that your data stays in the UK region by using [linked backends](https://learn.microsoft.com/en-us/azure/static-web-apps/apis-app-service) (which process and store your data) in the region you need. 

We're working to make that clearer in the Portal, thanks for the feedback.
