### ISSUE TITLE
The number of files in the app content folder exceeds the limit of 4000.

### ISSUE THREAD

**Issue by thllbrg** [Azure/static-web-apps#139]
Trying to use a few dependencies in the function app prevents github actions from uploading to azure.

Error message: 
---End of Oryx build logs---
Function Runtime Information. OS: Linux, Functions Runtime: v3, Node version: 12.X
Finished building function app with Oryx
Zipping App Artifacts
Done Zipping App Artifacts
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: BadRequest
Reason: The number of files in the app content folder exceeds the limit of 4000.

Reproduce: 
1. Follow https://docs.microsoft.com/en-us/azure/static-web-apps/add-api
2. Add dependencies to package.json
`
  "dependencies": {
    "google-auth-library": "6.0.5",
    "azure-storage": "2.10.3",
    "oauth-1.0a": "2.2.6",
    "request-promise": "4.2.6",
    "node-fetch": "2.6.0"
  },
`

Sample repository: https://github.com/thllbrg/azure-static-sample

Any workaround?

**Comment by miwebst** [comment]
Hi @thllbrg, this looks like a bug on our side. The root of the bug has to deal with how we are installing dependencies.

For a workaround, if you move your index.html and style.css into a folder called app and then change your workflow's app_location to be app then this should work.

In the meantime we will investigate what needs to be done to fix this issue!

**Comment by thllbrg** [comment]
Thanks, changing app_location work fine.

**Comment by LoopsGod** [comment]
@miwebst Nuxt.js Static Build function has an integrated crawler, which will generate an index.html for your route + payload.js to mock asyncData for SEO purposes. This'll generate about 2-4 files / page. 

If you've made a blog with a lot of pages, this'll force you to disable the crawler & fetch the data from your API -- this'll hurt SEO & UX. 

I'd recommend setting the file limit to about 15k-25k files for now. 

Do you think you can bump the limits?

**Comment by KevinKelchen** [comment]
Our app includes a very large third-party dependency (esri ArcGIS API for JavaScript, which is ~19k files) that results in our build output being 20k-21k files. The current file count limitation will prevent us from using Azure Static Web Apps.

**Comment by LoopsGod** [comment]
> Our app includes a very large third-party dependency (esri ArcGIS API for JavaScript, which is ~19k files) that results in our build output being 20k-21k files. The current file count limitation will prevent us from using Azure Static Web Apps.

You could lazy load the dependencies via the ArcGIS lazy load lib: https://developers.arcgis.com/javascript/latest/guide/esri-loader/

However, if you must implement the module in your box itself, you might be able to bundle them all in 1 Javascript file, or perhaps import only the one's you need. I'm not sure how that works for ArcGIS, but most of the time with external libs, I've been able to modularly inject dependencies.

Good luck.

**Comment by roarwrecker** [comment]
I have a similar problem. My static web site has more than 4000 images and deploying my site via github actions leads to a Bad Request "Reason: The number of files in the app content folder exceeds the limit of 4000."
Will this be changed in the near future? Do I have to look for an alternative to Azure Static Web Apps? Or will the number of file limitation be removed?

**Comment by miwebst** [comment]
This will change :) We are working on improvements to the service so this will no longer be a problem.

**Comment by KevinKelchen** [comment]
> > Our app includes a very large third-party dependency (esri ArcGIS API for JavaScript, which is ~19k files) that results in our build output being 20k-21k files. The current file count limitation will prevent us from using Azure Static Web Apps.
> 
> You could lazy load the dependencies via the ArcGIS lazy load lib: https://developers.arcgis.com/javascript/latest/guide/esri-loader/
> 
> However, if you must implement the module in your box itself, you might be able to bundle them all in 1 Javascript file, or perhaps import only the one's you need. I'm not sure how that works for ArcGIS, but most of the time with external libs, I've been able to modularly inject dependencies.
> 
> Good luck.

@LoopsGod, I really appreciate you taking the time to investigate my specific issue! That is kind of you, and I thank you for doing so! 😀

FWIW, we do currently use `esri-loader`. It's job is to help the web browser lazy-load the assets from the server. However, we have to get the assets on the server to host them in the first place, and there happens to be way more than 4k files to deploy for server hosting. Sadly, I don't think there's a viable way with the complexity of esri's build system to get a custom build that sufficiently reduces the number of files of various types given our use cases.

Thanks for offering some thoughts and ideas!


> This will change :) We are working on improvements to the service so this will no longer be a problem.

Awesome news, @miwebst! Thank you so much! 😀

**Comment by davidanthoff** [comment]
Is there a timeline when this file limit will be lifted?

**Comment by davidanthoff** [comment]
@miwebst, bump, any chance you can get us a rough timeline when this might be resolved?

**Comment by opdich** [comment]
Running into the same issue as @roarwrecker.

**Comment by miwebst** [comment]
We are hoping to have this fixed in roughly the next month, we have hit some unexpected delays on this so we appreciate your patience!

**Comment by davidanthoff** [comment]
Thanks!

And as far as I can tell, there is no known workaround at the moment, right?

**Comment by ChrisGibson1982** [comment]
Hi @miwebst is there any update on the timeline?

**Comment by TLA020** [comment]
Followed every step from the microsoft documentation and got stuck with this:

![image](https://user-images.githubusercontent.com/20934868/113760441-86b4c280-9716-11eb-9a00-4ef855cbb635.png)

**Comment by pioneerworksadmin** [comment]
Hi @miwebst per your advice I tried moving our Nuxt application to an "app" subfolder with updated app_location in the workflow, but still running into this "limit of 4000" error. Do you have any advice on how to use the workaround for a Nuxt app? Thank you

**Comment by miwebst** [comment]
Hey @pioneerworksadmin , that guidance was because the workflow was previously misconfigured and uploaded unnecessary files. Does your Nuxt app have more than 4k files?

For everyone else on the thread, we are hoping to adjust this limit in the next 2 weeks.

**Comment by pioneerworksadmin** [comment]
Ah, thank you @miwebst for the clarification and update! Our Nuxt website has 5-10k pages. Do you have a sense of what the new file limit will be? Trying to determine if we can make this project scalable as a static web app.

**Comment by miwebst** [comment]
We are actively determining that new limit as we are finishing up some architectural improvements that will let us improve this limit. Out of curiosity, are those 5-10k pages generated on each build or produced based on some CMS content? Would love to understand more about how these pages are managed.

**Comment by pioneerworksadmin** [comment]
Yes, the latter – the pages are generated from our Sanity.io CMS on "nuxt generate" per [this example](https://github.com/sanity-io/sanity-template-nuxt-events/blob/155afe0af8e91133b2cea286d6fce3678db9c871/template/web/nuxt.config.js). Happy to provide any info that can help! In our case, we are hoping to deploy our [arts journal](https://pioneerworks.org/broadcast/) as an Azure static web app.

**Comment by miwebst** [comment]
This has been bumped to10k files. Hopefully this unblocks your deployments. This limit will increase over time as we continue to make improvements to our platform!

**Comment by kkankala** [comment]
Hi, I have a nextjs app without azure function. Oryx is able to successfully build 5k pages and created around 11k files(file explorer count). 
I'm getting error that it exceeds 10k limit.
`The content server has rejected the request with: BadRequest
Reason: The number of files in the app content folder exceeds the limit of 10000.
`

Is there any workaround for this?

**Comment by miwebst** [comment]
Hey @kkankala, at this time there is no workaround. This limit will continue to be increased over time, just to confirm you are looking for the ability to upload 15k total files?

**Comment by kkankala** [comment]
yes, that will work for now. Thank you @miwebst

**Comment by kkankala** [comment]
Hi @miwebst, do you have any timeline when the limit will be increased to 15k?

**Comment by miwebst** [comment]
We are working on the change now, should be available in a week or two.

**Comment by epreviati** [comment]
Hi @miwebst, do you have any updates regarding the limit increase? Actually we are stuck for the 10k files limit.

Many thanks!

**Comment by msaltitudo** [comment]
> 
> 
> We are working on the change now, should be available in a week or two.

It's been 2 weeks but there is no news yet ... We are trying to do our job well but 4k or 10k for the limit is a bit ridiculous :)

**Comment by LockTar** [comment]
I see the limit is now on 15k files. 

This sounds a lot but with [Blazor WebAssembly Compression](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#compression) settings on (default on) you already get a lot of files added to your project. My file count was already around the 28k.

I disabled it for now (this is not what I want) the following way as described [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-5.0#compression):

```xml
<!-- Disable compression because of max file count in static web apps https://github.com/Azure/static-web-apps/issues/139 -->
<PropertyGroup>
  <BlazorEnableCompression>false</BlazorEnableCompression>
</PropertyGroup>
```

**Comment by davidanthoff** [comment]
Same here, 15k doesn't get anywhere close to what we need. We currently have something with already about 44k files we want to host, and that is only going to grow (significantly) larger over time.

**Comment by kkankala** [comment]
We have already surpassed 15k files. If you can increase it further that will be helpful. I agree with @davidanthoff , our files are at around 25k now and it may grow over time.
If possible, can you share more information on why such limitations exists and technical details behind it please?

**Comment by alexbruno** [comment]
It sounds crazy, but I need to deploy a website with almost 100k URL.
It would be great if I can do it with static pages.
Is there a way to go?

**Comment by kreativ-software** [comment]
Any news about this restriction?

**Comment by NoPodi** [comment]
FYI. Found a dirty workaround https://github.com/Azure/static-web-apps/issues/782#issuecomment-1186322614

**Comment by dligthart** [comment]
Currently we are experiencing issues because we have a large number of json files in our static web app build. Can the limit be bumped even more? >15K
