### ISSUE TITLE
Support branded identity.customdomain.com

### ISSUE THREAD

**Issue by DaveA-W** [Azure/static-web-apps#14]
As it stands, with a custom domain the token issuer and domain showing during consent prompts is still identity.azurestaticapps.net.  This will concern some users.  It'd be great to offer some opportunity to brand both the identity subdomain and consent pages.

I'm not quite sure what auth flow you are using, but as I understand current browser cookie handling, this may also be problematic under default Safari settings, as well as potentially Chromium-based browsers once they bring back in same-site cookie changes?

Appreciate some feedback on that, as well as any other considerations or current limitations with regards to hosting PWAs.

**Comment by mkarmark** [comment]
Thank you for using Azure Static Web Apps!

For preview, authentication to Azure Static Web Apps where the flow goes through identity.azurestaticapps.net is the only option for authentication/authorization. However, we have tested that it works with Chrome's Same site cookie changes and ensure that users should have a graceful login experience.

Supporting authentication such that users sign in to the customer's static web app is something we plan to offer in the future. 

Thank you for your feedback. Keep them coming.

**Comment by MichaelRoger** [comment]
any news about this? would love to see this coming to live.

is there a planned "end of preview"-Date?

Thanks

**Comment by miwebst** [comment]
End of preview date is today :) and you can use custom auth to avoid the identity page altogether! https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad

**Comment by MichaelRoger** [comment]
cool, is there anything to do? Or are the exisiting objects just rebranded?

**Comment by miwebst** [comment]
Nothing to do, when you use custom auth then the user logs directly in against your identity provider and redirects to your callback uri. In the process the identity page is skipped altogether.

**Comment by simonaco** [comment]
Seems like this issue has been addressed with custom auth, @DaveA-W please reopen if needed.
