### ISSUE TITLE
Angular: engine Not compatible with your version of node/npm

### ISSUE THREAD

**Issue by juanpabloguerra16** [Azure/static-web-apps#1400]
**Describe the bug**

I have a static website written in Angular 17.1.0, when I try to deploy to Azure Static Web Apps, it throws error below:

Node.js version v16.20.2 detected.
The Angular CLI requires a minimum Node.js version of v18.13.

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1701.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^18.13.0 || >=20.9.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-angular@17.1.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^18.13.0 || >=20.9.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }

using node 16 is quite outdated. I saw svelte had the same issue and it was fixed. See [here](https://github.com/Azure/static-web-apps/issues/1387).

Resolved by [changing](https://github.com/SciSharp/BotSharp-UI/commit/b694be1ba45c0e0101dab3848e0bbd642da1048c) the package.json file.

**Comment by YashrajDawkhar** [comment]
do add 

"engines": {
    "node": ">=18.0.0"
  }
  
  in your package.json

**Comment by juanpabloguerra16** [comment]
that worked. Thanks @YashrajDawkhar!

**Comment by juanpabloguerra16** [comment]
that worked. Thanks @YashrajDawkhar!

**Comment by ysavit** [comment]
Doesn't work anymore . Any other ideas
