### ISSUE TITLE
Nuxt 3 Deployment Issue

### ISSUE THREAD

**Issue by app-stealth-technologies** [Azure/static-web-apps#1413]
My Next 3 app is failing on build with the error below;

[***7mCopying files to destination directory '/bin/staticsites/***55e***7b8-e69f-427a-bebd-ede***67a47ce9-swa-oryx/app'...[***m
[***7mDone in *** sec(s).[***m
[***7m[***m
[***7mRemoving existing manifest file[***m
[***7mCreating a manifest file...[***m
[***7mManifest file created.[***m
[***7mCopying .ostype to manifest output directory.[***m
[***7m[***m
[***7mDone in ***4 sec(s).[***m
[***7m[***m
[***7m[***m
[***7m---End of Oryx build logs---[***m
[***7mTry to validate location at: '/bin/staticsites/***55e***7b8-e69f-427a-bebd-ede***67a47ce9-swa-oryx/app/.output/public'.[***m
[***1mThe app build failed to produce artifact folder: '.output/public'. Please ensure this property is configured correctly in your workflow file.[***m

**Comment by thomasgauvin** [comment]
Can you share a repo with a reproduction of your issue?

**Comment by app-stealth-technologies** [comment]
Hi Thomas,

https://github.com/app-stealth-technologies/NexSyncBE/actions is a
repository with the issue.
You can see the logs of the build error in the workflow. I tried different
approaches and different directories, but none worked.

Best regards
