### ISSUE TITLE
Facing error while Deploying Nextjs App to Azure

### ISSUE THREAD

**Issue by BlockchainDeveloper009** [Azure/static-web-apps#1430]
```[10](https://github.com/BlockchainDeveloper009/defi_jul2_sol_hd_ts/actions/runs/8257178701/job/22587250784#step:4:11)
DeploymentId: b3aac478-9b29-4f8f-8[12](https://github.com/BlockchainDeveloper009/defi_jul2_sol_hd_ts/actions/runs/8257178701/job/22587250784#step:4:13)9-c83ae1863e79

Try to validate location at: '/github/workspace/frontend/will_settler_ui'.
App Directory Location: '/frontend/will_settler_ui/' was found.
Try to validate location at: '/github/workspace/swa-db-connections'.
Looking for event info
The content server has rejected the request with: BadRequest
Reason: No matching Static Web App was found or the api key was invalid.

```

I dont know what api key is invalid. if you feel I lack knowledge in deploying webapp to azure, please point me to proper documentation. I followed whats explained in Microsoft documentation.

Thanks a lot for your help

**Comment by thomasgauvin** [comment]
Hi @BlockchainDeveloper009, how have you configured your deployment to your Static Web Apps resource? It appears there's a misconfiguration in the static web app or the deployment token which is usually configured for you when you create a static web app resource from the Azure Portal.

**Comment by thomasgauvin** [comment]
Closing this issue, feel free to reopen with additional info!
