### ISSUE TITLE
"Configuration" UI in Azure Portal doesn't actually save all the newly entered values

### ISSUE THREAD

**Issue by scale-tone** [Azure/static-web-apps#145]
Steps to repro:
* Goto your Static Web App in Portal, goto "Configuration" tab.
* Try adding e.g. 5 new config values.
* Press **Save**.

The page says everything was successfully saved, but if you refresh the page, some of your newly added params will be missing.
Specifically, it seems to be saving not more than two values at a time.

Also, the page keeps saving previously entered values in browser's autocomplete cache and then keeps showing those values as suggestions. That is a huge security issue. You never want your secrets to be silently cached anywhere!

**Comment by anthonychu** [comment]
The bug is the same as #121.

Turning off autocomplete for these fields is a good idea.

@takyyon @miwebst

**Comment by miwebst** [comment]
Closing as duplicate.
