### ISSUE TITLE
'The Static Web App contents cannot be updated while a backend migration is in progress.'

### ISSUE THREAD

**Issue by rob-balfre** [Azure/static-web-apps#1451]
When attempting to deploy via an Azure DevOps pipeline or the SWA cli we get the error:

```
The content server has rejected the request with: BadRequest
Reason: The Static Web App contents cannot be updated while a backend migration is in progress.
```

It was working fine for months until we added an API (Azure managed), first deployment worked and then all deployment since have failed with this error message.

**Comment by iomariani** [comment]
Same things happened here.

```
The content server has rejected the request with: BadRequest
Reason: The Static Web App contents cannot be updated while a backend migration is in progress.
```

Can't deploy anymore, even removing the SWA api folder completely...

**Comment by rob-balfre** [comment]
We had to delete the app and start a fresh one!

**Comment by g2o-patrickpoole** [comment]
Same issue here. We have tried creating a new instance twice and each time we see this issue when attempting to deploy from SWA CLI after waiting a few minutes.

**Comment by Tff27** [comment]
I'm facing the same issue deploying using a github action (Azure/static-web-apps-deploy@v1)

```
The content server has rejected the request with: BadRequest
Reason: The Static Web App contents cannot be updated while a backend migration is in progress.
```

Is there a way to see the backend migration progress?

**Comment by marc-on-github** [comment]
Same issue here

**Comment by MPdeconcern** [comment]
Same issue here. Help would be awesome

**Comment by iomariani** [comment]
> We had to delete the app and start a fresh one!

This is what we had to do, and as precaution, detached the API deploy from the SWA action.

**Comment by Tff27** [comment]
> > We had to delete the app and start a fresh one!
> 
> This is what we had to do, and as precaution, detached the API deploy from the SWA action.

I will do that as last resort but I would like to understatnd if this is a bug or if there is sometthing happening in the background

That backend migration error message is puzzling me.

**Comment by bitsnorbytes** [comment]
I have encountered the same issue. This is what i have done to fix it. It's a bit lengthy but does the job. 

- Delete the existing app through azure cli (or create a new one - step 2). 

`az staticwebapp delete--name <app_name> -g <resource_group>`

- Create a new app with no github integration etc. 

`az staticwebapp create --name <app_name> -g <resource_group>`

- Fetch the deployment token using the following command 

`az staticwebapp secrets list --name <app_name> --query "properties.apiKey"`

- Modified my github actions to use [swa cli](https://azure.github.io/static-web-apps-cli/) instead of the official github action - [Azure/static-web-apps-deploy@](https://github.com/Azure/static-web-apps-deploy)

```
 - name: Install Azure SWA CLI
   run: npm install -g @azure/static-web-apps-cli

 - name: Deploy 
   run: swa deploy <app_location> --api-location <api_location>--env <env>  --deployment-token <deployment_token> -name <name_of_the_app>
```
Note: You can use the the official github action - [Azure/static-web-apps-deploy@](https://github.com/Azure/static-web-apps-deploy) to do deployment too but i haven't tested it. So, cannot confirm if it will work. I prefer this way.

**Comment by serena-shen2** [comment]
@rob-balfre @Tff27 @iomariani @bitsnorbytes @MPdeconcern @marc-on-github @g2o-patrickpoole  If your site is still experiencing this issue would be able to provide the site’s default host name or site name so we can look into this issue.

**Comment by mkarmark** [comment]
We have identified the issue and are working on a mitigation strategy. I apologize for any inconvenience that this may have caused.

**Comment by Tff27** [comment]
> @rob-balfre @Tff27 @iomariani @bitsnorbytes @MPdeconcern @marc-on-github @g2o-patrickpoole If your site is still experiencing this issue would be able to provide the site’s default host name or site name so we can look into this issue.

I imagine with the issue already being uncovered you don't need this anymore
Let me know if this is still required

**Comment by serena-shen2** [comment]
> > @rob-balfre @Tff27 @iomariani @bitsnorbytes @MPdeconcern @marc-on-github @g2o-patrickpoole If your site is still experiencing this issue would be able to provide the site’s default host name or site name so we can look into this issue.
> 
> I imagine with the issue already being uncovered you don't need this anymore Let me know if this is still required

No it's not required anymore, thanks for checking in.

**Comment by Tff27** [comment]
> We have identified the issue and are working on a mitigation strategy. I apologize for any inconvenience that this may have caused.

It's working just fine now 🚀

**Comment by lgastler** [comment]
Seems to be working again for us too 👍🏼
