### ISSUE TITLE
About host.json option

### ISSUE THREAD

**Issue by renakim** [Azure/static-web-apps#146]
I modified `host.json` file in /api directory to use `watchDirectories` option. (to use shared code)

below is host.json code.
```
{
  "version": "2.0",
  "watchDirectories": ["lib"],
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```
It works fine for local tests using VSCode.
So I pushed code to my Github repository(for static web app) and github action built successfully.

But, It seems the API functions don't recognize the host.json option.

Should I upload the value myself like local.settings.json?
Or, can't use `host.json` option in static web apps?

**Comment by anthonychu** [comment]
That setting watches a directory for changes and restarts the function host if a file changes. This shouldn’t be needed in production as function files do not change. Can you explain a bit more about what you want to accomplish?

**Comment by renakim** [comment]
Thank you for your reply.

I want to use some shared code between APIs.
So I added the config to host.json. There are several files in the lib folder, one of which works but one does not.
npm packages are installed.

Can I monitor each API function like the Azure function service?
It works well locally, but it does not work in production, so I need to debug.

**Comment by anthonychu** [comment]
Oh okay. I see. There should be no need to configure the watch directories. Instead, if you need access to logging and telemetry in your API app, you can enable Application Insights. The process to do this is a bit manual right now. You need to create an Application Insights resource in your Azure subscription. Then take its key and add an application setting named `APPINSIGHTS_INSTRUMENTATIONKEY`. There is a bit more information here about how to do it with a regular Azure Functions app. https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring?tabs=cmd#enable-application-insights-integration

For more information about how to add an app setting to Static Web Apps, see the documentation here: https://docs.microsoft.com/en-us/azure/static-web-apps/application-settings

**Comment by renakim** [comment]
I set up the application insights.
It works, thank you.
