### ISSUE TITLE
100Mb limit is too small

### ISSUE THREAD

**Issue by takekazuomi** [Azure/static-web-apps#147]
Thank you for this fantastic feature.

I'm using a static web app with mkdocs. Usage is just static html hosting. Last couple of weeks when I got the following errors. mkdocs generate more than 100Mb contents. Do you have any schedule or plan about change this limitation?

If I can use my storage account for static web apps hosting that's best.

```
The content server has rejected the request with: BadRequest
Reason: The size of the app content was too large. The limit for this static site is 100000000 bytes.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a Github issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

**Comment by miwebst** [comment]
This is currently our preview limit, we set it modestly for preview so we could get some feedback on what people need. This is great feedback!

Just curious what is the size of your application after being built?

**Comment by orta** [comment]
I've hit this limit with the TypeScript website too - it's nearly all page data (e.g. `.json` and `.html` files) (though there's 4mb of images)

Each site localization could easily end up about 30-40mb in size

![Screen Shot 2020-09-21 at 12 55 34 PM](https://user-images.githubusercontent.com/49038/93796865-72412a80-fc09-11ea-8982-ab783c723d59.png)

[( This action has a zip of the site )](https://github.com/microsoft/TypeScript-Website/actions/runs/265412003)

**Comment by ktm** [comment]
I’m working on a simple marketing app which just went over 100MB when we added some fresh content.  A few recipes and a lot of photos.  It’s for a holiday campaign so I guess we’ll host it somewhere else.  Super bummed because this static web app offering is perfect for my agency client.

**Comment by miwebst** [comment]
We are actually looking to bump this limit this week after lots of great feedback on it being too restrictive! I will update this thread once we have done this. Most likely will be 250 MiB as the new limit.

**Comment by miwebst** [comment]
cc @craigshoemaker

**Comment by miwebst** [comment]
250 MiB is our new limit on maximum app size!! @craigshoemaker do you mind updating the docs?
