### ISSUE TITLE
Azure Function written in C# results in deployment error

### ISSUE THREAD

**Issue by marxxxx** [Azure/static-web-apps#15]
I created my backend Azure Function using C#, but this results in the following deployment error:

`Error: Platform 'dotnet' version '3.1' is unsupported. Supported versions: `

As all the samples i saw are using JavaScript for the backend as well i'm wondering if this is a known limitation of the service at it's current stage or if i just messed something up in my demo project (https://github.com/marxxxx/asw-demo2).

**Comment by miwebst** [comment]
This is a known limitation, we are working to add this as we speak :)

**Comment by marxxxx** [comment]
Thank you for your reply. I think it would be worth mentioning that limitation in the docs.

**Comment by craigshoemaker** [comment]
I [updated the docs](https://docs.microsoft.com/azure/static-web-apps/apis) to note that we only support JavaScript at the moment. The update will appear when the daily refresh is made to the live docs site.

**Comment by marcpiechura** [comment]
Hi, 

looking forward to this improvement! 
Will this be language dependent or will it work for any .Net binary, i.e. F# based functions?

Thanks
