### ISSUE TITLE
Can't deploy Staging environments

### ISSUE THREAD

**Issue by matsunotsuma** [Azure/static-web-apps#1516]
I want to deploy react app to SWA from GitHub.
GitHub workflow ends successfully, and product environment is deployed.
But branch environments are not deployed.
Build and Deploy message ends with this "[WARNING] Staging environments are not allowed for this Static Web App.".
My SWA's plan is Standard.

Best Regards

**Comment by howard0su** [comment]
Have the same problem.

**Comment by matsunotsuma** [comment]
This problem is solved.
A SWA's property was incorrect.
I changed "stagingEnvironmentPolicy" property from "Disabled" to "Enabled" in "export template" page.
