### ISSUE TITLE
Add azurestaticapps.net to Public Suffix List

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#153]
https://twitter.com/marvelade/status/1304741329558278144

> I was just exploring your preview of Azure Static Apps and noticed that the domain http://azurestaticapps.net is not yet added to the Public Suffix List (https://publicsuffix.org/learn/). Please add it, analogous to http://azurewebsites.net as IMO the same risks apply.

**Comment by miwebst** [comment]
Done https://github.com/publicsuffix/list/pull/1133!
