### ISSUE TITLE
API throws 503 error since yesterday

### ISSUE THREAD

**Issue by nogic1008** [Azure/static-web-apps#155]
My app's API throws 503 error since yesterday.
And, Application Insights cannot track it.
## Reproduce
GET https://www.ddradar.app/api/v1/notification
## Current status
```
Function host is not running.
```
## Expected behavior
Returns JSON
## Environments
- [ddradar/ddradar](https://github.com/ddradar/ddradar)

**Comment by miwebst** [comment]
We will take a look and followup!

**Comment by miwebst** [comment]
Hey @nogic1008, looks like it is having a tough time parsing your function.json Could not parse function.json. Does this run locally within VS Code?

**Comment by nogic1008** [comment]
@miwebst 
I found `{` and `}` that was not properly escaped!
Thank you for your advice!!
https://github.com/ddradar/ddradar/blob/86e474c72309597e5e053e290566133bac914110/api/postSongScores/function.json#L9

**Comment by bessgeor** [comment]
I'm getting a very similar issue, but with C# functions created via VS Community.
[repo](https://github.com/bessgeor/schedule-voter)
[published](https://calm-grass-0f5341503.azurestaticapps.net/?staticName=whatever&startDate=2021-02-08&weeks=2)

Scenario is pretty much the same: requests from front-end receive status code 503, direct requests (e.g. cURL) are getting `Function host is not running.` response.  The only log I managed to found in Azure portal is the Activity log, there are couple of ClientClosedRequest errors on `Create or Update Static Site Build App Setting` which seems irrelevant
