### ISSUE TITLE
The content server has rejected the request with: InternalServerError

### ISSUE THREAD

**Issue by bablu-smartdecision** [Azure/static-web-apps#1564]
Describe the bug

The build and deploy job fails with an error during the deployment of the Azure Static Web App. The error log indicates that the deployment process fails due to an internal server error after the application is built successfully and the Data API artifacts are zipped.

To Reproduce

	1.	Trigger the GitHub Action for the Azure Static Web App deployment.
	2.	Wait for the build process to complete successfully.
	3.	Observe the logs during the deployment phase after the Data API artifacts are zipped.
	4.	The deployment fails with an internal server error.

Expected behavior

The Azure Static Web App should build successfully, deploy the application, and create Azure Functions (if applicable) without any errors. The deployment process should complete without encountering internal server errors.

Screenshots

If applicable, attach screenshots or logs to provide more context:

	•	Log output from the failed build:

          The content server has rejected the request with: InternalServerError
          Reason: An unexpected error has occurred. Please try again later.

Device info (if applicable):

	•	OS: macOS
	•	Browser: Chrome ![Image](https://github.com/user-attachments/assets/8e92595a-30dd-4626-885a-04af63400a0b)

	•	Version: Azure Static Web Apps Deploy v1

Additional context

	•	The build process completes successfully, and the Data API artifacts are zipped without any issues.
	•	An internal server error is encountered during the deployment, which prevents Azure Functions from being created. The error suggests retrying the deployment later.
	•	Configuration files involved: staticwebapp.config.json, swa-db-connections/staticwebapp.database.config.json

**Comment by bablu-smartdecision** [comment]
![Image](https://github.com/user-attachments/assets/87f90194-3ce3-446e-afcc-4d5cf435eeb0)

**Comment by bablu-smartdecision** [comment]
found the issue, Maximum number of environments reached on Azure static web app environments. Previously it was showing a specific error, now it shows an internal server error. This was so frustrating.

**Comment by EricHier** [comment]
Thank you for pointing that out @bablu-smartdecision ! :) Saved me so much time 😅
