### ISSUE TITLE
Function execution error

### ISSUE THREAD

**Issue by leduqueiroz** [Azure/static-web-apps#157]
1. Function works in portal and on my local development:

![image](https://user-images.githubusercontent.com/11163846/93977635-2ac5b600-fd51-11ea-9ce8-540925d2b6e6.png)

2. Function code (ps: with moongose)

```
module.exports = async function (context, req) {
    const log = context.log;
    log('[RAN] RequestUri=%s', req.originalUrl);

    try
    {
        const name = req.body.name;
        const email = req.body.email;
        const twitch_id = req.body.twitch_id;
        const event_time = new Date();

        const mongoose = require('mongoose');
        const DATABASE = process.env.MONGODBATLAS;
        mongoose.connect(DATABASE);
        mongoose.Promise = global.Promise;

        mongoose.connection.on('error', (err) => {
                context.log(`ERROR→ ${err.message}`);
            });

        require('./inviteuser');
        const Invite = mongoose.model('Invite');

        const finalData = {
              name: name,
              email: email,
              twitch_id: twitch_id,
              event_time: event_time,
        };

        try
        {
           var invite = new Invite(finalData);
           await invite.save();
        } catch (e) {

        }
    }
    catch {

    }
    finally
    {
        context.res = {
            body: {
                code: code,
                text: "works"
            }
        };

        context.done();
    }
};
```

3. HTML script

```
<script>
  async function postData() {
    let response = await fetch('/api/invite', 
                            { 
                              method: "post",
                               body: JSON.stringify({name: document.getElementById('username').value,
                                                                 email: document.getElementById('usermail').value,
                                                                 twitch_id: document.getElementById('twitchid').value
                                                    })
                            });

    let invite = await response.json();

    $('#registermodal').modal('hide');

    if (invite.code == 200)
         swal("Uhul!", invite.text, "success");
    else
       swal("Ops!", invite.text, "error");
  };
```

3.  Liver server works on my local development

![image](https://user-images.githubusercontent.com/11163846/93978386-4e3d3080-fd52-11ea-8e0a-69d9b2fa1a9d.png)

4. Static web app with Custom Domain

![image](https://user-images.githubusercontent.com/11163846/93978547-8a709100-fd52-11ea-8bb8-1f03e9679874.png)

5. Pending (zzzzzzzz...)

![image](https://user-images.githubusercontent.com/11163846/93979011-29958880-fd53-11ea-8d1b-44e1390fa786.png)

6. Custom domain request

![image](https://user-images.githubusercontent.com/11163846/93979081-45009380-fd53-11ea-93b9-49b46d45065d.png)

7. Response after 1.7 m

![image](https://user-images.githubusercontent.com/11163846/93979250-7b3e1300-fd53-11ea-91a9-b73d18305817.png)

Helppp meeeee :boom::boom::boom::boom:

**Comment by anthonychu** [comment]
You may need to add Application Insights to your app to get more details. This is a manual process right now. More info here: https://github.com/Azure/static-web-apps/issues/29#issuecomment-633403479

1.7 minutes is suspiciously close to 100 seconds. It’s possible there’s a timeout while connecting to Mongo or running a query. You should see more info from app insights.

**Comment by LudicrousLiam** [comment]
Did you remember to set the mongo connection string in the environment variables in the configuration for the  static web app? (Non local)

**Comment by leduqueiroz** [comment]
@LudicrousLiam my connection string is only in function settings. i try it and comeback latter, tks!

**Comment by leduqueiroz** [comment]
> Did you remember to set the mongo connection string in the environment variables in the configuration for the static web app? (Non local)

My connection string is only in function settings. i try it and comeback latter, tks! :+1:

**Comment by leduqueiroz** [comment]
### It worked! :rocket:

Properties must be in **static web app** and the same values must be in **function app**, this is the tip.

tks @LudicrousLiam , tks @anthonychu  :clap: :clap: :clap:
