### ISSUE TITLE
Azure Static Web App deployment Failing with 'The content server has rejected the request with: InternalServerError'.

### ISSUE THREAD

**Issue by baodv1001** [Azure/static-web-apps#1580]
Recently our SWA deployments have not been successful. We've retried 10 times today, and gave it some time to determine if it was temporary.

Below is the error:

---End of Oryx build logs---
Try to validate location at: '/bin/staticsites/37c1136c-b628-4fb7-a911-c7f0f9e35897-swa-oryx/app/.next'.
Oryx has determined that the app build artifacts are in the '.next' directory. If this is incorrect please specify the app artifact location.
Finished building app with Oryx
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
[WARNING] For Next.js apps, staticwebapp.config.json features are not fully supported yet!
Detected standalone folder, so using it for deployment.
Repackaged Next.js app to deploy on the backend.
Skipping step to build /bin/staticsites/37c1136c-b628-4fb7-a911-c7f0f9e35897-swa-oryx/app/.next/standalone with Oryx
Web App Runtime Information. OS: linux, node version: 18
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: InternalServerError
Reason: An unexpected error has occurred. Please try again later.

Last week:

Try to validate location at: '/bin/staticsites/3a4f40df-a248-4f76-b3aa-ce39665fd528-swa-oryx/app/.next'.
Oryx has determined that the app build artifacts are in the '.next' directory. If this is incorrect please specify the app artifact location.
Finished building app with Oryx
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
[WARNING] For Next.js apps, staticwebapp.config.json features are not fully supported yet!
Detected standalone folder, so using it for deployment.
Repackaged Next.js app to deploy on the backend.
Skipping step to build /bin/staticsites/3a4f40df-a248-4f76-b3aa-ce39665fd528-swa-oryx/app/.next/standalone with Oryx
Web App Runtime Information. OS: linux, node version: 18
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.321599(s)
Status: InProgress. Time: 15.3974428(s)
Status: InProgress. Time: 30.5063308(s)
Status: InProgress. Time: 47.1417133(s)
Status: InProgress. Time: 62.2216336(s)
Status: InProgress. Time: 77.3170782(s)
Status: InProgress. Time: 92.3931886(s)
Status: InProgress. Time: 107.468602(s)
Status: InProgress. Time: 122.5577429(s)
Status: InProgress. Time: 137.6611644(s)
Status: InProgress. Time: 152.7477435(s)
Status: InProgress. Time: 167.8399552(s)

Please let me know something news needs to be adjusted with my github actions or Azure SWA.

**Comment by rvanoord** [comment]
Weare are experiencing similar issues on a pipeline that worked previously: "The content server has rejected the request with: InternalServerError" - with no indication of what the error is and no logs in Azure Portal.

**Comment by jlalonde-mvp** [comment]
We are experiencing the same issue.  Creating a new static web app using the same branch works fine, but the original swa action fails with this error.

**Comment by adam-javelin** [comment]
Same issue here. LMK if you need logs or something

**Comment by adam-javelin** [comment]
Ok I figured it out. You need to go into your Azure Portal portal.azure.com and manually kill the preview environments. For us we are only allowed 3. 

![Image](https://github.com/user-attachments/assets/edc0777c-c5e7-4532-9ed1-c508e5b57cac)

Once you delete the preview envs then re-run the build and it will succeed and all good from there.

**Comment by thejoltjoker** [comment]
> Ok I figured it out. You need to go into your Azure Portal portal.azure.com and manually kill the preview environments. For us we are only allowed 3.
> 
> ![Image](https://github.com/user-attachments/assets/edc0777c-c5e7-4532-9ed1-c508e5b57cac)
> 
> Once you delete the preview envs then re-run the build and it will succeed and all good from there.

Had the same issue, this worked for me. Thanks!

**Comment by baodv1001** [comment]
> Ok I figured it out. You need to go into your Azure Portal portal.azure.com and manually kill the preview environments. For us we are only allowed 3.
> 
> ![Image](https://github.com/user-attachments/assets/edc0777c-c5e7-4532-9ed1-c508e5b57cac)
> 
> Once you delete the preview envs then re-run the build and it will succeed and all good from there.

Yes, when I tried to merge to the main branch, the wf worked well. So, I guessed that there is a limitation with the number of preview environments. So, we need to delete the preview environments manually on Azure. I tried to delete the unused branches related to some preview environments but it didn't kill the preview environments as well.
