### ISSUE TITLE
Deploying static web app fails with InternalServerError

### ISSUE THREAD

**Issue by winsmith** [Azure/static-web-apps#1586]
As of around 7 hours ago, our deployments to Azure Static Web Apps are failing for a specific repository (`agreeable-stone` in the Static Web Apps).

However, another static web app that we're deploying with a similar workflow seems to be working.

![Image](https://github.com/user-attachments/assets/06906774-b9af-41d0-9f78-01b3c86fcc3a)

The only thing that changed is that Dependabot updated a dependency, but that should trigger an error during build, not deploy, right? But the build process works, just not the deploy:

![Image](https://github.com/user-attachments/assets/5a986b74-ee8a-4883-b9f1-5cfb02c2f471)

**Comment by winsmith** [comment]
Nevermind, I had too many open environments. A clearer error message would be appreciated here.

**Comment by daniel-v-nanok** [comment]
> Nevermind, I had too many open environments. A clearer error message would be appreciated here.

Had this going on/off for a few weeks, thanks
