### ISSUE TITLE
Oryx error for Hugo with valid config.toml

### ISSUE THREAD

**Issue by joshdcar** [Azure/static-web-apps#160]
I recently changed the theme and the corresponding config.toml on an Azure Static Web App configured for Hugo. The build had previously worked.  The build was throwing an "Oops.. An unexpected error has occurred".  Outside the obvious that Oryx should provide a better exception I discovered the root cause of this issue to be section ordering in the config.toml.  The configuration itself is valid for Hugo (runs\builds fine locally) and the toml is of course valid but will fail in Oryx. 

![image](https://user-images.githubusercontent.com/24570240/94476867-12b1c480-019f-11eb-8343-826b9b4d373f.png)

Oryx throw an error after "Detecting platforms..." when a "sub-section" is defined before the "root" section.  

    [params.search]
     enable = true

    [params]
     author = "my name"

However the following works successfully:

    [params]
     author = "my name" 

    [params.search]
     enable = true

After playing with around a dozen themes I found this pattern to be fairly prevalent.  I agree that logically [params] should appear before [params.search] but in general, if the configuration is valid for hugo it should IMO work in Oryx \ Azure Static Web Apps as well.  I couldn't figure out how to get some more diagnostic details from Oryx. 

I set up a repo that you can use to reproduce this issue at https://github.com/joshdcar/azure-static-web-app-hugo-build-fail . The repo has the same details in the readme and it's also wired up to an azure static web app where I've "broken" the build on purpose. 

Tagging @anthonychu here since we chatted on twitter about this.  Unsure if this should be in this repo or the Oryx repo - happy to move it over there if that's a better home.

**Comment by miwebst** [comment]
Hey @joshdcar thanks for sharing! Yes I think this should go to the Oryx repo. @kichalla as an fyi

**Comment by joshdcar** [comment]
Thanks @miwebst . I was thinking it likely belonged over in the Oryx repo.  I've gone ahead and created a new issue over there available at https://github.com/microsoft/Oryx/issues/801 . I'll go ahead and close this issue.  Thanks!
