### ISSUE TITLE
Resource-Based authentication and User Bindings?

### ISSUE THREAD

**Issue by rhalaly** [Azure/static-web-apps#166]
Can I use the Static Web Apps with authorization strategy depends upon the resource being accessed? I see that you [do provide the user information](https://docs.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=javascript#api-functions) but how can I use it with, for example, Cosomos-DB bindings?

For example, an API that get all the items in the partition `{User.id}-todos`.

**Comment by rhalaly** [comment]
@miwebst can you assist please?

**Comment by miwebst** [comment]
@anthonychu can you help here?

**Comment by anthonychu** [comment]
I don’t think this is possible with the bindings because you need to decode the user data in the function. Your best bet is to use Cosmos DB SDK.

**Comment by rhalaly** [comment]
Hmm, thanks. I'm just wondering... You have some layer between the client front-end side and the azure functions that encodes the user principal data (since the client doesn't send the `x-ms-client-principal` header in the Ajax).

So, I'm wondering if you can send the user principal data as query params instead of custom header to the function. For example if the data will arrive as `$user_id=xyz&$user_provider=aad&...` query params, we will be able to use them as Cosmos bindings and save more code with such binding `partition: "{Query.$user_id}"`.

**Comment by anthonychu** [comment]
Related to this issue: https://github.com/Azure/static-web-apps/issues/21

**Comment by Reshmi-Sriram** [comment]
Closing due to no traction. 
Can continue the discussion in #21 Feel free to reopen if required!
