### ISSUE TITLE
Jekyll app: Oryx built the app folder but was unable to determine the location of the app artifacts

### ISSUE THREAD

**Issue by Gordonby** [Azure/static-web-apps#167]
A site that i've had working since 8/4 now receives an error when the GitHub action runs.
I haven't changed the action, and my only change was some additional content to my **Jekyll** blog.

> Oryx built the app folder but was unable to determine the location of the app artifacts. Please specify the app artifact location through the Github workflow file.

The App Artifact Location is specified as optional in the action yaml from SWA.
```
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/_site" # App source code path
          api_location: "api" # Api source code path - optional
          app_artifact_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
```

**Comment by miwebst** [comment]
Do you mind sharing the repository or full action log? If _site contains the built application content then it should not be building the app folder.

**Comment by Gordonby** [comment]
_site does contain the built app content.  Contents for _site;
<img width="589" alt="blog_site" src="https://user-images.githubusercontent.com/17914476/95234043-3dce9080-07fd-11eb-8b2d-9c8f3d8d6d5b.png">

full action log;
[logs_6.zip](https://github.com/Azure/static-web-apps/files/5335450/logs_6.zip)

**Comment by miwebst** [comment]
Gotcha, thanks for sharing! Looks like Oryx is picking up php and thinking it needs to be built with that:

Version '7.3.21' of platform 'php' is not installed. Generating script to install it...

@kichalla can you take a look at the detection logic here?

**Comment by Gordonby** [comment]
Is there a way to provide the platform, rather than Oryx detect?

If i look in the Action logs for one of the previous successful ones, this is what it says;

> Detecting platforms...
> Could not detect any platform in the source directory.
> Error: Could not detect the language from repo.
> 
> 
> ---End of Oryx build logs---
> Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
> Finished building app with Oryx

**Comment by miwebst** [comment]
Yes this is good feedback, basically tell the Action to skip the build step. We can add this to the backlog!

**Comment by Gordonby** [comment]
Is there any workaround in the meantime? 
I've got content that T can't publish at the moment, without rolling back from Static Web Apps to Azure Web Apps + CDN.

**Comment by kichalla** [comment]
@Gordonby Is it possible to share your app or a repro sample?

**Comment by Gordonby** [comment]
I've added you to the repo @kichalla

**Comment by Gordonby** [comment]
Any thoughts @kichalla  ?

**Comment by Gordonby** [comment]
I've reverted back to Azure storage static web + CDN now for hosting, so no rush. 

I've left the SWA running so can always test again when you have a fix 👌

**Comment by Suirtimed** [comment]
It looks like I've hit the same issue. The site had some .php files in it, so I tried renaming them to *.wasphp. I'll see if I missed any of them and try again.

**Comment by anthonychu** [comment]
@Gordonby @Suirtimed We're going to work on first class Jekyll support in the GitHub Action. If possible, can you please share your repos. We'd like to make sure it works for your scenarios, and also wondering why there are PHP files in there. Thanks!

**Comment by anthonychu** [comment]
There were two updates that should have addressed these issues.

* The GitHub Action now supports a `skip_app_build` command that will ensure Oryx does not try to build your app at all, so the previous issues with erroneously detecting an PHP app will not happen.
* Oryx added first class support for building Jekyll apps automatically.

**Comment by Gordonby** [comment]
Didn't seem to get/see the notification for this update @anthonychu 

I can confirm that the skip build flag works great.
```yaml
skip_app_build: true
```

**Comment by anthonychu** [comment]
This was adding during public preview and it wasn't officially announced anywhere except for updating the docs to reflect it.

For bigger features, we'll publish them on [Azure Updates](https://azure.microsoft.com/en-us/updates/). We do want to start publishing monthly/quarterly changelogs that would include smaller updates but are thinking about where to publish them. Where would you expect to see these updates?

**Comment by Gordonby** [comment]
Responding/tagging on the issue is enough.
I had to stop using SWA because of this problem, so fell back to CDN + AzureStorage.

My GitHub action that targets SWA now works again, so thats good news for the future.
