### ISSUE TITLE
Support multiple custom domains and APEX domain

### ISSUE THREAD

**Issue by cmaneu** [Azure/static-web-apps#168]
Right now, you can only map: 
- One custom domain per SWA
- subdomains

If you want to host an app, a personal blog or anything else, there is chance that you'll need to map both www.mydomain.com and mydomain.com.

**Comment by miwebst** [comment]
This is available now :) https://docs.microsoft.com/en-us/azure/static-web-apps/custom-domain?tabs=azure-dns

**Comment by mattcofer** [comment]
I am not seeing "Host name record type: TXT" as an option.  CNAME is the only option. Does it just take time to propagate since this was released today or is there another issue?
