### ISSUE TITLE
Building my first static web app in the Azure portal

### ISSUE THREAD

**Issue by Eco2020a** [Azure/static-web-apps#171]
I want to build my first static web app in the Azure portal. I have followed each step of the article 'Building your first static web app in the Azure portal'. https://docs.microsoft.com/en-gb/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript

Yes, I successfully created it. Thank you the article author!

Then, I click at 'Click here to check the status of your GitHub Actions runs' to view the website. Then the problem happens at GitHub, which resists build and deploy job. It says that 'Error: Could no detect the language from repo' and 'Failed to find a default file in the app artifacts folder (/). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file (located in .github/workflows) points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.'

Is there superman/woman who can fix this problem!

Thank you for your help.

Best,

Kate

**Comment by anthonychu** [comment]
@Eco2020a There is only a README.md in [your repo](https://github.com/Eco2020a/my-first-static-web-app3/tree/master). Can you add a file named *index.html*?

**Comment by Eco2020a** [comment]
@anthonychu

Hi, Thank you for you comments. 

Yes, I created index.html at the repo, named docs/index. Then, I type this code: <html><body><p>Hello World</p></body></html>
Hum... It does not work...never mind. Probably, in beginning, it was not that good idea to use Azure static web apps for SaaS business, but WordPress. (I saw the potential in static generator or static CMS in terms of security and dynamic in backend. However..) Never mind. 

Anyway thank you so much for your attention and suggests. 

All the best,

Kate

**Comment by miwebst** [comment]
Hey @Eco2020a do you mind clarifying the issue? We require the content deployed to Azure Static Web Apps to have an index.html file and it doesn't seem like your repo has that. As for using static generators/CMS with Static Web Apps, we have already seen people do this so its definitely supported :)

**Comment by Eco2020a** [comment]
Hi @miwebst, Thank you so much for your note. Kate
