### ISSUE TITLE
"Configuration" UI in Azure Portal still does autocompletion. That is, it stores your secrets in browser cache, where they never should be stored.

### ISSUE THREAD

**Issue by scale-tone** [Azure/static-web-apps#172]
Not sure why #145 was closed as "duplicate". As I can see, the textbox for editing config settings in Azure Portal still shows autocomplete suggestions. Which it should never do, because these settings are used primarily for providing secrets, and caching them in browser cache is a huge **security issue**.

@miwebst, would you please pay closer attention.

**Comment by miwebst** [comment]
Per that discussion: "The bug is the same as #121."

#121 is still open and we are looking at fixing this, that is why it is marked as duplicate. Unless you see a need for 2 issues I will close this one as a duplicate as well.

**Comment by scale-tone** [comment]
@miwebst, once again, it's **not** the same.
#121 is about unreliable Save button, this one is about autocompletion. Please, pay closer attention.

**Comment by miwebst** [comment]
Ah I see, sorry about that. Probably makes sense for this to be its own issue anyway. Thanks for correcting me!

**Comment by shimedh** [comment]
The autocompletion issue has been fixed and deployed for a while now from the UX side. We forgot to update here sorry.
