### ISSUE TITLE
Get issues with `package.json` discovery for a Blazor WASM app

### ISSUE THREAD

**Issue by daveabrock** [Azure/static-web-apps#173]
I am trying to run a Blazor WASM app in Azure Static Web Apps. A simple front-end, calling an Azure Function, using the default paths ('Api', 'Client', etc.) I am getting errors in my GitHub Action, when I [run it](https://github.com/daveabrock/NASAImageOfDay/runs/1244808084?check_suite_focus=true):

```
Detecting platforms...
Detected following platforms:
  nodejs: 12.18.3
  dotnet: 3.1.8
Version '3.1.8' of platform 'dotnet' is not installed. Generating script to install it...
Error: Could not find either 'build' or 'build:azure' node under 'scripts' in package.json. Could not find value for custom run build command using the environment variable key 'RUN_BUILD_COMMAND'.


---End of Oryx build logs---
Oryx could not find a 'build' or 'build:azure' script in the package configuration. Please add one of these commands to your package configuration file (i.e. package.json). Alternatively, you can add the app_build_command to the build/deploy configuration section of your workflow file. For example, app_build_command: 'npm run docs:build'
```

When I created the app in the Azure portal (and selected 'Blazor' and the appropriate paths), I didn't even have any `dotnet` steps in the Actions script, so I tried to use what [Tim Heuer did back in May](https://timheuer.com/blog/hosting-blazor-in-azure-static-web-apps/).

I'm not sure why it is discovering Node and wanting a `package.json`. I have one locally for building CSS but it isn't published in GitHub. Here's a [link to my repository](https://github.com/daveabrock/NASAImageOfDay).

**Comment by anthonychu** [comment]
Wonder if it’s getting confused by the package-lock.json in the Client folder.

**Comment by daveabrock** [comment]
Fixed that and recreated the resource in Azure and it worked (merely deleting the file still caused issues).

Thanks, @anthonychu! I'm writing a blog post about this and will tag you on Twitter when it's done. Great stuff here!

**Comment by davewevans** [comment]
Have you finished that blog post? I'm having the same issue trying to run a Blazor WASM app in Azure Static Web Apps.

**Comment by daveabrock** [comment]
Hey @davewevans, I sure did: https://daveabrock.com/2020/10/13/azure-functions-static-apps-blazor

I had it passing, now it's failing again but it's probably my fault since I did a lot of project targeting changes. Feel free to pass along your pipeline/repo...

**Comment by davewevans** [comment]
Great! Thanks. I finally deleted my package.json file and that fix it for some wacky reason, but I look forward to reading your blog and getting a better understanding of this.

**Comment by daveabrock** [comment]
Sounds good. The issue is that with a package.json, Onyx makes an assumption you are targeting Node. I think it's a common use case to use Blazor with some interop dependencies, so hopefully they make this more flexible.
