### ISSUE TITLE
---End of Oryx build logs--- The function language 'nodejs,python' is unsupported or invalid.

### ISSUE THREAD

**Issue by mctouch** [Azure/static-web-apps#175]
Trying to build the example static web app VUE-APP however I keep receiving the below error, a similar error happens when I try to build my vue app

---End of Oryx build logs---
The function language 'nodejs,python' is unsupported or invalid. The following languages are valid: node, dotnet, python.

Not sure where this is being generated or where I edit this to be valid

**Comment by miwebst** [comment]
@kichalla can you take a look at this? This seems to be an issue with the detection.

@mctouch are you using Azure Functions? Could you provide some context on the repo structure/how you configured your static web app?

**Comment by kichalla** [comment]
cc @arroyc

**Comment by DiegoSilvaP** [comment]
I get the same issue as @mctouch when running with react

**Comment by miwebst** [comment]
@DiegoSilvaP would you mind sharing your repository? We'd like to see how it is configured, the last time we saw this issue it was caused by not having the api_location set properly.

**Comment by DiegoSilvaP** [comment]
@miwebst sure, https://github.com/DiegoSilvaP/my-static-web-app the only thing I did was to generate the repo

**Comment by miwebst** [comment]
Thanks! @DiegoSilvaP looking at the logs, I dont see this particular error, but I'm not sure why this is failing. @johnpapa can you take a look at this? Is there a problem with the react app in the learn module?

**Comment by miwebst** [comment]
Hey @DiegoSilvaP, took a look and figured out the issue. If you want to unblock yourself feel free to make a change like this to your generated repo. I will work on getting the mslearn repo updated too:

https://github.com/miwebst/mslearn/commit/12966f48fd9a0f6fef7356e489a6fb73ebe2b0e4

**Comment by DiegoSilvaP** [comment]
Thank you @miwebst I'll take a look!

**Comment by miwebst** [comment]
We have made some updates to give clearer error messages when this happens.

**Comment by alkwa-msft** [comment]
I recently ran into this issue as well. @miwebst you refer to a repo but its been removed. Do we have a way to go about this issue?

my structure of my application is 

/app 
/api <-- has two nodejs azure functions
