### ISSUE TITLE
Azure web app for Blazor 3.1 app with no index.html 

### ISSUE THREAD

**Issue by wcpinyan** [Azure/static-web-apps#176]
Built Blazor 3.1 app that has startup and program files but no index.html in wwwroot.  The defaults for app_location, api_location,etc. do not work.  For app_location I have tried "/" and "/app" and for api_location=""...I have no api.
For app_artifact_location I have tried "wwwroot" and "".
I have tried every permutation of those (and others) with no luck.
I am using entity framework with a local(client) sqlite database, but I don't think that should matter.

Thanks,

**Comment by miwebst** [comment]
Can you share the error you are getting or the GitHub Action log (would be even better)?

**Comment by wcpinyan** [comment]
I have tried so many permutations that it is hard to pick one.
The consistent error centers around the fact that it can't find the
artifacts...which are normally pointed to by "wwwroot".
But my dotnet 3.1 balzor app has no index.html in the www.root.

Thanks,

**Comment by miwebst** [comment]
So the restriction is that the output folder that will be uploaded to Azure needs to have an index.html file at the root. With most Blazor WASM apps, the build step produces a wwwroot folder that has an index.html file.

So for example, if your Blazor app was at the root of your project, your app_location would be "/" and assuming that building this project creates a wwwroot folder with an index.html in it then your app_artifact_location would be "wwwroot".

It sounds like you have tried these but your Blazor app does not produce an index.html file? If that's the case then its not producing the required static assets and will fail. Are you using Blazor WASM or just Blazor?

**Comment by wcpinyan** [comment]
The app was built a couple of months ago with .net 3.1.  It created an
_Host.cshtml page but no index.html page in wwwroot.
The default nav is "/". The app was created as a WASM, but I think I added
PWA files later.
I have tried creating a new .net 5.0  WASM/PWA and then porting the pages,
components, etc. over.  But this is tricky because there is no startup.cs
and establishing all the "add services" stuff over I started getting errors
around sqlIte, dbcontext and such.  I tried all the permutations of nuget
packages for sqlite and sqlitetools with no luck. The app works from Azure
app services, but I ultimately want to put it on Static Web Apps.

I will keep trying. I really want to get this app on Static Web Apps before
I deploy to the app stores.

Thanks for your help

**Comment by Marini83** [comment]
Did you solve the issue? I'm having the same problem!

**Comment by wcpinyan** [comment]
I think this was solved by moving to dotnet 5

**Comment by anthonychu** [comment]
@Marini83 can you share your repo if it’s public or provide more information? Blazor WebAssembly apps should produce a wwwroot folder with an index.html when published.
