### ISSUE TITLE
Build fails with exit ode 1

### ISSUE THREAD

**Issue by StrawMonkey** [Azure/static-web-apps#179]
Yarn fails when I try to use static-web-apps-deploy@v0.0.1-preview

![image](https://user-images.githubusercontent.com/5722041/96351262-8ec26c80-10ba-11eb-9d9c-8830df4caf1f.png)

Only difference from locally that I can see is the yarn version, which I am unable to change. If I do I get

`The engine "yarn" is incompatible with this module. Expected version "1.22.5". Got "1.17.3"`

**Comment by miwebst** [comment]
The other difference may be that this is running in CI mode (the log says "Treating warnings as errors because process.env.CI true"), does running your project locally produce any warnings?

**Comment by StrawMonkey** [comment]
No warnings when building locally. I think it's "yarn install --prefer-offline" which has an outdated version of "caniuse-lite"

**Comment by miwebst** [comment]
I see, can you try turning the process.env.CI off? https://github.community/t/treating-warnings-as-errors-because-process-env-ci-true/18032

You can add this to the build and deploy task

**Comment by kktam** [comment]
can anyone offer insights into how to modify CI build options inside .github\workflows\azure-static-web-apps.yml  ?

**Comment by imamahmadrazatrustadmin** [comment]
Can someone please help me where to modify in below yml file to fix this issue?

`name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_WAVE_0F2948000 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_WAVE_0F2948000 }}
          action: "close"
`

**Comment by diberry** [comment]
@imamahmadrazatrustadmin Can you post your build error in your GitHub repo's actions tab and GitHub repo/branch it is used with?

**Comment by danielcdcj** [comment]
For the CI build options inside .github\workflows\azure-static-web-apps.yml, add these two lines as shown
```
env:
    CI: false
```

![Screen Shot 2023-09-09 at 00 38 28](https://github.com/Azure/static-web-apps/assets/5447994/d192a7a8-1a8b-4fa6-bcf3-b760675ff08c)
