### ISSUE TITLE
SSL certificate support

### ISSUE THREAD

**Issue by manhvo** [Azure/static-web-apps#18]
I would love to have the ability to config my domain certificate instead of azurewebsites.net one.

**Comment by miwebst** [comment]
Hi @manhvo can you clarify? There are no azurewebsites.net certificates in play here. We have azurestaticapps.net certificates and if you bring a custom domain, we provision a certificate for your custom domain.

Do you wish to configure your own certificate for your custom domain?

**Comment by manhvo** [comment]
Looks like after configuring a custom domain, a certificate was issued for my domain. It works like a charm now. Sorry for the confusion.

**Comment by miwebst** [comment]
yup no problem!

**Comment by tonygomez** [comment]
> Looks like after configuring a custom domain, a certificate was issued for my domain. It works like a charm now. Sorry for the confusion.

@manhvo how long did it take for the certificate to issue? its been 24 hours after adding my custom domain and I still see 'not secure' error.

fyi - @miwebst

**Comment by tonygomez** [comment]
@manhvo @miwebst Figured it out.  The domain ssl worked near immediately after adding www.
