### ISSUE TITLE
Using AD Authentication

### ISSUE THREAD

**Issue by Hypothesys-Smithgor** [Azure/static-web-apps#183]
Hi,

Apologies in advance if this is a dumb question - still trying to understand the whole Azure/Blazor security model.

I created a Blazor static web app from the template following default instructions, setup and deployed - all worked fine.

Next step, I want to add some authentication, so I set my routes.json as below and deploy:

```
{
  "routes": [
    {
      "route": "/counter",
      "allowedRoles": [ "test" ]
    },
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ]
}

```
I create an invite with the test role, and go through the enrolment.  All good, and user shows up in my role assignment.

I navigate to the new site, un-authenticated.  Click on Counter from the menu, and the page shows - didn't expect that to happen as I wasn't authenticated.

I select the URL in the address bar and refresh - get a 404: Not Found.  
I then copy the URL and try to hit it in another browser window and still get the 404: Not Found.
I repeat the two steps for the Fetch Data page, and all works fine.

So, questions I have:
- I wouldn't expect to be able to access the Counter page initially when not authorized.  Is there something else I need to do?
- The 404 page tells me the routing is doing something, but I would have expected an unauthorized page rather than not found?
- Is there any documentation that walks through the setup of an authenticated site in the same way as the initial setup?

Thanks in advance.
Gordon

**Comment by miwebst** [comment]
For the counter route, my guess based on your description is that this is a client side route? Auth only works for files that are requested to the server. If you want to perform authentication on a client side route (not necessarily recommended) you can use the /.auth/me endpoint to have the Blazor wasm retrieve the user details and then make auth decisions.

https://docs.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=javascript#direct-access-endpoint

**Comment by Hypothesys-Smithgor** [comment]
Thank you - finally the penny drops!
I'm not used to writing SPAs like this, so didn't sink in that the authentication of each page would not be happening on the server.
I'll use the API to limit the pages (direct to login) but certainly put the authentication on the functions to limit access to data.
Again, many thanks.
