### ISSUE TITLE
Reading environment variable in azure function fails

### ISSUE THREAD

**Issue by sanjaydebnath** [Azure/static-web-apps#184]
Hi Guys

I am trying out static web apps & I need to read a storage connection string in the function app. below is what I am trying to do to read the connection string as we normally do in azure function projects (.net core web app).

`[FunctionName("GetImages")]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequest req, ILogger log)`
        `{`
`var storageAccountAddress = System.Environment.GetEnvironmentVariable("AzureWebJobsStorage");
            `
`var storageAccount = CloudStorageAccount.Parse(storageAccountAddress);`
`//...............`
        `}`
"AzureWebJobsStorage" is added as a config key in portal. 
![image](https://user-images.githubusercontent.com/28987981/96572389-9d0eb500-1281-11eb-8efb-f78353d3e09e.png)

But I am receiving this below error in app insights, which means storageAccountAddress is coming as null.

_Exception while executing function: GetImages Value cannot be null. (Parameter 'connectionString')_

Any help is appreciated. I tried to browse the existing issues but didn't find any related one that has a solution for this.

Just to note it works fine with local.settings.json file.

Thanks
Sanjay

**Comment by miwebst** [comment]
Is this the same as https://github.com/Azure/static-web-apps/issues/78?

**Comment by anthonychu** [comment]
See this comment on what application settings are currently blocked in managed functions. https://github.com/Azure/static-web-apps/issues/80#issuecomment-653790284

@ehamai @takyyon Is it possible to display an error in the portal?

**Comment by sanjaydebnath** [comment]
> See this comment on what application settings are currently blocked in managed functions. [#80 (comment)](https://github.com/Azure/static-web-apps/issues/80#issuecomment-653790284)
> 
> @ehamai @takyyon Is it possible to display an error in the portal?

Thanks for the update. So for now I will rename it to something else. yes, a message would be better.

**Comment by sanjaydebnath** [comment]
Duplicate of [https://github.com/Azure/static-web-apps/issues/80#issuecomment-653790284](url)
