### ISSUE TITLE
Azure Functions: Error 403 - This web app is stopped

### ISSUE THREAD

**Issue by estruyf** [Azure/static-web-apps#185]
While opening my static site, there was no data coming back. When I checked the API calls, it returns all `Error 403 - This web app is stopped`.

Is there any way to restart this again? Already tried to do another build, and that works fine. 

When I check the portal, it doesn't show any APIs / Functions anymore:

![Screenshot 2020-10-20 at 22 10 05](https://user-images.githubusercontent.com/2900833/96638838-0c87b180-1321-11eb-8d18-aa819d44d765.png)

The action uploaded the API correctly

![image](https://user-images.githubusercontent.com/2900833/96638996-51abe380-1321-11eb-8006-afb118955527.png)

**Comment by miwebst** [comment]
Interesting, do you mind sharing the default hostname (autogenerated hostname) so we can take a look? This is unexpected behavior.

**Comment by anganti** [comment]
@miwebst Could be a side-effect of the DailyMemoryUsageLimit set in the free-tier (2000 gb-sec). @estruyf Do you think this could be the reason? Are you still experiencing it?

**Comment by estruyf** [comment]
@miwebst the autogenerated hostname is: `victorious-hill-020356103.azurestaticapps.net`

@anganti shouldn't be the case, as the number of visitors is still extremely low because I didn't promote the site yet. The Azure Function is just used as a proxy, and data is cached on the client.

**Comment by anganti** [comment]
@estruyf Seems like you are able to get the functions executed again "sessionize-get". The portal usually takes some time to showup the functions list due to caching. 

Could you provide more information on when the APIs stopped working,
Were you able to execute them before? Did it ever work?
Was this happening right after deployment?
Any other information that would be helpful?

**Comment by estruyf** [comment]
Thanks, @anganti for confirming, although it is weird that with almost no load, the function runtime went down and this weekend with 1 million hits, it kept running.

**Comment by mwaddell** [comment]
@miwebst  This just happened to us yesterday on https://lively-mushroom-0a4ab8810.azurestaticapps.net -- the site was working correctly as of 11:55am CST but at noon all the functions became inaccessible with the "Error 403 - This web app is stopped" message.  The HTML was still up and running normally.  When I reran the GHA to deploy it, it came back up right away.  Is there a quota that we hit?

**Comment by mwaddell** [comment]
I see on #190 something about quotas needing to be removed - were those never removed?

**Comment by miwebst** [comment]
They were removed. @annaji-msft can provide more details on when those quotas were removed and can probably diagnose why the app was stopped.

**Comment by mwaddell** [comment]
Thank you! 

@annaji-msft  - let me know if you need any additional information from me to identify the issue.  Feel free to email me at mwaddell@pangaeatech.com as well.

**Comment by annaji-msft** [comment]
@mwaddell since you reran the GHA. Your app should be good now and not run into quota issues again. We are still in the process of backfilling existing apps but any new GHA should also remove quotas. 

please let us know if you run into this again.
