### ISSUE TITLE
User Information in Functions

### ISSUE THREAD

**Issue by Hypothesys-Smithgor** [Azure/static-web-apps#186]
Hi,

Finally got my head around client and function role authentication, and working very well, thanks, really liking the static-web-apps!

One final missing piece I have is how to determine the currently authenticated user within the Azure function.

I have role authentication protecting the function, but need to do things like log user who made changes to data, and restrict some data to certain users.  Role authentication isn't granular enough for that purpose - I need to manage that from within my app.

There seem to be conflicting views on whether this is possible - best option I can think of is calling \.auth\me from within the function itself.

Is there a recommended method for this?

Many thanks
Gordon

**Comment by miwebst** [comment]
Take a look at this:  https://docs.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=javascript#api-functions

We are looking at making this easier long term, but for now you can use this system-provided header.

**Comment by Hypothesys-Smithgor** [comment]
Perfect - all up and running now.
Many thanks.
