### ISSUE TITLE
[Question] Why max limit of 1 PR and when will it be removed?

### ISSUE THREAD

**Issue by thomastvedt** [Azure/static-web-apps#187]
Hi, we're testing Azure Static Web Apps, and this looks really great, plug-and-play with little hazzle. I noticed however that you have a limit of max 1 Pull Request preview as long as Azure Static Web Apps are in preview 😢 This is sadly a showstopper for us, depending on when this limit will be removed.

Questions:
1. Do you have an idea of when Azure Static Web Apps will be released / out of preview?
2. Do you have any plans to remove this max limit of 1 PR any time soon?

**Comment by anthonychu** [comment]
No timeline on GA yet.

Can you please share more details on your scenario, such as type of app and size of team? This will help provide a bit more data as we make decisions about this limit. We've had a few requests for this https://github.com/Azure/static-web-apps/issues/63 and it's possible we could change this limit during preview, but can't make any promises right now.

**Comment by thomastvedt** [comment]
Hi @anthonychu , we're a small company with a team size of 20. We have several applications where we want to use this, mainly Angular apps. Our main motivation for adding this is that we want to preview multiple PRs / alternative implementations and let our customers decide on which alternative we should go for. We also want to be able to have multiple PRs open at the same time, and be able to preview these changes to our QA team so they can verify that everything is implemented correctly.

It would be really awesome if you could increase the limit of 1 PR during preview. In our case (small team) I think a limit of 3-5 would work just fine while we're waiting for GA (general availability). What do you think, is this possible? 

We did investigate other alternatives using azure functions, proxies, custom proxies to handle deep linking, subfolders, etc. etc. We probably spent around 20 hours on this already and still hasn't come up with a good solution. This is not something we want to spend time on, and we would gladly pay for a solution like Azure Static Web Apps ;-)

**Comment by miwebst** [comment]
We will be updating this to allow up to 3 PR sites during preview shortly! Thanks for the feedback!

cc @craigshoemaker

**Comment by thomastvedt** [comment]
That is great news! 👏🏼 👏🏼 👏🏼  Thank you 😄

**Comment by miwebst** [comment]
This was updated to be 3 staging environments for Free static web apps :)
