### ISSUE TITLE
My Hugo site fails to build

### ISSUE THREAD

**Issue by mahoekst** [Azure/static-web-apps#19]
Tried out the support for Hugo. Set all up according to the docs but the build fails with this error:

/usr/bin/docker run --name be76db3742c4258d2045bd9d18e2a545bed1a3_c46332 --label be76db --workdir /github/workspace --rm -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_API_LOCATION -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_API_BUILD_COMMAND -e INPUT_APP_BUILD_COMMAND -e INPUT_ROUTES_LOCATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/blogtest/blogtest":"/github/workspace" be76db:3742c4258d2045bd9d18e2a545bed1a3
App Directory Location: '/' was found.
[WARNING] Api Directory Location: 'api' could not be found. Azure Functions will not be created.
The content server has unexpectedly rejected the request with: NotFound
Exiting

**Comment by miwebst** [comment]
Hi @mahoekst, can you retry and see if this is still happening? If so can you provide the region of your app?

**Comment by mahoekst** [comment]
Build succeeded now. thanks for the prompt response.

**Comment by miwebst** [comment]
No problem!
