### ISSUE TITLE
API Function returning Error 403 - This web app is stopped.

### ISSUE THREAD

**Issue by kbarnes3** [Azure/static-web-apps#190]
I'm getting a 403 error on my a small Function attached to my Static Web App. The error is "Error 403 - This web app is stopped." and I don't see any of the issues called out on the linked help pages. This sounds a lot like Issue #185, but I don't know how to confirm it is the same or how to recover.

My website is:
https://ashy-bush-00c3f3c1e.azurestaticapps.net/
The single API endpoint is:
https://ashy-bush-00c3f3c1e.azurestaticapps.net/api/ping
(a GET request should be valid with no parameters and return some JSON)

The source code is at:
https://github.com/kbarnes3/whos-there

Do you have any insight into what quota(s) I'm hitting and how to recover?

**Comment by miwebst** [comment]
Hi @kbarnes3 we are working on removing these quotas that were in place earlier. We will take a look to see if you are hitting the same thing and mitigate you accordingly!

**Comment by kbarnes3** [comment]
Thanks @miwebst! It looks like my API has started working again. As far as I'm concerned, this issue is resolved. Feel free to close this issue as appropriate!

**Comment by kbarnes3** [comment]
@miwebst This issue started happening again for my web app. The symptoms and details above are still accurate. Is this expected based on the quota changes you made a couple weeks ago?

**Comment by miwebst** [comment]
Ah sorry to hear this! Our deployment to remove all quotas got delayed due to the election, we are fairly close to having these quotas removed across the board, but potentially this one still has quotas. We can take a look.

cc @annaji-msft
