### ISSUE TITLE
An unknown exception has occurred while uploading

### ISSUE THREAD

**Issue by dereklegenzoff** [Azure/static-web-apps#192]
I'm unable to get my application deployed to static web apps. When I add the `.yml` file to the repo and it runs, I get the following error:

```
An unknown exception has occurred while uploading
```

Any idea what causes this error and how I can fix it?

![image](https://user-images.githubusercontent.com/19762985/97644801-81857600-1a08-11eb-8dd7-8025b7842405.png)

**Comment by m-sterspace** [comment]
I don't know if it's the same issue but I'm also unable to deploy at the moment. I've suddenly started getting a different build error, but one that could also be related to the status of the Static Web App servers:

`azure_static_web_apps_api_token provided was invalid.`
![image](https://user-images.githubusercontent.com/37154205/97654155-b4476280-1a38-11eb-9517-ca551f03c78c.png)

**Comment by miwebst** [comment]
@dereklegenzoff do you mind sharing access to your repo? I'd like to take a closer look at your setup. @m-sterspace I saw you have opened issue #193, lets work through the api token issue there.

**Comment by miwebst** [comment]
Closing as it was resolved offline.

**Comment by stunney** [comment]
> Closing as it was resolved offline.

How was this resolved?

**Comment by tej-rana** [comment]
I just experience this same issue. There is no api, so there won't be an api key.
