### ISSUE TITLE
Cannot Deploy - azure_static_web_apps_api_token provided was invalid.

### ISSUE THREAD

**Issue by m-sterspace** [Azure/static-web-apps#193]
I'm currently unable to deploy the latest changes to my app. 

As of at least last night as of 11pm and continuing this morning, I'm unable to deploy my web app as my github actions fails to build:

`azure_static_web_apps_api_token provided was invalid.`

![image](https://user-images.githubusercontent.com/37154205/97706968-f0a4ae00-1a8c-11eb-907c-2353c40ec9cf.png)

I double checked my git repo and nothing about my actions files (including the api tokens) have changed since my last successful build so I don't know what's going on?

**Comment by miwebst** [comment]
Interesting....when was the last time you successfully deployed?

We are working on adding the ability to get/reset your api token via the portal.
Can you try getting your api token via az cli like so?

az rest --method post --url /subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.Web/staticSites/<sitename>/listsecrets?api-version=2020-06-01

Then you can update the GH secret and see if that fixes things.

**Comment by m-sterspace** [comment]
Last successful build was October 19th, 9:56am EST

I'll give the token reset a shot and let you know how it goes

**Comment by m-sterspace** [comment]
Hmmm, tried resetting the token via the cli but I'm getting the following error:
`Method Not Allowed({"error":{"code":"HttpMethodIsNotSupported","message":"The HTTP method 'POST' is not supported."}})`

![image](https://user-images.githubusercontent.com/37154205/97904222-2efcd000-1d0e-11eb-9bd6-8261709a5604.png)

**Comment by miwebst** [comment]
Ah sorry, looks like the GitHub comment parsed the url I provided above. Let me try it again. Looks like you are missing the name of the static web app. You need to fill in the []'s:

url: /subscriptions/[subName]/resourceGroups/[rgName]/providers/Microsoft.Web/staticSites/[staticWebAppName]/listsecrets?api-version=2020-06-01

**Comment by m-sterspace** [comment]
Ah, I had caught the resourceGroup and subscription but missed the web app name. Updated the command and got the intended response:
![image](https://user-images.githubusercontent.com/37154205/97911104-bea77c00-1d18-11eb-976a-09a4afbf1763.png)

When I went to paste the key into my repo's secrets I noticed that it had been changed 7 days ago, and the logs (and an annoyed IM) confirmed that my colleague had messed with the secret. 

That being said, while the build is progressing all the way through now (instead of exiting immediately), at the end it's hitting an error when it goes to deploy to the hosting provider and I'm not quite sure why:

`The content server has rejected the request with: BadRequest`

`Reason: No matching static site was found or the api key was invalid.`

![image](https://user-images.githubusercontent.com/37154205/97911696-b734a280-1d19-11eb-9415-f66c5778c1b2.png)


I double checked that it's the same `"apiKey"` returned by the az cli command. Do I need to include apiKey= or something like that?

**Comment by miwebst** [comment]
Interesting, did the name of the branch or repository change relative to the details that are showing up in portal? We made some changes a little while ago to break the dependency but if those do not match then you may need to reset your api token to get this to work again.

**Comment by m-sterspace** [comment]
Hmm, no, I don't believe they've changed, it's still our develop branch and the repo name hasn't changed. Some work was done in feature branches that was then merged back into develop but that's about it. How would I go about resetting the api token?

**Comment by miwebst** [comment]
You should be able to call an api like this:

az rest --method post --url /subscriptions/[subName]/resourceGroups/[rgName]/providers/Microsoft.Web/staticSites/[staticWebAppName]/resetapikey?api-version=2020-06-01 --body "{\"location\": \"centralus\", \"properties\": {}}"

**Comment by m-sterspace** [comment]
Hmm, that didn't seem to quite work. 

When I tried initially I got an error that it was missing the Content-Type header and couldn't decode as an octet stream:
![image](https://user-images.githubusercontent.com/37154205/97994986-f44d7300-1db3-11eb-8217-fc9df75d1045.png)

So I explicitly set the Content-Type header to `application/json` and I'm not getting the following error:

`Bad Request({"Code":"BadRequest","Message":"Parameter resetPropertiesEnvelope is null or empty.","Target":null,"Details":[{"Message":"Parameter resetPropertiesEnvelope is null or empty."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51011","MessageTemplate":"Parameter {0} is null or empty.","Parameters":["resetPropertiesEnvelope"],"Code":"BadRequest","Message":"Parameter resetPropertiesEnvelope is null or empty."}}],"Innererror":null})`

![image](https://user-images.githubusercontent.com/37154205/97995120-1ba44000-1db4-11eb-91c6-caaaed711df9.png)

**Comment by miwebst** [comment]
So this works for me in the same region as your static web app so hopefully should also work for you! I'm not using powershell but using cmd, which is probably why my escape characters look different. Can you try cmd as well with these escape characters?

az rest --method post --url /subscriptions/[sub]/resourcegroups/[rg]/providers/Microsoft.Web/staticSites/[swa name]/resetapikey?api-version=2020-06-01 --body "{\"location\": \"centralus\", \"properties\": {}}"

**Comment by m-sterspace** [comment]
You were right, completely my mistake, I didn't realize that you had to escape with both a backtick and a backslash in powershell, it worked perfectly when I used cmd as well as when I went back to ps and escaped properly. Thanks a ton for all your help!

CMD
```console
az rest --method post --url /subscriptions/[subscriptionId]/resourcegroups/[resourceGroupName]/providers/Microsoft.Web/staticSites/[staticSiteName]/resetapikey?api-version=2020-06-01 --body "{\"location\": \"centralus\", \"properties\": {}}"

az rest --method post --url /subscriptions/[subscriptionId]/resourcegroups/[resourceGroupName]/providers/Microsoft.Web/staticSites/[staticSiteName]/listsecrets?api-version=2020-06-01
```

Powershell
```powershell
az rest --method post --url /subscriptions/[subscriptionId]/resourcegroups/[resourceGroupName]/providers/Microsoft.Web/staticSites/[staticSiteName]/resetapikey?api-version=2020-06-01 --body "{\`"location\`": \`"centralus\`", \`"properties\`": {}}"

az rest --method post --url /subscriptions/[subscriptionId]/resourcegroups/[resourceGroupName]/providers/Microsoft.Web/staticSites/[staticSiteName]/listsecrets?api-version=2020-06-01
```
