### ISSUE TITLE
Cannot deploy Blazor WebAssembly app from GitHub

### ISSUE THREAD

**Issue by cgideon** [Azure/static-web-apps#194]
I created a new Blazor WAS app from the dotnet template, set it up in my own GitHub repo and connected it to an Azure Static Web App. I get this error though in the GitHub build

The app build failed to produce artifact folder: 'build'. Please ensure this property is configured correctly in your workflow file.

Here is a link to the repo: https://github.com/cgideon/DemoStaticWebApp

**Comment by anthonychu** [comment]
The artifact folder should be `wwwroot`.

Give this config a try:
```
app_location: "/" 
api_location: "" 
app_artifact_location: "wwwroot"
```

**Comment by JustinGrote** [comment]
For reference here's a working (prototype) Blazor WASM static app and repo you can use for reference:
https://github.com/justingrote/azureprice
https://icy-field-0b85c881e.azurestaticapps.net/

**Comment by anthonychu** [comment]
@cgideon did you manage to resolve this?

**Comment by cgideon** [comment]
@anthonychu I have not had a chance to try it again, I will try this evening.

**Comment by cgideon** [comment]
@anthonychu This is fixed now, I followed @JustinGrote note and was able to successfully deploy a static web app. Closing ticket.
