### ISSUE TITLE
Adding a custom domain ends up with an infinite 301 redirection loop

### ISSUE THREAD

**Issue by sgisbert** [Azure/static-web-apps#195]
Hi,
I've succesfully added a custom domain to my Blazor static web app in Azure, so instead of https://gentle-flower-0fa0bcd03.azurestaticapps.net we can use the friendly: https://regenerate.saboraemocion.com, but while the original site works fine, the second creates an infite 301 loop redirection.

This is the content of my routes.json file:

`{
  "routes": [
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ]
}`

and I haven't added any routing specific code. This is a Blazor app created from the original starter kit in Github.

Any ideas why this behaviour is happening?

Many thanks in advance.
Sergi

**Comment by miwebst** [comment]
Hi @sgisbert,

Both sites seem to work for me, were you able to figure out what was causing the 301 loop?

**Comment by sgisbert** [comment]
Hi @miwebst, literally working on it. The domain is going through Cloudflare, which is enforcing HTTPS on their side, when I disabled it (not going through CF DNS), it started working, but still cannot figure out what the issue was.

I have another test app, this time running a Hosted WebAssembly Blazor app on a Web App Service, and got the same issue, but this time, instead of disabling Cloudflare, I could disable the line

`app.UseHttpsRedirection();`

at the Startup.cs file, and the "HTTPS only" option in the custom domain section. But this file is not part of the WebAssembly Blazor app, so I guess it is the own Static App service the one who is enforcing the redirection?

My other test app is https://test.interbuilders.es (https://blazorsignalrapp-dev-as.azurewebsites.net)

**Comment by miwebst** [comment]
Ah that makes sense! Static Web Apps enforces HTTPS by default, so if Cloudflare is reaching out to us via HTTP then we will redirect them to the same HTTPS endpoint. I suppose this could cause an infinite loop Cloudflare continually reaches out over http and we keep redirecting them to https?

**Comment by sgisbert** [comment]
That is probably it... Any workaround to keep using Cloudflare? I guess this would be quite a common use case, as we get all the CF benefits as well (CDN, free https, cache, etc..) on top of the Static Web App service.

**Comment by miwebst** [comment]
Most people that configure CF in front of Static web Apps use full SSL so that CF reaches out via https. Is is possible to setup full ssl in your scenario? https://support.cloudflare.com/hc/en-us/articles/200170416-End-to-end-HTTPS-with-Cloudflare-Part-3-SSL-options

**Comment by sgisbert** [comment]
Cloudflare is currently having issues to login to the dashboard, so difficult to tell atm... I will keep an eye on it

**Comment by sgisbert** [comment]
Hi @miwebst,

I think that did the trick! I changed the SSL settings in CF, and it looks like it is working now, with CF enabled.

Thanks for your help. Much appreciated!

Kind Regards,
Sergi
