### ISSUE TITLE
Support F# for the Functions in GA

### ISSUE THREAD

**Issue by ericsampson** [Azure/static-web-apps#199]
F# [already works great](https://twitter.com/isaac_abraham/status/1324041419892400132?s=20) for the Functions API endpoints, and people are excited about the possibilities.

Please consider officially supporting F# in GA. Thanks!

**Comment by aaronpowell** [comment]
Is there currently an issue that you've come across with Functions in F# using Static Web Apps?

I've personally deployed a number of Static Web Apps with an F# Functions backend.

**Comment by ericsampson** [comment]
@aaronpowell nope, just registering a request for official support in GA, as requested by the Functions team.

**Comment by anthonychu** [comment]
Thanks. This might just be a doc update. But want to ensure all F# apps build properly first before we declare that we officially support it.

**Comment by Reshmi-Sriram** [comment]
Closing due to no traction. Feel free to reopen if required!
