### ISSUE TITLE
Support for Blazor

### ISSUE THREAD

**Issue by djjeffg382** [Azure/static-web-apps#20]
Any idea if client side Blazor apps are/will be supported?

**Comment by anganti** [comment]
They are currently not officially supported but take a look at this blog https://www.maneu.net/blog/2020-05-deploy-blazor-client-apps-with-azure-static-apps/
 
They are definitely planned for the future releases.

**Comment by trevorkennedy** [comment]
See my repo for how to get the default Blazor app deployed to Azure SWA: https://github.com/trevorkennedy/blazor_swa

**Comment by Swimburger** [comment]
Not sure if this was possible when you originally asked this question, but Today you can also do this without modifying the Actions.
I think the trick is to configure the right paths when create the static web app:
![image](https://user-images.githubusercontent.com/3382717/91065694-ce129680-e5fe-11ea-8f6d-e679bbe0b7a4.png)
It works out of the box, check out my how-to: https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-azure-static-web-apps

**Comment by miwebst** [comment]
Take a look at this: https://github.com/Azure/static-web-apps/issues/105

1st class Blazor support launched today!
