### ISSUE TITLE
Provide a way to define the naming pattern from Staging envitonment

### ISSUE THREAD

**Issue by StefH** [Azure/static-web-apps#205]
Currently when the main URL is like `https://name-name-00bd1d203.azurestaticapps.net`, the Staging URLs are appending the PullRequest number like : `https://name-name-00bd1d203-1.westeurope.azurestaticapps.net/`.

It would be useful if we could define the naming pattern, so that the Staging URL would be like
`https://name-name-00bd1d203-staging.westeurope.azurestaticapps.net/` for the most recent PR, which would mean that you could also register this URL in your domain registrar as a CNAME.

So you could then use `https://mycompany.com` for production, and `https://mycompany-staging.com` for the PR Staging environment.

**Comment by miwebst** [comment]
I think this is a repeat of this request: https://github.com/Azure/static-web-apps/issues/22

**Comment by Reshmi-Sriram** [comment]
Apologies, we missed on updating this issue thread!
Static Web Apps announced support for [Named Preview Environments ](https://docs.microsoft.com/en-gb/azure/static-web-apps/named-environments?tabs=github-actions)in May 2022. This enables one to add a custom prefix to the default generated URL.

Do let us know if this helps solve your problems! :)
