### ISSUE TITLE
Update Oryx/AWS container to support .NET 5

### ISSUE THREAD

**Issue by JustinGrote** [Azure/static-web-apps#206]
Per https://github.com/microsoft/Oryx/issues/843, .NET 5 is now supported. Update so that it isn't downloading the runtime but instead has it cached natievly.

**Comment by miwebst** [comment]
This should be done now :)

**Comment by JustinGrote** [comment]
Hmm, I see the new oryx but it's not working for me...
![image](https://user-images.githubusercontent.com/15258962/99114653-fbd7fd80-25a5-11eb-92ba-57b2d036ab00.png)

**Comment by miwebst** [comment]
Hmm, you may want to follow-up with the Oryx team then.

cc @kichalla

**Comment by JustinGrote** [comment]
@miwebst did you include the dotnet 5 sdk into the github action image so that it doesn't have to be downloaded each time?

**Comment by miwebst** [comment]
I confirmed with the Oryx team that this is the desired behavior. This image is not just built for dotnet applications but is a generic solution for building applications that is also used by folks building JS applications. To avoid making download speeds longer for JS developers, Oryx will download dotnet 5 on the fly.

**Comment by JustinGrote** [comment]
@miwebst uh you sure about that? The dockerfile installs both SDK 2.2 and 3.0, why not 5.0?
https://github.com/microsoft/Oryx/blob/d63f5ec122b0d84fdafce720ad581ccb6085ac15/images/build/Dockerfiles/Dockerfile#L41-L42

@kichalla added these lines, and added 5.0 to the version list
https://github.com/microsoft/Oryx/blob/9da028ef15b4e9871ab12c943d510639e34ae5dd/build/__dotNetCoreSdkVersions.sh

Seems to me like Line 43 needs to now include 5.0.

**Comment by miwebst** [comment]
My understanding was that Oryx's logic is actually using one of those versions. Ideally we would not have either of these versions installed to speed up download time. @kichalla most likely knows the answer though.

**Comment by kichalla** [comment]
> Hmm, I see the new oryx but it's not working for me...

@JustinGrote I am not clear as to what is not working and what is the actual issue..Are you referring to the 'api' folder that your repo has? https://github.com/JustinGrote/AzurePrice/tree/main/Api ..Oryx looks for files with extensions `.csproj` or `.fsproj` but this folder does not have any of those files so Oryx is unable to detect the presence of a .NET project.

**Comment by JustinGrote** [comment]
@kichalla this was when I had a C# there, it's since been updated to use a proxy. Regardless you answered in the other thread that the goal is for the container to always download which is fine. Can some guidance be provided to use the `actions/cache` action to pre-cache the required items to speed it up? I'll close the issue on both fronts.
