### ISSUE TITLE
Are SWA functions breaking things?

### ISSUE THREAD

**Issue by GaryParr** [Azure/static-web-apps#207]
So, I'm asking this here on the (very) off-chance that my experiment with SWA somehow broke my trial subscription.

In brief, I've been using a free trial subscription to see how easy or beneficial it would be to migrate an existing single page application off of AWS and onto Azure. For the most part, I've been following the official Microsoft tutorials to jump start my Azure understanding.  I started with the static web apps guides as that seemed like a great fit. Unfortunately, until B2C is integrated into the offering it looks like I will need to use a more traditional component architecture.

So... I created a storage account for my static files and then went to create a Function App for my API.  Unfortunately, this is where things get weird.  Following [this document](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-azure-function) I am unable to select _any_ Plan Type besides an App Service plan. The MS guide clearly recommends the Consumption plan and also clearly states you can open a Free account to follow the tutorial. However, when I do this... both Consumption and Premium plans are greyed out in the Plan Type drop down on the Hosting tab. The text in the drop down next to these plans is "Plan not supported for selected region and operating system." 

I next tried to follow [this guide](https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-create-serverless) using the cloud shell. According to the documentation, this creates a _Consumption_ plan function. Again, even on a Free account.  When I ran the code as-is with no changes, it gave me a Y1:0 App Service Plan.  

**--- EDIT ---**
It was brought to my attention that I'm an idiot... the Y1:0 plan _is_ the consumption plan. So, deploying from the shell worked as expected. However, deploying from Portal still fails to allow me the Consumption plan. Something there is broken
**--- END EDIT---**

I tried asking Azure Chat support about this but they didn't provide much other than a suggestion that Consumption is not available on the Free Plan.  This could be the case but it contradicts all the official MS tutorial documents. Additionally, the pricing page for Function Apps clearly state that the free grants _within_ the consumption plan are not available unless you are on a paid subscription. This would seem to indicate the consumption plan itself should work fine... I'll just eat into my $200 free credit one fraction of a penny at a time for each call.

Adding a bit of really weird weirdness to this... Google tells me that the specific phrase "not supported for selected region and operating system" (in quotes) only appears on the web in the two questions I've raised about it so far. If this was a common problem with people like me trying to use consumption plans on a free trial where it wasn't supported... you would think there would be more hits in the search results.

So, the only things I can think of are either

A. I'm being really stupid (entirely possible) or
B. My deployment of an SWA containing a function somehow affected the plan types available on my subscription.

Anyway, if this is totally not the fault of SWA then sorry for bugging you.  But, on the off-chance it was caused by an SWA deployment I figured you should be made aware of my edge case madness.

**Comment by GaryParr** [comment]
So, to clarify... consumption plan does seem to work fine from the shell... and from the Advanced Deploy in VS Code. The Portal however refuses to let me chose anything other than an App Service plan during function creation.  Again, this may not be related to a prior SWA deployment at all, but it seems like such an odd thing to have happen that I wanted to make you all aware of it just in case.

**Comment by anthonychu** [comment]
Yep this appears to be an issue with creating a function app from the portal in certain trial subscriptions. I don’t think this is related to anything you did with Static Web Apps.

**Comment by anthonychu** [comment]
Created issue here to track: https://github.com/Azure/Azure-Functions/issues/1781 Thanks for reporting this.
