### ISSUE TITLE
Split build and deploy steps

### ISSUE THREAD

**Issue by svict4** [Azure/static-web-apps#209]
Hi is there a way to split the steps defined in the build_and_deploy action? https://github.com/Azure/static-web-apps-deploy
I'd like to run a post-build Github action which creates an extra asset that I want deployed along with the rest of the build artifacts.

**Comment by miwebst** [comment]
You can do this by building your app just like normal in a GitHub action and then passing the output folder as the app_location to the static-web-apps-deploy action. Take a look at this as an example: https://github.com/Azure/static-web-apps/issues/17
