### ISSUE TITLE
Relative URLs are treated like Absolute URLs

### ISSUE THREAD

**Issue by eat-sleep-code** [Azure/static-web-apps#210]
I setup a new Static Web App with a "custom" framework.    

I have a something like the following structure that is deployed, 

- /example1/index.html
- /example1/css/my.css
- /example1/images/my.jpg

In the HTML there is a relative link, similar to:  `<link href="css/my.css" rel="stylesheet" type="text/css">.   You will note that my href is relative.
`
I can goto `https://mycustomdomain.com/example1` and I see the page.   But the references to the CSS are broken.   They appear to try to pull from `https://mycustomdomain.com/css/my.css` instead of `https://mycustomdomain.com/example1/css/my.css`

This appears to be because, the I need to use a trailing slash, but we know folks aren't always going to type a trailing slash.   So, can is this something that can be corrected with a route configuration or something -- to always enforce a trailing slash?

The idea of this site is that I need to be able to drop these `example1` type folders into the root and have their contents work without having to refactor the paths in the pages that are being handed to us.

**Comment by miwebst** [comment]
This relative routing should be done by your browser based on the presence of these trailing slashes. Static Web Apps is just responding to what is requested. Can you take a look at the network trace to confirm my theory?

**Comment by eat-sleep-code** [comment]
Correct, it works fine with a trailing slash -- but as I noted, you can not expect folks to type the trailing slash in a web address.   So... was curious if there is a config/rule that can force all "folder" URLs to have a trailing /.   This can be done with IIS Rewrite, or .htaccess but not sure either is supported in this setup.

**Comment by miwebst** [comment]
Ahh I see, sorry I misunderstood your ask. Seems you have already found the existing issue:

https://github.com/Azure/static-web-apps/issues/42

Today we don't have a mechanism for doing this. I assume this would essentially be redirecting all folder requests without the slash to the same request path but with the slash? Do you have an example IIS Rewrite or .htaccess file for configuring this?

I'll add a note to the existing item in our backlog.

**Comment by eat-sleep-code** [comment]
Here is an example .htaccess rule.

```
RewriteCond %{REQUEST_URI} !/$
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule (.*)$ /$1/ [L,R]
```

Here is a URL rewrite rule:

```
<rule name="Add trailing slash" stopProcessing="true">
  <match url="(.*[^/])$" />
  <conditions>
    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
  </conditions>
  <action type="Redirect" redirectType="Permanent" url="{R:1}/" />
</rule>
```

**Comment by miwebst** [comment]
Awesome, that makes a lot of sense. Thanks for the feedback!

**Comment by anthonychu** [comment]
Would be great if this behavior can be the default or can be configured with a single setting.

**Comment by nategreen** [comment]
Any update on this? I was hunting for this when I asked [this question on StackOverflow](https://stackoverflow.com/questions/69260006/azure-swa-redirect-to-modified-version-of-requested-route/69260207#69260207).

**Comment by ikondrasovas** [comment]
> Here is an example .htaccess rule.
> 
> ```
> RewriteCond %{REQUEST_URI} !/$
> RewriteCond %{REQUEST_FILENAME} -d
> RewriteRule (.*)$ /$1/ [L,R]
> ```
> 
> Here is a URL rewrite rule:
> 
> ```
> <rule name="Add trailing slash" stopProcessing="true">
>   <match url="(.*[^/])$" />
>   <conditions>
>     <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
>     <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
>   </conditions>
>   <action type="Redirect" redirectType="Permanent" url="{R:1}/" />
> </rule>
> ```
> 
> You can see both offer a method of doing conditional rewrites.

Any tips on how to convert this rule to staticwebapp.config.json?

**Comment by joslinmicrosoft** [comment]
Hi all, thank you for your feedback and patience on this request. We have added the ability to configure trailing slash behavior with the `trailingSlash` configuration in your `staticwebapp.config.json` file. The documentation can be found here: https://docs.microsoft.com/azure/static-web-apps/configuration#trailing-slash. Please let us know if this works for your use cases!
