### ISSUE TITLE
Request support for environment presets

### ISSUE THREAD

**Issue by ElderJames** [Azure/static-web-apps#211]
For example, I have a Blazor application, but Need to use NPM to build JS and CSS.

We are currently unable to add the Node environment to a Blazor App.

![image](https://user-images.githubusercontent.com/7550366/99181342-ca5b5f80-2768-11eb-9db6-8087bfa61999.png)

**Comment by anthonychu** [comment]
@ElderJames thanks for filing this. Can you share a sample app?

**Comment by ElderJames** [comment]
Sure, I have setup in https://github.com/ant-design-blazor/ant-design-pro-blazor

**Comment by anthonychu** [comment]
@ElderJames  Thanks. And is the request to make npm available when building Blazor apps?
