### ISSUE TITLE
The content server has rejected the request with: BadRequest 147 Reason: The size of the function content was too large. The limit for this static site is 31457280 bytes.

### ISSUE THREAD

**Issue by myaesubi** [Azure/static-web-apps#214]
Hi @anthonychu/@annaji-msft,
I am developing the static website that I'm building is based on the **Blazor** framework.
I have NuGet library that is the bits around 30Mb should be part of the "Api" part. The CI/CD fails with the following error.

`The content server has rejected the request with: BadRequest 147 Reason: The size of the function content was too large. The limit for this static site is 31457280 bytes.`

Is there any way to fix this, increase the space. any urgency this be done much appreciated.

Thanks in advance,
Mohammad

**Comment by jrathgeber** [comment]
Hello. I have the exact same error. Only I am brand new at this and I am only trying to run the tutorial from the static web apps documentation. My app is supper small. It has no content is just 'hello world'. But I don't know what to do to resolve. 

![image](https://user-images.githubusercontent.com/10384129/99740908-e844ff00-2a9d-11eb-9cc0-78149be48104.png)

Attached an image of the error. Experience tells me if we both have the same error and it is very first in the list then maybe a new bug was just introduced. Or maybe we both need to set some configuration somewhere. I have looked around but I don't know what.

**Comment by anthonychu** [comment]
@jrathgeber Your app does not have an API, however, the workflow is configured with an [API location](https://github.com/jrathgeber/ReactWeb/blob/96c512979d287758c5f075f930ca37b91436effb/.github/workflows/azure-static-web-apps-nice-moss-0cfda6e0f.yml#L31), which caused the GitHub action to treat your entire app as an Azure Function app and try to deploy it, and it is hitting the API app limit of 30MB. Please change that valve to an empty string and see if that solves the issue.

**Comment by jrathgeber** [comment]
It works now. Thank you very much.

**Comment by anthonychu** [comment]
@myaesubi Can you let me know if you're still experiencing this problem and if you have more information that you can share about your app, especially the workflow file? Thanks.

**Comment by myaesubi** [comment]
Hi @anthonychu 
yes. I still have the issue. 
Basically, I use a NuGet package to create pdf from html file and that's above 30Mb size. I use the standard work flow that is being picked up when I create Blazor static web app in Azure portal.

I think the quota for Blazor apps should be increased, since they are sitting on the .NET side with .dll files, comparing to Angular JS or other Javascript frameworks.

Thanks,
Mohammad

**Comment by anthonychu** [comment]
Just to clarify, our limit for the frontend apps for the current free offering is 250MB. That should be plenty for your Blazor app. You are hitting the limit on the function app, which is currently at 30MB. We plan on increasing this.

If you believe your Blazor app is blocked by the 30MB limit, please share more information and we can help troubleshoot.

**Comment by myaesubi** [comment]
Hi Anthony,
you are correct. my limit size is in the API side which is Function apps.
I use DinkToPdf NuGet package which is a wrapper for multiple native libraries for each OS.
The size of those libraries each is above 40Mb.

Here is the [link:](https://medium.com/volosoft/convert-html-and-export-to-pdf-using-dinktopdf-on-asp-net-boilerplate-e2354676b357)

What I had to do is workaround is to put the a message to a message queue to be picked up by my pay-as-you-go Function Apps (consumption plan) and generate Pdf with that app service in meantime.

I really wish to have the function app self sufficient for generating the PDF file and eliminate the queue and queue trigger in my app service function app.

Thanks,
Mohammad

**Comment by anthonychu** [comment]
Yep. We will be increasing it soon. Thanks for your patience. /cc @annaji-msft

**Comment by anthonychu** [comment]
@jrathgeber Do you mind sharing which tutorial you were following? We want to make some updates to make it more clear that the API location should be left empty. Thanks!

**Comment by jrathgeber** [comment]
Good morning. I had a look at my history and this what I found. It was 2 weeks ago now. 
https://docs.microsoft.com/en-us/azure/static-web-apps/get-started-portal?tabs=react
I remember searching for static web apps on azure to find that. I also wanted to use Azure portal. 
However if you click the link to the git hub repo on that page you will find it is a broken link.
Not give up I went the root of that git hub repo and fin  https://github.com/staticwebdev/react-basic and was able to get going. 
At the bottom of the Microsoft link there is a button for Next Step "Add API" .
I seem to remember at some stage clicking it or even on Azure portal there was an API setting and I might have enabled it. 
That is it. I do plan to do the next step and enable the API!.

**Comment by anthonychu** [comment]
Thanks @jrathgeber! Just tried it and you are correct that the link (https://github.com/staticwebdev/react-basic/generate) is broken if you are not logged into GitHub. We will update the instructions in the quickstarts and tutorials so it works well whether you are logged in or not. /cc @craigshoemaker @johnpapa

**Comment by myaesubi** [comment]
Hi @anthonychu,
would you be able to advise a tentative timeline

> Yep. We will be increasing it soon. Thanks for your patience. /cc @annaji-msft

@anthonychu  could you be able to advise a tentative timeline please. Thanks.

**Comment by haojianzong** [comment]
Setting api_location to empty string resolves the issue for me, thanks for the excellent answer.

**Comment by miwebst** [comment]
Closing as bring your own functions serves as a workaround to this.

**Comment by wbwvos** [comment]
I'd like to reopen this thread. I am running into the same issue. I am running into the size limit whilst I only have one function in my api folder. It is a python function and I have about 100 lines of code and I import `pandas` and `sklearn`. Changing to the standard tier (instead of the free tier) does not change anything. When I upload my function separately, so not within the webapp, there is no issue. However, I cannot link the separate Function App to the WebApp in the free tier. So can you please advice? I really would like to deploy my webapp and api as a package. 

![image](https://user-images.githubusercontent.com/3786304/150299112-190636e9-5299-420d-9e87-b6fc9c441be7.png)

**Comment by hohenp** [comment]
Having the same issue deploying nextjs. Its a small "hello world"...

![image](https://user-images.githubusercontent.com/29328026/201749373-1831eb58-dfd8-4462-bb09-145e299bc1e3.png)

In the deployment job is set the api_location to an empty string.
api_location: ""

Are there any news on that?

**Comment by RaphaelSilv** [comment]
Me too facing the same issue on NextJs deployment, the task I'm using is as follows:

```yaml
  - deployment: 'DeployStaticwebapp'
    dependsOn: ['Build']
    environment: $(DevopsEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: 'self'

          - task: AzureStaticWebApp@0
            inputs:
              app_location: '/'
              output_location: 'build'
              azure_static_web_apps_api_token: $(deployment_token)
              app_build_command: npm run build
```


Note there is no reference to _api_location_.

**Comment by andrem0** [comment]
Same problem with NextJS hybrid here as well. I have tried to follow your suggestions @vivekjilla, but it doesn't solve the issue. The devops task is building both app and api, even though the api_location is empty string. The documentation is obviously also not good enough. Please fix this as soon as possible. If not able to fix it, please consider increasing the max size.

Looking forward to your swift response.

**Comment by saicoder** [comment]
We are facing the same problem with NextJS. Our .next folder after the build is under 2.5MB.

**Comment by gzSupertramp** [comment]
I am having exactly the same problem here while trying to create a hybrid Next.js website on Azure Static Web Apps. 

![image](https://user-images.githubusercontent.com/64129851/205508424-1cef7ac3-a9e8-47c5-9744-db8d6fa488ad.png)
![image](https://user-images.githubusercontent.com/64129851/205508449-ca771e4d-3a88-4394-b28c-72112649cf65.png)

It is a very light weight landing page with one extremely light API page.

Did anyone find a workaround?

**Comment by vivekjilla** [comment]
@saicoder @gzSupertramp if `.next` is small, the `node_modules` folder could be taking up the space, it's needed for the hybrid support. Can you see if you can remove any dependencies that are not needed by your app from the `package.json`. 

We're working on improving this experience, but unfortunately we're not aware of any workaround as of today. Apologies for the inconvenience.

**Comment by saicoder** [comment]
Thanks @vivekjilla. No, it's a plain Next.js app with only chakra-UI as a dependency. My `node_modules` is 230MB. Next.JS and TypeScript alone take over 187MB.

The only way currently is to export the Next.JS app as a static website without SSR.

**Comment by vivekjilla** [comment]
@saicoder Can you please try moving the TypeScript to devDependencies in the package.json and see if it helps.

**Comment by saicoder** [comment]
I've moved most of the dependencies to dev dependencies, and it did the trick. Thanks @vivekjilla 

Just one side note, it would be useful that build log shows the final zip size.

**Comment by andrem0** [comment]
We were finally able to solve this as well in the following way:
* Set "output" in next.config.js to "standalone"
* Run AzureStaticWebApp@0 in pipeline with following config:
```
- task: AzureStaticWebApp@0
    displayName: Deploy static web app (Next.js)
    inputs:
      app_location: '/'
      verbose: true
      azure_static_web_apps_api_token: XYZ
      app_build_command: 'yarn run build'
      api_build_command: 'rm -rf $SOURCE_DIR/node_modules/@next/swc-* && rm -rf $SOURCE_DIR/.next/cache'
```

This way, Oryx seems to find the standalone folder for the app on its own, being able to create the function app.

A permanent fix and better DevEx is definitely needed here anyways.

**Comment by plasticmik** [comment]
I have a static web app built with nextjs that doesn't use getStaticProps/getStaticPaths, neither SSR. It's a Redux RTK query base app that has some dynamic API calls in some pages that I use to populate form fields and submit them.
I'm deploying on an Azure static web app and I was having this error message:

`The content server has rejected the request with: BadRequest
Reason: The size of the function content was too large. The limit for this Static Web App is 104857600 bytes.`

So, after an entire morning spent looking for a solution I was able to overcome the problem by:

1. update the package.json with the 'next export' command right after 'next build':
```
"scripts": {
    "dev": "next dev",
    "build": "next build && next export",
    "start": "next start",
    "lint": "next lint"
  },
```

2. disabled the image optimization functionality in the next.config.js file:
```
images: {
  unoptimized: true,
}
```

3. Add the output directory path ("out" generated by the build and export command) to the azure workflow file:
```
app_location: "/" # App source code path
api_location: "" # Api source code path - optional
output_location: "out" # Built app content directory - optional
```

Hope this helps someone 👋🏻

**Comment by dan-eversen** [comment]
Confirming that this is still an issue. None of the fixes I've tried above have been able to get the package size under the limit, unfortunately.

**Comment by fballan93** [comment]
Im having this issue too and i couldn't find a fix . my api route in empty too

**Comment by mmeir11** [comment]
> 
Saved my day.
Thanks.

**Comment by Matt-CBI** [comment]
Having the same isse: https://github.com/Azure/static-web-apps/issues/1034#issuecomment-1490049973

Why is this topic closed?

**Comment by sheikhmubashi** [comment]
**Deployment Issue: Function Content Size Error on Azure Static Web App**

Hi everyone,

I’m currently facing a deployment issue with my Azure Static Web App. The application was working perfectly fine until I added one more page. Now, I’m encountering the following error during deployment:

`---End of Oryx build logs---
Web App Runtime Information. OS: linux, node version: 20
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: BadRequest
Reason: The size of the function content was too large. The limit for this Static Web App is 262144000 bytes.
`

**Here are the details of what I’ve tried so far:**

Verified that the maximum size limit on Azure is set to 500MB, so it shouldn’t be a size issue.
Reviewed other suggestions mentioned in similar threads (e.g., reducing dependencies, optimizing the build), but none of them worked.
I’m attaching the following files for context:

- package.json
- next.config.js
- GitHub Action Workflow File

The issue has broken my production environment, and I’d really appreciate it if someone could help me resolve this.

Thank you in advance!

package.json: 
```shell
{
  "name": "rewriterpro_nextjs",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emailjs/browser": "^3.11.0",
    "@headlessui/react": "^0.0.0-insiders.043edb8",
    "@heroicons/react": "^2.0.18",
    "@next/third-parties": "^14.1.3",
    "@react-oauth/google": "^0.12.1",
    "@tailwindcss/aspect-ratio": "^0.4.2",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "@types/jest": "^27.5.2",
    "@typescript-eslint/eslint-plugin": "^7.1.1",
    "@typescript-eslint/parser": "^7.1.1",
    "axios": "^1.6.7",
    "chatgpt": "^5.2.5",
    "crypto-browserify": "^3.12.0",
    "firebase": "^10.6.0",
    "next": "^14.1.1",
    "nextjs-toploader": "^1.6.12",
    "nprogress": "^0.2.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-firebase-hooks": "^5.1.1",
    "react-google-button": "^0.7.2",
    "react-minimal-pie-chart": "^8.4.0",
    "react-social-login-buttons": "^3.9.1",
    "rewriterpro_nextjs": "file:",
    "stream-browserify": "^3.0.0",
    "stripe": "^12.10.0",
    "txtgen": "^3.0.6",
    "web-vitals": "^2.1.4"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.1.1",
    "eslint-config-prettier": "^9.1.0",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
``` 
next config
```shell
/** @type {import('next').NextConfig} */
const nextConfig = {
};

export default nextConfig;
``` 

```shell
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_BUSH_0AF2C3D10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: ".next" # Built app content directory - optional
          app_build_command: 'yarn run build'
          api_build_command: 'rm -rf ./node_modules/@next/swc-* && rm -rf ./.next/cache'
        env:  # Put a node version on the following line
          NODE_VERSION: 20
          NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
          NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}}
          NEXT_PUBLIC_OPEN_AI_API_KEY: ${{ secrets.NEXT_PUBLIC_OPEN_AI_API_KEY}}
          NEXT_PUBLIC_WEBSITE_HTTPLOGGING_RETENTION_DAYS: ${{ secrets.NEXT_PUBLIC_WEBSITE_HTTPLOGGING_RETENTION_DAYS}}
          NEXT_PUBLIC_PRODUCT_ID: ${{ secrets.NEXT_PUBLIC_PRODUCT_ID}}
          NEXT_PUBLIC_ENV: ${{ secrets.NEXT_PUBLIC_ENV}}
          NEXT_PUBLIC_ATLAS_DATA_API_KEY: ${{ secrets.NEXT_PUBLIC_ATLAS_DATA_API_KEY }}
          NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_SERVICE_ID }}
          NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID }}
          NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_CONTACT_FORM: ${{ secrets.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID_CONTACT_FORM }}
          NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY }}
          NEXT_PUBLIC_STRIPE_SECRET_KEY_PROD: ${{ secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY_PROD }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/"
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_BUSH_0AF2C3D10 }}
          action: "close"

```

**Comment by Tibo46** [comment]
I had the same issue, and after looking a bit deeper at it, i actually had a typescript build error as well. Once the build error was fixed, everything was ok. Not sure why it triggered the too many files error for this.
