### ISSUE TITLE
Quickstart broken on React

### ISSUE THREAD

**Issue by aatifsyed** [Azure/static-web-apps#216]
Hello again `static-web-apps`
Following the quickstart guide at https://docs.microsoft.com/en-gb/azure/static-web-apps/getting-started?tabs=react leads to the following error in CI:

```
---End of Oryx build logs---
Function Runtime Information. OS: Linux, Functions Runtime: v3, Node version: 12.X
Finished building function app with Oryx
Found and validated 'routes.json' within build artifacts folder.
Zipping App Artifacts
Done Zipping App Artifacts
Zipping Api Artifacts
Done Zipping Api Artifacts
The content server has rejected the request with: BadRequest
Reason: The size of the function content was too large. The limit for this static site is 31457280 bytes.
```

This is with no deviations from the instructions, so I reckon it meets the bar for unexpected

**Comment by aatifsyed** [comment]
[vanilla_react_ci_logs.zip](https://github.com/Azure/static-web-apps/files/5579069/vanilla_react_ci_logs.zip)
Here are the logs from that CI job

**Comment by anthonychu** [comment]
In step 6 of “Create a static web app”, did you select “skip for now” for the API location? It appears “/“ was selected, causing the GitHub action to build the whole repo as an API when there is no API in this app.

If you still have the repo, you can fix this by editing the GitHub workflow file. Change the api_location from “/“ to “”.

**Comment by anthonychu** [comment]
Submitted an update to docs to make it more clear on the screenshots what the selected values should be. Also added an item for VS Code: https://github.com/microsoft/vscode-azurestaticwebapps/issues/266

Thanks for reporting this.

**Comment by simonaco** [comment]
@aatifsyed thank you for reporting this issue. please reopen if it's still a problem.
