### ISSUE TITLE
Suport for Root domains

### ISSUE THREAD

**Issue by alexanderomnix** [Azure/static-web-apps#221]
I setup an Azure static web app using an custom domain that I bought at godaddy, I follow the instructions on documentation and create a CNAME as instructed, the problem is my static web app is only avaliable using the www subdomain, how can I setup my Azure Static web App to use root domain?
Ex. Azure static web app only allow to access my site using www.example.com and example.com is not avaliable...
I found online a lot of people saying this is unavaliable, is true?
if so I think it is an important feature to support

**Comment by MaxMommersteeg** [comment]
They aren't supported yet, see official documentation:
https://docs.microsoft.com/en-us/azure/static-web-apps/custom-domain#configure-a-root-domain

The team working on this thinks it is an important feature too, as they call it an 'essential feature'.

**Comment by alexanderomnix** [comment]
1. thank you, I'll close this for now.
