### ISSUE TITLE
Route not work properly where user not have role

### ISSUE THREAD

**Issue by andreatosato** [Azure/static-web-apps#222]
Hi all,
I have this [routes.json](https://github.com/andreatosato/AzureWebSitesStatic/blob/main/Client/wwwroot/routes.json)
When I route to /reader or /superheroesgithub there aren't error 401.

/reader require "**reader**" OR "**authenticated**". But when I haven't autenticated view page.
/superheroesgithub require **superheroesgithub**. But when I haven't role I view page.

I don't understand why not work.

**Comment by anthonychu** [comment]
@andreatosato One thing to note is that if you are performing client side routing in a single page app, the app never makes a request to our servers at that route. The rule only comes into play if you access the route directly. You should see a 401 error if you click on this link: https://orange-mushroom-011535a03.azurestaticapps.net/superheroes

**Comment by andreatosato** [comment]
Ok, routing is for API not for Client.
Thanks a lot

**Comment by andreatosato** [comment]
@anthonychu 
I want to try **platformErrorOverrides** with **NotFound** like this.

![image](https://user-images.githubusercontent.com/24985956/100538628-2a560980-3231-11eb-9bad-1da576c05e57.png)

I create razor page [notfound](https://github.com/andreatosato/AzureWebSitesStatic/blob/main/Client/Pages/NotFoud.razor) that call Function not existing. 
I receive backend error (404) but can't redirect to [notfound](https://github.com/andreatosato/AzureWebSitesStatic/blob/main/Client/Pages/Page404.razor) page

Why this rule not work properly?
```json
{
        "errorType": "NotFound",
	"statusCode": "302",
	"route": "/notfoundapi"
}
```

**Comment by andreatosato** [comment]
I try fontend route and backend but not work

**Comment by mkarmark** [comment]
Hi @andreatosato, I don't know how your Unauthenticated platform error override is formatted but the path to serve should be assigned to a field called "serve" not "route"

**Comment by andreatosato** [comment]
This is my route:
```json
"platformErrorOverrides": [
		{
			"errorType": "NotFound",
			"serve": "/errors.html"
		},
		{
			"errorType": "Unauthenticated",
			"serve": "/errors.html"
		}
	]
```
For 404 error, my waiting is that redirect to [errors.html page](https://orange-mushroom-011535a03.azurestaticapps.net/errors.html). 
![image](https://user-images.githubusercontent.com/24985956/101241221-7eab2e80-36f4-11eb-8c9b-847d31547a95.png)

For 401 error, my waiting is that redirect to [errors.html page](https://orange-mushroom-011535a03.azurestaticapps.net/errors.html). 
![image](https://user-images.githubusercontent.com/24985956/101241246-9c789380-36f4-11eb-8f46-f777bd24bba9.png)

There is no redirection to the errors mentioned above.
Am I doing something wrong? @anthonychu 
I used **serve** instead of **route** as suggested @mkarmark

**Comment by anthonychu** [comment]
For a redirect you need to return a status code. Can you try this:

```
{
    "errorType": "NotFound",
    "statusCode": "302",
    "serve": "/errors.html"
}
```

**Comment by andreatosato** [comment]
This not work
```json
"platformErrorOverrides": [
		{
			"errorType": "NotFound",
			"statusCode": "302",
			"serve": "/errors.html"
		}
	]
```
Must I change page code? this line has error: **await Client.GetStringAsync("/api/notfound")**
```
@page "/notfound"
<h3>NotFound</h3>

@(FunctionCallString)

@code
{
    [Inject]
    public HttpClient Client { get; set; }
    public string FunctionCallString { get; set; } = "";

    protected override async Task OnInitializedAsync()
    {
        FunctionCallString = await Client.GetStringAsync("/api/notfound");
    }
}
```

This not work
```json
"platformErrorOverrides": [
		{
			"errorType": "NotFound",
			"statusCode": "404",
			"serve": "/errors.html"
		}
	]
```


**The strange thing I noticed is that if I refresh the page that just went wrong (https://orange-mushroom-011535a03.azurestaticapps.net/notfound), I am redirected to the static page error.html
Am I doing something wrong in blazor?** @anthonychu

**Comment by Reshmi-Sriram** [comment]
Closing due to no traction. Feel free to reopen if required!
