### ISSUE TITLE
Add arguments to the publish command

### ISSUE THREAD

**Issue by budcribar** [Azure/static-web-apps#223]
I would like to pass in the SourceRevisionId, BuildId, and BuildNumber during the publishing step so they show up in the about page. Is this currently possible? 

i.e. /p:SourceRevisionId=$(Build.SourceVersion) /p:BuildId=$(Build.BuildId) /p:BuildNumber=$(Build.BuildNumber)

**Comment by miwebst** [comment]
Hey @budcribar, 

GitHub actions offers a bunch of different environment variables that you can use: https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables

You should be able to have your build process look for these and update the corresponding static content during build.
