### ISSUE TITLE
Cannot publish Hugo-generated site to static web app.

### ISSUE THREAD

**Issue by akulbe** [Azure/static-web-apps#224]
Every attempt to publish results in an "Internal Server Error".

The [parameters](https://www.dropbox.com/s/woev7clfl9nwibd/parameters.json) I used are here.
The [template](https://www.dropbox.com/s/2gmwy5mukohjfqv/template.json) is here.

I also recorded a [screencast](https://www.youtube.com/watch?v=DvIs5yWveO0) that reproduces the steps.

**Comment by miwebst** [comment]
Thanks for the video and templates! From our logs looks like you were able to eventually deploy, but the 500's looked to be from errors when we were calling GitHub to add the workflow file.

A couple of quick questions about your template:
- I assume the repo token was actually populated, just not in the version you uploaded correct?
- Do you have functions in this repo? I assume "" is implying no?

**Comment by akulbe** [comment]
I didn't create any token for this, as I didn't know I would need to. Do I?

No functions in the repo.

**Comment by akulbe** [comment]
@miwebst as an aside, I also tried doing the same thing, but with a static site generated from Jekyll. It gave me issues during the build-and-deploy about the sass dependency not being installed. I wasn't sure how to modify the workflow file to get it included.

**Comment by miwebst** [comment]
Oh interesting, I would have expected things to fail differently if the token was not provided. The repository token (for GitHub) is a GitHub PAT that has admin access to your repo. Without this we can cannot add the workflow file to your repo. 

This certainly seems like a bug though so if that is the cause then we will need to investigate this more deeply on our side.

**Comment by miwebst** [comment]
For Jekyll, I don't believe we support this out of the box yet. You may need to adjust the workflow file to have it build before getting to the build and deploy step. You can find a tutorial here: https://docs.microsoft.com/en-us/azure/static-web-apps/publish-jekyll

**Comment by akulbe** [comment]
That was exactly the tutorial I'd followed, and even with doing that, it
still fails. In the output it talks about the "sass" dependency not being
available.

**Comment by anthonychu** [comment]
@akulbe If the repo is public, can you please share it? If not, please post the errors from the build and the workflow file. The SASS dependency error sounds like something from the build steps that are added before the Static Web Apps github action.

As for the original deployment problem. Looks like there's some confusion about whether you manually ran a template to deploy or if you deployed through the portal (in the video, it was the portal). The PAT is generally only an issue if running the ARM template yourself, you need to ensure you provide a PAT. This is done for you in the portal when you login in to GitHub on one of the the first steps.

**Comment by akulbe** [comment]
I think this ended up being an error on my part. I got it to publish now. Rudimentary and ugly, but it _works._

**Comment by jezkerwin** [comment]
@akulbe Would you mind sharing how your resolve this issue? I'm having the exact same one.
Thanks.
