### ISSUE TITLE
Changing configured Custom Domain

### ISSUE THREAD

**Issue by MaxMommersteeg** [Azure/static-web-apps#225]
Hi,

Today I tried changing the Custom Domain I had configured for my Static Web App. First off I tried validating the new custom domain `www.<new-domain>.com` which succeeded. After pressing `Add` I received the message explaining that it is currently only possible to have 1 custom domain being setup per Static Web App instance.

With that knowledge I decided to remove the old custom domain. After receiving a success message I tried adding the new custom domain again. Following notification popped up in Azure:
![image](https://user-images.githubusercontent.com/9657173/100767658-507ad580-33fa-11eb-82da-081f88bca06c.png)

However, the list of custom domains remained empty. The activity log gave me a bit more information:
![image](https://user-images.githubusercontent.com/9657173/100799022-b714e900-3424-11eb-8ca3-59c52c1840d3.png)

The top-level operation contains following status message:
```json
"statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"Unspecified\",\"message\":\"\"}]}}"
```
>Note: This is not the complete operation's JSON. I can post that later if requested.

It is not clear to me what fails. I tried adding the new domain, but also re-adding the old domain again. Both fail with the same message.

Thanks.

**Comment by miwebst** [comment]
Hey Max,

This is an issue with the service that helps us generate SSL certificates. We are working with them to fix this and then you should be unblocked.

**Comment by miwebst** [comment]
Hey Max, 

This should be resolved now, do you mind trying again?

**Comment by MaxMommersteeg** [comment]
Wow, that was really quick. It works, thanks!
