### ISSUE TITLE
How to enable API function-level authorization

### ISSUE THREAD

**Issue by rhollins** [Azure/static-web-apps#226]
Hello, 

I'm trying to prevent anonymous access to API running together with static web app however without using roles functionality (I don't want users to log in or authenticate to the static web app)

The MS doc here (https://docs.microsoft.com/en-us/azure/static-web-apps/add-api) suggests it is possible to use function-level authorization by specifying function key like it can be done for regular azure function.

The problem is that I cannot find this key anywhere by looking on static web app resource in azure... so just wonder is there a way to obtain it.

Or if not is there any other way to disallow anonymous access to API function only, since the function is in consumption offer I'm worried about cost the that can be generated should someone just decided to call the function directly multiple times.
Perhaps CORS rules allowing access only from static web app but again I couldn't find any information on that.

**Comment by annaji-msft** [comment]
For SWA functions, You can set the authlevel in function.json to function or admin Instead of anonymous and that should do. https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=csharp#configuration

You are right anonymous is not recommended in production. We will most probably lock down the anonymous authlevel for GA.

**Comment by rhollins** [comment]
Just wondering if there is a way to obtain keys for function running as part of a static web app normally for the regular function I would use "az functionapp function keys" but I can not see this option currently for "az staticwebapp"

**Comment by annaji-msft** [comment]
@rhollins SWA functions are not expected to be called outside SWA context. Also the keys are not exposed by design.

**Comment by anthonychu** [comment]
@rhollins Even if you were able to use function keys, you would probably embed the key in your static web app and someone can still use it to call your APIs from outside the context of you app. The most reliable solution is to require login.

**Comment by rhollins** [comment]
Thanks that makes sense.

**Comment by noontz** [comment]
> You can set the authlevel in function.json to function or admin

Setting the authlevel to admin is not allowed:

Error in processing api build artifacts: the file 'test/function.json' specifies an invalid authLevel. Allowed authLevels: anonymous, function.

**Comment by noontz** [comment]
@JayQuerido sorry no. I resolved to my default approach of giving up, when running into issues with SWA.
