### ISSUE TITLE
Custom domain error: Request Envelope is invalid.

### ISSUE THREAD

**Issue by Kryptryx** [Azure/static-web-apps#227]
When adding a custom domain to my static web app, I am getting the following error:

> Request Envelope is invalid. Please ensure the custom domain is not linked to another site.

I know that the domain name has propagated, because that would cause a different message.

I have successfully added custom domain names to other static web apps. 

Static web app: victorious-smoke-00203d10f.azurestaticapps.net
Customer domain: www.kryptryx.dev

I know that it has work for this particular domain previously when I was testing, and I know that when I deleted the test static web app, I did NOT manually delete the custom domain before hand. Is it possible this has resulted in some data inconsistency?

**Comment by miwebst** [comment]
Hey @Kryptryx,

Yes looks like something got corrupted, we will take a look!

**Comment by Kryptryx** [comment]
Tried again today, and it worked!
Either you fixed something in the data, or it repaired itself.
Issue closed.

**Comment by BieleckiLtd** [comment]
Are *.example.com custom domains on other DNS not supported? I got exactly the same error message when trying to add one.
