### ISSUE TITLE
Failed to update application settings: An error has occurred.

### ISSUE THREAD

**Issue by rhollins** [Azure/static-web-apps#228]
Hi, 

I've created azure static app on hugo framework with http triggered azure function, custom domain, and when I try to add a new item into settings I get the following error:

Updating application settings
Failed to update application settings: An error has occurred.

After that I cannot either edit or remove settings and also github action no longer can deploy and fail with the following error:

Azure/static-web-apps-deploy@v0.0.1-previw
...
Deployment Failed :(
Deployment Failure Reason: An error occurred during deployment
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Build And Deploy

The only way is to delete the static app resource and create a new one, I tried with three different static web apps all created in West Europe and have same problem.

**Comment by annaji-msft** [comment]
@rhollins Are you able to set the appsettings via Azure Portal? Or is this only happening from Github Actions or Az cli?

Could you provide more information about your app. 

Azure Resource Id:
Subscription Id:
Resource Group Name:
Static Web App Name:
Default Host Url:
GitHub Repo: 
Is Repo Public:
If Public, Branch Name:
Is Using APIs/Functions:

**Comment by rhollins** [comment]
So from what I can see the problem is the name of the setting if it's "username" then I get this error and the pipeline would fail, renaming it to "_username" and saving fixes the problem luckily so no need to recreate the resource.

I created public repo https://github.com/rhollins/static-app to test this issue.

The change was done through the portal to reproduce simply add name "username" with value "something" click save and here is the pipeline failure I got after that: https://github.com/rhollins/static-app/runs/1497691462?check_suite_focus=true

Azure Resource Id: n/a
Subscription Id: n/a
Resource Group Name: n/a
Static Web App Name: n/a
Default Host Url: https://polite-pebble-014137c03.azurestaticapps.net
GitHub Repo: https://github.com/rhollins/static-app
Is Repo Public: yes
If Public, Branch Name: master
Is Using APIs/Functions: yes

**Comment by simonaco** [comment]
@rhollins I wasn't able to reproduce your issue, please reopen if you're still seeing this.
