### ISSUE TITLE
_framework/blazor.webassembly.js missing on deployment

### ISSUE THREAD

**Issue by mschleifer** [Azure/static-web-apps#230]
I had trouble with my SWA deployment following the [documentation here](https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-blazor).

I have a [Blazor client + Node api app](https://github.com/mschleifer/FantasyLeagueReport) that would load initially, but then the console presented
`Loading failed for the <script> with source “<my app URL>/_framework/blazor.webassembly.js”.`

I ran into 2 issues with the automatically generated yml file

1. The "app_artifact_location" field was initially keyed as "output location" - [fix](https://github.com/mschleifer/FantasyLeagueReport/commit/789ea812e50b69357034373d38ed0453be373f46#diff-72b4c71fe3ac161941abd3de5179e119f859f11e7d8b2fd094985fe27866d9a8)

2. The Blazor project appears never to have been built in the "Build and Deploy" job - [failed job log](https://github.com/mschleifer/FantasyLeagueReport/runs/1503950485). I got the deployment working by [updating the yml file](https://github.com/mschleifer/FantasyLeagueReport/commit/2727b1cf5919df1f8b148fcab8ff0e439d05a021#diff-72b4c71fe3ac161941abd3de5179e119f859f11e7d8b2fd094985fe27866d9a8) to build the Blazor project explicitly similar to #220. 

I'd have expected the automatically generated yml or Oryx to take care of that step. Not sure if there's a bug with Oryx and Blazor + Node apps or if I setup my project wrong.

**Comment by miwebst** [comment]
Hey @mschleifer,

First for the output_location, check out this https://github.com/Azure/static-web-apps/issues/201 - we still need to document this but its hopefully more clear than app_artifact_location, @craigshoemaker can you help with this?

Second looking at your project (thanks for including links!), it looks like you are building the project earlier in the action and then passing the static content into the app_location. This is supported, but note app_artifact_location wont be used in this setup as it is only used if Static Web Apps/Oryx builds the project.

As for the initial failure, it looks correctly configured to me. I am a bit confused why this file did not exist. I'd actually expect that this is an Oryx issue and you may want to raise an issue there (https://github.com/microsoft/Oryx)

**Comment by mschleifer** [comment]
Looks like the app_artifact_location/output_location piece is unrelated to my problems then. If the missing bits of the Blazor app are probably related to Oryx I'll open an issue there and close this one. Thanks!
