### ISSUE TITLE
Docs: Quickstarts -> Build your first SWA -> VS Code: Outdated

### ISSUE THREAD

**Issue by webmaxru** [Azure/static-web-apps#234]
The flow described on this page https://docs.microsoft.com/en-gb/azure/static-web-apps/getting-started does not take Build Presets into account. I believe it was written before these presets were added. So if someone follows the guide, they might be confused by seeing another set of steps.

**Comment by jon-a-nygaard** [comment]
Hi @webmaxru, it looks like presets now has been added to the article at [Create a static web app -> step #5](https://docs.microsoft.com/en-gb/azure/static-web-apps/getting-started?tabs=vanilla-javascript#create-a-static-web-app). Can this issue be considered as solved and closed? 🙂
