### ISSUE TITLE
VS Code SWA Extension: DX improvement proposal/fix for creating new app flow

### ISSUE THREAD

**Issue by webmaxru** [Azure/static-web-apps#235]
When you create a new SWA app via VS Code extension and use Build Presets, there is no way to see/edit the values of these presets - after you selected preset, you can only select the region, and deployment starts immediately. In the best case scenario, if the preset 100% fits the application, this is ok. But for example for Angular, there is no chance to have properly configured deployment (because there is no "static" app artifact location for this framework, the path includes project name), so developers inevitably receive misconfigured app. I see the following solution:
- even after you selected a particular preset, you still go through app location / api location / output location dialogues, with the fields prefilled by the preset values.

**Comment by nturinski** [comment]
Thanks for your insights @webmaxru.  

We wanted to make creation more streamlined by having the build presets to reduce the number of steps.  We based the experience off the portal, but they just prefill the input forms for the users so it seems like that we have to still prompt for it anyway as you said.

![image](https://user-images.githubusercontent.com/5290572/101521381-a2f84c80-393a-11eb-9045-0bc754c55fcc.png)

For now, users could leverage the `staticWebApp.appSubpath`, `staticWebApp.apiSubpath`, or `staticWebApp.outputSubpath` settings to circumvent this, but this isn't a great or obvious solution.

Related to https://github.com/microsoft/vscode-azurestaticwebapps/issues/277

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurestaticwebapps/issues/337

**Comment by simonaco** [comment]
resolved in vs code extension
