### ISSUE TITLE
Feature request for lightweight authentication

### ISSUE THREAD

**Issue by kitmccormick-22ops** [Azure/static-web-apps#236]
We have a dev flow where the production application is visible to the world at large, but the dev and staging deployments are only visible to the dev team and our clients.  We have a couple of apps in progress, hosted on App Service, where the password is just an application setting.  These apps are on node/express and use a simple express middleware to screen access to the works in progress.  I would really like to target SWA for this sort of work (we are a creative agency, so this will be ongoing), but I need something lightweight to screen access to our respective dev and staging environments.

**Comment by anthonychu** [comment]
Related #94

**Comment by dbrennan** [comment]
+1

**Comment by SIkebe** [comment]
@anthonychu Is it possible to switch settings per environment like `staticwebapp.config.{environment}.json`?
Or something like this...
```
{
    "route": "/",
    "allowedRoles": ["anonymous"],
    "env": "production"
},
{
    "route": "/",
    "allowedRoles": ["contributor"],
    "env": "staging"
},
```

**Comment by anthonychu** [comment]
@SIkebe that’s a interesting suggestion, can you please file a new issue for it?

Password protecting a site is something we are looking at but the work isn’t committed yet so there’s no ETA at this time.

**Comment by miwebst** [comment]
This is now in public preview! Try it out and let us know what you think! https://azure.microsoft.com/en-us/updates/public-preview-protect-azure-static-web-apps-environments-with-a-password-2/
