### ISSUE TITLE
Support a custom user store for identity

### ISSUE THREAD

**Issue by adamjcooper** [Azure/static-web-apps#24]
Congrats on the beta release.

At the moment it looks like you have built-in support for some popular third-party auth providers, where users already have an account with the third party. What is the story if I want my users to be able to sign up for an account on my site directly? That is, how would I go about offering people a way to sign up for an account for my own domain rather than using an existing Facebook, Google, Twitter, GitHub, Azure AD, etc. account?

Thanks!

**Comment by m-sterspace** [comment]
As far as I can tell right now the primary issue is that the URLs aren't particularly stable, yet authentication services like Azure AD require stableish callback URLs. 

Unlimited staging slots based on pull requests seems great at first blush, but they're not the most useful to me if I have to go and manually update the callback urls for all my authentication providers every time one is created ...

**Comment by mkarmark** [comment]
Thank you for using Azure Static Web Apps!

For preview, using the five offered providers and having the users log in to Azure Static Web Apps is the only option for authentication/authorization.

Supporting custom authentication is something we plan to offer in the future.

Thank you for your feedback. Keep them coming.

**Comment by anthonychu** [comment]
We don't currently have plans to directly support authenticating against a custom user store that we provide. However, we may provide Open ID Connect support in the future and it might be possible to use a provider that supports a user store like Auth0 and Azure AAD B2C.

**Comment by DjolePetrovic** [comment]
So this [blog post](https://anthonychu.ca/post/azure-functions-app-service-openid-connect-auth0/) you wrote does not apply to azure static web apps? Or it does?

**Comment by anthonychu** [comment]
@DjolePetrovic That's correct. For the time being, OIDC integration is only available in App Service and Azure Functions.

**Comment by jpatdu-credovita** [comment]
+1 on OIDC integration for Azure Static Web Apps; this is the only thing missing for me to practically host all of my full stack web apps on ASWA.

**Comment by anthonychu** [comment]
We’re working on OpenID Connect support. No ETA yet but check back in a couple of months for updates.

**Comment by Sam-Rowe** [comment]
Custom auth using an OpenID connect is now in the docs - https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad

**Comment by anthonychu** [comment]
In addition to OpenID Connect support, we just released a feature to programmatically assign roles with a function. Within the function, you can look up user/role information from your own database or some other API. See the [documentation](https://docs.microsoft.com/azure/static-web-apps/authentication-authorization?tabs=function#role-management) for more details. There's also a [tutorial](https://docs.microsoft.com/azure/static-web-apps/assign-roles-microsoft-graph) with a sample app.

**Comment by smakinson** [comment]
@anthonychu Is the custom identity provider setup meant to allow end users to be created/stored with something like strapi or wordpress? If so, would users be able to sign up from a static web app site, login via `/.auth/login/strapiProvider`? And roles would all need to be handled via that new feature above?

**Comment by anthonychu** [comment]
It doesn't look like Strapi exposes itself as an OpenID Connect provider, so there might be no way to integrate it with Static Web Apps auth. You can try to instead use Strapi directly for auth and use Static Web Apps to serve your site's static assets.
/cc @simonaco

**Comment by Reshmi-Sriram** [comment]
Closing since no further discussions. Feel free to reopen if necessary!
