### ISSUE TITLE
Failed to upload build artifacts

### ISSUE THREAD

**Issue by sebastiansmithomm** [Azure/static-web-apps#240]
We get 'failed to upload build artifacts' lately on our static site build. 

![image](https://user-images.githubusercontent.com/74179584/102115111-ff73d400-3e32-11eb-9377-f6c677c1974f.png)

**Comment by miwebst** [comment]
Hey @sebastiansmithomm do you mind providing the region where this static web app is hosted or the default hostname of the static web app? We can take a look.

**Comment by tvonment** [comment]
I have the same Issue.
icy-wave-07c2c9f03.azurestaticapps.net -> in west europe.

**Comment by sebastiansmithomm** [comment]
Hi sorry for the delay

https://delightful-field-0ca858b03.azurestaticapps.net
ACG Basecamp Paris<https://delightful-field-0ca858b03.azurestaticapps.net/>
ACG Basecamp Paris
delightful-field-0ca858b03.azurestaticapps.net


West Europe.

Thanks

________________________________

Sebastian Smith
|
Technical Lead
OMM
|
+44 (0)1753 576989
|
Mobile +44 7739 019219‬
www.omm.agency
​

**Comment by sebastiansmithomm** [comment]
FYI this is still happening for me with multiple sites. @miwebst

**Comment by miwebst** [comment]
Hey @sebastiansmithomm do you mind sharing those as well? We believe we've identified the issue and it will roll out after the holidays but might be good to have a few more sites to validate our current theory.

**Comment by AndreasRenghart** [comment]
Same Problem: https://salmon-cliff-05fd9ec03.azurestaticapps.net/

**Comment by miwebst** [comment]
Yes this seems to be the same issue :( we apologize for the inconvenience! Our fix will be delayed due to the holiday season, but hoping to get this out after next week!

**Comment by tvonment** [comment]
it works for me again. thanks

**Comment by miwebst** [comment]
This should be fixed everywhere now, thanks for your patience!

**Comment by Herries2014** [comment]
@miwebst I am getting "Error: aborting artifact upload" while doing an urgent deployment. Please can you help?
![image](https://user-images.githubusercontent.com/7486135/146165156-4d9a8a17-83c8-40aa-87a7-29d102709139.png)

**Comment by miwebst** [comment]
I don't believe this is anything that we are involved with. Can you provide your workflow file / full action logs so we can confirm?

**Comment by sagar131setu** [comment]
![image](https://user-images.githubusercontent.com/116707851/217918855-414689ee-85f5-4396-b82f-c7bdbda13b28.png)
can you check this @miwebst

**Comment by Exitare** [comment]
I get this error also basically 50% of the time while trying to deploy to a static website.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/13048528/218235931-2df9881f-b2dd-4537-83f2-c7f269123c57.png">

**Comment by sagar131setu** [comment]
raised the new issue for this https://github.com/Azure/static-web-apps/issues/1075

**Comment by sagar131setu** [comment]
> I get this error also basically 50% of the time while trying to deploy to a static website.
> 
> <img alt="image" width="1058" src="https://user-images.githubusercontent.com/13048528/218235931-2df9881f-b2dd-4537-83f2-c7f269123c57.png">

https://github.com/Azure/static-web-apps/issues/1075 I have created this new issue for this same error

**Comment by sagar131setu** [comment]
> This should be fixed everywhere now, thanks for your patience!

https://github.com/Azure/static-web-apps/issues/1075 created new issue for same error @miwebst

**Comment by Tcsekhar74** [comment]
This has started to happen for me since today. I never had this issue before. It fails while trying to upload artifacts.

**Comment by AndronikosGiachanatzis** [comment]
I had the same issue and apparently my firewall was blocking the requests made to upload the artifacts to azure. It helped to allow all subdomain *.azurestaticapps.net" addresses
