### ISSUE TITLE
Provide an option to skip build entirely

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#248]
Would be great to provide an easy way to skip the app or API build. Currently we provide the ability to specify build commands, which might still run npm install (according to docs) and it’s not clear what to set there if we simply want to skip the build entirely.

The goal of this is to provide an easy way for the customer to manage the build of the app and/or API entirely and only use the action for deployment.

**Comment by riverar** [comment]
Agreed. This is especially important for projects that consolidate at the root and do not want to incur the GitHub Actions time penalty of being built _twice_. `app_build_command` and/or `api_build_command` set to `echo skipping build` is a decent workaround for now.

**Comment by itpropro** [comment]
I deploy a few static pregenerated sites with SWAs currently. At least for the html its enough to just specify the directory and Oryx will detect that there is nothing to build:
```Bash
Detecting platforms...
Could not detect any platform in the source directory.
...
---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
```

**Comment by itpropro** [comment]
@anthonychu do you know, if it's possible to use the Oryx environment configurations in GitHub Actions? https://github.com/microsoft/Oryx/blob/master/doc/configuration.md#oryx-configuration

**Comment by plamber** [comment]
Hello,
would find this feature useful. We want to use our dedicated runner servers and optimize the building process with different caching mechanisms. 

Having an Upload only for App and Api would be a good addition.

br,
Patrick

**Comment by miwebst** [comment]
This feature is now live! You can add this to your build configuration:
`skip_app_build: true`

When this is added we will skip the Oryx build of the app so you can just place your built application in the `app_location` directory. A couple of notes on this before we get documentation up:
- Output_location / app_artifact_location is ignored when using this option
- This only applies to the app, not the api. We are still working on that

@craigshoemaker as fyi

**Comment by anthonychu** [comment]
Closing this as resolved. Added new issue to track a similar capability for API build. #343
