### ISSUE TITLE
Feature Unavailable: Facebook Login is currently unavailable for this app.

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#250]
Error when trying to login with facebook

**Comment by anthonychu** [comment]
@drma-dev Please provide more info on the error and how you got it. I just tested it out and it's working fine. See here that I'm logged in and my profile is returned at `/.auth/me`.

![image](https://user-images.githubusercontent.com/3982077/103449259-9a094b00-4c5a-11eb-99f7-9846683e9fbb.png)

**Comment by drma-dev** [comment]
I do not know exactly

![image](https://user-images.githubusercontent.com/12803050/103449379-5b898580-4c86-11eb-8d70-32d6364b5646.png)
![image](https://user-images.githubusercontent.com/12803050/103449380-617f6680-4c86-11eb-9482-a0a1443f48c1.png)

**Comment by drma-dev** [comment]
I was thinking it could be something on my facebook, so I asked a friend to test it for me. Same result.

![image](https://user-images.githubusercontent.com/12803050/103461956-b8298680-4d00-11eb-9287-efc8fc64398f.png)

**Comment by tmol** [comment]
Hi guys, got the same problem. I configured in the FaceBook application the ”Valid OAuth Redirect URIs” to ”https://identity.azurestaticapps.net/.auth/login/facebook/callback”. The FaceBook app is working, I implemented a plain JavaScript authentication using the FB JS API.

Below is the invitationurl (the expiration is set for 48 hours):

https://red-dune-0ed2a5a03.azurestaticapps.net/.auth/invitations/accept?provider=facebook&userDetails=tibor.edgar.molnar%40gmail.com&roles=preecky_user&se=2021-01-04T20%3A05%3A14Z&sig=0X6YSvJiOwrG6wo1N%2BLM00Xs68avn7P7jdkdg%2BrBmtI8moJ%2BkCpogDbjUtPAias16nDdsraI%2BuBKMCCBnF0tx0DTIMXv4sLeWP1V%2Brdsyop4xa8nAhAng5BzM79KzDmfeQhyIdW2luPkkKT65Rcm6TEAv4Z085dtaJAomjP9ajLEx4Snd141UGBryQmXB3AbN5LduMYLvY8cuCJ%2BOBXlTQ%3D%3D

![image](https://user-images.githubusercontent.com/8946235/103465699-0792a580-4d47-11eb-9162-7d71a3e625fc.png)

**Comment by anthonychu** [comment]
@tmol Can you describe a bit more about how you’re setting this up? You cannot use your own Facebook app registration with Static Web Apps right now. You should be using the login links as described here: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization

We don’t currently support using the Facebook JS libraries to authenticate.

/cc @mkarmark

**Comment by tmol** [comment]
Thank you for your response. Yes sorry, I mixed things up :-) (I was testing manual login using a custom FB app). Bottom line is that I am using the steps defined in the article you mentioned (https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization), I am generating a link like the one mentioned above and receive the response described above "Feature Unavailable: Facebook Login is currently unavailable for this app.".

![image](https://user-images.githubusercontent.com/8946235/103473132-c679b000-4d9d-11eb-9b0e-1d84f976d271.png)

**Comment by Gabswim** [comment]
I am also experiencing this issue, and I'm using the standard URL stated in the documentation here: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization#login.
It was working before.

**Comment by anthonychu** [comment]
@mkarmark Could you please take a look?

**Comment by mkarmark** [comment]
I have resolved the issue that was preventing logins; Facebook logins should now be successful. Apologies for the inconvenience!

**Comment by drma-dev** [comment]
Well, now something else is happening. And now with all the logins: sorry there's nothing at this address

I'm getting this message in the browser, I don't know if it's related:
```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
```

It only works if I clear the cache and enter the address manually.

**Comment by mkarmark** [comment]
Sorry I'm not able to repro that on our end, could you email us a .har file or a video showing exactly how the flow is breaking for you?

**Comment by drma-dev** [comment]
right. which email?

**Comment by anthonychu** [comment]
@drma-dev Can you please send it to me at antchu@microsoft.com and I can relay it to @mkarmark? Thanks.

**Comment by drma-dev** [comment]
done. thanks.

**Comment by Gabswim** [comment]
@mkarmark it's working for me now. Thank you!

**Comment by tmol** [comment]
Is working for me too. Thank you @mkarmark  :-)

**Comment by saravanan-trika** [comment]
@mkarmark @drma-dev i have same problem, Please send to me also, shravanece3@gmail.com

**Comment by farhantariq916** [comment]
> @mkarmark it's working for me now. Thank you!

How you solve? Can you please help me?

**Comment by drma-dev** [comment]
there is nothing for the developer to do. it is an internal configuration from microsoft.

**Comment by imran-abbas1** [comment]
If anyone is still facing this issue. Please check in your developer account if you have a pending Data use Checkup.
Once you complete it, it should work.

**Comment by sumit2607** [comment]
While debugging this I found that it is a device-specific issue so don't really on one device test case just try with another device it will work fine. Note: This is related to Android only.

**Comment by Taha-Abdelmonim** [comment]
![facebbok](https://user-images.githubusercontent.com/89081670/234245933-1ba72faa-ee2d-46a8-a672-05f2aea62daa.png)

**Verification required Business must be verified**
