### ISSUE TITLE
401: Unauthorized - when you access the login page with expired cookie

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#251]
![image](https://user-images.githubusercontent.com/12803050/103458244-ea2cef80-4ce4-11eb-88ec-4f4458c6dba6.png)

**Comment by cirzoltan** [comment]
Any news on this? Google would be the main authenticator provider for our service so unless this is fixed soon we'll have to look elsewhere for hosting.

**Comment by mkarmark** [comment]
We are actively working on a fix we should have deployed soon, and will update this thread when it's out.

**Comment by drma-dev** [comment]
@mkarmark  is there a date to stop being a preview?

**Comment by stunney** [comment]
Hitting this issue now on our site (https://jolly-grass-07aed040f.azurestaticapps.net/)

Can you please review?

**Comment by lenniebriscoe** [comment]
same : https://delightful-moss-00b8bd103.azurestaticapps.net/
