### ISSUE TITLE
possibilities of multiple social logins for a unique user

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#252]
Would it be possible to use the '/.auth/login/*' feature to generate a single id with multiple logins?

```
{
	"clientPrincipal": {
		"userId": "1234567890",
		"userRoles": [
			"anonymous",
			"authenticated"
		],
		"logins": [
			{
				"identityProvider": "google",
				"userDetails": "my@gmail.com"
			},
			{
				"identityProvider": "facebook",
				"userDetails": "my@gmail.com"
			}
		]
	}
}
```

**Comment by mkarmark** [comment]
Currently, we only keep track of the user profile from the most recent login and don't have plans of aggregating multiple login profiles as shown in the json object above. Do you have a specific scenario in mind where that would be of benefit?

**Comment by drma-dev** [comment]
Well, it is that web applications generally offer multiple forms of access for a user. It serves both to validate the user's authenticity and when to lose access to a specific social network.
