### ISSUE TITLE
App settings editing is disabled when there's a function app

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#255]
If a function app has trouble starting up, the app settings pane in the portal cannot be modified. Often this may be because they need to add a setting (DB connection, etc) that makes the app start successfully, and there's no way to set this to resolve it.

I have another app that was working but is now returning 403 from the functions endpoint. I'm unable to modify app settings in an attempt to revive it. (for instance, I might want to add app insights to see what's wrong)

And eventually we'll allow some app settings that are for the SWA itself, not the API. Perhaps we should unblock the editing of app settings in the portal. Instead, provide a message on the purpose of app settings.

@ehamai @annaji-msft @takyyon

**Comment by Reshmi-Sriram** [comment]
Resolved as mentioned in https://github.com/Azure/static-web-apps/issues/289
Closing the issue
