### ISSUE TITLE
workflow file and portal UI show different field name for output_location

### ISSUE THREAD

**Issue by johnpapa** [Azure/static-web-apps#257]
Recently (Nov 2020) the default name was changed from `app_artifact_location` to `output_location`. The Portal still shows the old name but the workflow file shows the new name. I recommend using the new name of `output_location` everywhere.

Note - both still work, which is cool.

![image](https://user-images.githubusercontent.com/1202528/103670292-63c41800-4f47-11eb-9fd3-272c97055a9d.png)

cc @miwebst

**Comment by ehamai** [comment]
@takyyon can you take a look please?

**Comment by takyyon** [comment]
Closing this as the updates have been made and it should be live by the end of next week.
