### ISSUE TITLE
'service worker' does not work on static web app

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#258]
![image](https://user-images.githubusercontent.com/12803050/103767694-dabce780-4fff-11eb-82e4-74edf1a401b2.png)

**Comment by drma-dev** [comment]
Apparently the manifest too, despite being accessible

![image](https://user-images.githubusercontent.com/12803050/103770077-2e313480-5004-11eb-8f8d-45cfc4e2eb21.png)

**Comment by anthonychu** [comment]
Can you please provide more information? There should be nothing blocking service workers.

**Comment by drma-dev** [comment]
The most I can see is this
![image](https://user-images.githubusercontent.com/12803050/103800995-dd353680-502b-11eb-8ce8-c586f8f23e42.png)

I only realized it when I was trying to generate an app on https://www.pwabuilder.com/
![image](https://user-images.githubusercontent.com/12803050/103801258-3dc47380-502c-11eb-9330-62a853ffcea8.png)

**Comment by anthonychu** [comment]
Please see solution in #259
