### ISSUE TITLE
public and private accesses on API routes

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#260]
As I understand it from the documentation, putting 'anonymous' would free access for unauthenticated users.
```
{
  "routes": [
    {
      "route": "/.auth/login/aad",
      "statusCode": "404"
    },
    {
      "route": "/.auth/login/github",
      "statusCode": "404"
    },
    {
      "route": "/api/public/*",
      "allowedRoles": [ "anonymous" ]
    },
    {
      "route": "/api/*",
      "allowedRoles": [ "authenticated" ]
    },
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ]
}
```

But that is not what is happening. Or am I doing something wrong?

![image](https://user-images.githubusercontent.com/12803050/103787711-b15e8480-501c-11eb-9f13-bd904a04195f.png)

**Comment by miwebst** [comment]
I believe this is because routes are case sensitive. Can you try going to /api/**p**ublic/... and see if that fixes it?

**Comment by drma-dev** [comment]
Yes, that's right.

But I think it shouldn't be like that. It has great potential for generating unintended errors.
