### ISSUE TITLE
? added to redirect URL after login

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#262]
After redirecting browser to `/.auth/login/github` (likely other providers too), the browser is redirected to the root of the site, but with `?` appended to the end of the URL. Can't imagine this affecting the app itself, but would be better cosmetically if it wasn't there.

/cc @mkarmark

**Comment by itpropro** [comment]
Can confirm this issue from multiple instances.

**Comment by anthonychu** [comment]
This is now resolved.
