### ISSUE TITLE
trying to log in => sorry, there is nothing at this address

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#264]
![image](https://user-images.githubusercontent.com/12803050/104599240-48978d80-5656-11eb-91e4-b98c5218c304.png)

this error has been happening for a while, both when trying to log in and to log out. I found that deleting the 'index.html' file from the cache resolves and the targeting for that endpoint works again.

**Comment by drma-dev** [comment]
`const offlineAssetsExclude = [/^service-worker\.js$/, /^routes\.json$/, /^index\.html$/];`

removing the 'index.html' from the 'service-worker.published.js' file temporarily solved this problem.

**Comment by mkarmark** [comment]
Hi @drma-dev. This seems to be a caching issue we need to look deeper into. Do you mind sending us your har file in which you are able to repro this behavior. We can dig deeper into it once we have that.

**Comment by mkarmark** [comment]
Also do you mind sharing your app name, so that we can take a look at the logs on our end to see if anything is off?

**Comment by drma-dev** [comment]
I had already sent you a video by email.

app name: web-verusdate
https://green-grass-0dbf41210.azurestaticapps.net

**Comment by drma-dev** [comment]
@mkarmark  
did you manage to find out anything

**Comment by drma-dev** [comment]
@mkarmark the problem continues to this day...
