### ISSUE TITLE
Sku is invalid. This subscription has too many static sites with sku: Free.

### ISSUE THREAD

**Issue by m-sterspace** [Azure/static-web-apps#265]
I'm trying to create another Static Web App, and am hitting the error that my subscription has too many free static web apps. 

![image](https://user-images.githubusercontent.com/37154205/104624612-c9a85200-5661-11eb-8811-1ceceeeb1e00.png)

At present, I have 10 static web app instances set up under this subscription, however, I need the ability to add more as this is a corporate account and I do not have the freedom to create additional subscriptions. 

I understand that this service is still in preview, and there's no option to pay yet (would be more than happy to pay), but I really do need the option to have more instances. At present we are using three instances per website, as we need develop, staging, and production slots, and the base static web app preview's support for deployment slots will not work as it does not provide static or predictable urls as per [issue 22](https://github.com/Azure/static-web-apps/issues/22).

So I'm hitting this limit while trying to migrate our 4th website over (4x3 deployment slot = 12 instances, though only 4 of those see any real traffic). But is there any way to work around this before this services exits preview?

**Comment by miwebst** [comment]
Hey @m-sterspace sorry for the delay. At this time there isn't a way to go add more instances without adding another subscription. This will change in the coming months but for now you are likely blocked :(

**Comment by m-sterspace** [comment]
Ah, this service is already awesome, just take it out preview and [take my money](http://memecrunch.com/meme/TF8B/just-take-my-money/image.png)! 😋

**Comment by miwebst** [comment]
Hey @m-sterspace , sorry for the long delay on this, was waiting for GA to share details. The free limit is still 10 Free sku SWA's per sub, but you can have unlimited Standard sku SWA's per sub. So you should be able to use Standard to unblock!
