### ISSUE TITLE
Webpack issue?

### ISSUE THREAD

**Issue by stuartjdawson** [Azure/static-web-apps#266]
I run `npm run build` locally and my files get moved to my deploy folder perfectly.

I've set `app_build_command` to `npm run build` in the config .yml file but it appears only the HTML gets deployed in Azure and no JavaScript is injected into the page, as it is locally.

Any suggestions welcome!

(A quick Loom to help explain: https://www.loom.com/share/433e8ff41a1b4bd3b3b4c03d7d656c53)

**Comment by anthonychu** [comment]
@stuartjdawson Looks like we need to see the source to troubleshoot this. Can you share your repo or a sample repo that reproduces the problem?

**Comment by stuartjdawson** [comment]
Thanks, @anthonychu. Here is a simplified example repo that reproduces the issue:

https://github.com/stuartjdawson/ProblemDemo

**Comment by anthonychu** [comment]
Can you try:

```
app_location: "/"
api_location: ""
output_location: "deploy"
```

The action needs the folder where your package.json is as the app location. It should run `npm run build` for you (no need to specify explicitly). The output location is relative to the app location.

**Comment by stuartjdawson** [comment]
You're totally correct, @anthonychu , thank you!

Funnily enough, I tried this previously on my original repo but got a an error about one of my images. Turns out, it appears there is a case sensitity issue somewhere as when I renamed it from `.JPG` to `.jpg` all worked fine there too.

Anyway, thanks again. Much appreciated! 👍
