### ISSUE TITLE
Cannot access login pages in angular app

### ISSUE THREAD

**Issue by RunCMD159** [Azure/static-web-apps#267]
I try to login to any of the provided authentication providers but always get the following error when clicking the anchor element:
![image](https://user-images.githubusercontent.com/13946530/104837503-4848fd80-58b5-11eb-9d5f-35a887d9bd12.png)

The routes.json is configured as follows:
`{
  "routes": [
    {
      "route": "/admin/*",
      "allowedRoles": [
        "administrator"
      ]
    },
    {
      "route": "/api/admin",
      "allowedRoles": [
        "administrator"
      ]
    },
    {
      "route": "/github",
      "serve": "/.auth/login/github",
      "statusCode": "302"
    },
    {
      "route": "/facebook",
      "serve": "/.auth/login/facebook",
      "statusCode": "302"
    },
    {
      "route": "/google",
      "statusCode": "302",
      "serve": "/.auth/login/google"
    },
    {
      "route": "/logout",
      "serve": "/.auth/logout"
    }
  ],
  "platformErrorOverrides": [
    {
      "errorType": "NotFound",
      "serve": "/custom-404.html"
    }
  ]
}
`
I tried linking to the login pages via href and routerlink but nothing seems to work and I cannot figure out what I am doing wrong.

**Comment by anthonychu** [comment]
Can you open your browser and go directly to your app’s domain /github?

This looks like angular is not recognizing the route, which makes sense because it’s not an angular route. You likely have to use `window.location.href='/github'` in your code instead of using normal navigation to make this work.

**Comment by RunCMD159** [comment]
Thank you for your reply.
Your suggestion fixes a part of my problem.
As far as I can tell from my browser console, it seems that the angular cannot handle the redirect correctly after the login happens.
It says 'Cannot match any routes. URL Segment: '.auth/login/<provider>'

Do I need to let the angular router handle the redirect after the login?
If yes, what would be the best practice for this case?

Thank you in advance

**Comment by anthonychu** [comment]
I think we'll need more info to diagnose this problem. As far as I'm aware, `/.auth/login/`is not a location that is used in the post-login flow. By default, the login will redirect back to your app at `/`.

Can you share your network trace and any other relevant information?

cc @mkarmark

**Comment by RunCMD159** [comment]
Here's the network trace: 
[network-trace.zip](https://github.com/Azure/static-web-apps/files/5860099/network-trace.zip)
You could try it out yourself here if you want: [Test-App](https://delightful-forest-09c56ff03-27.westeurope.azurestaticapps.net/)

The app is a progressive web app, maybe it is an issue with the application cache?
The login seems to work sometimes but i cannot figure out when and how..

Please let me know if you need more information.

**Comment by RunCMD159** [comment]
Looks like the service worker is the problem here. The service worker is caching all routes of the domain so the login and logout urls are working sometimes when the cache is refreshed. 
I disabled the service worker for now and will try to add exceptions for the auth routes.

**Comment by rinoreji** [comment]
> Can you open your browser and go directly to your app’s domain /github?
> 
> This looks like angular is not recognizing the route, which makes sense because it’s not an angular route. You likely have to use `window.location.href='/github'` in your code instead of using normal navigation to make this work.

@anthonychu, I too had similar issue but only when adding `auth` section in `staticwebapp.config.json`. If I remove the `auth` section, all routes (login, logout and me) works.
