### ISSUE TITLE
Adding custom domain to static web app does not update URL to use the new domain

### ISSUE THREAD

**Issue by kevball2** [Azure/static-web-apps#268]
When I add a custom domain to my Static web app, the URL does not update to reflect the new domain. Is this expected behavior or is there additional information needed in routes.json to accomplish this?

SWA Config 
- Site created with Hugo 
- DNS host with cloud flare
   - CNAME set to pre-configured URL on static web app
   - CNAME set to just DNS redirect (No Proxy)

**Comment by joslinmicrosoft** [comment]
(I'm basing this response on the www.technicalpanda.com domain/site; please let me know if this is the wrong one.)

If I understand the problem correctly, the domain has been properly linked to the static web app, but the links on the site still use the default hostname we've generated. My guess is you have to change the baseUrl in your config.toml file https://github.com/kevball2/technicalpandadotcom/blob/e70b46e5d28a554614133c5c58fb01992e93978c/config.toml#L3. Currently, if you check the page source, the built site assets have the default hostname baked in.

**Comment by kevball2** [comment]
@joslinmicrosoft Thank you for pointing that out! Had been staring at the issue too long with the answer right under my nose :) appreciate the help!
