### ISSUE TITLE
Overriding of Authorization Bearer Header in API Request

### ISSUE THREAD

**Issue by connor-ww** [Azure/static-web-apps#275]
I am developing a Blazor WASM standalone app using AD B2C for user authentication and deploying to Static Web Apps.

I believe when calling the Azure Function API contained within my Static Web App, the service inserts its own auth token into the header. Since I am relying on the Authorization Bearer header to pass my B2C access token from app to api, it is being overwritten.

In my case, I am sending token:

```
{
  "typ": "JWT", 
  "alg": "RS256", 
  "kid": "{key value}"
}
{
  "iss": "https://{domain}.b2clogin.com/{tenant ID}/v2.0/", 
  "aud": "{client ID}"...
}
```
but my Azure Function API is receiving token:

```
{
  "typ": "JWT", 
  "alg": "HS256"...
}
{
  "iss": "https://{ID}.scm.azurewebsites.net", 
  "aud": "https://{ID}.azurewebsites.net/azurefunctions"...
}
```

Because of this, I'm unable to validate the request.

**Comment by miwebst** [comment]
I believe this is a repeat of https://github.com/Azure/static-web-apps/issues/34 We are working on some mechanisms to avoid using this header.

**Comment by connor-ww** [comment]
Ah, yes it is!  Thank you, I'll follow the status over there

**Comment by judedaryl** [comment]
i saw the same behavior with ``custom handlers``, when you try to use ``enableHttpRequestForwarding=true`` the headers get overwritten. However if you check the raw incoming http request by setting ``enableHttpRequestForwarding=false`` you get all of your incoming headers. Might be the reason why the supported runtimes do not have http like frameworks.

**Comment by Autosissy** [comment]
Why was this closed? It's not fixed. Managed api still has the problem.
