### ISSUE TITLE
Oryx build (Blazor wasm) fails - certificate issues

### ISSUE THREAD

**Issue by JStammen** [Azure/static-web-apps#276]
## Expected Behavior

Build should run and restore dotnet packages

## Actual Behavior

Console shows the following errors
/github/workspace/src/*/*.csproj : error NU3028: Package 'Microsoft.Extensions.FileSystemGlobbing 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain [/github/workspace/src/*/*.csproj]
/github/workspace/src/*/*.csproj : error NU3037: Package 'Microsoft.Extensions.FileSystemGlobbing 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. [/github/workspace/src/*/*.csproj]

## Steps to Reproduce the Problem

  1. Create blazor wasm application
  2. Create github workflow using Azure/static-web-apps-deploy@v0.0.1-preview
  3. Run workflow

After searching it might have to do with the following issue: https://github.com/NuGet/Home/issues/10491

**Comment by FBoucher** [comment]
It's totally is. 
Not sure if that new temporary image could do the trick...

**Comment by JStammen** [comment]
I checked and the dockerfile thats used by: Azure/static-web-apps-deploy@v0.0.1-preview which retrieves a docker container called:

FROM mcr.microsoft.com/appsvc/staticappsclient:stable

But since my own docker knowledge is very basic im not sure where the changed should be applied or how i could implement a work around.

**Comment by csharpfritz** [comment]
All of the Docker containers used by .NET and are based on Debian are broken.

Where can we find the source for this container `mcr.microsoft.com/appsvc/staticappsclient:stable` so that we can update it to run with the correct version?

I see there is no support or interaction on this repository in almost a year, how can we help get this fix deployed?

**Comment by anthonychu** [comment]
@csharpfritz Can you let us know what the fix is and we’ll apply it ASAP? Thanks. /cc @miwebst

**Comment by FBoucher** [comment]
Totally agree @JStammen. It was more a suggestion for the maintainers of this repo.

You can see the status and progress of this issue on NUget website: https://status.nuget.org/

**Comment by miwebst** [comment]
Thanks @FBoucher for the incident link. I'm assuming you all are using .net 5? Just wanted to double check that.

As for mitigating this, we utilize Oryx and they will need to update their Docker image with the suggested mitigation from nuget. We are working with them to get this fixed.

**Comment by JStammen** [comment]
@miwebst yeah were using .net 5 which is the reason why it stopped working right? So if the Oryx container gets updated the problem will be fixed? Or do the maintainers of this repo need to do something aswell?

**Comment by JStammen** [comment]
@csharpfritz i have tried to find the source of that specific container but to no luck. It doesnt seem to be hosted on dockerhub so im actually at a loss since where else should it be.

**Comment by miwebst** [comment]
@JStammen , @csharpfritz we have published a hot fix to the container to address this issue. Can you retry your build and see if the issue is resolved?

**Comment by JStammen** [comment]
@miwebst that seemed to have resolved to issue for me atleast

**Comment by csharpfritz** [comment]
Checking now...

**Comment by schotime** [comment]
Works for me here too. Thanks all.
