### ISSUE TITLE
Azure Function not set multiple cookies

### ISSUE THREAD

**Issue by hynjnk** [Azure/static-web-apps#278]
When setting multiple cookies on the Azure function response, but it send just one `Set-Cookie` header.

## Code
I set cookies like this. 
https://github.com/Azure/azure-functions-host/issues/2737#issuecomment-568037718

https://github.com/hynjnk/azure-static-web-demo
```
  context.res = {
    // status: 200, /* Defaults to 200 */
    body: 'Hello, world.',
    cookies: [
      {
        name: 'cookie1',
        value: 'value1'
      },
      {
        name: 'cookie2',
        value: 'value2'
      }
    ]
  }
```
## Function Endpoint
https://jolly-mud-0554ede00.azurestaticapps.net/api/SetCookie

## Result
![Screenshot from 2021-02-03 15-34-34](https://user-images.githubusercontent.com/38238305/106707919-647ac780-6635-11eb-8776-c13ddf0e69ce.png)

When run API locally, it works fine.
(Node v12.20.1, Function Runtime Version: 3.0.15193.0)
![Screenshot from 2021-02-03 15-33-47](https://user-images.githubusercontent.com/38238305/106707925-6a70a880-6635-11eb-96be-60c1f81da654.png)

**Comment by anthonychu** [comment]
@miwebst @annaji-msft Tested this on a deployed function app and it's working as expected. The problem appears to be when running in Static Web Apps.

**Comment by komayama** [comment]
@anthonychu I encountered same issue. Do you have a workaround in Static Web Apps Functions. I tried the following the code that set header multiple `Set-Cookie` but It doesn't work.

```
    context.res = {
        // status: 200, /* Defaults to 200 */
        body: responseMessage,
        headers: {"Set-Cookie" : "name=value2", "Set-Cookie " : "name3=value5"}
    };
```

Error
```
Microsoft.AspNetCore.Server.Kestrel.Core: Invalid non-ASCII or control character in header: 0x0020.
```

**Comment by hynjnk** [comment]
Thanks for the fix. It works well now.
![Screenshot from 2021-04-26 08-59-56](https://user-images.githubusercontent.com/38238305/116014293-979a8900-a66f-11eb-9c64-69c1f5f21d21.png)
