### ISSUE TITLE
Custom Routes Interfere with API Route Prefix

### ISSUE THREAD

**Issue by ghost** [Azure/static-web-apps#280]
Hey there,

I have a Static Web App running a React frontend and a C# backend.

I have several HTTP endpoints on the backend with custom routes. I've included an example below. When running them on my local machine, they are available at `api/<customRoute>`. However, when I open a pull request on GitHub, all of my API calls fail. After some experimentation, I've found that they're all available in the development branch preview under their un-prefixed custom route. So, for example, what should be `api/<customRoute>` is available instead at `<customRoute>`. I haven't fooled around at all with the Route Prefix settings (as the documentation says this is not supported), so I'm not sure what's causing the `api` prefix to be removed. 

```csharp
public static class GetPropertyIds
    {
        [FunctionName("GetPropertyIds")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "amenities/getPropertyIds")] HttpRequest req,
            ILogger log)
        {
            var db = await AmenityDbFactory.GetAmenityDb();
            IList<(int Id, string Name)> result;
            try
            {
                result = await db.GetPropertyIds();
            }
            catch (System.Exception)
            {
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
            var json = result.Select(p => new JObject(new JProperty("id", p.Id), new JProperty("name", p.Name)));
            return new OkObjectResult(json);
        }
    }
```

I appreciate any guidance you can give on this!

**Comment by anthonychu** [comment]
@ghost Is it possible to provide a version of this app that reproduces the issue? You mentioned pull requests, does this app work in the production site?

**Comment by anthonychu** [comment]
Closing this but please reopen if this is still an issue and you can provide more details.
