### ISSUE TITLE
Conditional access to a static web app

### ISSUE THREAD

**Issue by MichaelRoger** [Azure/static-web-apps#281]
Hi,
we are using static web apps in a employee enterprise scenario. This is why we don't want the page to be accessible from public. we already have configured the conditional access for the authentication, but we don't want the static ressources to be accessable either.
i tried to use the routes configuration and use the authentication mechanism, but the first time a user logs in via the static web app identity provider it redirects to a consent grant page. This page is neithter configurable (language or content) or deactivatable.

so the best way would be to use the conditional access (in our case on a defined ip range) to secure the static web app.

any ideas?
thanks,
Michael

**Comment by anthonychu** [comment]
@MichaelRoger Would [Private Link](https://docs.microsoft.com/en-us/azure/private-link/private-link-overview) or locking down access to only users in your Azure Active Directory work for you?

/cc @mkarmark @miwebst

**Comment by MichaelRoger** [comment]
hi, just reviewed "private links" and if i got it right, the public url of the static web app would still be available from the internet... so it will not make it for me :-(

**Comment by stemixreal** [comment]
You can do what you want in a azure storage gen V2 static website, you just have to do more of the plumbing by hand. Creating the cdn, adding your custom domain, etc. But you can make it private, use CI/CD (I used devops pipelines not github actions) and you can use functions.

**Comment by MichaelRoger** [comment]
hi, i don't use a "azure storage", i use https://azure.microsoft.com/en-us/services/app-service/static/ and i did not found any possiblity to secure the access by ip-range . We just added a custom domain to that static web app. But it is still reachable from it's generated url.

**Comment by stemixreal** [comment]
Hi, yes I realise you're using static web apps, ATS static websites are just an alternative as you have no way to achieve what you want at present. The services are very similar, I moved a storage hosted static website to a static web app with little effort. If you want to make your static website private you have an almost equivalent service just not managed in the same way - like the difference between running a web app in App Service or building your own VM to host one.

You may not have the option but I mention it in case the info is useful.

**Comment by anthonychu** [comment]
\+ @miwebst to chime in about whether Private Link can help here.

**Comment by MichaelRoger** [comment]
hi, just tried to use "Private link", but do not see the "static Web app"-Ressource:
![image](https://user-images.githubusercontent.com/47661151/108223137-c6f5bc80-7139-11eb-9b9d-56e888e43651.png)
![image](https://user-images.githubusercontent.com/47661151/108223157-ceb56100-7139-11eb-9a8f-0b597be52d50.png)
![image](https://user-images.githubusercontent.com/47661151/108223192-d8d75f80-7139-11eb-90e5-9b73e2fb3e6e.png)

**Comment by anthonychu** [comment]
@MichaelRoger sorry I wasn’t clear about this, but we’re still working on the feature and are looking for feedback if it would solve this problem for you when it is available.

**Comment by MichaelRoger** [comment]
if i could make a whish: there should be an option to enable access from specific ip-ranges.

**Comment by itpropro** [comment]
You have to distinguish between the two main ways of PaaS service network access control in Azure:
1. Public endpoints
- Firewall to control access from outside
- VNET Service Endpoints for Azure services in VNETs to resolve the public endpoint (no private IP address, just resolving of the public endpoint inside of the VNET)
2. Private endpoints 
- Provisioning of an additional private IP address resource
- Public access can be completely disabled (depending on the implementation)
- Additional private DNS zone is deployed to resolve the internal IP address

In both scenarios, the public DNS entry would still be resolvable, but depending on the config actual access would be blocked.

In my opinion, private endpoints don't make sense for Static Web Apps and are more of an Enterprise feature for strict environments with high security requirements (not the target group for SWA).
I think a firewall at the public endpoint like with Azure SQL or the other PaaS DBs would be fine.

**Comment by MichaelRoger** [comment]
thanks @itpropro , but it seems, that the azure static web apps https://portal.azure.com/#create/Microsoft.StaticApp
are not able to some kind of access security based on ip.

and we are in an enterprise environment and the endusers of the SWA are our employees.

i think we just need an option to secure the access on static content. because there is already a function to use authentication (which provides a non customizable "grant site"). But in our scenario, we just want to secure the static content from public access.

**Comment by itpropro** [comment]
As I understood @anthonychu, we were just discussing options to be implemented in the future. None of these are available today as of my knowledge.
Today, authentication can only be done with routes.json, where you can deny access to all paths. The grant site itself cannot be customized, as it's using the default OIDC flow provided by the authentication provider. When you authenticate to other apps on the internet you will also get the exact same grant site from Twitter, GitHub, etc..
We will have to wait until there is some other way to authenticate to SWA or to integrate our own authentication.

**Comment by MichaelRoger** [comment]
any news about this?

**Comment by miwebst** [comment]
Hey @MichaelRoger , as Anthony mentioned above, we are working on supporting private endpoints which should fit your enterprise need. We are also in discussions on creating an ip address feature to restrict access to a list of CIDR blocks. Private endpoint support should come in the next few months. We don't have an ETA on the allowedIPs feature.

**Comment by simonaco** [comment]
@MichaelRoger a quick update on this thread, you can now restrict access to your application from specific ip ranges, see steps on how to configure this on the [Networking](https://docs.microsoft.com/azure/static-web-apps/configuration#networking) page. Thank you for raising this!
