### ISSUE TITLE
Deployment to existing static app failed updating node.js version.

### ISSUE THREAD

**Issue by stemixreal** [Azure/static-web-apps#283]
Hi Folks, 

I have a static web app and have recently added additional functions to /api to enable me to use cosmos db. After adding and testing the functionality locally I deployed the changes.

The deployment failed with the following Oryx errors

Detecting platforms...
Detected following platforms:
  nodejs: 14.15.1
Version '14.15.1' of platform 'nodejs' is not installed. Generating script to install it...

**Error:** Could not find either 'build' or 'build:azure' node under 'scripts' in package.json. Could not find value for custom run build command using the environment variable key 'RUN_BUILD_COMMAND'.Could not find tools for building monorepos, no 'lerna.json' or 'lage.config.js' files found.

---End of Oryx build logs

Oryx could not find a 'build' or 'build:azure' script in the package configuration. Please add one of these commands to your package configuration file (i.e. package.json). Alternatively, you can add the app_build_command to the build/deploy configuration section of your workflow file. For example, app_build_command: 'npm run docs:build'

...

![image](https://user-images.githubusercontent.com/57687696/107865504-19478c80-6e5f-11eb-8b36-39c2542b69ca.png)

-----------------------------

I've had a look around and found:

https://github.com/microsoft/Oryx/issues/891

but as everything has worked without issue in deployment so far I haven't really looked into Oryx/Actions in any great detail so I don't know if the fix is something I can use for static web apps. Where would I apply the suggested workaround if it is possible? I can't see anything in the workflow yaml that gives me any clues. The solution is for an app service hosted function.

https://github.com/microsoft/Oryx/issues/891#issuecomment-756147542

Any pointers greatly appreciated. Cheers
Steve

**Comment by monksudo** [comment]
Same issue for me as well.

**Comment by stemixreal** [comment]
I'm finding my way with this but adding

_- uses: actions/setup-node@v2
        with: 
       node-version: 14_

produces

_Run actions/setup-node@v2
  with:
    node-version: 14
    always-auth: false
    check-latest: false
    token: ***
**Found in cache @ /opt/hostedtoolcache/node/14.15.4/x64**_

Adding

_- run: npm install
- run: npm test_

fails with the error that package.json doesn't exist in the root of the app as indicated in a roundabout way in the original second error.

I've installed the node modules in /api and package.json was created there automatically. Do I need a copy in the root too/in place of? I've have tried that but no luck. Same error. So I'm missing something obviously.

**Comment by stemixreal** [comment]
Ok I think I've sorted this out. At least, everything builds though there were a couple of errors during the build they don't break the build - missing descriptions and the like.

@monksudo, there were superfluous package files in my root (an oversight on my part). Once I deleted those the app deploys ok. I deleted both _package.json_ & _package-lock.json_ which caused the build process to try to install node in the root which is unwanted and impossible anyway it seems.

**Comment by anthonychu** [comment]
@stemixreal If you can share a repo that reproduces the original problem, happy to take a look to see if there's anything we can do to make this experience better.

**Comment by stemixreal** [comment]
Hi Anthony, thanks. The error was mine. I mistakenly installed all the node packages in the web root initially and neglected to deleted the node_modules folder from there. I didn't notice it among other files and folders to be honest. So even though I then installed things correctly, the build was trying to install node in the SWA root.

The repo is private but happy to send an  invite. It's just a static web app with some signalr hub and cosmos db tests for a game I'm working on.

I guess I must have broken something when fiddling about though. I'm getting internal server errors from the function that was working. No worries though. It's no problem to take a couple of steps back.

**Comment by appasaheb4** [comment]
<img width="1372" alt="Screenshot 2021-05-04 at 8 40 49 AM" src="https://user-images.githubusercontent.com/24726539/116957286-23866380-acb5-11eb-86e5-77c2ea20aa64.png">
same issue facing

**Comment by jrathgeber** [comment]
Same error. Deleting  package-lock.json fixed it. Thank you !

**Comment by wan-liyang** [comment]
I get same issue, my case is because in `package.json` don't have command `build`, only have other `build:env` command, then `AzureStaticWebApp` pipeline task cannot find `build` command, then give error, below is solution I observed.

option1: add `skip_app_build: true` if already build in previous step, but since not build by `task: AzureStaticWebApp@0` the folder location may different

```
- task: AzureStaticWebApp@0
  inputs:
    skip_app_build: true
```

option2: use `app_build_command: '$(build_command)'` to customize command, for example variable `build_command` map to command `npm run build:uat`

```
    - task: AzureStaticWebApp@0
      inputs:
        app_build_command: '$(build_command)'
```
