### ISSUE TITLE
Function proxies support

### ISSUE THREAD

**Issue by danspark** [Azure/static-web-apps#284]
Are there any plans to add support for [Azure Functions Proxies](https://docs.microsoft.com/en-us/azure/azure-functions/functions-proxies)? Since the API only supports HTTP triggers I think it makes sense to allow proxies

**Comment by anthonychu** [comment]
Functions proxies should work within the function app. If it's not working, can you share your app or one that reproduces the issue?

**Comment by danspark** [comment]
@anthonychu Sorry for taking so long to answer. It's embarrassing, but it actually was an issue with my configuration settings. I'm closing this, thank you for answering so fast!
