### ISSUE TITLE
Incorrect platform detected during build step

### ISSUE THREAD

**Issue by Aegman** [Azure/static-web-apps#285]
I'm having an issue deploying to a static web app, where the build process is incorrectly detecting a Hugo platform. Really all we need to do is copy the content of the GitHub repo to the service

```
Detecting platforms...
Detected following platforms:
  hugo: 0.76.3


Source directory     : /github/workspace
Destination directory: /bin/staticsites/ss-oryx/app


Using Hugo version:
Hugo Static Site Generator v0.76.3-E9623459/extended linux/amd64 BuildDate: 2020-10-08T17:17:16Z

Error: module "themes/default/" not found; either add it as a Hugo Module or store it in "/github/workspace/themes".: module does not exist
Total in 3 ms
```

The site we are trying to deploy is a pre-built static pages app with some javascript and a few JSON files, I suspect the name of one of these files is what is causing the issue?

I've tried modifying the action with `api_build_command` and `app_build_command` set to `echo skipping build` but it continues the build anyway.
```
with:
azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_SKY_0AD835903 }}
repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
action: "upload"
app_build_command: "echo skipping build"
api_build_command: "echo skipping build"
###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
app_location: "/" # App source code path
api_location: "" # Api source code path - optional
output_location: "" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

**Comment by anthonychu** [comment]
@miwebst do you know how to skip Oryx build if setting the build commands aren’t working?

https://github.com/Azure/static-web-apps/issues/248

**Comment by Aegman** [comment]
As a quick work around, I've moved my web-app into a subfolder, and placed an index.html in the root folder that redirects to my app in the subfolder. This will deploy correctly without trying to build the non-existent Hugo app.

Would be nice to resolve this issue though.

**Comment by qianz2** [comment]
Hi @Aegman , Oryx identifies hugo app by detecting if there has a config.toml/config.yml/config.json/config.yaml file at the root or a config/**/*.toml file inside config subfolder. So I  think you included such files in your app previously. You could use DISABLE_HUGO_BUILD to avoid any hugo platform detection and builds.

**Comment by Reshmi-Sriram** [comment]
Closing due to no traction. Feel free to reopen if required!
