### ISSUE TITLE
Enable configuration on function apps with no functions

### ISSUE THREAD

**Issue by danspark** [Azure/static-web-apps#289]
Currently it is not possible to create configuration settings on the portal when there are no functions in the function app. This makes me unable to use only function proxies as I can't create settings.

A workaround to this issue is creating a dummy function that'll never be called.

This is the message that I receive when there are no functions:
![no functions on bff](https://user-images.githubusercontent.com/23037278/108418444-0c84b900-7210-11eb-887d-845785136494.png)

**Comment by anthonychu** [comment]
Related: #255

**Comment by miwebst** [comment]
This is fixed.
