### ISSUE TITLE
Logs/Monitoring for Azure Functions

### ISSUE THREAD

**Issue by amykapernick** [Azure/static-web-apps#29]
Would be great to see some kind of monitoring or logs for the Azure Functions. I'm unable to see anything about what's happening on there, just that I have functions

**Comment by anganti** [comment]
Thank you for trying out the service.

AppInsights is supported https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#appinsights_instrumentationkey

Note: This must give you enough to identity logs/metrics. But there is still some work on our end to improve observability overall.

**Comment by aaronpowell** [comment]
@anganti with that will we be able to get the request metrics as well, or only where we do telemetry within the Function? For me, I'd like to be able to click on the Function name and get the minimal monitoring like I can do when deployed to a Function App.

**Comment by anganti** [comment]
@aaronpowell sounds like a valid ask that we could add to our backlog as we invest more into logs/metrics @dariagrigoriu

**Comment by anthonychu** [comment]
Can we add App Insights by default but turn on the daily cap so that it is free to use?

**Comment by anganti** [comment]
@anthonychu we had managed AppInsights but took it away for the preview release. Need more deeper understanding on the scale/limits of AppInsights per subscription and billing for it, if MICROSOFT manages the resource onbehalf. Happy to have that conversation again.

**Comment by oadrian2** [comment]
Would it be possible to get some sort of documentation on how to attach App Insights. For those of us coming from the existing Azure Functions panel, logging was basically automatic. How do we do that here?

**Comment by aaronpowell** [comment]
Not official docs @oadrian2, but I blogged about it - https://www.aaron-powell.com/posts/2020-08-12-getting-logs-from-static-web-apps-apis/

**Comment by burkeholland** [comment]
Looks like @craigshoemaker is working on the official doc for this. Looking at an end of February time frame right now.
