### ISSUE TITLE
Support for HTTP/2 protocol

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [Azure/static-web-apps#292]
Hello! Does Static Web App support HTTP/2 protocol? I'm experiencing delay when visiting my web page hosted on Azure Static Web App, where one of the main issues is that requests are being stalled because the requests are on HTTP/1.1 protocol which doesn't support multiplexing. I've attached an image below for reference:

![image](https://user-images.githubusercontent.com/19281514/108583942-4375de80-7378-11eb-916e-958b590acf64.PNG)

Apologies if my question isn't clear or if this isn't the right place for this question; I've been reading up and am still quite newb in my understanding of web technologies. Thank you!

**Comment by anthonychu** [comment]
@Zhiyuan-Amos Is it possible to share your site's URL? If you want to share it privately, please send it to antchu@microsoft.com.

I'm seeing http/2 in my Blazor app:

![image](https://user-images.githubusercontent.com/3982077/108589483-4d192b00-7313-11eb-9ef6-54ba7faccb0c.png)

**Comment by Zhiyuan-Amos** [comment]
Hi @anthonychu , thanks for your prompt reply! Your response made me wonder whether there's something wrong with my device, so I verified by loading my webpage on another device and turns out it works fine; it's running http/2 protocol.

After some investigation, turns out my [antivirus software](https://community.bitdefender.com/en/discussion/81392/browser-http-1-1-instead-of-http-2-online-global-protection) is causing the problem. Deleted Bitdefender on my original device, and it's running on http/2 protocol as well.

Thanks for your time & help @anthonychu!
