### ISSUE TITLE
[Question] Staging environment domain as env var

### ISSUE THREAD

**Issue by svict4** [Azure/static-web-apps#293]
Is it possible to get the stanging domain name as an environmental variable so that I can use it during build time?
e.g. `https://something-else-18b0d761e-5.westus2.azurestaticapps.net/` or `something-else-18b0d761e-5`

**Comment by svict4** [comment]
Ah I'm trying to solve what is pointed out in https://github.com/Azure/static-web-apps/issues/22#issuecomment-743321541
> Dynamic deployment slots and URLs only work if your app either doesn't have authentication, or if you use the built in authentication.

**Comment by svict4** [comment]
Adding the following to the github action, then manually appending the domain during build should work:
```
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
```

**Comment by a2441918** [comment]
This is what I am doing. Anyway to manualy get the "something-else-18b0d761e" value?
