### ISSUE TITLE
Oryx looks here - /home/site/wwwroot/register instead of here /api for "requires(..)"

### ISSUE THREAD

**Issue by stemixreal** [Azure/static-web-apps#294]
Hi, I hope everyone is having a good day

I have a static web app with a function working locally. It use the Playfab Node SDK to register players with PlayFab and modifies some settings. When deployed the function fails with the error below. 

Application Insights logs show me that there's an

> Exception while executing function: Functions.register Result: Failure
Exception: Worker was unable to load function register: 'Error: Cannot find module 'PlayFab-Sdk'
Require stack:
> /home/site/wwwroot/register/index.js
> ....

I know it's something I've missed. The node package was installed in /api using _npm i playfab-sdk_.  As I say it works perfectly when running locally, some screenshots..

![image](https://user-images.githubusercontent.com/57687696/108695460-3aac1680-74f8-11eb-920c-d3b4ee5adecb.png)

and the playstream

![image](https://user-images.githubusercontent.com/57687696/108697562-eeaea100-74fa-11eb-84df-9db6b8b720d4.png)

The package-lock.json has just the one entry

> {
  "name": "api",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "playfab-sdk": {
      "version": "2.64.210208",
      "resolved": "https://registry.npmjs.org/playfab-sdk/-/playfab-sdk-2.64.210208.tgz",
      "integrity": "sha512-RBJz4HxclyC8rVw26n9GlxSCOSQDLYxQyuihZTGCxyWpAPpImtOWAE9n/xNiESp574YnQahEKTO4/YRztFTG1Q=="
    }
  }
}<

and package.json

>{
  "name": "api",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "func start",
    "test": "echo \"No tests yet...\""
  },
  "dependencies": {
    "playfab-sdk": "^2.64.210208"
  },
  "devDependencies": {}
}<

I haven't changed any of the default setting such as api/app location. Everything seems to build ok except the first pass stats Oryx can't determine the language 

>Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.<

Node is detected ok

>Detecting platforms...
Detected following platforms:
  nodejs: 14.15.1
Version '14.15.1' of platform 'nodejs' is not installed. Generating script to install it...<

This path is wrong >/home/site/wwwroot/register/index.js<  but I don't know how to fix it.

ps. Some additional info. 

The folder /home/site/wwwroot exists nowhere in my project, no variables contain it either so it's a default from the Oryx build process.

Any guidance is greatly appreciated.

Cheers
Steve

**Comment by stemixreal** [comment]
Apologies for all the title changes. I'm new to github and didn't realise they showed up in the thread for everyone to see.

reading [https://github.com/Azure/static-web-apps/issues/17#issuecomment-632406729](url)

Is that my issue, the node libraries I'm trying to use don't exist in the Oryx mage and I should figure out how to add the required modules in the build process?

thanks
Steve

**Comment by anthonychu** [comment]
Sorry it took a while to respond. I had to read this a few times to understand what's happening.

I think the problem is your require statement in `register/index.js`. Your function app is deployed to Linux, which has a case sensitive file system. The package has all lowercase characters `playfab-sdk`. From the error, it looks like your require statement uses mixed case (`PlayFab-Sdk`), which might work in Windows or macOS because their file systems are case-insensitive, but will fail in Linux. Change your require statement to `require('playfab-sdk')` and try again.

As for `/home/site/wwwroot`, this is the root folder that your app runs in when it's deployed. This is normal.

**Comment by stemixreal** [comment]
Hi Anthony, 

Thank you so much!

3 days! lol. 3 days I've been scratching my head and that was it. I was looking at the require statement in the early hours this morning, I almost changed it to lower case but didn't. I think by the time I considered that I'd convinced myself it couldn't be the problem.

Thanks again Anthony, can't say how helpful you've been, saved the day so to speak. Apologies if my post was unclear.

**Comment by anthonychu** [comment]
No worries. Happy to help! And nothing wrong with your issue. You included lots of details which is great! It just took a while to find the right clues. 🕵️‍♂️
