### ISSUE TITLE
Support for .NET 6.0 Preview 1 for Client 

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [Azure/static-web-apps#295]
Hello! I tried upgrading my Blazor WASM Client to .NET 6.0 Preview 1, and GitHub actions failed with the following error message:

> Error: Platform 'dotnet' version '6.0' is unsupported.

When will .NET 6.0 Preview 1 be supported for Client? I read about some [performance gains](https://www.reddit.com/r/Blazor/comments/lmnlt7/blazor_webassembly_performance_in_net_6_preview_1/) and would love to try it out.

Thank you!

**Comment by qianz2** [comment]
Thanks @Zhiyuan-Amos for reporting this, we've added it into Oryx backlog. Will work on supporting it.

**Comment by qianz2** [comment]
Hi @Zhiyuan-Amos , we've been working on this, it will be available on our next release. So please wait until then to try it out.

**Comment by Zhiyuan-Amos** [comment]
@qianz2 I noticed new releases on the oryx branch. Any idea when will they be available over here? :)

**Comment by qianz2** [comment]
Yes, we had a new release, pinging @anthonychu here for questions of the schedule.

**Comment by anthonychu** [comment]
@qianz2 Can you please start an internal thread with @miwebst, if you haven't already, with the new version that we should be upgrading to? Thanks.

**Comment by Zhiyuan-Amos** [comment]
Hello @qianz2 , any updates? Thanks! 😃

**Comment by anthonychu** [comment]
We should have an update to the GitHub Action coming out next week that should include this.

**Comment by anthonychu** [comment]
This should be working now. Please give it a try and reopen this issue if you run into any issues.
