### ISSUE TITLE
How to resolve 404 issue in Azure Static Web App in Angular?

### ISSUE THREAD

**Issue by imvikaskohli** [Azure/static-web-apps#296]
I m able to deploy Angular build with Github, now every time when I push to the specific branch it builds and uploads to the server by CI/CD

Let's assume there is a URL vikasazurestaticapps.net/auth/login, and when I try to refresh that URL, it shows a 404 error page.
![image](https://user-images.githubusercontent.com/23357854/108710603-4ae4e580-753a-11eb-8a30-6fa2b6a1dd3f.png)

When I navigating from one page to another page without refreshing on entering a manual URL it works fine.

So in IIS Server, I usually add a web.config file there which handles that.
Similarly, in Nginx default configuration files, we do change in the file then it works

But what I do in that azure static website so refresh or manual enter URL won't throw 404 error page?

**Comment by anthonychu** [comment]
Yes please take a look at fallback routes. https://docs.microsoft.com/en-us/azure/static-web-apps/routes#fallback-routes

**Comment by imvikaskohli** [comment]
Thanks @anthonychu 

I have added the routes.json file in the src folder with the following code as described in the Microsoft Azure Static Web App documentation:-

routes.json file
{
  "routes": [
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ]
}


Then in the Angular.json after Angular version 6, for less than or equal to 5 than in angular-cli.json file you need to add

in the build command 

"assets": [
                            "src/favicon.ico",
                            "src/assets",
                            "src/routes.json" //here add routes.json
                        ],

**Comment by zakariAlfadhli** [comment]
and react js
----------------
add
routes.json file in file  public
{
"routes": [
{
"route": "/*",
"serve": "/index.html",
"statusCode": 200
}
]
}

**Comment by manekinekko** [comment]
@imvikaskohli @zakariAlfadhli  please note that the current recommended way of dealing with SPA is to use the `staticwebapp.config.json` file with the following content:


```
{
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["/*.{     ADD_FILE_EXTENSIONS_HERE    }"]
  }
}
```

See an example for Angular: https://github.com/manekinekko/azure-static-web-apps-playground/blob/main/src/assets/staticwebapp.config.json

**Comment by axell9641** [comment]
> @imvikaskohli @zakariAlfadhli please note that the current recommended way of dealing with SPA is to use the `staticwebapp.config.json` file with the following content:
> 
> ```
> {
>   "navigationFallback": {
>     "rewrite": "index.html",
>     "exclude": ["/*.{     ADD_FILE_EXTENSIONS_HERE    }"]
>   }
> }
> ```
> 
> See an example for Angular: https://github.com/manekinekko/azure-static-web-apps-playground/blob/main/src/assets/staticwebapp.config.json

Updated link : https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#fallback-routes

**Comment by DevCreator0705** [comment]
Hello, everybody.
In react-app, what should I prevent 404 error when I refresh the current page?

**Comment by j33mk** [comment]
I am working in angular 17 and have fixed this issue by following these steps

1. Create a file **staticwebapp.config.json** inside assets folder of angular project. _**Make sure it is inside assets folder**_ 
2. After that inside this file write this

`{
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["/*.{ico,js,map,css}"]
  }
}`

3. Save it and re-deploy the app. The error will be not come up again
4. If you want to manually re-write the routes, refer to this file in the playground [staticwebapp.config.test.json](https://github.com/manekinekko/azure-static-web-apps-playground/blob/main/src/assets/staticwebapp.config.test.json), this will help you setup routes manually

Thanks to @manekinekko for pointing us out in correct direction

**Comment by dabuk58** [comment]
> 1. Create a file **staticwebapp.config.json** inside assets folder of angular project. _**Make sure it is inside assets folder**_



Worked like a charm, thank you

**Comment by danvod** [comment]
@j33mk ,For some reason, I still have this issue. Navigating to the app is fine and all the routes work, but if I reload the page, I get a bunch of 

chunk-54LC4K26.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

I tried many variants of copying the file, placing it in other folders, and I can confirm that staticwebapp.config.json is in the output directory, but still, it's as if it's not there. Any ideas what to try next?

**Comment by rezshek** [comment]
> hi , guys,it should be noted, this file staticwebapp.config.json should be in the public folder for react application, NOT in the root directory, it takes me so long time to check, so dumb!!!! ![Screen Shot 2024-05-07 at 10 42 41 PM](https://github.com/Azure/static-web-apps/assets/86191390/9fda3043-4945-451a-82a5-7ebd05233ef2)

Man, you saved me soooooooooooooooooo much, I was dead in water and I was trying anything! this simply fixed the F**** issue! :-)
Thanks.
