### ISSUE TITLE
Support deployment from other CI/CD services, such as GitLab, BitBucket, Jenkins, CircleCI

### ISSUE THREAD

**Issue by softchris** [Azure/static-web-apps#298]
- zip up the artifacts
-  make artifact available at a URL, storage account?
- zip deploy

**Comment by anthonychu** [comment]
Chatted with @softchris offline. Deployment from CLI is tracked at #7. But the original request about deployment from other CI/CD providers such as GitLab, Jenkins, BitBucket, etc. Updating this issue's title to reflect this.

Options to support this include:
* Support deployment from CLI #7 
* Create a general purpose docker container that can be run anywhere to deploy a Static Web App (and build too?)

**Comment by msdmcmurrian** [comment]
Can we also add a flag in the git action and Azure Dev task to only do the upload?  This will allow someone to separate the build and deploy process of their application.

**Comment by miwebst** [comment]
That has been added for the app build. We still need to document it but you can add `skip_app_build: true` to your GH action config and then it will just do upload.

**Comment by nbkhope** [comment]
Hello, is support for other ways of deploying the app planned? Are there any workarounds for the time being, such as uploading the files manually?

**Comment by danielmackay** [comment]
We are also waiting on a solution that allows us to deploy to SWA from Bit Bucket.  Right now the only option we have is to use `mcr.microsoft.com/appsvc/staticappsclient:stable` which is not supported or recommended.

**Comment by anthonychu** [comment]
@danielmackay If we were to document and support the use of that docker image, would it work for you?

**Comment by danielmackay** [comment]
@anthonychu - yes that would work for us.  We are already using it, but I see you've said this is not recommended and not supported.  Would be great to get a bit more documentation and official support for this docker image.

Thanks for the response!

**Comment by anthonychu** [comment]
Not currently supported but we are looking into getting the image to a state where we can document and support its use outside of the GitHub action.

**Comment by matkoch** [comment]
@danielmackay can you share a few bits maybe?

**Comment by Reshmi-Sriram** [comment]
Hey all,
A couple of updates here. We have recently published official documentation on how to deploy using [Bitbucket](https://docs.microsoft.com/en-us/azure/static-web-apps/bitbucket?tabs=vanilla-javascript) and [Gitlab](https://docs.microsoft.com/en-us/azure/static-web-apps/gitlab?tabs=vanilla-javascript) as the CI/CD agents.

On supporting deployment via other non-CI/CD modes, we are currently working towards a solution for the same and should be seeing updates on this in another couple of months :)

Hope this helps!!

**Comment by smeraner** [comment]
I am using the gitlab image for deployments from my local machine as temporary solution.

podman run --volume "$(pwd)":/root/app \
  --volume "$(pwd)"/api:/root/api \
  --env API_TOKEN=$DEPLOYMENT_TOKEN \
  --env APP_PATH=/root/app \
  --env API_PATH=/root/api \
  --env OUTPUT_PATH=/root/app/dist \
  registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy

**Comment by ofcoursedude** [comment]
I would actually like to vote for a non-oryx-based build/deploy support. While it sounds cool to have universal build system, oryx 1) is a huge image, 2) runs on x64 only, 3) requires a container and 4) is pretty slow compared to other methods, making it expensive to run on cloud agents and tricky to work with on self-hosted agents. Just my $.02.

**Comment by Reshmi-Sriram** [comment]
Hi @ofcoursedude ,

Thank you for your views! Like mentioned earlier, we are currently working on a non-CI/CD support to be able to deploy directly from your local environment. 

Stay tuned! :)

**Comment by adriancuadrado** [comment]
Would it be possible to add an option to deploy using local git and use FTP, etc. just like in Azure App Service?

**Comment by smeraner** [comment]
> Would it be possible to add an option to deploy using local git and use FTP, etc. just like in Azure App Service?

The current available option works with any repository but requires docker runtime and it's slow. Looking forward to the release of the deployment tool, that is currently part of the image.

**Comment by anthonychu** [comment]
@ofcoursedude Regarding your comment about x64, what OS/arch are you looking for?

**Comment by smeraner** [comment]
This version is faster as workaround, it uses a different image and loads dependencies only once:

# spin up container for deployment once
podman run -t -i \
  --volume "$(pwd)":/root/app \
  --volume "$(pwd)"/api:/root/api \
  --env API_TOKEN=$DEPLOYMENT_TOKEN \
  mcr.microsoft.com/appsvc/staticappsclient:stable \
  /bin/bash

# run for every deployment with Oryx build
/bin/staticsites/StaticSitesClient update --deploymentaction upload --app /root/app --api /root/api --appArtifactLocation /root/app/dist --apiToken $API_TOKEN

**Comment by Reshmi-Sriram** [comment]
Hi all,
We have now officially announced the GA of [Static Web Apps CLI](https://aka.ms/swa-cli-ga)🎉🎉
This is a power-packed tool which now enables features such as login, deploy from local, automatic framework detection **and much more - all from your local development system!**
Do have a look and let us know how you like it :) (_P.S. It is Open Source, so feel free to contribute to the next set of features you'd like to see_!) 🌟

**Comment by ofcoursedude** [comment]
> @ofcoursedude Regarding your comment about x64, what OS/arch are you looking for?

linux/arm64 such as Raspberry Pi or AWS Ami arm-based VMs

**Comment by Reshmi-Sriram** [comment]
Closing this issue, feel free to re-open!

**Comment by jpalo** [comment]
Also looking for "linux/arm64 such as Raspberry Pi or AWS Ami arm-based VMs" in order to run GitHub actions on local RasPi runner.

**Comment by tatsuyaHello** [comment]
Hi @anthonychu
Do you have any update about using frp?
I understood that we can not use ftp and kudu deploy.
