### ISSUE TITLE
adding a staticwebapp.config.json results in a failed build

### ISSUE THREAD

**Issue by sfabriece** [Azure/static-web-apps#299]
The following `staticwebapp.config.json` results in an error when uploading artificts:

```json
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/*.{png,webp,eot,svg,ttf,woff,woff2,ico}", "/main.css"]
  }
}
```

**Comment by mkarmark** [comment]
Hi, I'd be curious to see the exact error with which this navigationFallback section errored. Would you mind linking your github repo if public or sharing the github action logs here?

**Comment by sfabriece** [comment]
![image](https://user-images.githubusercontent.com/3108592/108926114-12c6cb00-763e-11eb-8a24-417aa28a0074.png)

@mkarmark

**Comment by sfabriece** [comment]
Full logs [here](https://pipelines.actions.githubusercontent.com/xpwniGrBDUHJ39tZyg6b2EpnMeW5TTXxH1nF7pAJYDQEyKY9Bg/_apis/pipelines/1/runs/453/signedlogcontent/4?urlExpires=2021-02-24T00%3A18%3A56.6091399Z&urlSigningMethod=HMACV1&urlSignature=eNd%2FZJx74amQNhA0tvHXGajAT%2BeI44txxO5j7PR8eZA%3D) @mkarmark

**Comment by mkarmark** [comment]
I'm not able to access that link nor am I able to repro this issue myself. I'll need to take a look at the full logs and the full staticwebapp.config.json to be able to proceed further in this investigation.

**Comment by sfabriece** [comment]
[logs_453.zip](https://github.com/Azure/static-web-apps/files/6032746/logs_453.zip)
Does that help? @mkarmark .

In the config I only had:
```json
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/*.{png,webp,eot,svg,ttf,woff,woff2,ico}", "/main.css"]
  }
}
```

**Comment by mkarmark** [comment]
Where in the directory is the staticwebapp.config.json file located, so we can try to repro as closely as possible?

**Comment by sfabriece** [comment]
The build output is in dist/release and that's where the config is.

**Comment by miwebst** [comment]
Hey @sfabriece we think we know what's going on. We should have a fix for this in the next couple of days. In the meantime, our assumption is that the staticwebapp.config.json file has been placed in your 'assets' folder and thus is copied to the output. This is not required for this new config file (one of the changes from routes.json). As long as the staticwebapp.config.json file is in the app_location folder, we will find it and include it in the upload. You should be unblocked if you remove it from 'assets' or remove the mechanism that is copying it to dist/release.

**Comment by sfabriece** [comment]
Thanks for the support @miwebst @mkarmark  😄

**Comment by miwebst** [comment]
Hey @sfabriece, our fix for this should be out. Do you mind checking if your project is still hitting this error?

**Comment by sfabriece** [comment]
Hi @miwebst , I'll try to get to it in the weekend.

**Comment by mmisztal1980** [comment]
@miwebst for clarity's sake: does the folder have to be named `app_location` ?

**Comment by miwebst** [comment]
Hi @mmisztal1980, I think you may have this confused with the static site offering from Azure Storage. There is no such blob container in static web apps, these are different products with unfortunately similar naming.

**Comment by stemixreal** [comment]
Hi @miwebst , I did that. A few months ago I was working on a static website in blob storage and the .netconf had all this amazing stuff about SWA which I confused for blob sites so had a little trouble with routes.json until I realised my mistake. 

Just FYI as I've seen others confused by the similar names too. Might be something to highlight in the docs

**Comment by mmisztal1980** [comment]
that's quite possible...

**Comment by miwebst** [comment]
Closing this one as the initial issue should be fixed, as for the issue with the $web, seems like that is a separate service
