### ISSUE TITLE
Support Azure B2C as an Authentication Provider

### ISSUE THREAD

**Issue by jordanfinners** [Azure/static-web-apps#3]
For greater customisation of the auth process it would be great to support Azure B2C/customisation as a provider for authentication.
This would also enable more people to migrate over to this service.

**Comment by mkarmark** [comment]
Thank you for using Azure Static Web Apps!

For preview, using the five offered providers (Azure Active Directory, Facebook, GitHub, Google, and Twitter) is the only option for authentication/authorization.

Supporting Azure B2C/custom providers as an authentication providers is something we plan to offer in the future.

Thank you for your feedback. Keep them coming.

**Comment by TellonUK** [comment]
Is this in active development? Just wondering when B2C support will be added.

**Comment by deepbass** [comment]
This would be super useful for me. I'm currently handling this clientside with MSAL and deploying my function app seperately which is a bit of a faff and reduces the value of static web apps for this use case

**Comment by danijam** [comment]
@mkarmark is there any update on future plans to support something like Azure B2C or i guess more specifically the ability to define a OpenID Connect IDP as the authentication provider in a Azure Static Web App.

**Comment by GaryParr** [comment]
Update on this would be appreciated. I've been holding off on doing anything with SWA because B2C integration is a requirement.

**Comment by anthonychu** [comment]
Rough ETA is in about a month.

**Comment by GKanitz** [comment]
Hi @anthonychu just out of curiosity, are there any updates on the ETA?

**Comment by miwebst** [comment]
This is available now, you can try these docs: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad
