### ISSUE TITLE
Request for custom HTTP 404 page

### ISSUE THREAD

**Issue by wictorwilen** [Azure/static-web-apps#30]
I'd like to see an option to have a custom HTTP 404 page. Super simple implementation would be to publish a page to `/404.html` (how Hugo does it by default)

**Comment by miwebst** [comment]
Hi @wictorwilen,

This exists today: https://docs.microsoft.com/en-us/azure/static-web-apps/routes#custom-error-pages 

Take a look at the example routes.json file as it shows a custom 404

**Comment by wictorwilen** [comment]
Thanks!

**Comment by jpalo** [comment]
FYI, you need to use 
```
    "responseOverrides": {
        "404": {
          "rewrite": "/404.html"
        }
    }
```
as defined at https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#response-overrides

as 
```
  "platformErrorOverrides": [
    {
      "errorType": "NotFound",
      "serve": "/custom-404.html"
    }
  ]
```
does nothing for some reason.
