### ISSUE TITLE
Cannot override values in local.settings.json

### ISSUE THREAD

**Issue by wilberolive** [Azure/static-web-apps#300]
In Azure Functions I used to be able to override values in local.settings.json by doing something like this in Startup for example.

```
builder.ConfigurationBuilder
    .SetBasePath(context.ApplicationRootPath)
    .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
    .AddJsonFile("secret.settings.json", optional: true, reloadOnChange: true)
    .AddEnvironmentVariables()
    .Build();
```

The order in which the settings files are added to the configuration allows values in local.settings.json to be overridden with values in secret.settings.json for example. This is useful as it allows local.settings.json to hold all non-sensitive values as well as empty sensitive values as a template, which can then be uploaded to source control. Then secret.settings.json can just contain the sensitive values and only kept locally.

I just set up a new Azure Function project in Visual Studio to test with a new Static Web App, but noticed that this doesn't appear to work anymore. It seems like local.settings.json is hardcoded to be loaded by the runtime and cannot be overridden? Is that correct?

**Comment by anthonychu** [comment]
This is probably best asked here: https://github.com/Azure/azure-functions-core-tools/issues or here: https://github.com/Azure/azure-functions-host/issues

But local.settings.json is not a normal appsetting file. It's a specific format that is meant to be read by Azure Functions Core Tools. When running in locally in Core Tools, the values in the `Values` section will be made available in your function app as environment variables. See this doc here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v2%2Ccmd#environment-variables

local.settings.json is not meant to be deployed to production.

If you want to use config files like appsettings.json, see this doc: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources 

In general, when committing apps to source control and deploying them to the cloud, avoid storing secrets in config and use environment variables where possible.

**Comment by wilberolive** [comment]
Yep, understand. All my sensitive secret values are stored as environment variables in the Azure Static Web App portal. However, I need to store them locally as well for local testing.

My concern is that local.settings.json has a bunch of other stuff in it as well that would be a real pain to have to recreate from scratch if I somehow lost it as I only have it locally. You know, stuff for CORS and various other non-sensitive values that just allow everything to run properly. I know I can hunt all this down again in the docs, but it would just be painful.

So what I've done to get around the problem is create a file called local.settings.template.json. It is a copy of the local.settings.json file just with any sensitive secret values replaced with a string telling me where that value can be found in Azure (such as a Cosmos DB primary connection string for example). I then commit this file to github.

Now if something happens in the future, I can just pull the repo from github, rename that file back to local.settings.json and then follow my own instructions in each sensitive value to replace it with the actual secret value so that I can compile and run again locally with minimal fuss.

**Comment by anthonychu** [comment]
Yep totally agree with you here. Let me know if the solution proposed here would work for you: https://github.com/Azure/azure-functions-core-tools/issues/2070

**Comment by wilberolive** [comment]
Haha... Yes! It is funny I pretty much came up with the same solution as proposed there. I even coincidently named the file the same.

**Comment by Reshmi-Sriram** [comment]
Closing the issue, marking as resolved.
