### ISSUE TITLE
Is SWA the right choice?

### ISSUE THREAD

**Issue by stemixreal** [Azure/static-web-apps#301]
Please excuse me if I'm asking this in the wrong place. I'm starting here because my question is about static web app function use. I'd appreciate being redirected if this isn't a question for here.

Is it possible to install a node package to be used by the a javascript function api?

Some node packages can be used without issue, qs for instance. Others can't, and I break the api github build process with attempts to install them.

I've looked around a lot without any real luck, hints in posts about technology that we can use in an SWA. I have the things I need working locally but pretty much anytime I deploy, when I'm using node packages, I get failures. I asked a related question a couple of days ago #294 showing successful use of Microsoft PlayFab NodeSDK which shows the local api working with remote PlayFab servers.

Should I just stick with my App Service? I like SWA a lot but I can't keep fighting the build process, it's taking too much time. Am I trying to do something SWAs are not intended for?

Thanks
Steve

**Comment by anthonychu** [comment]
@stemixreal Please take a look at my comment in #294 to see if it solves your problem.

**Comment by stemixreal** [comment]
Thank you @anthonychu it did solve my problem
