### ISSUE TITLE
Resource move is not supported for resource types 'Microsoft.Web/staticSites'

### ISSUE THREAD

**Issue by plamber** [Azure/static-web-apps#303]
Hello,
I tried to move a static Web App in a different resource group and received this error message:
![image](https://user-images.githubusercontent.com/18241305/109108355-a6c68e80-7733-11eb-952e-da088c1ad4d8.png)

Do you have any plans to support a move in future?

What is your suggestion if this will not be the case? If you have for example a domain associated with the Azure Static Web App, a transfer by creating a new resource will result in a service downtime because I haven't found a simple way to register a domain on two separate static apps.

Thank you for your feedback,
Patrick

**Comment by miwebst** [comment]
Hey @plamber, we are working on supporting resource move, it should light up in the next few months. In the meantime, there is a flow for adding a custom domain via a txt record, but there is not a Portal experience for it (just ARM apis). Let me know if you'd like more guidance on manually using this api's for txt record validation!

**Comment by plamber** [comment]
Thank you @miwebst. 

I do not necessarily need a portal experience. Would be interested to know more about the domain addition via txt record. 

The usecase would be this one:
- I have a running web app or static web app with custom domain
- I want to build a fresh static web app with the same domain but without any service disruption
- Ideally I can setup the new static web app, configure the custom domain, wait that the ssl certificate is installed and then perform the necessary DNS changes to point on the new resources

With this approach I could switch to static web apps without service interuption.

Thank you

**Comment by mkarmark** [comment]
Hi @plamber, resource migration should now be available. Let us know if you have any questions/issues with it we can improve on!

**Comment by plamber** [comment]
Thank you for your help.

I was able to successfully move a resource without any downtime. Thank you very much.
