### ISSUE TITLE
SWA Function Quotas

### ISSUE THREAD

**Issue by stemixreal** [Azure/static-web-apps#305]
Hi Folks,

I have an SWA with some functions and I was wondering about function quotas. Are they the same as specified in the [docs](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#azure-functions-limits)?

I've accounted for the preview limits with most functions passing work off to other azure services acting as a kind of message broker. So users are not directly managed by the app, routes.json isn't used for user authentication for example. The SWA acts as a "lobby" for users to look around, register, log-in etc.

Whilst in the lobby a user can receive updates via SignalR. This requires a connection to a SignalR Hub which maintains the actual connection to the user, sending updates it receives from messaging function in the SWA api. There are also connections made to CosmosDB, and so on.

I read about SWA limits [here](https://docs.microsoft.com/en-us/azure/static-web-apps/quotas), 

I'm particularly interested in Function inbound/outboud connections and other function quotas in the SWA environment. I read somewhere or saw on the .NetConf last year, something about SWA performance in preview. I can't find it but I'm looking!

Also, it may not but does Function usage in SWA go towards quotas my subscription?

Many Thanks
Steve

**Comment by anthonychu** [comment]
We don't enforce quotas anymore. Your functions executions count as regular Azure Functions executions in your subscription.

The SignalR output binding does not require a persistent connection. Maintaining a persistent connection to other services does not incur a charge. You are only billed when a function is executing. The monthly Azure Functions [free grant](https://azure.microsoft.com/en-us/pricing/details/functions/) applies to Static Web Apps function executions as well.

**Comment by stemixreal** [comment]
Thanks @anthonychu , appreciate the info. I wasn't aware quotas had been removed. That's great!
