### ISSUE TITLE
Restricting Azure Static Web Apps easy auth to a single tenant

### ISSUE THREAD

**Issue by jennirethi** [Azure/static-web-apps#308]
I am wanting to use the baked in auth feature of Azure Static Web apps. I'm able to secure my routes by just simply using the authenticated role, but I am seeing that I have the ability to sign in from id's that are not singly restricted to my Azure AD tenant. If I don't want to invite users/define custom roles and simply want to use the authenticated role, how can I restrict access to only my tenant?

Here is my routes.json file:

{ "routes": [ { "route": "/", "allowedRoles": ["authenticated"] }, { "route": "/login", "serve": "/.auth/login/aad" } ], "platformErrorOverrides": [ { "errorType": "NotFound", "serve": "/" }, { "errorType": "Unauthenticated", "statusCode": "302", "serve": "/login" } ] }

Thanks!

**Comment by anthonychu** [comment]
We're working on a feature that allows you to bring your own auth registration which should allow you to do this. You would be able to restrict AAD logins to just your tenant. Then you can use routing rules to lock down parts or all of your site. Only users from your tenant can log in and have the `authenticated` role.

**Comment by miwebst** [comment]
Hey @jennirethi , this is available now, you can try it through these docs: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad

**Comment by bdm123** [comment]
@jennirethi I'm having this same issue and have read the doc linked below.  What specific changes would you make in the original poster's config?
> Hey @jennirethi , this is available now, you can try it through these docs: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad
