### ISSUE TITLE
enable GitHub Discussions in this repository

### ISSUE THREAD

**Issue by k-miyake** [Azure/static-web-apps#309]
You are aware of the Discussions feature on GitHub.
https://docs.github.com/en/discussions/quickstart

This repository is getting so crowded with issues that it's getting hard to find the important ones.
Why not use GitHub Discussions to make it easier to find issues?

**Comment by simonaco** [comment]
@k-miyake  thank you for the suggestion, we just enabled GitHub Discussions.
