### ISSUE TITLE
Angular app with routing raises 404 Not Found after page is loaded

### ISSUE THREAD

**Issue by mahmoudajawad** [Azure/static-web-apps#31]
In my tests for SWA, I pushed an Angular app which is working fine, loading, then after the page is loaded (which is using Angular routing to change the URI to `/home`) it gives 404 Not Found Azure error page.

I understand there's a necessity to adding routes, but my understanding is these are required only for accessing the routes directly (as in typing the domain + route and hitting enter), not for the app when it internally changes the URI (with `history` and similar methods). Is this a bug or this is the intended behaviour?

**Comment by anthonychu** [comment]
@mahmoudajawad Do you have a repo or deployment that shows the problem?

**Comment by mahmoudajawad** [comment]
Yes, @anthonychu, I have but I would prefer to pass it to you privately. Can I use your email to send the deployment URI?

**Comment by anthonychu** [comment]
Feel free to send me an email at antchu at microsoft com. Thanks.

**Comment by mahmoudajawad** [comment]
@anthonychu, thanks for offering help. I just sent an email including the deployment URI. The thing I noticed is if I add a trailing slash (`deplyment URI + /`) it wouldn't raise the 404. Network tab is showing a redirection occurring, although effectively this is not a redirection but internal Angular routing. I'm willing to add routes file but would like to expose this first to understand what is going on with it.

**Comment by anthonychu** [comment]
@mahmoudajawad Could you please confirm that you've sent it to antchu@microsoft.com? I haven't yet received it. Thanks.

**Comment by mahmoudajawad** [comment]
Oh! I've sent it to the email listed in your profile. I'll forward the message to the one you just mentioned.

**Comment by mahmoudajawad** [comment]
@anthonychu, to keep reference to others on this issue I'm going to continue here.

First, thanks a lot for taking time to check on the deployment, which I missed, where the app is reloading the page after failing to connect to dev websocket, because the app was built against development configurations, not production.

So, I never realised SWA service is building against `npm run build` and not detecting this as Angular project and invoking `ng build --prod` which is the defacto for production deployments. Just by editing `package.json` and updating `scripts.build` to be `ng build --prod`, I got new deployment with working app that doesn't reload  the page because it's correctly connecting to the production environment.

May I suggest that SWA service be little more smart and invoke `ng build --prod` rather than `npm build run` if it detects an Angular project? I'm going to close this issue and bring up this suggestion in another one to keep issues clean.

Thanks a lot.

**Comment by anthonychu** [comment]
@mahmoudajawad glad you got it working. Yes that’s a problem specific to Angular and @johnpapa @manekinekko are aware and are discussing options. It makes sense that that websocket was from a non production build.

**Comment by conchris** [comment]
create a new file named staticwebapp.config.json in your src, enter the above code in the file

{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
  }
}


add in angular.json under options in assets array the above code 

"assets" : [ {
                "glob": "staticwebapp.config.json",
                "input": "src/",
                "output": "/"
              }]

build and deploy.
