### ISSUE TITLE
Best place to get news and updates on Static Web Apps?

### ISSUE THREAD

**Issue by wilberolive** [Azure/static-web-apps#310]
Hello, just wondering where the best places it to get news and updates regarding new features and changes to the Static Web Apps platform? I can't find any blog or "what's new" sort of page anywhere.

**Comment by anthonychu** [comment]
This is good feedback. We’ve been having internal discussions about this and are looking at ways to better communicate updates and new features.

For now, our [Twitter account](https://twitter.com/azurestaticapps) might be the best place for updates.
