### ISSUE TITLE
Save button on Configuration page is greyed after adding a new setting

### ISSUE THREAD

**Issue by borisno2** [Azure/static-web-apps#314]
The Save button stays greyed out after a new setting is added.
![image](https://user-images.githubusercontent.com/8251494/110236682-4f25ef80-7f8b-11eb-83b8-1475aa865284.png)
It becomes available after clicking the "Hidden Value"

**Comment by anthonychu** [comment]
This is related to #121. I can reproduce this sometimes as well, so I think this issue persists in some scenarios. @takyyon can you please take another look?

**Comment by borisno2** [comment]
Yes, reading through #121 looks to be similar to what I have been experiencing in the portal. Let me know if you need any more info.
