### ISSUE TITLE
.NET 5 Worker Support

### ISSUE THREAD

**Issue by JustinGrote** [Azure/static-web-apps#319]
Obviously it was *just* released, but I thought it would be good to know what the roadmap looks like for adding .NET 5 worker support to static web apps as a backend function type.

**Comment by xgalaxy** [comment]
Dang. Disappointed to come here and see this ticket. I got all excited to see Azure Functions supports .NET 5 and now it turns out Static Web apps doesn't support the new Azure functions running .NET 5 😭

**Comment by anthonychu** [comment]
Static Web Apps supports specific versions of each language runtime. They're currently:
* Node.js 12 LTS
* .NET Core 3.1 LTS
* Python 3.8

We'll evaluate other runtimes and languages based on demand in the context of HTTP APIs used in Static Web Apps. We are looking into providing ways for you to bring a function app that you manage to Static Web Apps.

**Comment by simonaco** [comment]
Static Web Apps now supports .NET 6.0
