### ISSUE TITLE
Page fails to load (credentials required) when using Azure storage

### ISSUE THREAD

**Issue by rahul-rxr** [Azure/static-web-apps#32]
I have a react app where I am using Azure table storage to create a user form.

```
// App.js
import React from 'react';
import azure from 'azure-storage';

...

const tableService = azure.createTableService(
      process.env.REACT_APP_AZURE_STORAGE_CONNECTION_STRING
);
...
```
This app is connected to Azure Static Web Apps through GitHub actions. The app works normally on local (pre and post-react build). The CI/CD is passing as well and the app is deployed on Azure successfully.

However, when I navigate to the app URL, the page fails to load with the following error.

```
react-dom.production.min.js:209 Error: Credentials must be provided when creating a service client.
    at Function.T.createFromEnvironment (storageservicesettings.js:182)
    at Function.H.getStorageSettings (storageserviceclient.js:925)
    at new T (tableservice.js:77)
    at Object.t.createTableService (azure-storage.js:62)
    at index.js:27
    at is (react-dom.production.min.js:211)
    at bc (react-dom.production.min.js:257)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Hi (react-dom.production.min.js:122)
    at mc (react-dom.production.min.js:257)
```

I believe it's failing because Azure cannot establish a connection to storage account due to absence of connection string. What's the correct way of passing env variables in such situations through GH actions?

**Comment by miwebst** [comment]
Hi @rahul-rxr, 

Can you explain your setup a little more closely? Is the connection string getting built into the client-side JS? If so, you can accomplish this by adding the connection secret to your Github Action Secrets and adding an env variable to your workflow.

That being said, this approach will publicly expose your connection string, you may want to consider using a function for this use case.

**Comment by anthonychu** [comment]
@rahul-rxr Yes, @miwebst is correct. You should call a function to return a SAS that allows the client a limited time window to access the container. Take a look at the example here: https://github.com/sunrise-standup/sunrise-standup/blob/master/api/GetSASToken/index.js#L49 (Looks like there's a bug in the date calculation there, `86400` is in milliseconds, so the token is only good for a couple of minutes but the intention was probably 24 hours).

**Comment by rahul-rxr** [comment]
Thanks guys, I will try it out and close the issue accordingly.
