### ISSUE TITLE
Oryx Unrecognized command or argument

### ISSUE THREAD

**Issue by navi1995** [Azure/static-web-apps#326]
Hi there, 

I'm trying to get a React app built and deployed using mostly defaults from Azure Static Web App setup. I've run a few different commits now mostly changing around directories to see if that's the issue but keep getting this issue. 

```
App Directory Location: './Movie Night Bot Website/bot-dashboard/' was found.
No Api directory specified. Azure Functions will not be created.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
Oryx will build app with the following custom override command: npm run build
---Oryx build logs---


Specify --help for a list of available options and commands.
Unrecognized command or argument 'Night'


---End of Oryx build logs---
Oryx has failed to build the solution.
```

The build command works fine on my local machine.

My YML file for the action is at https://github.com/navi1995/Movie-Night-Discord-Bot/blob/master/.github/workflows/azure-static-web-apps-jolly-rock-0315ee91e.yml 

The repo contains various code, and the react app exists at /Movie Night Bot Website/bot-dashboard

I also have an API but for the time being just want to get my files deployed to see exactly how azure works.

Any help is appreciated, thanks!

**Comment by navi1995** [comment]
My biggest guess is that it's due to the space in my directory Movie Night Bot Website, and something to do with how Ubuntu handles directories? Assume I could fix this by renaming the folder to not have spaces.

**Comment by anthonychu** [comment]
Yes the spaces could be the problem. Can you try removing them and see if it fixes it?

**Comment by navi1995** [comment]
Renaming my folder structure to no longer have spaces did work if anyone has this problem in future. Seems odd though still.

**Comment by anthonychu** [comment]
@miwebst Is there a way to get it to work with spaces in the directory name?
