### ISSUE TITLE
React Build Failed When There Is Axios Import Statement

### ISSUE THREAD

**Issue by slefved** [Azure/static-web-apps#327]
I tried to create new react app in my local computer using npx create-react-app. I installed axios and pushing my codes to github repository. Then I created static-web-app in azure using my github account. It was all fine, Github CI/DI workflow done succesfully, web was deployed and I can see it through the browser.

Then I made slight change in my code, I added axios import library statement import axios from 'axios'; and push it to Github, the CI/ID workflow failed to build my code.

it says:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pustaka-react@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pustaka-react@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2021-03-22T03_41_53_537Z-debug.log

---End of Oryx build logs---
Oryx has failed to build the solution.

**Comment by anthonychu** [comment]
@slefved Is your repo public? We might be able to help if you can share the repo? If not, can you share your package.json and how you are using axios?

**Comment by slefved** [comment]
@anthonychu this is my public repo https://github.com/slefved/pustaka-react

This is just a plain react project with only axios installed. All was fine untill I import "import axios from 'axios';" in app.js file.

**Comment by diberry** [comment]
@slefved Axios isn't in your package file - that I can see.

**Comment by anthonychu** [comment]
The branch in use is [`development`](https://github.com/slefved/pustaka-react/tree/development), and `axios` is in package.json.

The problem here is that the build will treat warnings as errors when it's running in a CI environment, which includes GitHub Actions. There's a warning by the linter:

```
Creating an optimized production build...

Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

src/App.js
  Line 2:8:  'axios' is defined but never used  no-unused-vars
```

Once you use `axios` in your code, the error will disappear. There are more details here: https://github.com/facebook/create-react-app/issues/3657
