### ISSUE TITLE
Error validating custom domain: Request Envelope is invalid. Apex Domains must use dns-txt-token as the ValidationMethod.

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#329]
When adding a custom domain, you may encounter this error message:

![image](https://user-images.githubusercontent.com/3982077/112061307-89f75e00-8b1b-11eb-90a1-2e105d77ff51.png)

> Request Envelope is invalid. Apex Domains must use dns-txt-token as the ValidationMethod.

This is because Static Web Apps currently does not support apex domains (that feature is tracked at #168).

**Comment by stemixreal** [comment]
Hi @anthonychu, In the March edition of Azure Functions Live you mention Apex domains are close. I have a App service website that's on the HSTS preload list. It's an app I've been moving to SWA and serverless. I can hack it with cloudflare it seems but don't know enough to know if that hack would invalidate the preload status and to be honest would rather not do that as SWA apex domains are close.

I know it's difficult to give a time frame so I just wanted to say if you're looking for developers to test this out before it goes out generally I'm really very keen to implement this.

**Comment by anthonychu** [comment]
Some priorities changed and we're still at least a month away. As you can see by this error, we have some of the components rolled out to support apex domains but still needs more work in other places.

**Comment by stemixreal** [comment]
cool, thanks for the update.

**Comment by dpiessens** [comment]
Hi,
Any ETA updates on this? It's the last thing we need to move to static web apps. The offering is great overall!

**Comment by miwebst** [comment]
This is available now: https://docs.microsoft.com/en-us/azure/static-web-apps/custom-domain?tabs=azure-dns

**Comment by stemixreal** [comment]
Awesome!

**Comment by tseward** [comment]
> Some priorities changed and we're still at least a month away. As you can see by this error, we have some of the components rolled out to support apex domains but still needs more work in other places.

This issue still seems to be a problem with IDNs (punycode). I'm encountering the exact same issue as the OP, but only for IDNs.
