### ISSUE TITLE
Significantly reduced service quality since March 16.

### ISSUE THREAD

**Issue by cirzoltan** [Azure/static-web-apps#330]
For about a week now the amount of availability of functions have been atrocious with regular 503 errors for hours at a time.

Looking at the logs it seems to have started around March 16.

There have been no back-end changes to our site in that period so I cannot pin this on anything on our side.

Any suggestions, updates, some sort of light at the end of the tunnel? If things don't change soon I'll likely have to move the site to some other hosting plan.

**Comment by miwebst** [comment]
Have you already setup App Insights to see the function logs?

If you have and you didn't see any useful logs, then I'd also recommend filling a support ticket so you can provide all of the time ranges, app name, etc. without needing to publicize it here.

**Comment by cirzoltan** [comment]
I have set up App insights now and will keep an eye on it. I was mostly curious if there's any planned maintenance or other things going on. Normally I wouldn't expect this but SWA being in preview has me a bit on the edge.I was hoping we'd get an official release of SWA before our service went live, because frankly I really enjoy using it, and replicating the same serverless setup with non-preview Azure products would be a mess.

**Comment by cirzoltan** [comment]
It seems like my the cause of my woes were related to the back-end functions going into a "cold" state overnight causing the described issue first thing in the morning (the service sees pretty much all traffic during business hours in one time zone).

I'm basing this assumption on the fact that ever since I added an availability test on App insights (which includes a regular ping) the problem disappeared (classic case of a Heisenbug). 

The fact that the cold starts took multiple minutes instead of the few second's I'd expect is still a bit concerning but at least now I have something to go by.

I think we can close this issue, thanks for the help!

**Comment by anthonychu** [comment]
@cirzoltan Is your app in a public repo? Would like to look into the cause of the long cold start of the function app.
