### ISSUE TITLE
Cannot create application setting starting with "IDENTITY_"

### ISSUE THREAD

**Issue by itpropro** [Azure/static-web-apps#334]
When creating application settings starting with `IDENTITY_` they don't show up in the SWA.

Steps to reproduce:

`az staticwebapp appsettings set --name <YOUR_SWA_NAME> --setting-names IDENTITY_DB_NAME=test IDENTITY_DB=test IDENTITY_ABC=test test=test`

Results in these app settings:

![image](https://user-images.githubusercontent.com/15030951/112750891-4a24f080-8fcb-11eb-86af-f063066f81e5.png)

**Comment by anthonychu** [comment]
@annaji-msft

**Comment by miwebst** [comment]
Hey @itpropro, these are some of the app settings that are not allowed. If you'd like to use them you need to use bring your own functions, more details here:

https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints

**Comment by itpropro** [comment]
Thanks for documenting them @miwebst I will close the issue now :)
