### ISSUE TITLE
Failed to upload build artifacts

### ISSUE THREAD

**Issue by sbyse** [Azure/static-web-apps#338]
I'm seeing this lately with our deployments, seems to fail about 30% of the time:
![image](https://user-images.githubusercontent.com/1544753/112977102-94ce7600-914d-11eb-8a98-52898684f032.png)

Our deployment is in West Europe.

**Comment by anthonychu** [comment]
@joslinmicrosoft @miwebst Can you please take a look?

**Comment by anthonychu** [comment]
@sbyse We are rolling out a fix for this issue affecting larger deployments. Let us know if you're still experiencing this problem. Thanks.

**Comment by sbyse** [comment]
Thanks @anthonychu - looks much better so far. Thank you!
