### ISSUE TITLE
Angular App with Azure Devops - Error : Failed to find a default file in the app artifacts folder (dist). Valid default files: index.html,Index.html.

### ISSUE THREAD

**Issue by sajeetharan** [Azure/static-web-apps#340]
Hi all, since Azure static web app went public preview, i just wanted to try deploying an angular application which i have deployed with github actions in the past using azure devops. 

I tried different ways in configuring the app_location , but nothing seem to be working. What could be the issue?

**Here is the error log with azure devops**

Copy '/working_dir/node_modules' with all dependencies to '/working_dir/.oryx_all_node_modules'...

Copying production dependencies from '/working_dir/.oryx_prod_node_modules/node_modules' to '/working_dir/node_modules'...
Preparing output...

Copying files to destination directory '/ss-oryx/app'...
Done in 2 sec(s).

Removing existing manifest file
Creating a manifest file...
Manifest file created.

Done in 172 sec(s).

---End of Oryx build logs---
Finished building app with Oryx
Failed to find a default file in the app artifacts folder (dist). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file (located in .github/workflows) points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

Finishing: AzureStaticWebApp

**Here is the YAML:**

`trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: AzureStaticWebApp@0
  inputs:
      app_location: "/" 
      api_location: "api"
      output_location: "dist/meme4fun"
  env:
      azure_static_web_apps_api_token: $(deployment_token)

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
`

**Here is the Angular App Repository :** https://github.com/sajeetharan/meme4fun

**Note** : I have tried with all possible values for output_location and app_location as well. why does the error says .github/workflows when i am trying to deploy with azure devops?

**Comment by anthonychu** [comment]
@sajeetharan Can you run a GitHub Actions deployment with these inputs to confirm that this is still working with GitHub?

```
app_location: "/"
api_location: "api"
output_location: "dist/meme4fun"
```

In your workflow above, you are running a build after the deployment. Is there a reason for this?

We use the same container to build in both GitHub and DevOps. Looks like we need to clean up the error messages to be more environment agnostic. @miwebst

**Comment by sajeetharan** [comment]
Thanks @anthonychu  seems there was a typo in the package.json , i was able to successfully deploy with azure devops. 

Also thanks for the hint on the order in the YAML. it was not intentional

Published a blog on the same :  https://sajeetharan.com/2021/04/02/azure-static-web-apps-with-azure-devops/

**Comment by DeepakR-28** [comment]
hey @sajeetharan i am facing this same issue while deplyoing my Nextjs website as a static web app, i get the following error

`Failed to find a default file in the app artifacts folder (.next). Valid default files: index.html,Index.html.`

i also tried many possible values for the output location. none worked, hope you could help.

**Comment by sajeetharan** [comment]
let's have a look!

**Comment by DeepakR-28** [comment]
![image](https://user-images.githubusercontent.com/33338977/135391948-dd36ff02-6ca9-4dea-9ee5-896a8e07612a.png)
This is the error

**Comment by DeepakR-28** [comment]
Hey, i found the fix 
i was running `  "build": "next build' instead of `  "build": "next build && next export"`

:)

**Comment by sajeetharan** [comment]
@DeepakR-28 Sorry just now I noticed, glad that you've found a fix
