### ISSUE TITLE
Dependencies (i.e. net sdk or node) used in workflow are reinstalled during deploy step

### ISSUE THREAD

**Issue by kaylumah** [Azure/static-web-apps#342]
When playing around with static web apps I stumbled upon a couple of things (see #341).
To verify if api would still work because I mis interpreted the docs I added a .net / C# azure function.

![image](https://user-images.githubusercontent.com/8428126/113323028-c09c5800-9315-11eb-99da-be8d6d5d67a8.png)

As you can see in the screenshot I install 2 versions of the .NET sdk.
Since I like the use of new build feature introduced in the .NET5 sdk, but I strongly believe the code it self should be LTS supported. This means I can build via NET5 sdk but target netcoreapp3.1

For some reason the actions tries to install .net again, as oposed to reusing the installation I already did.

```
Detecting platforms...
Detected following platforms:
  dotnet: 3.1.12
Version '3.1.12' of platform 'dotnet' is not installed. Generating script to install it...

...

```

Just to make sure it was not netcoreapp3.1 related I also generated a .net5 function.
This triggers the same warning, and installs another sdk.

```
Detecting platforms...
Detected following platforms:
  dotnet: 5.0.3
Version '5.0.3' of platform 'dotnet' is not installed. Generating script to install it...

...

```

Should the `Azure/static-web-apps-deploy@v0.0.1-preview` step make use of depedencies like NODE, DOTNET etc installed in the Workflow or does this action run isolated (seems that the second action added docker to proces static web apps).

Is this the intended behavior? Or what is the best way to handle my use-case.
(note build failed on the fact that I have a global.json requiring net5sdk in the build, which now of course failed because it only tried to install the netcore3 one)

Fun fact, also verified the typescript nodejs azure function which installed nodejs even though it is already installed in the workflow.

```
Detected following platforms:
  nodejs: 14.15.1
Version '14.15.1' of platform 'nodejs' is not installed. Generating script to install it...
```

**Comment by anthonychu** [comment]
`Azure/static-web-apps-deploy@v0.0.1-preview` runs in its own container and uses [Oryx](https://github.com/microsoft/Oryx) to build the frontend and API apps, so the dependencies you install in previous steps are not used.

If you are building the app already in previous steps, use the following settings in the workflow:

* `app_location`: Your build app's _publish output_ folder
* `output_location`: `""`
* `api_location`: Currently, you must use the Static Web Apps action to build and deploy an API app. Building in a previous step is not supported.

**Comment by kaylumah** [comment]
Thanks for clarifying, since you mention 'Currently' can I interpreted that as in the future this might be a feature?

**Comment by anthonychu** [comment]
We want to enable this, but there's some special logic that the API build does that determines the language, and that information is used downstream to provision the right function app for you. Until we figure out how to do this, the action needs to build the function app. Is there a reason you want to build the API app yourself?

**Comment by kaylumah** [comment]
Not necessarily but I did find that my .editorconfig (it enforces file headers) and global.json from the root are used.
So as I explained I used .net5sdk to build TFM netcoreapp3.1, which works great if I build my self.

The logic in the step however assumes I need netcoreapp3.1 downloads the latests, and then says no no your global.json wants something else.


So both of these caused build errors, which got me wondering how these API projects are build. (please note as of right now I don't have the need of functions, but because of my previous created issue I played around with how it would work)

**Comment by Reshmi-Sriram** [comment]
Closing due to no traction. Feel free to reopen if required!
