### ISSUE TITLE
Azure Function Not accepting Content Type header

### ISSUE THREAD

**Issue by amykapernick** [Azure/static-web-apps#35]
When setting the content type on the Azure function response it's not passing that through

## Code
<https://github.com/amykapernick/quokkas/tree/broken-azure-function>
```
// api/whatsapp/index.js
  context.done(null, {
        status: 200,
        body: message.toString(),
        headers: {
            'Content-Type': 'text/xml'
        },
    })
```

But on the response, it doesn't have the content type coming through

## Function Endpoint
https://brave-ground-020b74800.azurestaticapps.net/api/whatsapp
Custom Domain - https://quokkas.amyskapers.dev/api/whatsapp

When deploying that exact same code to regular Azure Functions it works fine
https://quokkatest.azurewebsites.net/api/whatsapp

Have confirmed with @aaronpowell that this is broken and not working as intended

**Comment by miwebst** [comment]
Yup this is an error on our end! We will get a fix out for this and I'll respond here when it is fixed :)

**Comment by miwebst** [comment]
This should be fixed globally now

**Comment by amykapernick** [comment]
Awesome, that's all working now!

Thanks
