### ISSUE TITLE
Allow all authenticated users

### ISSUE THREAD

**Issue by niicojs** [Azure/static-web-apps#350]
Is it possible to allow all authenticated users without having to invite them one by one?
This seems like a pretty big limitations

thanks

**Comment by RichyP7** [comment]
That´s already possible. You just have to invite them if you need specific roles. If you authenticate with your auth provider you get the authenticated role which you can use to secure your app without invitations. Look [here](https://docs.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=javascript#client-principal-data)

**Comment by niicojs** [comment]
Thanks. However my requirement is to be able to authenticate people without having to invite them first.
Inviting user one by one is not doable for company wide webapps and also not compatible with the 25 users max limit.

**Comment by anthonychu** [comment]
@niicojs As @RichyP7 mentioned, you do *not* need to send invitation if your goal is to allow all authenticated users. Anyone who authenticates (with or without an invitation) will be in the `authenticated` role.

Can you share more about your requirements? It sounds like you want to allow *some* users (those who work in your company) but not *all* users. We are planning some improvements related to this and want to see if they would work for your scenario.

**Comment by niicojs** [comment]
What I'm trying to do is to authenticate anybody from AAD. Ideally I would like to restrict to my company but I can do that easily through custom code.
The thing is, people that I didn't send invite to are getting a "an administrator need to give access". It may be on my side...

**Comment by anthonychu** [comment]
@niicojs Might be an issue on your side. We're working on a feature that will allow you to use your own AAD registration, which will restrict logins to only identities in your AAD.

**Comment by niicojs** [comment]
Ok, good news then. That means I should be able to fix this :)
Closing the issue.
