### ISSUE TITLE
Deployment suddenly started failing with error : 'Yarn command "plugin" not found'

### ISSUE THREAD

**Issue by prateek14** [Azure/static-web-apps#353]
Deployment suddenly started failing for api folder. Here is the error log:

`Detecting platforms...
Detected following platforms:
  nodejs: 14.15.1

Source directory     : /github/workspace/api
Destination directory: /bin/staticsites/ss-oryx/api

Using Node version:
v14.15.1

Using Yarn version:
1.22.10

Installing production dependencies in '/github/workspace/api/.oryx_prod_node_modules'...

Running 'yarn plugin import workspace-tools && yarn workspaces focus --all --production'...

yarn run v1.22.10
error Command "plugin" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Running 'yarn plugin import workspace-tools && yarn workspaces focus --all'...

yarn run v1.22.10
error Command "plugin" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Running 'yarn run build'...

yarn run v1.22.10
$ tsc
/bin/sh: 1: tsc: not found
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting`

**Comment by miwebst** [comment]
@arroyc is this a regression in the new version of oryx? can you take a look?

**Comment by anthonychu** [comment]
@qianz2 Do you know how the detection logic works for Yarn 1 vs 2?

**Comment by qianz2** [comment]
We've recently added yarn 2 detection logics: Either the repo contains a `.yarnrc.yml` file or the `yarn.lock` file is in valid yaml format,  these two cases can be detected as yarn 2. So it may be the case that repo contains a `.yarnrc.yml` file. This remind us that we may need to have a stricter way to detect for yarn 2.

**Comment by anthonychu** [comment]
This was fixed in https://github.com/microsoft/Oryx/pull/982. We should have this available in Static Web Apps next week.
