### ISSUE TITLE
Unable to map subdomain to SWA

### ISSUE THREAD

**Issue by vladiliescu** [Azure/static-web-apps#354]
I'm unable to map a subdomain to my SWA instance. 

I'm trying to map `forecasts.vladiliescu.net` to my SWA, and as you can see below the Azure portal insists I map a CNAME to `www` (and not `forecasts` like one might expect). Adding a CNAME entry for `forecasts` will not work, and results in the following error: **CNAME Record is invalid. Please ensure the CNAME record has been created.**

The expected behavior is to be able to map any subdomain to a SWA, not just WWW. 

<img width="575" alt="image" src="https://user-images.githubusercontent.com/331671/113884287-84f70780-97c7-11eb-90ab-bd95eff620a2.png">

**Comment by miwebst** [comment]
Hi @vladiliescu,

Thanks for calling this out. The Portal UX is incorrect here. To add your custom domain, you want to create a CNAME like forecasts.vladiliescu.net -> delightful-coast-....azurestaticapps.net

We will work on fixing this experience.

**Comment by vladiliescu** [comment]
Hi @miwebst, exactly, that's what I had expected. However, adding a CNAME entry for forecasts doesn't work, I'm assuming it's because it still checks for `www`.

**Comment by miwebst** [comment]
It shouldn't check for www. The validation is checking the existence of the CNAME. From what I see here, it appears that the CNAME has not been set?

https://www.digwebinterface.com/?hostnames=forecasts.vladiliescu.net&type=&ns=resolver&useresolver=8.8.4.4&nameservers=

**Comment by vladiliescu** [comment]
Not sure how to interpret the output of digwebinterface, however looking at the output, I see what appears to be Azure IPs right? I'm using Cloudflare for DNS, and I get the same IPs whether I choose to have the entry proxied by CF or not.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/331671/113900757-d490ff80-97d6-11eb-9311-88c06faed60e.png">

If I remove my CNAME from Cloudflare I get a different output, as seen below.

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/331671/113900900-fb4f3600-97d6-11eb-9624-89ff2a18346d.png">

All this, coupled with the error message I'm getting for https://forecasts.vladiliescu.net makes it look like Azure is not correctly configured.

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/331671/113900927-030eda80-97d7-11eb-8b3c-e61f162c746e.png">

**Comment by vladiliescu** [comment]
Ah, they're not Azure IPs right, they're Cloudflare IPs I guess.

Then, I guess this means I can't use custom domains for SWA unless I don't proxy traffic through CF? Feels weird, to be honest.

Note that with CF proxying disabled, at every two refreshes of digwebinterface I get this output.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/331671/113902408-841aa180-97d8-11eb-8de6-54d2469e8b08.png">

**Comment by miwebst** [comment]
This is all about proving domain ownership. You can switch back to CF once you've proved ownership and added the custom domain on our side.

We are also working on adding TXT record validation which would be another avenue for verifying domain ownership when using a CDN in front of a SWA. @anthonychu as fyi

**Comment by vladiliescu** [comment]
Thanks, I'll wait for TXT record validation to be added then.

**Comment by Taras-Tyrsa** [comment]
I can confirm that validation doesn't allow anything except www for me as well...

**Comment by ARambazamba** [comment]
Same Problem ...

**Comment by Taras-Tyrsa** [comment]
Hi. That's interesting, as now I was able to add non-www subdomain through portal. I can say that I had completely different UI the last time I've checked. Feels like there is some kind of A/B testing going on. Good to know that things are moving forward.

**Comment by ARambazamba** [comment]
> Hi. That's interesting, as now I was able to add non-www subdomain through portal. I can say that I had completely different UI the last time I've checked. Feels like there is some kind of A/B testing going on. Good to know that things are moving forward.

So that means I am another deployment ring or B 🥲 still the same ui ... can only setup www, which I dont want to do, as it is used by a produvtion website

**Comment by anthonychu** [comment]
There's currently a bug in the portal UI that we're going to fix. It says the subdomain must be `www`, but in fact it can be any subdomain. We do not block non-www subdomains. There's no A/B testing going on here.

**Comment by miwebst** [comment]
Both types of domains are now supported: https://docs.microsoft.com/en-us/azure/static-web-apps/custom-domain?tabs=azure-dns

**Comment by rts-pgilligan** [comment]
This is also currently happening to me as per the post above, however, unlike the post above this one, it still is not working for me. I am going to go ahead and sleep on it. I hope its just some type of DNS propagation issues happening.
