### ISSUE TITLE
Reliability Issues with Azure Functions Backend

### ISSUE THREAD

**Issue by rconard** [Azure/static-web-apps#355]
I have been running an Azure Static Web App that includes both a web application and a backend for an IoT project. Both the API endpoints for the front-end and for the IoT devices are managed through the SWA.

There are a couple of issues that have made the Azure Functions implementation difficult to rely on.

## 1. Backend API Reliability
A Raspberry Pi sends data to a function that is managed through the SWA project every 10 seconds, and I keep logs on the success of these requests.

There seem to be intermittent periods of reduced reliability that range from a single call to many calls over a period of hours. 

Here is a sanitized version of my logs:
https://gist.github.com/rconard/86cad4ca05caf3c392411392eaec2d1f

The errors include:
- 404: Not Found
- 500: Internal Server Error
- 502: Bad Gateway
- 503: Service Unavailable

## 2. Long Response Times
Starting a few weeks ago, I am frequently getting API response times of 4 to 10 seconds. This is fine for a machine-2-machine communications, but it is uncomfortably long for an SPA that relies on an API response to load the interface. Application Insights is showing these longer response times.

These slow responses do seem to be connected to cold starts as they frequently occur when the SWA is first pulled up in the browser. They occur more frequently when the Raspberry Pi sending data is offline, but they still occur many times a day while the Raspberry Pi is sending a request every 10 seconds from the same IP address. Prior to a few weeks ago, responses seemed to be consistently fast as long as the Raspberry Pi was sending data.

Note: I have shared additional information on accessing my application's telemetry with @anthonychu .

**Comment by mkarmark** [comment]
Hi, could you please provide us with an app name and we can investigate what is going on.

**Comment by anthonychu** [comment]
Thanks @mkarmark added you to an internal thread with more info.

**Comment by miwebst** [comment]
Closing as issue should be mitigated.
