### ISSUE TITLE
Restriction based on allowed roles not working

### ISSUE THREAD

**Issue by mritconsulting** [Azure/static-web-apps#357]
I am trying to restrict all access to /app/* to only "appeaser" role. 
However it appears that any authenticated users are able to access the protected routes.
I did notice that if those users were to refresh the page they would be severed a 404 page. While users with the correct permission can refresh with no issues. 

Here is a my staticwebapp.config.json file

{
    "routes": [
        {
            "route": "/app/*",
            "rewrite": "/index.html",
            "allowedRoles": ["appuser"]
        },
        {
            "route": "/",
            "redirect": "/login"
        },
        {
            "route": "/login",
            "rewrite": "/index.html"
        },
        {
            "route": "/.auth/login/twitter",
            "statusCode": 404
        },
        {
            "route": "/logout",
            "redirect": "/.auth/logout"
        },
        {
            "route": "/404",
            "rewrite": "/index.html"
        }
    ],
    "responseOverrides": {
        "401": {
            "redirect": "/login",
            "statusCode": 302
        },
        "404": {
            "rewrite": "/404"
        }
    }
}

**Comment by miwebst** [comment]
Hi @mritconsulting, is your application using client side routes to determine the content? Auth enforcement is done based on server requests so if you application is using client side routes, then your end users wont make any server requests until they refresh. 

If that is the case, one option for restricting this sort of page access is to use the /.auth/me endpoint to make routing decisions based on the currently signed in user. You can find docs on that here: https://docs.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=javascript#direct-access-endpoint

**Comment by mritconsulting** [comment]
Perfect. I implement restriction based on the doc you provided, and it is working as intended. 
Thank you,
