### ISSUE TITLE
[Question] ETA on dropping "preview"

### ISSUE THREAD

**Issue by erwinsmit** [Azure/static-web-apps#362]
Hi all,

I would love to use Azure static web apps for a client soon. However the quota's are currently too low for it to be "production ready". 

I can't find any documentation or blogposts on when azure static web apps will be moved out of preview. Is there an ETA available on this?

Thanks!

**Comment by miwebst** [comment]
Our team is working to be GA (generally available), @anthonychu may be able to provide more details on a good ETA.

As for your comment on quota's being too low. Which ones specifically?

**Comment by erwinsmit** [comment]
@miwebst 
Thanks for the reply.

The maximum of 25 users and the 100gb bandwidth is an issue. 
Also the fact that this message is above the quota table doesn't make us feel comfortable using it for production:
**"Azure Static Web Apps is in public preview and is not intended for production use."**

However, if we know that it will only be in preview in our development phase we would consider it.

**Comment by miwebst** [comment]
Hey @erwinsmit, Static Web Apps is now GA! https://twitter.com/AzureStaticApps/status/1392533175570632706?s=20

For the 100 Gb bandwidth and 25 users limits check out the new Standard sku. The Standard sku does not have a bandwidth cap and you can use your own auth registration to get around the 25 users limit.
