### ISSUE TITLE
[Question] How to set deployment token on Release pipeline?

### ISSUE THREAD

**Issue by MaximBalaganskiy** [Azure/static-web-apps#363]
Is it possible to specify the deployment token for the Static Web App step when Release pipeline is configured?
There is no direct YAML editing and the relevant field is also missing in step settings.

**Comment by MaximBalaganskiy** [comment]
Any news on this?

**Comment by anthonychu** [comment]
The task has been updated with an input for the token. You should see it when configuring it.
