### ISSUE TITLE
Build react-app Azure DevOps

### ISSUE THREAD

**Issue by jrmedd** [Azure/static-web-apps#364]
I've had some success [following the instructions here](https://docs.microsoft.com/en-us/azure/static-web-apps/publish-devops) to deploy a simple React app. 

This works well with a pre-commit hook to ensure that my build directory is in place, though I'm wondering if it's possible to run the necessary install/build commands in my Azure DevOPs pipeline instead? It's unclear from the documentation whether or not this is possible. 

I'm not hugely familiar with ADO (I've just joined an organisation using it) but I did try to use other tasks in my pipeline to build, then put $(Build.SourcesDirectory) in my AzureStaticWebApp configuration but with no joy.

Any assistance on this (or a push in the direction of the correct documentation) would be appreciated!

**Comment by anthonychu** [comment]
The app location and API location in the Static Web Apps task are relative to the root of your app. So if you have a folder named build and you just want to deploy that, try setting app_location to “build”. Leave output location “”.

If that doesn’t work, please share more info on your pipeline as well as folder structure of your repo.

**Comment by jrmedd** [comment]
Thanks for your response @anthonychu. As I said in my original post, it's working well for me when I've already got the build directory in place (using husky to run`npm run build` prior to committing). I was just wondering what the most straightforward way would be to include that as part of my pipeline, instead of on my local machine.

**Comment by anthonychu** [comment]
You can add build tasks to your pipeline to run the build command.

The Static Web Apps task should be able to build for you as well if it set the app and output locations correctly.

**Comment by jrmedd** [comment]
Ah, I put an `npm install && npm run build` in the Static Web Apps task and it worked a treat! Thanks!

**Comment by anthonychu** [comment]
@jrmedd Can you share some info about your app? Those commands (`npm install && npm run build `) should be run by default in the task. If you need to add it for your build to work, we’d like to investigate that.

Some info about the pipeline yaml, dependencies in your package.json, and general folder structure would be helpful. Thanks!
