### ISSUE TITLE
Custom domain or subdomain option for staging

### ISSUE THREAD

**Issue by antonioberetini** [Azure/static-web-apps#37]
I just realized that it is not possible to map a subdomain to staging environment. This is very common and useful to help people find staging easily.

**Comment by miwebst** [comment]
Hey @antonioberetini I think this may be a duplicate of this issue: https://github.com/Azure/static-web-apps/issues/22

**Comment by antonioberetini** [comment]
You are right

**Comment by antonioberetini** [comment]
> Hey @antonioberetini I think this may be a duplicate of this issue: https://github.com/Azure/static-web-apps/issues/22 

You are right
