### ISSUE TITLE
Facebook auth is no longer working

### ISSUE THREAD

**Issue by Gabswim** [Azure/static-web-apps#370]
When trying to login with Facebook, I get this message which basically translates to:

_The user is not allowed to see this application. The user is not allowed to see this application because of the config set by this developer._

I don't know if it can be related to #349 or #250 (which I had previously [commented](https://github.com/Azure/static-web-apps/issues/250#issuecomment-755056698) on).

<img width="1792" alt="Screen Shot 2021-04-18 at 9 52 17 PM" src="https://user-images.githubusercontent.com/2859712/115171198-8a3e3700-a090-11eb-9922-e7fceacf407f.png">

If you need a sandbox to reproduce the bug, I would be happy to provide one to you in a private conversation.

**Comment by Gabswim** [comment]
I don't know if you fixed it but it seems to be working again.

**Comment by miwebst** [comment]
We did fix the problem, thank you for reporting.
