### ISSUE TITLE
Function set cookie with expired date

### ISSUE THREAD

**Issue by hynjnk** [Azure/static-web-apps#371]
Set cookies without `expires` but functions of static web apps set cookies with `expires=Mon, 01 Jan 0001 00:00:00 `.

## Code 
https://github.com/hynjnk/azure-static-web-demo
```
  context.res = {
    // status: 200, /* Defaults to 200 */
    body: 'Hello, world.',
    cookies: [
      {
        name: 'cookie1',
        value: 'value1'
      },
      {
        name: 'cookie2',
        value: 'value2'
      }
    ]
  }
```

## Function Endpoint
* Static Web Apps Function https://jolly-mud-0554ede00.azurestaticapps.net/api/SetCookie
![Screenshot from 2021-04-19 13-49-40](https://user-images.githubusercontent.com/38238305/115183307-7f2dea00-a116-11eb-83ae-c09af9f17a85.png)

* Functions App https://azure-function-demo.azurewebsites.net/api/SetCookie

![Screenshot from 2021-04-19 13-49-27](https://user-images.githubusercontent.com/38238305/115183312-805f1700-a116-11eb-9f6a-1b0b141555f4.png)

**Comment by anthonychu** [comment]
@mkarmark Could you please take a look?

**Comment by mkarmark** [comment]
The fix for this issue has been globally deployed. Let me know if you have any further concerns!

**Comment by hynjnk** [comment]
Looks good. Thanks for the fix!
![Screenshot from 2021-04-26 08-59-56](https://user-images.githubusercontent.com/38238305/116014159-d24ff180-a66e-11eb-84b8-32f3c36591dd.png)
