### ISSUE TITLE
App Settings creation in Azure Portal does not work at all

### ISSUE THREAD

**Issue by lbugnion** [Azure/static-web-apps#374]
Steps to repro:
- Open a Static Web app in Azure portal
- Go to Configuration
- Add an app setting, for example
  - AzureWebJobsStorage
  - {connection string}
- (in preview portal): Click save
Expected: App Setting is saved
Actual: App Setting appears to be saved for 2 seconds then it disappears

- (in public portal): Save button is disabled
- Click on Show Values -> the Save button is enabled
- Click Save
Expected: App Setting is saved
Actual: App Setting appears to be saved for 2 seconds then it disappears

https://user-images.githubusercontent.com/4922457/115230966-4e998080-a115-11eb-81eb-0b350c3a9a82.mp4

**Comment by stemixreal** [comment]
Hi @lbugnion , there are some restricted settings - AzureWebJobsStorage is one of them - #324

**Comment by lbugnion** [comment]
I see. In that case, is it documented anywhere, and why is there no error message? The current behavior is extremely confusing.

**Comment by anthonychu** [comment]
Docs should be updated soon. We're working on displaying a meaningful error instead of failing silently.

**Comment by jahlen** [comment]
Hi! I can just add that I also have experienced similar problems with the Application settings discarding my settings. This happens regardless of the names of the settings. If for example I add four settings, it may save only the first two. It seems to help to wait before clicking the Save button.

Here's an example:
https://youtu.be/O7cbfiabJno?t=2760

**Comment by jon-a-nygaard** [comment]
Hi @anthonychu @lbugnion, I am suggesting that this issue can be closed now.
The [documentation has been updated](https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints) by Anthony with a list of reserved prefixes, and the UI is displaying a meaningful error when trying to add and save such an application setting 🙂

**Comment by simonaco** [comment]
Closing as per @jon-a-nygaard suggestion. Thank you!
