### ISSUE TITLE
Cookies on requests are sent "randomly" to API functions

### ISSUE THREAD

**Issue by bgrainger** [Azure/static-web-apps#376]
If an Azure Functions API (for a Static Web App) includes a `Set-Cookie` header on the response, that cookie is provided "randomly" to future API requests, irrespective of what the browser actually sends (in a `Cookie` header) in an HTTP request to the API.

### Basic SWA setup

Create a new GitHub repository with an empty HTML file. Create Static Web App through Portal as per [these instructions](https://docs.microsoft.com/en-us/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript#create-a-static-web-app); for build presets select "Custom", set API to `/api`.
Create an `api` folder; in that folder, run `func init --worker-runtime dotnet` then create a new Azure function with `func new -t "HTTP Trigger" -n Test`.

### Function and Frontend

Create a simple C# function that reads the current value of the `test` cookie, and sets a new cookie if a `setcookie` query parameter is present: https://github.com/bgrainger/StaticWebAppCookies/blob/master/api/Test.cs
Create a simple JavaScript function in the HTML that makes repeated requests to the `/api/Test` endpoint, periodically setting a new cookie, and dumping the results into the current page: https://github.com/bgrainger/StaticWebAppCookies/blob/master/index.html

## Expected output

If you run `swa start` and `func start`, you will get the following output in the HTML:

```
API output:
Request Cookie = .
Request Cookie = .
Request Cookie = . Setting cookie to 3.
Request Cookie = 3.
Request Cookie = 3.
Request Cookie = 3. Setting cookie to 6.
Request Cookie = 6.
Request Cookie = 6.
Request Cookie = 6. Setting cookie to 9.
Request Cookie = 9.
Request Cookie = 9.
Request Cookie = 9. Setting cookie to 12.
```

Every third request instructs the API to set a new cookie, and then subsequent requests send that cookie to the backend.

## Actual output

Push the code to GitHub so that it gets deployed to Azure. My example site is at https://nice-grass-0c7fb261e.azurestaticapps.net/. It produces this output:

```
API output:
Request Cookie = .
Request Cookie = .
Request Cookie = . Setting cookie to 3.
Request Cookie = 3.
Request Cookie = .
Request Cookie = . Setting cookie to 6.
Request Cookie = 3.
Request Cookie = 6.
Request Cookie = . Setting cookie to 9.
Request Cookie = .
Request Cookie = 3.
Request Cookie = 6. Setting cookie to 12.
Request Cookie = 12.
Request Cookie = 12.
Request Cookie = 3. Setting cookie to 15.
Request Cookie = .
Request Cookie = .
Request Cookie = . Setting cookie to 18.
Request Cookie = 18.
Request Cookie = 18.
Request Cookie = 15. Setting cookie to 21.
Request Cookie = 12.
Request Cookie = .
Request Cookie = 18. Setting cookie to 24.
Request Cookie = 21.
Request Cookie = 21.
Request Cookie = 21. Setting cookie to 27.
Request Cookie = 24.
Request Cookie = 9.
Request Cookie = 27. Setting cookie to 30.
```

Note that due to https://github.com/Azure/static-web-apps/issues/371, the `Set-Cookie` header actually includes `expires=Mon, 01 Jan 0001 00:00:00 GMT;` so it's never actually set in the browser. That is, the web browser never actually sends a `Cookie` header to the Static Web App API. Yet the API is reporting that it's set on most requests. (If you were to fix that `expires` setting on the cookie you would still find that the cookies read by the API are "random" and unassociated with the actual requests.)

If the cookie is used for authentication, this could be a serious security issue, as logged-in users might see data for other users (because the cookies sent by the browser are unrelated to the cookies processed by the Functions API backend).

On a minor note, it's a little frustrating that local development doesn't reproduce this problem; it only happens when it's deployed to Azure.

**Comment by bgrainger** [comment]
There's no problem inside a standalone Azure Functions App (without the Static Web App proxy): https://cookie-test-func.azurewebsites.net/api/Home deployed from https://github.com/bgrainger/FunctionsCookies.

**Comment by anthonychu** [comment]
Thanks @bgrainger we'll look into this. /cc @mkarmark

**Comment by mkarmark** [comment]
The fix for this issue has now been globally deployed, and customers should no longer experience this behavior. Let me know if there is still any unexpected behavior regarding the function cookies!

**Comment by bgrainger** [comment]
Looks good; thanks!
