### ISSUE TITLE
Cannot add azure_static_web_apps_api_token value on Deploy Azure Static Web App release task

### ISSUE THREAD

**Issue by cdalto** [Azure/static-web-apps#377]
I am trying to deploy some static code compiled as an artifact by a build pipeline in Azure DevOps. I found an "Azure Static Web App" release pipeline task that I wanted to use to deploy the artifact to Azure Static Web App. The YAML in the example for building and releasing has a field for the token:
```
    env:
      azure_static_web_apps_api_token: $(deployment_token)
```

However, the UI for this release step does not have a place to add the token:
<img width="1666" alt="Screen Shot 2021-04-20 at 11 58 06 AM" src="https://user-images.githubusercontent.com/7283577/115436280-6bdf5500-a1d0-11eb-9a61-56a1c1ab63f6.png">

I have tried adding a `azure_static_web_apps_api_token` variable in the Variables tab with the deployment token from my hosted Azure Static Web App, but I still receive the following error on release:
```
azure_static_web_apps_api_token was not provided.
The azure_static_web_apps_api_token is required for deploying content. If you'd like to continue the workflow run without deployment, add the workflow configuration skip_deploy_on_missing_secrets set to true
```

**Comment by anton-brass** [comment]
same here... how to use that ?

**Comment by anthonychu** [comment]
We are working on a fix for this. https://github.com/microsoft/azure-pipelines-tasks/pull/14798

**Comment by krisnuttall** [comment]
This linked fix now shows as merged to master. When will it be available for use?

**Comment by anthonychu** [comment]
@krisnuttall We're trying to get an ETA from our partners in Azure DevOps. Will let you know if we get an estimate.

**Comment by anthonychu** [comment]
The fix should now be deployed. 
![image](https://user-images.githubusercontent.com/3982077/122510545-9d9b4f00-cfba-11eb-80ed-eba890adcd49.png)
