### ISSUE TITLE
Redirect removing trailing slash

### ISSUE THREAD

**Issue by jahlen** [Azure/static-web-apps#381]
Hi!

I have a multi-lingual website and I wish to automatically redirect / to /en/
The trailing slash is important because of SEO purposes.

This is from my staticwebapp.config.json config:
``` json
    "routes": [
        {
            "route": "/",
            "redirect": "/en/",
            "statusCode": 302
        }
    ],
```

As you can see here, the trailing slash is not included. How can I make it redirect to /en/?

![image](https://user-images.githubusercontent.com/11652570/116052320-c9b0e880-a679-11eb-854a-f2801a9a4dff.png)

Here is my website:
https://www.how2code.info

**Comment by anthonychu** [comment]
@mkarmark Could you please take a look?

**Comment by miwebst** [comment]
Hey @jahlen, this is a bug, we will get a fix ready for this.

**Comment by jahlen** [comment]
Hi! This works now. You can close the issue.
