### ISSUE TITLE
Azure AD B2B Integration

### ISSUE THREAD

**Issue by gavinmorrison** [Azure/static-web-apps#383]
I am working with a client who has >1000 guests (External Identities) from >100 different tenants within their Azure AD directory; these guests are from their clients and partners.

The client now has a requirement to publish a static web app to a group of these users. Azure Static Web Apps appears to be great solution for this, and it's trivial for me to integrate Azure AD authentication. However, I don't want to have to re-invite those users and manage them separately through Static Web Apps, as they already exist as guests in the tenant.

Are there plans for a better / tighter integration with Azure AD? Ideally, I would just be able to specify a security group in Azure AD in the route definition.

**Comment by mkarmark** [comment]
Yes, this is definitely in the works for the future. We can keep you posted as we get more concrete details on an ETA.

**Comment by gavinmorrison** [comment]
That's fantastic, do you have an approximate ETA for planning purposes? Is it something we can expect this calendar year?

**Comment by miwebst** [comment]
Hey @gavinmorrison , this is available now, give it a try and let us know what you think! https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad
