### ISSUE TITLE
[Question] Why automatically attach SSL certificate?

### ISSUE THREAD

**Issue by komayama** [Azure/static-web-apps#385]
When create custom domain in Static Web Apps and access to site, there is SSL certificate. I checked which certificate use in Static Web Apps. This SSL certificate published by the Digcert.
Is this design to attach automatically the Digcert SSL certificate when create custom domain on Static Web Apps?

![image](https://user-images.githubusercontent.com/24888431/116327284-6baf0d00-a801-11eb-9fcd-0d9276bd469e.png)

**Comment by anthonychu** [comment]
Yes. The free certificates that Static Web Apps provides are currently supplied by DigiCert.

**Comment by komayama** [comment]
@anthonychu 
Thank you for quick response.
I'm appreciate if you can answer. I think this custom domain feature that automatically to attach free certificate is under use managed certificate the following document. Is this correct processing?

https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate#create-a-free-managed-certificate-preview

**Comment by miwebst** [comment]
So that link is for the free certificate feature available to App Service users. That is separate from Static Web Apps. With Static Web Apps, all traffic is HTTPS only and the certificate for your site or your custom domain is managed for you by the service.
