### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by cirzoltan** [Azure/static-web-apps#386]
I'm trying to add an API proxy to my SWA but I get a HTTP 413 when trying to send requests with payload above 30MB.

According to the docs 100MB should be possible with Azure functions (and I'd assume unlimited for proxying?) but I couldn't find any way to achieve this with either Node or Dotnet backends.

The closest I got was trying to set the FUNCTIONS_REQUEST_BODY_SIZE_LIMIT environment variable app settings, but it gets immediately erased.

That 30 to 100MB bump could mean the difference between me being able to use SWA for this project or not.

**Comment by miwebst** [comment]
Hey @cirzoltan, we will look into this but likely this size payload would not be supported. Is the goal to use this api to upload something to storage?

**Comment by cirzoltan** [comment]
The goal is to allow authenticated users to upload files for processing to another (non SWA) API managing a compute cluster. 
The only role the SWA back-end is supposed to play is to authenticate the user and tack on a header with a subscription key for the compute API.
I'm trying to accomplish this using a simple setup in the proxies.json file (I'm not even using any functions c# or nodejs), but ran into the request size issue mentioned above.

**Comment by cirzoltan** [comment]
We went for a different solution.
