### ISSUE TITLE
Queue and timer triggers not supported on API

### ISSUE THREAD

**Issue by alanta** [Azure/static-web-apps#389]
I'm building an open source app to handle comment submission and approval on JamStack sites: [Bolt Comments](https://github.com/alanta/bolt-comments). This is a React app with C# functions.

I'm using a storage account to hold the data and was expecting to use storage queues to decouple invocation of out-bound web hooks from the incoming API calls. This works great in local testing with the SWA CLI so I was fully expecting this to work when deployed to Azure as well, but I'm getting an error while building the project in a GitHub action:

> Error in processing api build artifacts: the file 'NotifyNewComment/function.json' has specified an invalid trigger of type 'queueTrigger' and direction ''. Currently, only httpTriggers are supported. Visit https://github.com/Azure/azure-functions-host/wiki/function.json for more information.

The build output is [here](https://github.com/alanta/bolt-comments/runs/2452218645?check_suite_focus=true#step:4:212)

* The documentation linked to is not relevant for the error; it actually lists queue triggers as valid triggers.
* I've been unable to find any documentation on what function triggers are actually supported

So, I was fully expecting the queue trigger to work as it does with 'regular' functions projects. As a fallback, I tried to add a timer trigger but found that was not available either.

Are there plans to support other trigger types on the API?

**Comment by anthonychu** [comment]
We currently only support HTTP APIs. See [this page](https://docs.microsoft.com/azure/static-web-apps/apis#constraints) for more details.

@miwebst Can we update the help link to: https://docs.microsoft.com/azure/static-web-apps/apis#constraints

There are plans to allow you to use other function apps if the function apps provided by Static Web Apps do not meet your needs.

**Comment by alanta** [comment]
That's too bad. I was really hoping for an all-in-one solution for (relatively) simple web apps. 

I think this means that durable functions will not work either?

**Comment by miwebst** [comment]
Correct, Durable functions will not work either. Hopefully the solution Anthony has alluded to is not too much overhead.

**Comment by alanta** [comment]
@anthonychu any idea when support for using other function apps will be available?

**Comment by anthonychu** [comment]
@alanta It's available now in the new Standard tier: https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own

**Comment by alanta** [comment]
Thanks for the update @anthonychu

**Comment by remcohuijser** [comment]
I would like to propose this issue is reopened. Using your own API can work around the problem of missing timer triggers, but as far as I can see you lose the ability to deploy your SWA with front-end and back-end together (for example to staging).

**Comment by maersk96** [comment]
When will timerTriggers be available?
