### ISSUE TITLE
Azure static web app with Application Insights ARM template

### ISSUE THREAD

**Issue by sayanghosh123** [Azure/static-web-apps#394]
I am trying to get an automated deployment for SWA going with bicep. I understand there are not official ARM templates, but there are working examples provided in this repository (which are working). What I have not been able to do yet is to provision an App Insights resource and connect to the SWA similar to how it can be done using the UI. I tried the export template option but seems that doesn't work for SWA yet. Is there a template available which we can use?

**Comment by miwebst** [comment]
Hey @sayanghosh123, I'd recommend taking a look at this thread. There is a bug that is preventing this from working and the fix is rolling out. Once the fix is out you will be able to run a very similar template but use the app insights key as the app setting. https://github.com/Azure/static-web-apps/issues/384

**Comment by sayanghosh123** [comment]
Hwy @miwebst - Thanks for your reply. I've looked at that and actually made my Bicep code from that ARM 👍. I have also seen the bug which should be resolved soon. Are you saying that after it's resolved -

- we can set up an AppInsights resource (+ a LWP which AppInsights will need) independently and retrieve its key
- Populate that key in the app setting with a key name APPINSIGHTS_INSTRUMENTATIONKEY
- That will set up the connection between them 

Is that the right interpretation?

**Comment by miwebst** [comment]
Yup exactly! This is true for any app settings that you need to make available to the function app.

**Comment by sayanghosh123** [comment]
Thanks! We will wait for that fix to land. My understanding is that would be available soon. Thanks for your help and guidance on this.

**Comment by miwebst** [comment]
This should be available now!

**Comment by sayanghosh123** [comment]
Just tested this morning and it worked perfect! Thanks for the follow through!
