### ISSUE TITLE
Blazor with SWA Authentication - Redirect issue 

### ISSUE THREAD

**Issue by jhueppauff** [Azure/static-web-apps#396]
Hey Folks, 

first of I am not sure if this is the right repo or if this is a Blazor related issue. 

I start to see an issue when using "Navigation.NavigateTo($"/.auth/login/github);" to redirect to the login endpoints.
Blazor changes the url but it seems blazor tries to serve it (HTTP 404). So maybe the route is interpreted wrong?
![image](https://user-images.githubusercontent.com/20532954/116866245-5d9b2b00-ac0b-11eb-8d72-4da0917dab0c.png)

When I actively refresh the page it will call the authentication backend without an issue.

My route.json looks like this:
```json
{
    "routes": [{
            "route": "/api/*",
            "allowedRoles": ["authenticated"]
        },
        {
            "route": "/*",
            "serve": "/index.html",
            "statusCode": 200
        }
    ]
}
```

I use a custom component in the app.razor to redirect when the user is unauthorized. 
```csharp
<CascadingAuthenticationState>
    <Router AppAssembly="@typeof(Program).Assembly">
        <Found Context="routeData">
            <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                <NotAuthorized>
                        <RedirectToLogin />
                </NotAuthorized>
            </AuthorizeRouteView>
        </Found>
        <NotFound>
            <LayoutView Layout="@typeof(MainLayout)">
                <p>Sorry, there's nothing at this address.</p>
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

```csharp
@inject NavigationManager Navigation

@code {
    protected override void OnInitialized()
    {
        Navigation.NavigateTo($"/.auth/login/github?post_login_redirect={Uri.EscapeDataString(Navigation.Uri)}");
    }
}
```

Any idea what I am doing wrong? If I can recall correctly this worked some days ago. Not sure though.

**Comment by miwebst** [comment]
Do you mind sharing the url so we can try to repro this? Or share the network trace to see if the service worker is responding or if it is the backend?

**Comment by anthonychu** [comment]
@jhueppauff Can you try setting `forceReload` to `true`? https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.navigationmanager.navigateto

**Comment by jhueppauff** [comment]
When I set it to true it works. Thanks :) 

Should I still provide the url to repo it or is this a know issue/design behavior? :)

**Comment by anthonychu** [comment]
This is expected behavior for Blazor and other frontend frameworks. The auth URLs are server-side routes and many frameworks' client-side routers intercept navigation requests by default. You might need to make a small change to ensure the requests reach the server.

**Comment by jhueppauff** [comment]
Alright thanks.
