### ISSUE TITLE
An unknown exception has occurred while uploading (redux)

### ISSUE THREAD

**Issue by riverar** [Azure/static-web-apps#397]
During build/deployment of a very simple SWA, the pipeline throws error `An unknown exception has occurred while uploading`.

Snippet:
```
---End of Oryx build logs---
Function Runtime Information. OS: Linux, Functions Runtime: v3, Node version: 12.X
Finished building function app with Oryx
Zipping App Artifacts
An unknown exception has occurred while uploading

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

Pipeline logs: https://github.com/riverar/azure-swa-repro-1/runs/2494881586?check_suite_focus=true
Repository (as of c40926d): https://github.com/riverar/azure-swa-repro-1/tree/c40926d26e0fce2255c174ce44a015aebd39af8d

Be sure to `git checkout c40926d` as I intend to continue troubleshooting.

Probably related: #192

**Comment by riverar** [comment]
Removing the `custom-module` I added resolves. <shrug>

There's something going on with npm dependencies; having similar troubles with these local dependencies in another SWA deployment as well.

Actions run https://github.com/riverar/azure-swa-repro-1/runs/2495040681?check_suite_focus=true
Commit https://github.com/riverar/azure-swa-repro-1/commit/1a2c1237f5e3bd7242e20a49e92ab7ad270ae0ee

**Comment by miwebst** [comment]
Hey @riverar , we think we understand the problem and are investigating a solution. Thanks for sharing!

**Comment by miwebst** [comment]
@riverar are we good to close this? The fix went out and should mitigate the issue.

**Comment by riverar** [comment]
@miwebst Yep, all good. Thanks again.

**Comment by stunney** [comment]
I just hit this issue on a private repo

```
---End of Oryx build logs---
Finished building app with Oryx
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
Copying 'staticwebapp.config.json' to build output
Zipping App Artifacts
Done Zipping App Artifacts
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Uploading build artifacts.
An unknown exception has occurred while uploading

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```
