### ISSUE TITLE
Oryx built the app folder but was unable to determine the location ...

### ISSUE THREAD

**Issue by mobicycle-consulting** [Azure/static-web-apps#398]
_**Oryx built the app folder but was unable to determine the location of the app artifacts. Please specify the app artifact location through the GitHub workflow file.**_

This message is unclear and not written in simple English. What exactly do you mean by "app artifacts"?

_**For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/**_

This webpage is outdated.

**Comment by diberry** [comment]
Please add link to your repo and branch.

**Comment by mobicycle-consulting** [comment]
SOLUTION: This section was missed during setup. The section appeared at the bottom of the screen. I re ran after updating the .yml file. It did not work. We deleted the app then created a new version with React selected. It worked.

_In the Build Details section, add configuration details specific to your preferred front-end framework.

No Framework
Angular
React
Vue
Select React from the Build Presets dropdown
Keep the the default value in the App location box
Clear the default value from the Api location box
Type build in the App artifact location box_
