### ISSUE TITLE
CNAME only for domain verification

### ISSUE THREAD

**Issue by mobicycle-consulting** [Azure/static-web-apps#399]
Domain verification is by CNAME only. It requires setting the name field to www and data field representing Azure's domain.

The name field for www could already be pointing to a different domain.

Domain verification by TEXT would avoid this problem.

**Comment by anthonychu** [comment]
We're working on adding TXT record validation to support this scenario. Hope to have it available soon.

**Comment by lotz** [comment]
What are the odds? Glad to hear this is now supported.

<img width="1076" alt="root_domain" src="https://user-images.githubusercontent.com/3892627/118067931-7de78a00-b36f-11eb-8dff-c7374815d32b.png">
