### ISSUE TITLE
Canceling Facebook Auth leads to error page

### ISSUE THREAD

**Issue by johnpapa** [Azure/static-web-apps#40]
Steps to reproduce:

1.  auth with facebook
1. click cancel (dont authorize fb)
1. it bring me to this page

![image](https://user-images.githubusercontent.com/1202528/83375005-7962d500-a39b-11ea-8b73-aece3784441d.png)

```
{"code":401,"message":"An error of type 'access_denied' occurred during the login process: 'Permissions error'"}
```

It should bring me back to my app

**Comment by mkarmark** [comment]
Hi @johnpapa,

Thanks for using Azure Static Web Apps! We have identified the issues, and are working on a fix, which should be out soon!

**Comment by mkarmark** [comment]
Hi @johnpapa 

This issue has been resolved in our latest release. Thanks for your feedback!
