### ISSUE TITLE
Uploading plain html/css webpage

### ISSUE THREAD

**Issue by Exitare** [Azure/static-web-apps#405]
I am trying to upload a plain html/css webpage without any framework. 
I use the default action created by the azure pipeline.

Although no dist folder is given or required, i receive this issue:

Oryx built the app folder but was unable to determine the location of the app artifacts. Please specify the app artifact location through the GitHub workflow file.

I don't know what to do. 
This is my action:

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.xxx }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/website" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.xxx }}
          action: "close"

Is there something wrong on my end ? How to i tell the action that there is no output directory needed ?

**Comment by stemixreal** [comment]
Hi @Exitare , I'm doing the same thing myself so take an interest in questions where no framework is used.

Probably, your problem is you haven't copied your html/css source files to the folder "website" which is specified by - app_location: "/website" # App source code path

I hadn't used devops for this so I quickly tried it out. Here is a [website](https://proud-desert-0b0e2781e.azurestaticapps.net/) when built with the html & css in the \website folder.

So you either need to move your files to the website folder or remove "website" -  app_location: "/" # App source code path

**Comment by Exitare** [comment]
Hi @stemixreal,
thanks for your response. I am quite sure all of my html/css and related other static files are in the /website folder. Therefore, this shouldn't be an issue. 

Anyways, I changed the path to "/".
I still receive the same issue, which is:
---End of Oryx build logs---
65
Oryx built the app folder but was unable to determine the location of the app artifacts. Please specify the app artifact location through the GitHub workflow file.

**Comment by miwebst** [comment]
Hey @Exitare, does the website folder have a package.json in it? From your logs it seems like Oryx is trying to build something. We have just added the skip_app_build command to DevOps (it may take a few weeks before it is rolled out) but you could also use that to force Oryx not to run in the future.
