### ISSUE TITLE
Automatic cache busting? 

### ISSUE THREAD

**Issue by diberry** [Azure/static-web-apps#406]
Does SWA do any automatic cache busting on deploy for the client-side app - or is this still something we have to add into the client for each individual app?

**Comment by miwebst** [comment]
Static Web Apps uses e-tags for client side caching. You can see these headers coming back on the responses. When you update your site, we will change these and any client that supports e-tag caching will invalidate the cache automatically:

Response headers: 
etag: "65982876"
