### ISSUE TITLE
Files with special characters in their name not served

### ISSUE THREAD

**Issue by stephtr** [Azure/static-web-apps#41]
First of all, thank you for your work, Azure Static Web App is exactly what I was waiting for!

When testing, I noticed, that files with special characters (like `[`, `]` (as being used by Next.js' dynamic routes) or umlauts) in their filename aren't being served. I have uploaded an example to https://white-island-0f55a8203.azurestaticapps.net/.

**Comment by takekazuomi** [comment]
Also, Japanese characters aren't being served too. May be caused by URL escaped chars. Since URL escaping is a common feature, this issue is critical for hosting an existing static site. 

https://gentle-sand-0f46f010f.azurestaticapps.net/

**Comment by Misiu** [comment]
same with files that contain space in the name (shown in @takekazuomi example)
This works without a problem with other hosting providers but not here.

**Comment by miwebst** [comment]
This should be fixed now! Let us know if you have any more issues with special characters.

**Comment by takekazuomi** [comment]
It works fine now. quick job great!

**Comment by stephtr** [comment]
Thank you!
Since all my special character related issues are now solved and takekazuomi's test case is also working, I think it should be fine.
