### ISSUE TITLE
Globally Available - Action not at 1.0?

### ISSUE THREAD

**Issue by hjfitz** [Azure/static-web-apps#411]

**Comment by anthonychu** [comment]
Should be using `@v1`. I think we need to create a GitHub release. Thanks for letting us know. @mkarmark @miwebst 

Docs updates should be coming today.

**Comment by miwebst** [comment]
This is released, you can find v1 in the marketplace.

**Comment by jeroenvdmeer** [comment]
Where can I find more information about the changes between releases v0.0.1 and v1?

**Comment by miwebst** [comment]
The 2 releases are the same. We renamed and republished the existing action for consistency as the product went GA and we wanted to get rid of -preview from the v0.0.1-preview. v0.0.1-preview will continue to be maintained for backwards compatibility but you can safely update your workflows to use v1. All newly created workflow files will also use v1.

**Comment by hjfitz** [comment]
Thank you!
