### ISSUE TITLE
Custom auth not yet working?

### ISSUE THREAD

**Issue by liprec** [Azure/static-web-apps#413]
First thanks for including custom auth to the GA version of SWA, but somehow I am running into an issue:
As soon as I add the code snippet for AAD (https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#tabpanel_1_aad&WT.mc_id=DP-MVP-5003419) to my `staticwebapp.config.json` file I am getting a 404 on the `/.auth/login/aad` url.

So it looks like there is something not working, but I have no clue what: is there a sample application/walkthrough available with custom (aad) authentication or any other way to debug what is misconfigured?

For completeness: the SWA is upgraded to a standard SKU, configured to use a system identity with access to a key vault and the clientid and secret link are set as application settings.

**Comment by miwebst** [comment]
Hey @liprec, you may be running into an issue in our docs that we are working to fix. The docs incorrectly suggest to have this in your config file:

```
"auth": {
    "azureActiveDirectory": {
      "registration": {}
}
}
```

you really need:

```
"auth": {
   "identityProviders": {
    "azureActiveDirectory": {
      "registration": {}
     }
   }
}
```

Notice the identityProviders section. If you look at the OIDC section it is correct there. You could be running into this or a different problem, feel free to share your default hostname and we can investigate as well.

**Comment by liprec** [comment]
Hi @miwebst, that helps. Now I can login, but getting a 403 error `We need an email address or a handle from your login service`. Probably need some extra config regarding the application and/or my user, any idea?

**Comment by mkarmark** [comment]
Azure Active Directory features versioned endpoints which affect how your registration is configured. If you are using AAD v1 (the issuer endpoint does not end with "/v2.0"), then you need to add the following `userDetailsClaim` entry to your configuration in the `"azureActiveDirectory"` object.

```json
"azureActiveDirectory": {
  "registration": { ... },
  "userDetailsClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" 
}

Note that we are working to update the docs with this info as well, it should be published by the end of the day!

**Comment by liprec** [comment]
Thanks you all: it is working with `https://login.microsoftonline.com/<TENANT_ID>/v2.0` as issuer url.
And is it correct that I can remove the `clientSecretSettingName` as the identity is turned on? Or am I hitting a cached version?

**Comment by javier-romera** [comment]
There is something is still not clear to me. How to set only the AAD for a tenant.

I added the setup like in the link and it requests a proper login in my tenant. But still accepts any AAD user.
If I set "/.auth/login/aad" to a StatusCode 404 like with other providers, it seems that it ignores it and any non-authorized user can access even if the route "/" is only accessible by "authenticated" users.

I am sure I am doing something wrong.

Is there a simple example file on how to configure **only one AAD tenant**? I cannot find it. 

Thanks.

**Comment by liprec** [comment]
If I use the following `staticwebapp.config.json` it is working only with my tenant. And make sure that the App registration used to authenticate is set to `Accounts in this organizational directory only (tenant only - Single tenant)` to disable multitenant logins.

```
{
  "routes": [
    {
      "route": "/*",
      "allowedRoles": ["authenticated"]
    },
    {
      "route": "/api/*",
      "allowedRoles": ["authenticated"]
    },
    {
      "route": "/login",
      "rewrite": "/.auth/login/aad"
    }
  ],
  "responseOverrides": {
    "401": {
      "redirect": "/login",
      "statusCode": 302
    }
  },
  "auth": {
    "identityProviders": {
      "azureActiveDirectory": {
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/<tenantid>/v2.0",
          "clientIdSettingName": "STATICWEBCLIENTID"
        }
      }
    }
  }
}
```

**Comment by javier-romera** [comment]
Thanks for your config file. It was like mine, except that I was using "/" instead of "/\*".
But this is the problem. I cannot use "/\*" and "/api/\*". It complains and does not upload.
At least on an Azure DevOps repository. Maybe it works on Github.


    Encountered an issue while validating staticwebapp.config.json:
    A route is covered up by a wildcard route and would not be evaluated.
    Route: /api/*, Wildcard(s): /*. Please either delete or move the unreachable route.


I think this is an error. Using only "/" lets open for everybody all other pages.
I am sorry for hijacking your issue report. If I do not get an answer I will create my own issue request.

**Comment by liprec** [comment]
As my authentication is still working I can conclude that the identity is working and I can leave out the `clientSecretSettingName` value. And will close this issue.
