### ISSUE TITLE
Mono Repo support for staticwebapp.config.json

### ISSUE THREAD

**Issue by joelcoxokc** [Azure/static-web-apps#416]
I have built a Mono repo using Angular and Nx. 

I would like to be able to reference a different `staticwebapp.config.json` per app. 

I see that the `staticwebapp.config.json`is automatically looked up inside the `app_location`. However, I am unable to change the app_location to anything other than `/` inside of an angular project. Otherwise the github action throws errors. 

Any help or direction on this would be great. Thanks.

**Comment by miwebst** [comment]
Hey @joelcoxokc,

Do you mind sharing the project structure and the error you are seeing when the `app_location `is not `/` ? You should be able to have the `app_location` be other directories as well.

**Comment by joelcoxokc** [comment]
@miwebst 

Here is my configuration

```
with:
    azure_static_web_apps_api_token: ***
    repo_token: ***
    action: upload
    app_location: apps/app1
    output_location: dist/apps/app1
    app_build_command: npm run build:app1:qa
```


Here is my project structure

```
package.json
angular.json
dist/apps/*
apps/
    app1/
        src/
            staticwebapp.config.json
            index.html
    app2/
        src/
            staticwebapp.config.json
            index.html
```

I tried setting `app_location` to `apps/app1` but I get the following error.

```
Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx
Failed to find a default file in the app artifacts folder (apps/oikos). Valid default files: index.html,Index.html.
If your application contains purely static content, please verify that the variable 'app_location' in your workflow file (located in .github/workflows) points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.
```

**Comment by joelcoxokc** [comment]
@miwebst  I also tried setting `app_location` to `apps/app1/src`

However, the build command must be run at the root. So the app doesn't get built when the `app_location` is not at the root.

**Comment by joelcoxokc** [comment]
I tried setting `routes_location` to `apps/app1/src` and get the following error

```
routes_location: route file 'apps/app1/src/routes.json' could not be found.
```

Is it possible to have a `config_location`. I see that yall just fixed this same issue with the `static-webb-apps-cli` tool.

**Comment by miwebst** [comment]
I see, so you need to build at the root but your app location is at a sub directory. We can make the routes_location work for staticwebapp.config.json too to unblock this scenario. Lets close this one and use the other issue for tracking.

**Comment by joelcoxokc** [comment]
Great Sounds good!
