### ISSUE TITLE
Azure Functions and staging details: limited regions

### ISSUE THREAD

**Issue by bmaruyama** [Azure/static-web-apps#417]
I had hoped that general availability would allow creation of Azure Static Web Apps in more regions. In Canada, several industries have rather strict data governance regulations.  When will we see broader deployment options so that the Azure Functions can be located in the same regions as the associated data (e.g. Cosmos DB)?

**Comment by anthonychu** [comment]
For full control of your Azure Functions app, including its region, we recommend you use the [bring your own function app](https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own) feature of the new Standard plan.

**Comment by bmaruyama** [comment]
This flexibility is certainly useful, but Azure State Web Apps hangs its hat on its ease of use. So, having to manage Azure Functions deployment separately and having it only supported in production adds a few extra hurdles to an otherwise excellent product.
