### ISSUE TITLE
Possibility to enforce trailing slashes

### ISSUE THREAD

**Issue by stephtr** [Azure/static-web-apps#42]
It would be nice, if one could enforce trailing slashes at least for specific urls. In my case I would like 
to forward `/admin` to `/admin/`, but doing that via the `routes.json` file results in a redirection loop.

**Comment by anthonychu** [comment]
I agree that this would be a nice feature. Often this comes up with default pages in subfolders that use relative URLs in links and access resources (like images) with relative URLs. Example:

If there's a file at `/foo/bar/index.html`, it can be accessed at all of the following locations: 

* `/foo`
* `/foo/`
* `/foo/index.html`

If there are any relative URLs in the page, those URLs will not work when accessing the page using `/foo`. To deal with this, most web servers will redirect `/foo` to `/foo/`.

Here's an example here:

`/foo/index.html` has a link `<a href="bar.html">relative link to bar.html</a>`:

* Link works: https://delightful-island-0d63ac010.azurestaticapps.net/foo/index.html
* Link works: https://delightful-island-0d63ac010.azurestaticapps.net/foo/
* Link doesn't work: https://delightful-island-0d63ac010.azurestaticapps.net/foo
    - without the trailing slash, the base URL is `https://delightful-island-0d63ac010.azurestaticapps.net/` which causes the relative link to fail

@stephtr Is this the same scenario you're running into, or do you have other reasons to need this redirect?

**Comment by stephtr** [comment]
That's more or less exactly my use case.

**Comment by SamBroner** [comment]
Could you do two redirects?
```
redirect /foo => /temporary/
redirect /temporary/ => /foo/
```

**Comment by eat-sleep-code** [comment]
Did anyone ever getting a resolution on this?   Encountering the same issue.

**Comment by kkankala** [comment]
Any update on this Issue please?

**Comment by rickersilva** [comment]
I'm running into this same problem. I posted a stackoverflow question on this. https://stackoverflow.com/questions/70254772/github-not-deploying-the-code-i-push-to-azure-static-web-app

Is there anyway to make Azure static web apps to work as expected. in VSCODE running locally, the local servers adds the trailing slash automatically.

**Comment by joeclarkejacobs** [comment]
Just discovered this issue - wondering if anyone has figured out a workaround, or better yet, if Microsoft are planning to fix the issue?

**Comment by rickersilva** [comment]
For a cool workaround take a look here. No definitive solution still because we depend on Microsoft for this.

https://stackoverflow.com/questions/70254772/azure-static-web-apps-not-loading-page-resources-correctly-css-or-javascript-fi

**Comment by joslinmicrosoft** [comment]
Hi all, thank you for your feedback and patience on this request. We have added the ability to configure trailing slash behavior with the `trailingSlash` configuration in your `staticwebapp.config.json` file. The documentation can be found here: https://docs.microsoft.com/azure/static-web-apps/configuration#trailing-slash. Please let us know if this works for your use cases!

**Comment by MichelSakr** [comment]
Hi
Where is this json file located on an Azure storage static site?! @joslinmicrosoft 
Thanks

**Comment by stephtr** [comment]
I don't think these settings map one on one to Azure storage static sites.

> Please let us know if this works for your use cases!

Thank you all for your work! I think it's time to close this issue.
