### ISSUE TITLE
CI/CD not running, 14+ hours in Queue

### ISSUE THREAD

**Issue by smarigowda** [Azure/static-web-apps#421]
![image](https://user-images.githubusercontent.com/1831259/118435281-97bdff80-b6d6-11eb-8111-8a197e9c1685.png)

**Comment by anthonychu** [comment]
Looks like there was an [incident](https://www.githubstatus.com/incidents/zbpwygxwb3gw) with GitHub Actions earlier today which may have affected your app. Can you [cancel](https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow) those workflows an either re-run them or trigger new ones by creating another commit?

**Comment by smarigowda** [comment]
Thank you. This is now resolved.
