### ISSUE TITLE
404 error when using custom authentication.

### ISSUE THREAD

**Issue by TellonUK** [Azure/static-web-apps#422]
I am using Azure B2C as a OpenID Connect provider, and have used the example auth configuration from [https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom ). I have used the B2C setup with MSAL several times without issue, and testing the B2C user flow works without issue.

When I launch the static website i get a 404 error on the /.auth/login/myProvider page. Is there anything missing in the documentation, my configuration or a way to troubleshoot the issue? (No errors in the github deployment action)

I confimed the app/route works using the oob github identity provider.

My Config:

```
{
  "routes": [
    {
      "route": "/api/*",
      "allowedRoles": ["authenticated"]
    }
  ],
  "auth": {
    "identityProviders": {
      "openIdConnectProviders": {
        "azureb2c": {
          "registration": {
            "clientIdSettingName": "MY ID",
            "clientCredential": {
              "secretSettingName": "My Secret"
            },
            "openIdConnectConfiguration": {
              "wellKnownOpenIdConfiguration": "https://tenant.b2clogin.com/tenant.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_authSignIn"
            }
          }      
        }
      }
    }
  }
}
```

Error
`GET https://<site>/.auth/login/azureb2c 404`

**Comment by aaronpowell** [comment]
Is the GitHub repo public that I could take a look at?

**Comment by TellonUK** [comment]
Sure, just made one.

[https://github.com/TellonUK/azureswa](https://github.com/TellonUK/azureswa)
( I've setup a Azure SWA at [https://polite-desert-0bd142f0f.azurestaticapps.net/](https://polite-desert-0bd142f0f.azurestaticapps.net/) I just need to configure the env config for a demo b2c, will update here when that's done too )

**Comment by anthonychu** [comment]
In [staticwebapp.config.json](https://github.com/TellonUK/azureswa/blob/51e79736693338acd58f87934bda0f257ecf1675/staticwebapp.config.json#L12-L20):

```json
  "auth": {
    "identityProviders": {
      "openIdConnectProviders": {
        "azureb2c": {
          "registration": {
            "clientIdSettingName": "<SWACLIENTID>",
            "clientCredential": {
              "secretSettingName": "<SWASECRET>"
            },
            "openIdConnectConfiguration": {
              "wellKnownOpenIdConfiguration": "<SWAWELLKNOWN>"
            }
          }
        }
      }
    }
  }
```

The `clientIdSettingName`, `secretSettingName`, `wellKnownOpenIdConfiguration` properties are invalid.

Try removing the `<>` in the setting names:

```json
          "registration": {
            "clientIdSettingName": "SWACLIENTID",
            "clientCredential": {
              "secretSettingName": "SWASECRET"
            },
```

And create 2 [app settings](https://docs.microsoft.com/en-us/azure/static-web-apps/application-settings#using-the-azure-portal): one named `SWACLIENTID` containing the client ID, and one named `SWASECRET` containing the secret.

And for `wellKnownOpenIdConfiguration`, change `<SWAWELLKNOWN>` in the config file to the actual value of the issuer url.

\+ @mkarmark to take a look as well. There might be other issues here.

Regarding this:

> Not seeing any documentation on how to save an environment variable in the JSON file so that its picked up by the value in the Application Settings. (process.env.xxx works for the API but cant use that in JSON). 

@craigshoemaker I think the [app settings](https://docs.microsoft.com/en-us/azure/static-web-apps/application-settings#using-the-azure-portal) page might need to be updated now that app settings are no longer just for API apps.

**Comment by aaronpowell** [comment]
@anthonychu I wouldn't have thought that failing to get the values from config would result in a 404 on the auth provider, I'd have expected a 500

**Comment by TellonUK** [comment]
In my [staticwebapp.config.json](https://github.com/TellonUK/azureswa/blob/main/staticwebapp.config.json) I updated it to the suggested format.

```
{
  "routes": [
    {
      "route": "/api/*",
      "allowedRoles": ["authenticated"]
    }
  ],
  "auth": {
    "identityProviders": {
      "openIdConnectProviders": {
        "azureb2c": {
          "registration": {
            "clientIdSettingName": "SWACLIENTID",
            "clientCredential": {
              "secretSettingName": "SWASECRET"
            },
            "openIdConnectConfiguration": {
              "wellKnownOpenIdConfiguration": "https://glmtesting.b2clogin.com/glmtesting.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_authSignIn"
            }
          }
        }
      }
    }
  }
}
```

I also updated my SWA app settings to have keys SWACLIENTID and SWASECRET, using a @Microsoft.KeyVault value and then also the ClientID and Secret in plaintext. Neither resolved the issue. 

The [SWA](https://polite-desert-0bd142f0f.azurestaticapps.net/.auth/login/azureb2c)  site still has a 404 when you go to [/.auth/login/azureb2c](https://polite-desert-0bd142f0f.azurestaticapps.net/.auth/login/azureb2c)

When I have the auth key in my [staticwebapp.config.json](https://github.com/TellonUK/azureswa/blob/main/staticwebapp.config.json) the [/.auth/login/github](https://polite-desert-0bd142f0f.azurestaticapps.net/.auth/login/github) route also responds with a 404. Which I would expect, as per the [documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad) when you override a pre-configured provider by configuring an auth section the built in providers are disabled. This suggests the auth section of my [staticwebapp.config.json](https://github.com/TellonUK/azureswa/blob/main/staticwebapp.config.json) is being picked up. I can also confirm, if I remove the auth section from my [staticwebapp.config.json](https://github.com/TellonUK/azureswa/blob/main/staticwebapp.config.json)  then the [/.auth/login/github](https://polite-desert-0bd142f0f.azurestaticapps.net/.auth/login/github) route works again.

I have replicated the issue on two SWA's, in the East US 2 region using the above staticwebapp.config.json, both have the same 404 issue.

**Comment by mkarmark** [comment]
Hi @TellonUK, can you rename in the json "openIdConnectProviders" to "customOpenIdConnectProviders"? That should fix the issue. We realize the docs are leading people to incorrectly use "openIdConnectProviders" and are trying to get the fix out ASAP.

**Comment by TellonUK** [comment]
Thanks, That did the trick.
