### ISSUE TITLE
Deployment Failure Reason: An unknown error has occurred.

### ISSUE THREAD

**Issue by pmeems** [Azure/static-web-apps#423]
I'm trying to build and deploy a Blazor WASM application with Azure Functions as the back-end.
Yesterday I had no issues building and deploying it, but today it keeps failing at the deployment step.
Since the reason is `An unknown error has occurred.` and nothing else is reporting I'm not sure what to do next.
```
---End of Oryx build logs---
Function Runtime Information. OS: Windows, Functions Runtime: v3, .NET Core version: 3.1
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1461574(s)
Status: InProgress. Time: 15.2671687(s)
Status: InProgress. Time: 30.3909712(s)
Status: Failed. Time: 45.517795(s)
Deployment Failed :(
Deployment Failure Reason: An unknown error has occurred.
```

I've attached the log archive:
[logs_20.zip](https://github.com/Azure/static-web-apps/files/6500386/logs_20.zip)

The repo is private, but I can give you access if needed.

Locally I have no problem running my application.

**Comment by miwebst** [comment]
Hey @pmeems can you check if you are using any of the app settings listed in the constraints: https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints

**Comment by pmeems** [comment]
Thanks @miwebst 
I had `AzureWebJobsStorage` in my app settings. Not sure when I added it, at least a few weeks ago.
I removed it and now the deploy process continues.

It would be nice if the deployment step would tell that this is the problem, instead of `An unknown error has occurred.`

I'm closing this issue.

**Comment by miwebst** [comment]
Totally agree, we have a change in flight that will make these a little clearer (it will say something like deploying the function failed) but we are also working on some tooling to help surface these errors more easily.
