### ISSUE TITLE
staticwebapp.config.json being ignored

### ISSUE THREAD

**Issue by amkcs** [Azure/static-web-apps#424]
Hello,

I've looked through the open issues and I see two that are similar but have not solved my problem.  I'm experimenting with Azure Static Web Apps and working off of the Blazor template.  I followed the documentation's steps to clone the templated project and setup a GitHub workflow.  I am using VS 2019 and not VS Code for development, but I'm able to commit and push to a branch, merge back to main, and deploy to staging and production through the workflow properly.

I decided to start working on adding authentication and routing and removed the deprecated routes.json file and added a staticwebapp.config.json file in it's place (in the wwwroot folder, as recommended by the documentation).  I set the file to always copy to the output folder just so that I can see that it is placed where it is supposed to and that seems to work - it gets copied to the Client/bin/netstandard21/wwwroot folder.  I've also tried moving the file to the root Client folder to match the app_location, and it copies it to Client/bin/netstandard21, instead.  

To test the routing I added a second html page and configured the JSON file to serve that file, instead of index.html.  I also put a fallback where only images were allowed to be served; however, the second html page is never served and I can view the project's CSS file in the browser (it does not fallback to the html page). 

I uploaded the staticwebapp.config.json file to the checker in the awesome-azure-static-web-apps repository and the example URLs work as expected.  I don't have any roles defined in Azure, but my understanding is that by default anonymous is granted to all users.  I've also tried adding the anonymous role as an allowed role in the config file, but my site still does not respect the setting.

Here is the content in the staticwebapp.config.json:

{  
    "routes": [    
    {      "route": "/",      
           "serve": "/htmlpage.html",      
           "allowedRoles": ["anonymous"]    
    }  
    ],  
    "navigationFallback": 
    {    "rewrite": "htmlpage.html",    
         "exclude": [ "/images/*.{png,jpg,gif}" ]  
    }
}

**Comment by anthonychu** [comment]
staticwebapp.config.json has a different format than routes.json. It no longer uses the “serve” property. It should use “rewrite” instead. I think what is happening is that serve is being ignored in the rule; it’s still a valid rule that doesn’t do anything useful.

@mkarmark can we see if we can catch these issues during deployment? Could consider validating against the JSON schema too.

One more note about staticwebapp.config.json… it doesn’t need to be copied to the publish output folder. We look for it under app_location. It still works in those case because wwwroot is a sub folder under app_location.

**Comment by amkcs** [comment]
Thank you for your response.  I updated the staticwebapp.config.json file to use "rewrite" in the routes element and it worked when navigating the site after the deployment.  However, it still loads the CSS file when I navigate to the URL /css/app.css.  In the checker in the awesome-azure-static-web-apps repository, it shows that it should re-route to the htmlpage.html page, so I know that the config file is fine.  Am I missing anything in the fallback element that would cause that?

**Comment by anthonychu** [comment]
Based on the rules above, if you request /css/app.css, it doesn’t match the routing rule you defined so there are no routing rule in effect. The file exists and we serve it. Navigation fallback only comes into play if the file does not exist. Your app is behaving as designed.

The route checker utility doesn’t match the routing rules exactly. It appears you ran into 2 cases where they don’t match. @manekinekko is it possible to mark the tool as experimental?

**Comment by amkcs** [comment]
Yes, that's right.  I misread the [Fallback routes](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#fallback-routes) section.  I added a new rule to rewrite to the html file when the CSS file is requested and it worked.

Thank you for your help.  I'm going to close this issue.

**Comment by amkcs** [comment]
Sorry, I just reopened this to ask one more question related to a previous response of yours, @anthonychu.  About the staticwebapp.config.json file not needing to be copied to the output folder, whether I copy it to the output folder or not locally, my local instance is not respecting the rule when I run the project (either in Debug Mode or Release Mode).  Is that expected behavior because of the differences between running it in a local environment vs the environment present in the cloud when the app is built and deployed with the workflow?

**Comment by Azuredevmuc** [comment]
Hey all, first of all - thanks to all the work going into this project.
I'm working to add Auth as well by using the Blazor Starter Template.
I added the config proper, as mentioned here already.
But - it looks like, Blazor ignores the routing config. 
I added inside the app a page and tried to protect it by adding it to the config file.
But I'm still able to reach that page by using the Navigation in the App.
I then added to protect the /api/ path to be protected. This seems to protect the API to be used by non authenticated user.

My question: do i have to implement it in Blazor App itself - cause, as far as i understand, there is a routing inside?
Sry - i'm not a Blazor profesional yet.
Thanks for helping!
Ralf

Link to Project page: https://orange-rock-0ffc5e810.azurestaticapps.net/
Link to Github: https://github.com/Azuredevmuc/StaticWebAppBlazorDemo

**Comment by Azuredevmuc** [comment]
@amkcs - it looks like that either not VS Code support this yet, nor the CLI support the config file yet.
For CLI see more here: https://github.com/Azure/static-web-apps-cli/issues/205

**Comment by Azuredevmuc** [comment]
Okay all,
I found this nice article about how this is working with Blazor.
Since Blazor has it's own routing, it must be implemented another way round.
https://anthonychu.ca/post/blazor-auth-azure-static-web-apps/
My be, this helps others too.
BR
Ralf
