### ISSUE TITLE
401 on callback after login with Auth0 custom OpenID Connect provider

### ISSUE THREAD

**Issue by Skleni** [Azure/static-web-apps#425]
I'm trying to use Auth0 as a custom OpenID Connect provider as described [here](https://www.aaron-powell.com/posts/2021-05-13-using-auth0-with-static-web-apps/).

When I navigate to `/.auth/login/auth0`, the redirect to the Auth0 login screen works. After entering my credentials I'm redirected to the callback url, for example `https://<site>.azurestaticapps.net/.auth/login/auth0/callback?code=5ExeTIAuE2snRMXW&state=%2F.auth%2Fcomplete`, but the web app returns 401: Unauthorized there.

![image](https://user-images.githubusercontent.com/10420514/118802217-2af76080-b8a2-11eb-8178-76f8eeb88336.png)

I entered `https://<site>/.auth/login/auth0` as Application Login URI and `https://<site>.azurestaticapps.net/.auth/login/auth0/callback` as Callback URL in the Auth0 application settings.

Do you have any ideas what I'm missing?

**Comment by TellonUK** [comment]
I have the same problem when using AzureB2C as a custom provider, a code is returned to the custom callback url per the [documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad) but the site shows a 401 error.

Callback URL: https://<SITE>/.auth/login/azureb2c/callback

Here is my [staticwebapp.config.json](https://github.com/TellonUK/azureswa/blob/main/staticwebapp.config.json) and the [Github Repo](https://github.com/TellonUK/azureswa)

**Comment by mkarmark** [comment]
@Skleni Do you mind sharing your sitename with us? I can start looking at our logs. 

@TellonUK I have the logs for your site and know what's going on, but due to the sensitivity of auth, would you rather open a support ticket so I can communicate my findings privately to you?

**Comment by Skleni** [comment]
Sure, the sitename is `salmon-island-017870503`.

**Comment by TellonUK** [comment]
> @Skleni Do you mind sharing your sitename with us? I can start looking at our logs.
> 
> @TellonUK [Edit] ~I have the logs for your site and know what's going on, but due to the sensitivity of auth, would you rather open a support ticket so I can communicate my findings privately to you?~ The issue is actually quite straighforward to explain here. Can you change the `secretSettingName` in the config to `clientSecretSettingName` and give it a try? The correct field name is `clientSecretSettingName` and I realize the docs have the incorrect value so I'm working to fix the docs ASAP. Sorry for the confusion!!

That resolved my issue. I have another question about claims, but will open a new issue rather than clutter this thread as its not related to Skleni's issues.

**Comment by mkarmark** [comment]
@skleni the issue with your app seems similar in that the client secret isn't getting set correctly. Could you check in the staticwebapp.config.json says "clientSecretSettingName" and change it to that if it doesn't?

**Comment by Skleni** [comment]
Yes, that worked, thank you!

**Comment by escudero** [comment]
@Skleni, Did you correct the problem just by changing the name to `clientSecretSettingName`?
I'm having the same problem and couldn't solve it.
My configuration:
`
{
    "routes": [
        {
            "route": "/login",
            "rewrite": "/.auth/login/iam"
        },
        {
            "route": "/logout",
            "redirect": "/.auth/logout"
        }
    ],
    "auth": {
        "identityProviders": {
            "customOpenIdConnectProviders": {
                "iam": {
                    "registration": {
                        "clientIdSettingName": "CLIENTID",
                        "clientCredential": {
                            "clientSecretSettingName": "CLIENTSECRET"
                        },
                        "openIdConnectConfiguration": {
                            "wellKnownOpenIdConfiguration": "https://...../oauth/nam/.well-known/openid-configuration"
                        }
                    },
                    "login": {
                        "scopes": ["openid"]
                    }
                }
            }
        }
    }
}
`

**Comment by Skleni** [comment]
@escudero Yes, that was the only change. This is my configuration:

```json
{
    "auth": {
        "identityProviders": {
            "customOpenIdConnectProviders": {
                "auth0": {
                    "registration": {
                        "clientIdSettingName": "Auth0ClientId",
                        "clientCredential": {
                            "clientSecretSettingName": "Auth0ClientSecret"
                        },
                        "openIdConnectConfiguration": {
                            "wellKnownOpenIdConfiguration": "https://.../.well-known/openid-configuration"
                        }
                    },
                    "login": {
                        "nameClaimType": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
                        "scopes": ["openid", "profile"]
                    }
                }
            }
        }
    }
}
```

**Comment by escudero** [comment]
Thank you,
It was missing the `nameClaimType` property.

**Comment by cd-Roid** [comment]
Hello, Im having the same issue with Nextjs14 and  a custom openID provier. 

i provided the callback url as in the documentation: https://<YOUR_SITE>/.auth/login/<PROVIDER_NAME_IN_CONFIG>/callback

this is my staticwebapp.config.json  

```javascript
{
  "routes": [
    {
      "route": "/",
      "allowedRoles": ["authenticated"]
    },
    {
      "route": "/.auth/*",
      "allowedRoles": ["anonymous"]
    }
  ],

  "auth": {
    "identityProviders": {
      "customOpenIdConnectProviders": {
        "fuersie": {
          "registration": {
            "clientIdSettingName": "CLIENT_ID",
            "clientCredential": {
              "clientSecretSettingName": "CLIENT_SECRET"
            },
            "openIdConnectConfiguration": {
              "issuer": "ISSUER",
              "authorizationEndpoint": "AUTHORIZATION_ENDPOINT",
              "tokenEndpoint": "TOKEN_ENDPOINT",
              "userInfoEndpoint": "USER_INFO_ENDPOINT"
            }
          },
          "login": {
            "nameClaimType": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
            "scopes": ["openid"]
          }
        }
      }
    }
  }
}
```
