### ISSUE TITLE
custom authentication request documentation has a typo in the login object

### ISSUE THREAD

**Issue by TellonUK** [Azure/static-web-apps#426]
I have setup my staticwebapp.config.json per the [documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad).
```

{
  "routes": [
    {
      "route": "/api/*",
      "allowedRoles": ["authenticated"]
    }
  ],
  "auth": {
    "identityProviders": {
      "customOpenIdConnectProviders": {
        "azureb2c": {
          "registration": {
            "clientIdSettingName": "SWACLIENTID",
            "clientCredential": {
              "secretSettingName": "SWASECRET"
            },
            "openIdConnectConfiguration": {
              "wellKnownOpenIdConfiguration": "https://glmtesting.b2clogin.com/glmtesting.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_authSignIn"
            }
          },
          "login": {
            "scope": ["openid"]
          }
        }
      }
    }
  }
}
```

No scope is sent with the network request and the azureb2c provider also provides a callback with the error `AADB2C90010: The request does not contain a scope parameter`

The documentation needs to be updated, it should be 'scopes' and not 'scope'

**Comment by anthonychu** [comment]
Thanks for pointing this out. We've submitted an update to the docs. Docs publishing is currently on pause so it'll take about a week to be live.
