### ISSUE TITLE
Can't change hosting plan on Devops powered static web app

### ISSUE THREAD

**Issue by JoshuaLowe1002** [Azure/static-web-apps#427]
Great to see Static Web Apps out of preview!

I'm running into issues changing the hosting plan to standard from free for my static web app that is powered by Azure DevOps. 

It's Asking for a GitHub URL that I don't have, any ideas? Thanks!

![image](https://user-images.githubusercontent.com/25752941/118842823-6e14fc00-b8c1-11eb-8e80-6d543a342aab.png)

**Comment by miwebst** [comment]
Ouch! There is a fix rolling out that will fix this, but that fix will take some time. Can you try using az cli to unblock you for the moment? I believe this should work:
`az staticwebapp update -n your-app-name --sku Standard`

**Comment by miwebst** [comment]
Actually, this may still fail...let me know if it does, I'll paste another (hacky) az cli command you can use if this doesnt work either.

**Comment by anthonychu** [comment]
We've identified the problem but will take some time to resolve it.

The above command might not always work. Please follow these steps if you want to change the hosting plan for an app that is _not_ using GitHub:

1. Disconnect the app from source control by running the following Azure CLI command:
    ```bash
    az staticwebapp disconnect -n $APP_NAME -g $RESOURCE_GROUP_NAME
    ```

1. Use the portal to change the app's hosting plan.

1. The above steps reset the app's deployment token. Obtain the deployment token from the portal and update the Azure Pipelines variable with this value.

Sorry for the inconvenience that this is causing.

**Comment by miwebst** [comment]
This should be fixed now. Sorry for the inconvenience!

**Comment by Greg-Hyliion** [comment]
@anthonychu @miwebst I just encountered this bug attempting to transition a free plan app to a standard plan. 
The application is deployed via Azure devOps and is not linked to a github repo. I tried the above workaround without any success. 

I'm using Azure CLI v2.28.0. 

The error I'm receiving from the portal is: `RepositoryUrl is invalid.  RepositoryUrl cannot be empty.`

Running the disconnect command does not return any output, while the update command returns a json representation of the app but no error message.

**Comment by miwebst** [comment]
Hi @Greg-Hyliion , what AZ CLI command are you running?

**Comment by Greg-Hyliion** [comment]
Yes, I ran the below commands after replacing the variables with the values for my app:

```
az staticwebapp disconnect -n $APP_NAME -g $RESOURCE_GROUP_NAME
az staticwebapp update -n $APP_NAME --sku Standard
```

I also tried running `az staticwebapp disconnect -n $APP_NAME -g $RESOURCE_GROUP_NAME` and then updating the sku in the portal, but that still gave the same error.

**Comment by capyash** [comment]
@miwebst, I'm having some issues sharing this with you as my company's security folks are hesitant about sharing everything. What do you need, exactly?

**Comment by jpalo** [comment]
```
az staticwebapp disconnect -n $APP_NAME -g $RESOURCE_GROUP_NAME
az staticwebapp update -n $APP_NAME --sku Standard
```
Worked well. Attempting to update SKU via portal didn't work, however.
