### ISSUE TITLE
Unable to add custom domain with TXT

### ISSUE THREAD

**Issue by cnotoham** [Azure/static-web-apps#432]
I am having a problem in attempting to create a custom domain with TXT. I am using the Azure DNS Zone. I have followed the steps provided in https://docs.microsoft.com/en-au/azure/static-web-apps/custom-domain?wt.mc_id=azurestaticwebapps_inline_inproduct_general&tabs=azure-dns#configure-txt-record-with-your-domain-provider.

It shows the status as validating for a long time and eventually disappear from the list. Screen shot:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/8342758/119259279-d260f400-bc10-11eb-8c5a-77298cebd341.png">

I am not sure if every one else having this same issue.

**Comment by ffMathy** [comment]
How long time did you give it? For me, it took a couple of days.

**Comment by ffMathy** [comment]
Also, what is your domain?

**Comment by anthonychu** [comment]
@cnotoham Currently, if validation fails, it fails silently and the domain simply disappears from the list. We're working on getting the error to display on the screen instead. In the meantime, @miwebst might be able to help look into the error.

**Comment by cnotoham** [comment]
> @cnotoham Currently, if validation fails, it fails silently and the domain simply disappears from the list. We're working on getting the error to display on the screen instead. In the meantime, @miwebst might be able to help look into the error.

Thank you @anthonychu for your reply. Hi, @miwebst, let me know what further information you need from me in order to investigate this issue. I tried again today with no luck.

**Comment by cnotoham** [comment]
It's working now after many attempts and I also noticed that it now shows the validation errors rather than disappear from the list. Closing this issue now.
