### ISSUE TITLE
PNG files seem to be ignored

### ISSUE THREAD

**Issue by BastiaansenXYZ** [Azure/static-web-apps#437]
I have a Hugo website running on Azure Static Web App. A couple of PNG images were added to a blogpost on that site. They didn't seem to show up, JPG's around the site did. I have redone those images and converted them to JPG and suddenly it all works. What are the supported image-types that an Azure Static Web App supports?

**Comment by anthonychu** [comment]
Looks like the PNGs had uppercase `.PNG` extensions but the img tags referenced them in lowercase. URLs in Static Web Apps is case sensitive. Renaming the files should resolve this issue.

**Comment by BastiaansenXYZ** [comment]
I tried going back to lowercase .png extensions. Even with lower-case it doesn't work. Zo it seems it completely ignores .png files.

**Comment by anthonychu** [comment]
Can you share the repo and site?

**Comment by BastiaansenXYZ** [comment]
This is the repo: https://github.com/BastiaansenXYZ/BastiaansenXYZHugo

The actual site is: https://bastiaansen.xyz

The images that were affected where the ones in blogpost 2021, WiFi Camera

**Comment by anthonychu** [comment]
Notice the files have uppercase `.PNG` extensions. You’ll need to either rename the files to lowercase or update references to use uppercase. https://github.com/BastiaansenXYZ/BastiaansenXYZHugo/tree/main/static/images

**Comment by BastiaansenXYZ** [comment]
Wow I see now yea! It seems the push to the repo didn't change the casing of the extensions. Problem solved, thanks!
