### ISSUE TITLE
Is function private or public in SWA? 

### ISSUE THREAD

**Issue by diberry** [Azure/static-web-apps#439]
If I creata a function app in the /api directory as part my SWA, is that function private only to the client request or is it publicly available if someone knows the correct URL/PORT?

**Comment by anthonychu** [comment]
Public. You can add auth if you want to lock it down some more.

**Comment by diberry** [comment]
I would rather have my API private by default. I don't think most people would expect the API of the SWA to be public by default. Would this be a private endpoint or a firewall issue?

**Comment by anthonychu** [comment]
Can you explain what you mean by “private”? I think the expectation from customers is that these are public, as they need to be called by clients on the public web. However, auth can be enabled, and we are working on options to limit access to the entire static web app.

**Comment by diberry** [comment]
I was thinking that my SWA's only public endpoint would be the front/client portion with a private link to the Azure Function. As a SWA, I don't need the Azure Function API to be public because the connection between client and API is proxied (yes?).

**Comment by miwebst** [comment]
There is no private link to the Azure Function, to ensure it cannot be accessed publicly you should set the authLevel to be `function` in your _function.json_.

**Comment by Reshmi-Sriram** [comment]
Closing the issue
