### ISSUE TITLE
Cannot restore nuggets from private feed

### ISSUE THREAD

**Issue by amilcarvalho-dev** [Azure/static-web-apps#440]
Publishing a Azure static web app failes when restoring private nuggets.Here is the error:

/tmp/oryx/platforms/dotnet/5.0.202/sdk/5.0.202/NuGet.targets(131,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/xxxx/_packaging/xxxx/nuget/v3/index.json. [/working_dir/src/Client/Client.csproj]
/tmp/oryx/platforms/dotnet/5.0.202/sdk/5.0.202/NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/working_dir/src/Client/Client.csproj]

**Comment by jak-hammond** [comment]
We're currently experiencing this issue and it's making SWA non-viable for our usage. 

If this was closed, what is the solution or workaround for this, closing without comments doesn't really help any of us who stumble over this issue and the docs don't seem be of any help either.

**Comment by anthonychu** [comment]
@jak-hammond Do you need this for the frontend build or function app?

**Comment by jak-hammond** [comment]
@anthonychu The backend function app, we seem to be able to build the frontend app fine, but when it restores the nuget packages, it seems to be doing so from within the oryx-based container/image, which is where I image the source of the problem is coming from?

**Comment by anthonychu** [comment]
Ensure you have a NuGet.config file in the folder specified as `api_location` that has the package source specified, including [the credentials](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials). You can add a step in your workflow before the Static Web Apps action to create/update this file using the NuGet CLI. The passwords need to be in plain text but can use environment variables if you are using GitHub actions (variables support is coming to Azure DevOps in a month).

**Comment by jak-hammond** [comment]
We are currently using Azure DevOps so it would have to be a plaintext password, but is there no way to authenticate this task/these pipelines in a more seamless way, having to maintain either a PAT or some other form of service based access to our internal feeds seems like an unnecessary overhead, when the current NPM and Nuget tasks seem to be able to access feeds, so long as they existing within the same organisation/project as the pipeline/task that is running?
