### ISSUE TITLE
Using VPN in SWA

### ISSUE THREAD

**Issue by escudero** [Azure/static-web-apps#441]
Hello,
Is it possible to use Static Web App on VPN?
Because I can't find the network configuration in Azure for SWA.

Thanks,
Escudero

**Comment by miwebst** [comment]
Hi @escudero how are you looking to restrict the SWA? Are you looking to restrict what ip's can access it? Or are you looking to be able to only access it through a particular Azure virtual network?

**Comment by escudero** [comment]
Hi @miwebst,
Only through a particular Azure virtual network.

**Comment by miwebst** [comment]
This will be achievable when private endpoint support is ready which should be around ~1-2 months from now.
