### ISSUE TITLE
Region availability

### ISSUE THREAD

**Issue by mauve** [Azure/static-web-apps#443]
Now that Static Web Apps is GA, I expected more regions to be supported as well, however I am presented with this when trying to deploy to `northeurope`, we need `northeurope` because of data residency laws*:

```
LocationNotAvailableForResourceType - The provided location 'northeurope' is not available for resource type 'Microsoft.Web/staticSites'. List of available regions for the resource type is 'westus2,centralus,eastus2,westeurope,eastasia'.
```

* = for simplicities sake we have all our resources in the same region and I would prefer not to mix resources from different regions

**Comment by anthonychu** [comment]
Azure Static Web Apps is a global service and there are no data residency guarantees. The location only dictates where the API and staging environments are hosted. If you’d like to use a function app in a region that is not supported or want full control of your function app, our current recommendation is to [bring your own function app](https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own).

**Comment by mauve** [comment]
Thanks for clarifying.
