### ISSUE TITLE
How to get `deployment_token` using CLI or ARM template?

### ISSUE THREAD

**Issue by mauve** [Azure/static-web-apps#444]
To automate stage setup and deployment I would like to be able to get the `deployment_token` using the `CLI` so that I can acquire the token in my pipeline before I deploy from Azure DevOps.

I couldn't find a way to do that.

Even better of course would be if I could just use my AAD credentials instead of a special credential to do my deployments.

**Comment by anthonychu** [comment]
There’s no Azure CLI command for token management yet but it’s tracked here and you can see the `az rest` command that you can use for now to retrieve the token: https://github.com/Azure/azure-cli/issues/16470#issue-782483120

The request for authenticating using service principal is here but not something we have committed to add yet: #312

**Comment by ebuzyuma** [comment]
As for ARM templates, I managed to get it like this:
```
    "variables": {
        "resourceId": "[resourceId('Microsoft.Web/staticSites/', parameters('webAppName'))]"
    },

    "outputs": {
        "deploymentToken": {
            "type": "string",
            "value": "[listSecrets(variables('resourceId'), '2019-08-01').properties.apiKey]"
        }
    } 
```

**Comment by MPapst** [comment]
Found this through google. `az staticwebapp secrets list` is working in az cli 2.30.0

**Comment by LayZeeDK** [comment]
@ebuzyuma 
According to Bicep lint rule `outputs-should-not-contain-secrets, outputting sensitive data is a bad idea`:
>Don't include any values in an output that could potentially expose secrets. For example, secure parameters of type `secureString` or `secureObject`, or [list*](https://docs.microsoft.com/da-dk/azure/azure-resource-manager/bicep/bicep-functions-resource#list) functions such as `listKeys`.
>The output from a template is stored in the deployment history, so a malicious user could find that information.

**Comment by johnnyreilly** [comment]
Here's an example pipeline that acquires the secrets used for deployment; https://blog.johnnyreilly.com/2021/12/05/azure-static-web-app-deploy-previews-with-azure-devops#azure-pipelines-tweaks

**Comment by Reshmi-Sriram** [comment]
Hey all, as @MPapst has mentioned above, we can officially get the deployment token now from the AZ CLI using `az staticwebapp secrets list`. For more information, check out the [official documentation](https://docs.microsoft.com/en-us/cli/azure/staticwebapp/secrets?view=azure-cli-latest#az-staticwebapp-secrets-list). 
Closing this issue.

**Comment by AdamPrendergast** [comment]
Amazing... thanks @austincrft

Feels like the Powershell option should be added to the docs here:
https://learn.microsoft.com/en-us/azure/static-web-apps/static-web-apps-cli-deploy
