### ISSUE TITLE
Deploy ReactJs Azure Static Web App based on Azure DevOps git repo via Azure CLI

### ISSUE THREAD

**Issue by MPiwowarski** [Azure/static-web-apps#446]
I have already created a [query on StackOverflow](https://stackoverflow.com/questions/67702715/deploy-reactjs-azure-static-web-app-based-on-azure-devops-git-repo-via-azure-cli/67710960#67710960) but then I came to the idea to open a new issue here to get some more help as so far I haven't received any valid solution to my problem.

TLDR; when I try to run the following command via Azure CLI:
`az staticwebapp create -l westus2 -n appNameTest1 -g TestPrEnvResourceGroup -s "https://dev.azure.com/myOrganisationName/myProjectName/_git/myRepoName -b "main" --token "generatedTokenValuefwfsdgsgsd"`

I'm getting the following exception:

`Command group 'staticwebapp' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus Operation returned an invalid status 'Bad Request'`

For more info please check out the SO query that I linked.
Any ideas on how can I resolve the issue and what causes it?
Cheers

**Comment by anthonychu** [comment]
We currently don’t support automatically creating Azure DevOps pipelines. This is the supported path for using Azure DevOps: https://docs.microsoft.com/en-us/azure/static-web-apps/publish-devops

**Comment by MPiwowarski** [comment]
Is there a way to set up some kind of public voting thing for a community to support the Azure Cli deployment in the future for Azure DevOps repos the same as it [actually works for GitHub](https://docs.microsoft.com/en-us/azure/static-web-apps/get-started-cli?tabs=react#create-a-static-web-app)?

**Comment by Reshmi-Sriram** [comment]
AzCLI now supports creating Azure Pipelines. Marking this as resolved. Feel free to reopen if required!
