### ISSUE TITLE
Unable to push to SWA from Github Actions

### ISSUE THREAD

**Issue by adamtay** [Azure/static-web-apps#447]
Hi,

We have a React/.NET application deployed via GitHub Actions to SWA.

As of 12hrs ago from this time of post, we have not been able to successfully complete the deployment process. We did note some outages/downtime for GitHub Actions that was tracked through GitHub Status but there are currently no known issues.

The build log is as below. Is this related to SWA itself? The actual building of the React/.NET applications are working as expected locally and on GitHub Actions but fails during the upload/deployment process.

Thanks

```
---End of Oryx build logs---
Function Runtime Information. OS: Windows, Functions Runtime: v3, .NET Core version: 3.1
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.3084819(s)
Status: InProgress. Time: 15.6535476(s)
Status: InProgress. Time: 31.014116(s)
Status: Failed. Time: 46.3574082(s)
Deployment Failed :(
Deployment Failure Reason: An unknown error has occurred.
```

**Comment by miwebst** [comment]
This particular error signature usually implies that the Function app is unable to start. We are working on improving this error message with our next release. Have you made changes to the function app since the last successful deployment?

**Comment by adamtay** [comment]
We bumped from free tier to paid tier yesterday. Could that be it?

**Comment by miwebst** [comment]
It shouldn't be, if you haven't changed anything with your .NET functions then we will need to take a deeper look. Do you mind providing your defaulthostname or some other way to identify your app?

**Comment by adamtay** [comment]
https://icy-river-0a3fa0100.azurestaticapps.net/

**Comment by sayanghosh123** [comment]
Thanks @adamtay 

Hi @miwebst Thanks for jumping in to this. This is blocking our release at a critical juncture in our project so any help will be super appreciated.

**Comment by miwebst** [comment]
Can you double check that you are not using an app settings from this list? https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints 

I confirmed it is a problem with the function deploying. If you are not using any of these we can take a deeper look.

**Comment by adamtay** [comment]
Nothing from that list and I believe Azure portal enforces those constraints so that you cannot add them as app settings.

**Comment by miwebst** [comment]
Hmm, are you sure you aren't using AzureWebJobsStorage? That is what we are denying.

**Comment by sayanghosh123** [comment]
Hi @miwebst - I took a look and doesn't look like we don't use any of these. Here is a screenshot of what we have.

![image](https://user-images.githubusercontent.com/11399751/119746047-dc197e80-bed2-11eb-826e-e73f681b3ff8.png)

**Comment by miwebst** [comment]
Right, AzureWebJobsStorage is 3rd from the bottom and not allowed.

**Comment by sayanghosh123** [comment]
Thanks - let me work with my team to understand.

**Comment by adamtay** [comment]
@miwebst removing `AzureWebJobsStorage` did the trick. Not entirely sure how that got there in the first place but appreciate you working with us to get it resolved. Thanks and will close the issue.
