### ISSUE TITLE
Azure DevOps git repo via Azure CLI : Command group 'staticwebapp' is in preview and under development.

### ISSUE THREAD

**Issue by sajeetharan** [Azure/static-web-apps#450]
**Describe the bug**
I came across this question in a forum on how to deploy a react application to Azure static web apps with Azure Devops.

**To Reproduce**

Execute the following command,

```
az staticwebapp create \
    -n my-first-static-web-app \
    -g <RESOURCE_GROUP_NAME> \
    -s https://github.com/<YOUR_GITHUB_ACCOUNT_NAME>/my-first-static-web-app \
    -l <LOCATION> \
    -b main \
    --app-artifact-location "build" \
    --token <YOUR_GITHUB_PERSONAL_ACCESS_TOKEN>
```

`az staticwebapp create -l westus2 -n appNameTest1 -g TestPrEnvResourceGroup -s "https://dev.azure.com/myOrganisationName/myProjectName/_git/myRepoName -b "main" --token "generatedTokenValuefwfsdgsgsd"
`

**Error**

Command group 'staticwebapp' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus Operation returned an invalid status 'Bad Request'
 
https://i.stack.imgur.com/d22hy.png

**Additional Context**

It works well when it is created in portal

**Comment by miwebst** [comment]
Hey @sajeetharan,

As mentioned in this issue (https://github.com/Azure/static-web-apps/issues/446) setting up DevOps is not currently supported. To use SWA with DevOps, you should create an empty SWA and then follow this tutorial: https://docs.microsoft.com/en-us/azure/static-web-apps/publish-devops 

The AZ CLI is over-enforcing the requirements, to create an empty SWA I was able to do it with this command:

`az staticwebapp create -l westus2 -n appNameTest2 -g staticsites-prod -s "" -b "" --token "x"`

**Comment by MPiwowarski** [comment]
I created a request on the Azure community site to support this feature:
https://feedback.azure.com/forums/34192--general-feedback/suggestions/43530636-support-static-web-apps-with-azure-cli

Whoever wants it please give a vote guys!
