### ISSUE TITLE
Restricting access to Static Web App: Role Management and staticwebapp.config

### ISSUE THREAD

**Issue by afogarty85** [Azure/static-web-apps#451]
How can I restrict access to my static web app permanently? I seemingly have to re-issue codes to team members and myself through `Role Management` on a daily basis. My `staticwebapp.config.json` looks like this:

```
{
    "routes": [
        {
            "route": "/login",
            "serve": "/.auth/login/github"
        },
        {
            "route": "/login/aad",
            "serve": "/.auth/login/aad"
        },
        {
            "route": "/.auth/login/twitter",
            "statusCode": "401"
        },
        {
            "route": "/.auth/login/facebook",
            "statusCode": "401"
        },
        {
            "route": "/.auth/login/google",
            "statusCode": "401"
        },
        {
            "route": "/*",
            "serve": "/index.html",
            "allowedRoles": [
                "reader",
                "contributor"
            ]
        }
    ]
}
```

Thanks for your time and help!

**Comment by miwebst** [comment]
Hey @afogarty85, seems like you are using deprecated `routes.json` properties in the `staticwebapp.config.json`. Please take a look at: https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#defining-routes

**Comment by afogarty85** [comment]
Thanks for your time and assistance! I am still having some issues and hoping that maybe you can more specifically advise me on what I should do.

Using a lightly edited version of a complete `staticwebapp.config.json` from https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#example-configuration-file, which looks like:

```
{
  "routes": [
    {
      "route": "/",
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/admin/*",
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/images/*",
      "headers": {
        "cache-control": "must-revalidate, max-age=15770000"
      }
    },
    {
      "route": "/api/*",
      "methods": ["GET"],
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/api/*",
      "methods": ["PUT", "POST", "PATCH", "DELETE"],
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/api/*",
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/login",
      "rewrite": "/.auth/login/aad"
    },
    {
      "route": "/logout",
      "redirect": "/.auth/logout"
    },
  ],
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
  },
  "responseOverrides": {
    "400": {
      "rewrite": "/invalid-invitation-error.html"
    },
    "401": {
      "redirect": "/login",
      "statusCode": 302
    },
    "403": {
      "rewrite": "/custom-forbidden-page.html"
    },
    "404": {
      "rewrite": "/404.html"
    }
  },
  "globalHeaders": {
    "content-security-policy": "default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none'"
  },
  "mimeTypes": {
    ".json": "text/json"
  }
}
```

This lets anyone in AAD access to my website when, from my interpretation of the code, only people that I have allowed specifically through `Role management` within Static Web App.

**Comment by afogarty85** [comment]
Good Evening @mkarmark! I have lightly edited `staticwebapp.config.json` as follows:

```
{
  "routes": [
    {
      "route": "/",
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/custom-forbidden-page.html",
      "allowedRoles": ["anonymous"]
    },
    {
      "route": "/images/*",
      "headers": {
        "cache-control": "must-revalidate, max-age=15770000"
      }
    },
    {
      "route": "/api/*",
      "methods": ["GET"],
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/api/*",
      "methods": ["PUT", "POST", "PATCH", "DELETE"],
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/api/*",
      "allowedRoles": ["contributor"]
    },
    {
      "route": "/login",
      "rewrite": "/.auth/login/aad"
    },
    {
      "route": "/logout",
      "redirect": "/.auth/logout"
    },
  ],
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
  },
  "responseOverrides": {
    "400": {
      "rewrite": "/invalid-invitation-error.html"
    },
    "401": {
      "redirect": "/login",
      "statusCode": 302
    },
    "403": {
      "rewrite": "/custom-forbidden-page.html"
    },
    "404": {
      "rewrite": "/404.html"
    }
  },
  "globalHeaders": {
    "content-security-policy": "default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none'"
  },
  "mimeTypes": {
    ".json": "text/json"
  }
}
```

The problem I have is, people can still get access to the website my manually adding `index.html` at the end of the URL, despite being sent to the custom forbidden page.

```
    {
      "route": "/custom-forbidden-page.html",
      "allowedRoles": ["anonymous"]
    },
```


Any thoughts?

**Comment by afogarty85** [comment]
Leaving this here for posterity, here is what worked for me, thanks to @mkarmark:

```
{
    "routes": [
        {
            "route": "/login",
            "redirect": "/.auth/login/aad"
        },
        {
            "route": "/logout",
            "redirect": "/.auth/logout"
        },
        {
            "route": "/*",
            "allowedRoles": ["specialRoles"]
        }
    ],
    "responseOverrides": {
        "401": {
          "statusCode": 302,
          "redirect": "/login"
        }
    }
}
```

**Comment by DevSecNinja** [comment]
Thanks @afogarty85 for the working config file! Hope Microsoft publishes this one on their Docs page as more people might be looking for it.

**Comment by wakesurfer2** [comment]
> We currently don't support AAD role management. There are a couple options to achieve the scenario you want: (1) **Preferred option**: Make use of the custom authentication offering in the standard plan (https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad). This will enable you to restrict logins to a particular tenant or (2) Assign special roles through Static Web Apps role management (https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization#role-management). This offering has limitations though as we only support 25 special-role users per static web app.
> 
> We are hoping to support AAD role management in the future.

Does standard Azure authentication work now for static web apps using the free plan?
Does authorization with custom roles work for static web apps ?
