### ISSUE TITLE
Allow for "deny by default" authorization

### ISSUE THREAD

**Issue by jeroenvdmeer** [Azure/static-web-apps#455]
All users of my application must authenticate before they can use the application. I solved this easily the following route: `{ route": "/*", allowedRoles": ... }`. However, due to reasons I need one page (callback.html) that is publically accessible. I was hoping that adding a route to make callback.html accessible for users with the [built-in role "anonymous"](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization#roles) would do the trick. Unfortunately this triggered the following error: _A route is covered up by a wildcard route and would not be evaluated. Route: /callback.html, Wildcard(s): /*. Please either delete or move the unreachable route._

As a result I needed to create multiple route to restrict access to my application and make callback.html publically accessible. I quickly realised this is a tricky task, because I initially forgot to restrict index.html while I restricted access to the route "/". Therefore I believe the lack of options to overwrite wildcard routes is a risk to the authorization features of Azure Static Web Apps. The risk is developers forget to restrict access to routes after adding them, and exposing sensitive information to the public. Whereas with a "/*" route these newly added information would be restricted by default.

I propose to allow overwriting wildcard routes to pave the way for implementing the "deny by default" principle highlighted as OWASP's first step under "How to prevent" for [A5:2017-Broken Access Control](https://owasp.org/www-project-top-ten/2017/A5_2017-Broken_Access_Control):

```
{
    "route": "/*",
    "allowedRoles": ["administrator"]
},
{
    "route": "/callback.html",
    "allowedRoles": ["anonymous"]
}
```

**Comment by nils-ws** [comment]
You can, you'll just have to change the order of your routes. The explicit route needs to come before the wildcard one:

```json
{
    "route": "/callback.html",
    "allowedRoles": ["anonymous"]
},
{
    "route": "/*",
    "allowedRoles": ["administrator"]
}
```

**Comment by jeroenvdmeer** [comment]
Ah you're right, @nils-ws. Thanks for pointing this out!
