### ISSUE TITLE
401 on callback after login with Azure AD B2C custom OpenID Connect provider

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/static-web-apps#457]
I've followed this thread, https://github.com/Azure/static-web-apps/issues/425 to no avail.

After I login, I get this screen:
![image](https://user-images.githubusercontent.com/1428703/120626711-ee467000-c430-11eb-96ab-20e61312b071.png)

Is there something AD B2C is doing that in the thread above Auth0 isn't doing? (Should I have created this on that Auth0 issue, too?)

Here's my staticwebapp.config.json file, 

```json
{
  "routes": [
    {
        "route": "/admin/*",
        "allowedRoles": [
            "authenticated"
        ]
    },
    {
        "route": "/login",
        "rewrite": "/.auth/login/b2c"
    },
    {
        "route": "/logout",
        "redirect": "/.auth/logout"
    }
],
    "auth": {
      "identityProviders": {
        "customOpenIdConnectProviders": { 
          "b2c": {
            "registration": {
              "clientIdSettingName": "AppRegId",
              "clientCredential": {
                "clientSecretSettingName": "AppRegClientSecret"
              },
              "openIdConnectConfiguration": {
                "wellKnownOpenIdConfiguration": "https://<domain>.b2clogin.com/<domain>/<policy>/v2.0/.well-known/openid-configuration"
              }
            },
            "login": {
              "nameClaimType": "emails",
              "scopes": ["openid"]
            }
          }
        }
      }
    },
    "platformErrorOverrides": [
      {
        "errorType": "NotFound",
        "serve": "/custom-404.html"
      },
      {
        "errorType": "Unauthenticated",
        "serve": "/login"
      }
    ]
  }
```

**Comment by mkarmark** [comment]
Hi, thanks for bringing this to our attention. We are working on this issue and will post here when we have updates to share!

**Comment by irwinwilliams** [comment]
Thanks @mkarmark, willing to try workarounds if any are available in the meantime.

**Comment by TellonUK** [comment]
Is this a general outage? I notice code written previously no longer works.

[https://github.com/TellonUK/azureswa](https://github.com/TellonUK/azureswa)

**Comment by mkarmark** [comment]
Yes, this is a recent regression that will be experience intermittently, that we are actively working to fix in the next couple days. Will post here when the fix is out :)

**Comment by DaveMiscampbell** [comment]
Confirming I have the same issue - is there anything we can do to mitigate in the meantime?

**Comment by mkarmark** [comment]
This issue should now be fully mitigated. Can y'all confirm that your apps are in fact unblocked now, and I can close this issue. Thanks for your patience!

**Comment by TellonUK** [comment]
> This issue should now be fully mitigated. Can y'all confirm that your apps are in fact unblocked now, and I can close this issue. Thanks for your patience!

All my sites are working now.

**Comment by irwinwilliams** [comment]
Confirming it works for me, @mkarmark 
Many thanks, team!
