### ISSUE TITLE
Cannot see Microsoft.Web/staticSites in resources.azure.com

### ISSUE THREAD

**Issue by mauve** [Azure/static-web-apps#459]
static sites do not turn up in resources.azure.com (nor does the provider)

**Comment by mkarmark** [comment]
Hi, this is something we are working on that should get updated soon. Is there something you are blocked on without access to resources.azure.com?

**Comment by mauve** [comment]
I am trying to write ARM Bicep templates and the ARM reference contains no information (and export templates not supported yet), so I am trying to figure out what I should put in my templates.

**Comment by Reshmi-Sriram** [comment]
This issue should be resolved now. Feel free to reopen if needed!
