### ISSUE TITLE
Default document not served when directory name contains a period.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/static-web-apps#46]
If the directory name contains a period ".",  when accessing that directory not served default document (index.html).

1. /dot.dir/index.html is works fine.
2. /dot.dir/ is 404.

https://gentle-sand-0f46f010f.azurestaticapps.net/

Also, I cannot find a document with a filename that can be used as the default document.

**Comment by miwebst** [comment]
Hi @takekazuomi, thanks for reporting this! We will take a look. As for right now we always look for index.html as our default document. It is not currently configurable.

**Comment by miwebst** [comment]
This should be fixed now. Please let us know if the issue persists.

**Comment by takekazuomi** [comment]
It works fine now. Thank You for your great job.
