### ISSUE TITLE
Cannot find Static Web Apps in "All services"'s searchbox

### ISSUE THREAD

**Issue by victorp13** [Azure/static-web-apps#461]
The Azure portal has a "All services" section, but typing "static" into the searchbox above does not lead to any result.

![image](https://user-images.githubusercontent.com/1854749/120887465-5e045880-c5f3-11eb-9e2c-9cd82e8ae7d3.png)

**Comment by anthonychu** [comment]
Thanks we'll look into this. /cc @ehamai

**Comment by victorp13** [comment]
I believe this issue has been resolved 
![image](https://user-images.githubusercontent.com/1854749/126841370-ad94228b-d842-4eb7-873e-c531b831f361.png)
