### ISSUE TITLE
Facebook as Authentication Provider

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [Azure/static-web-apps#464]
Hello! I noticed that Facebook is no longer an authentication provider since Azure SWA went GA. However, I'm still able to set Facebook as an authentication provider on Azure Portal:

![image](https://user-images.githubusercontent.com/19281514/120925169-ed039480-c709-11eb-831f-6fa5b680139f.png)

Would like to check if Facebook is still supported, thanks!

**Comment by anthonychu** [comment]
While Facebook and Google may be functional, they are not currently supported in GA. Thanks for pointing it out here. We'll update this UX accordingly.

**Comment by Reshmi-Sriram** [comment]
tracked in #695 and #967
