### ISSUE TITLE
Remove Header in proxies.json 

### ISSUE THREAD

**Issue by lenisha** [Azure/static-web-apps#465]
currently if trying to use Static site to secure access to Blob Storage with proxies functions, it passes Authorization header in a format that storage does not accept,
tried to re-write with sas token , but it fails with error 400 - incorrect Authorization header format
```
{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "DeepZoom": {
            "matchCondition": {
                "route": "/api/deepzoom/{*restOfPath}"
            },
            "backendUri": "https://<blob>.blob.core.windows.net/dzi/{restOfPath}%sas_token%",
            "requestOverrides": {
                "backend.request.headers.Accept": "*/*",
                "backend.request.headers.Cache-Control": "no-cache",
                "backend.request.headers.Pragma": "no-cache",
                "backend.request.headers.Accept-Encoding": "gzip, deflate",
                "backend.request.headers.Authorization": ""
            },
            "debug": true
        }
    }
}
```
Setting in proxies.json header to empty does not help:
"backend.request.headers.Authorization": "" 

Is there a way to remove header?
Or set Authorization Header to Managed identity token?

similar in concept to https://github.com/Azure/static-web-apps/issues/335 
but  Javascript points to proxy route it can't inject MSI identity token in the `x-custom-authorization` header

**Comment by anthonychu** [comment]
As mentioned here https://github.com/Azure/Azure-Functions/issues/1930, this is not supported by proxies at this time. We have a separate issue regarding the authorization header here: https://github.com/Azure/static-web-apps/issues/34

**Comment by Reshmi-Sriram** [comment]
Closing this issue.
