### ISSUE TITLE
Publish a Blazor Static Web App using an Azure DevOps pipeline

### ISSUE THREAD

**Issue by colinrippeyfinarne** [Azure/static-web-apps#468]
Hi,

I am hoping this is an easy fix.

I have followed the steps in the Deploy Blazor tutorial and all is well, my github action successfully deploys the repo to the website and I can click the Fetch data link and get results returned from the api.

https://docs.microsoft.com/en-gb/azure/static-web-apps/deploy-blazor

I have tried to replicate this using only Azure DevOps pipelines. I've imported the github repo into an Azure DevOps repo and then built a pipeline using the steps in this article:

https://docs.microsoft.com/en-gb/azure/static-web-apps/publish-devops

I then modified the build pipeline to include steps to build the blazor app and point at the correct locations:

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'Client'
      app_build_command: 'dotnet build'
      output_location: 'wwwroot'
      api_location: 'api'
      api_build_command: 'dotnet build'
      routes_location: '/Client/wwwroot'
    env:
      azure_static_web_apps_api_token: $(deployment_token)

This build "works" and the static website gets deployed and I can browse to it (so the Blazor app seems to work), but upon clicking the Fetch data link I can see a 404. It's as if the API just isn't there.

My question I hope is simple, is there some simple fix to the api_build_command for example?

**Comment by anthonychu** [comment]
The build runs on Linux and the file system is case sensitive. Can you change `api_location: 'api'` to `api_location: 'Api'`?

There should be no need to override the build commands for either api or app build as the task is capable of detecting and building Blazor WebAssembly and .NET Core 3.1 function apps, you can remove those lines.

**Comment by colinrippeyfinarne** [comment]
Thanks @anthonychu I just noticed this and closed the issue, but good to know there's no need to add any custom build steps too.
