### ISSUE TITLE
Application Configuration no longer accepts names with a colon

### ISSUE THREAD

**Issue by gavinwilliams** [Azure/static-web-apps#469]
**Describe the bug**
Adding an application setting with a colon (:) in the name now throws an error in the Applications Configuration page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your app Configuration
2. Add a setting with the name **This:MakesNoSense**
3. Set a value of **Test**
4. Press OK
5. Press Save

**Expected behaviour**
The settings save, as there are a number of .NET libraries with settings that follow this format

**Screenshots**
![image](https://user-images.githubusercontent.com/611832/121096252-be5ceb00-c7e9-11eb-87c6-a17b05f9f8a8.png)

**Device info (if applicable):**
Not relevant

**Additional context**
Not relevant

**Comment by gavinwilliams** [comment]
Managed to get around this by using double _ i.e. **This__MakesNoSense**. I feel like this change should be documented somewhere, given that using colons has been working fine until today.

**Comment by mkarmark** [comment]
@craigshoemaker Could we specify in the docs that we only support alphanumeric characters, '.', and '_' for app settings? @gavinwilliams I believe we've had this rule in place for a while now. Do you have the last time you made a successful change with a ':'?

**Comment by gavinwilliams** [comment]
> @craigshoemaker Could we specify in the docs that we only support alphanumeric characters, '.', and '_' for app settings? @gavinwilliams I believe we've had this rule in place for a while now. Do you have the last time you made a successful change with a ':'?

A little over a month ago

**Comment by craigshoemaker** [comment]
The Application settings doc is now updated with the character allow list.

**Comment by jon-a-nygaard** [comment]
Suggesting that this issue can be closed now that the [documentation article](https://docs.microsoft.com/en-us/azure/static-web-apps/application-settings) has been updated 🙂 @gavinwilliams @mkarmark
