### ISSUE TITLE
Using Configurations / Environment Variables without Functions

### ISSUE THREAD

**Issue by justinyoo** [Azure/static-web-apps#47]
Currently, when I deploy an app without API using Functions, I can't add environment variables to the `Configuration` blade. But while I've been playing around this feature, I found a couple of things for you to confirm.

1. I can add the environment variables, if I deploy an empty Functions (no endpoint, but runtime).
2. By adding environment variables to the `Configuration` blade, I expected that I would be able to access to those environment variables from the front-end side by `process.env["xyz"]`. However, apparently they are only accessible from the Function side.

With regards to the no. 2 question, many use cases use the AJAX calls directly from the app, not through the facade, I mean Functions. In this case, direct access to the environment variables through the `process.env` object makes more sense to me.

For me, I'm using Blazor Web Assembly that wants to access to the environment variables. But there's no way to get to the value, other than deploying `appsettings.json` together.

**Comment by anganti** [comment]
Please refer to the comments in #48

**Comment by miwebst** [comment]
Closing this as we are serving static content, this would make it non static :)

**Comment by arifemir** [comment]
> Closing this as we are serving static content, this would make it non static :)
LOL
