### ISSUE TITLE
Unable to Logout

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [Azure/static-web-apps#471]
**Describe the bug**
See issue title.

**To Reproduce**
1. Go to https://orange-island-0901fe000-59.eastasia.azurestaticapps.net/
2. Log in with an Azure AD account
3. Go to https://orange-island-0901fe000-59.eastasia.azurestaticapps.net/.auth/logout
4. User is still logged in

**Expected behavior**
User should be logged out

**Additional context**
1. The `logout` request returns the index page, based on Chrome Devtools -> Network.

**Comment by anthonychu** [comment]
Looks like the service worker might be messing things up here. I haven't tried this but I think you might need to exclude server-side paths: https://docs.microsoft.com/en-us/aspnet/core/blazor/progressive-web-app?view=aspnetcore-5.0&tabs=visual-studio#support-server-rendered-pages

**Comment by Zhiyuan-Amos** [comment]
Thanks for pointing me into the right direction Anthony! :)
