### ISSUE TITLE
Service Worker seems to interfere with Authentication

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [Azure/static-web-apps#474]
**Describe the bug**
Users that are automatically logged out of my Blazor WASM PWA are still able to access the web pages, even though they are not allowed to as configured in `staticwebapp.config.json`. I investigated and it seems that the Service Worker is interfering as it returns a cached view of the page despite being connected to the Internet.

**To Reproduce**
1. Go to 'https://orange-island-0901fe000-59.eastasia.azurestaticapps.net/login' and log in with an Azure AD account
2. Remove the Cookie in 'Cookies' (i.e. leave 'Cache Storage', 'Indexed databases' and 'Service Workers' untouched).
3. Refresh the webpage. Observe that page loads successfully.
4. Force refresh the webpage. Observe that you have been redirected to 401 page.

**Expected behavior**
Step 3 should have already resulted in a 401 response.

**Screenshots**
Page returned by service worker when accessing web page or refreshing web page.
![image](https://user-images.githubusercontent.com/19281514/121612868-e2405b00-ca8d-11eb-862f-a972bcd7a95b.png)

Page returned by server on force refresh.
![image](https://user-images.githubusercontent.com/19281514/121612939-0dc34580-ca8e-11eb-9e53-e8373bb907dc.png)

**Comment by anthonychu** [comment]
The service worker is part of Blazor. Perhaps they can help you in the aspnet repo.
