### ISSUE TITLE
Vague error message

### ISSUE THREAD

**Issue by pingdong** [Azure/static-web-apps#477]
Could someone kindly point where is the problem of the below bicep file? 

I'm trying to deploy an empty SWA then deploy code using AzureStaticWebApp@0 later.

Bicep File

@minLength(3)
param project string
@minLength(3)
param environment string
@minLength(3)
param location string = 'eastus2'

param sw_sku string = 'Free'

// Static Website
resource website 'Microsoft.Web/staticSites@2021-01-01' = {
  name: 'sw-dew-${project}-frontend-${environment}'
  location: location

  sku: {
    name: sw_sku
    tier: sw_sku
  }
}

The transpiled JSON code snippet

  "resources": [
    {
      "type": "Microsoft.Web/staticSites",
      "apiVersion": "2021-01-01",
      "name": "[format('sw-dew-{0}-frontend-{1}', parameters('project'), parameters('environment'))]",
      "location": "[parameters('location')]",
      "sku": {
        "name": "[parameters('sw_sku')]",
        "tier": "[parameters('sw_sku')]"
      }
    }
  ] 

Error:

There were errors in your deployment. Error code: InvalidTemplateDeployment.
##[error]The template deployment 'frontend-20210615-065307-7eab' is not valid according to the validation procedure. The tracking id is 'd842c51f-0a34-4994-9ef7-19a98587c1a0'. See inner errors for details.
##[error]Details:
##[error]ValidationForResourceFailed: Validation failed for a resource. Check 'Error.Details[0]' for more information. [{"code":"InvalidName","message":"One or more properties, including the resource name, are missing. Please add them and retry."}]
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Task failed while creating or updating the template deployment.
Finishing: [frontend] Validate the Template, Scope: Resource Group

**Comment by mkarmark** [comment]
I believe this has to do with the "properties" object being null in the resource. At the same level as "sku" and "location", try adding "properties":{}. I believe that will unblock you from that error.

**Comment by pingdong** [comment]
Thanks for replying, I tried adding an empty properties{}, but it didn't pass the validation of AzureResourceManagerTemplateDeployment@3.

**Comment by mkarmark** [comment]
Do you mind posting the sitename here? I'll take a closer look at the logs.

**Comment by pingdong** [comment]
I would like to share, but the issue happens before deploying to Azure. In my pipeline, the transpiling and validating steps are done in the stage inside Azure DevOps pipeline. The real deployment only happens in the next stage. I've attached the log of the pipeline.

[log.txt](https://github.com/Azure/static-web-apps/files/6665698/log.txt)

**Comment by mkarmark** [comment]
The error message text definitely seems like the exact phrase we would return if we reject the payload, so I'm pretty confident the request is hitting Azure. An app name will help to diagnose this further.

**Comment by pingdong** [comment]
From the pipeline log, the deployment name was:  frontend-20210615-065307-7eab

The attached image is the screenshot of deployment of the targeted resource group. I can't find this deployment task in Azure. Since the deployment was failed, I don't think any SWA was created. 

Here are the task of validation:

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: '[${{ parameters.artifactPrefix }}] Validate the Template, Scope: Resource Group'
      inputs:
        deploymentScope: Resource Group 
        deploymentMode: Validation
        azureResourceManagerConnection: ${{ parameters.azureResourceManagerConnection }}
        subscriptionId: ${{ parameters.subscriptionId }}
        resourceGroupName: ${{ parameters.resourceGroupName }}
        location: ${{ parameters.location }}
        csmFile: ${{ format('{0}/{1}.json', parameters.workingDirectory, parameters.artifactPrefix) }}
        csmParametersFile: ${{ format('{0}/{1}.parameters.{2}.json', parameters.workingDirectory, parameters.artifactPrefix, parameters.environment) }}
        overrideParameters: ${{ parameters.overrideParameters }}

![image](https://user-images.githubusercontent.com/5837194/122490637-92860480-d036-11eb-819a-7e13006c8e23.png)

**Comment by pingdong** [comment]
@mkarmark Do you have any update?

**Comment by miwebst** [comment]
Hey @pingdong, check out this arm template that is used in situations where you don't want to configure SWA against a GitHub repo: {
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "string"
        },
        "location": {
            "type": "string"
        },
        "sku": {
            "type": "string"
        },
        "skucode": {
            "type": "string"
        }
    },
    "resources": [
        {
            "apiVersion": "2019-12-01-preview",
            "name": "[parameters('name')]",
            "type": "Microsoft.Web/staticSites",
            "location": "[parameters('location')]",
            "tags": null,
            "properties": {},
            "sku": {
                "Tier": "[parameters('sku')]",
                "Name": "[parameters('skuCode')]"
            }
        }
    ]
}

**Comment by pingdong** [comment]
@miwebst 2019-12-01-preview seems a wrong version.

But I tried downgrading the api version from 2021-01-01 to 2020-12-01. It works now. It seems an issue inside the api. 

Thanks again

**Comment by pingdong** [comment]
@miwebst I tried again of 2021-01-01. It works as well. Something could be changed in azure side. But anyway, this issue can be closed now.
