### ISSUE TITLE
Custom Domain Redirects

### ISSUE THREAD

**Issue by kushwanth** [Azure/static-web-apps#482]
Where are Azure Static Web Apps servers located?

My debugging shows that my static web app resolves to 4 different IP's in which two of them are in US, one in Netherlands and last one in Hong Kong and yes my site loads twice as fast in US when compared to Asia. Is there any configuration I am missing (or) are there only four of them?

**Comment by kushwanth** [comment]
Docs say that "served from points geographically distributed around the world. This distribution makes serving files much faster as files are physically closer to end users"

They don't where are points (PoP's) located.

My site is pre-built html with a CSS file and very little JS. webpagetest.org shows almost it takes more time to load in Asia/Pacific which most of the viewers are compared to US.

Are there any plans to add new servers?

**Comment by mkarmark** [comment]
We do not have a published list of our PoP's/Servers, but they are geographically distributed to have low latency when accessing the site globally. That being said we are not a CDN, so we don't have nearly as much geographical coverage as a service such as Azure Front Door. If you want something closer to a CDN, I suggest putting a front door in front of your static web app.

**Comment by kushwanth** [comment]
I realised that today by doing some test.Will there be any increase in coverage in coming months?
Azure Front Door is an overkill, It will empty my student credits in less than a 6 months. Also another thing I am trying to do is the redirect from default azure provided URL to my custom domain. My site plain HTML without any frontend framework. So I was hoping for a feature to allow domain level redirects using configuration file. Netlify has this feature.

**Comment by mkarmark** [comment]
We don't have plans to add more PoPs in the coming months. For the feature you talked about of redirecting to the custom domain, that feature is in the works and should be available in the next month or two.

**Comment by miwebst** [comment]
More coverage is coming :) we don't publish our IP's to avoid anyone taking dependencies on them while we continue to add more servers. We are working to expand our existing footprint and that will be transparent to users.

**Comment by miwebst** [comment]
Also updating title to reflect the open question here.

**Comment by anthonychu** [comment]
You can now redirect all traffic to a default (primary) custom domain. Documentation will be updated in the next day or so.

![image](https://user-images.githubusercontent.com/3982077/128270560-bb1ef218-e471-45e4-8273-97948b6fdd8a.png)
