### ISSUE TITLE
NavigationFallback fails with long URLs

### ISSUE THREAD

**Issue by stianl** [Azure/static-web-apps#489]
The `navigationFallback` setting in `staticwebapp.config.json` does not seem to work with long URLs.

I've reproduced the issue with a simple application based on the [Vanilla Javascript app from the getting started guide](https://docs.microsoft.com/en-us/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript).
I've added a [staticwebapp.config.json file](https://github.com/stianl/my-first-static-webapp/blob/main/staticwebapp.config.json) with the following content:

```json
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/static/*", "/*.{png,ico}"]
  }
}
```

If you go to the application using a [very long URL parameter](https://delightful-bay-0769bc110.azurestaticapps.net/dashboard?123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123456789123453) it will fail with the error message: **The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.** (HTTP 404).

If I remove the last character in the URL it will load the index.html page as expected. The `navigationFallback` setting also works fine if I use eg. `nosuchfile.html`. It seems like there's a limit around 2048 characters.

If you attempt another resource that doesn't exist (but is not configured to use the `navigationFallback` setting), eg. [/static/nonexistant.png](https://delightful-bay-0769bc110.azurestaticapps.net/static/nonexistant.png) it will also give a HTTP 404 response, but with a different page and the message "We couldn’t find that page, please check the URL and try again.".

I'd at least expect the same 404 page to always be returned, but ideally I would like to get my "fallback" page even if the URL is too long.

This may be a minor issue, but this problem came up when integrating with an Oauth2/OIDC authorization server. Sometimes the `access_token` and `id_token` passed in the `redirectURL` are too long, so right now this is blocking me from using OIDC with Azure static web apps.

**Comment by miwebst** [comment]
Hi, @stianl thanks for surfacing this. Yes today we have a limit on the request length that is processed before the navigation fallback. On the OIDC redirect url, are you controlling the length of those or is it another identity provider?

**Comment by stianl** [comment]
Sorry for the late response - no, I have no control of the length of the tokens in the redirect URLs - it's another identity provider.

**Comment by mucahitgurbuz** [comment]
Experiencing the same issue. I am converting my dynamic queries to base64 and append to URL. 
When I am routing to these page, works fine. However when I refresh the page, I am getting an error `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable`. I have only experience this when I have long query string.

**Comment by miwebst** [comment]
This should be fixed now, long query strings are now allowed.
