### ISSUE TITLE
Staging environment not cleaned up if PR is closed while building (Azure/static-web-apps-deploy@v1)

### ISSUE THREAD

**Issue by mattixittam** [Azure/static-web-apps#494]
**Describe the bug**

When we make a PR which triggers a staging environment build (through Azure/static-web-apps-deploy@v1) and close that PR when the environment is still building, the `Close Pull Request Job` cannot find a matching environment and does nothing. This causes the Staging environment to stay around until we manually delete it from the portal.

Our workflow file is an unchanged automatically generated yml file (apart from adding a few env variables).

**To Reproduce**

0. Make sure your staging build job takes several minutes (longer than the close PR job)
1. Make a PR which triggers a Staging environment build 
2. Close the PR immediately
3. Check the github actions, two should be running (the build job and the close PR job)
4. See that the `Close Pull Request Job` does nothing because the environment is not yet deployed
5. See the `Build and Deploy` job finishes as normal
6. You now have a staging environment which will never be automatically removed

**Expected behavior**
I would expect the ongoing build to be cancelled if the PR is closed while it is building.

**Comment by miwebst** [comment]
This is a repeat of this issue correct? Will close if you agree: https://github.com/Azure/static-web-apps/issues/162

**Comment by mattixittam** [comment]
Yup, seems to be the same thing: the deploy and close jobs interacting badly if running in parallel. This can be closed.
