### ISSUE TITLE
Error when deploying with ARM/Bicep

### ISSUE THREAD

**Issue by aleksandervalle** [Azure/static-web-apps#495]
**Describe the bug**

When provisioning/deploying static web app with Bicep, a Github Actions workflow file is automatically generated in the web app repository. After deploying web app again from web app repository through generated workflow, subsequent runs of Bicep pipeline will fail with error:

`ERROR: ***"error":***"code":"InvalidTemplateDeployment","message":"The template deployment 'main' is not valid according to the validation procedure. The tracking id is 'c551199a-04c4-45c9-a941-ace3e85e9739'. See inner errors for details.","details":[***"code":"BadRequest","message":"Provider is invalid.  Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider."***]***
Error: Error: az cli script failed.`

Deleting resources from Azure (through portal) and attempting rerun of Bicep pipeline still yields same error (as if site is hanging around even after I delete it). Renaming the `Microsoft.Web/staticSites` resource in Bicep template will give me green Bicep pipeline, but same problem occurs again if I repeat the process.

**To Reproduce**
Reproduced in these two repos:
https://github.com/aleksandervalle/reproduce-staticsite-issue-bicep
https://github.com/aleksandervalle/reproduce-staticsite-issue-client

(Also, see workflow runs.)

1. Deploy resources with Bicep pipeline
2. Deploy static web app from client repo (using generated workflow file)
3. Run Bicep pipeline again. See error.

**Expected behavior**
I expect Bicep pipeline to run without errors, even after I've deployed web app through web app repo's pipeline.

EDIT:
Entire log from "Deploy resources" step (https://github.com/aleksandervalle/reproduce-staticsite-issue-bicep/runs/2913094159?check_suite_focus=true):

```
Run Azure/cli@1.0.4
  with:
    inlineScript: az deployment sub create --location norwayeast \
  --parameters repositoryToken=*** \
  --template-file ./main.bicep
  
    azcliversion: latest
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
Starting script execution via docker image mcr.microsoft.com/azure-cli:latest
ERROR: ***"error":***"code":"InvalidTemplateDeployment","message":"The template deployment 'main' is not valid according to the validation procedure. The tracking id is 'c551199a-04c4-45c9-a941-ace3e85e9739'. See inner errors for details.","details":[***"code":"BadRequest","message":"Provider is invalid.  Cannot change the Provider. Please detach your static site first if you wish to use to another deployment provider."***]***
Error: Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_1624615755173_CONTAINER
```

**Comment by miwebst** [comment]
Hi @aleksandervalle, we will take a look!

**Comment by RossMurr4y** [comment]
Just ran into this issue as well.

I used PowerShell to interrogate the configuration after my initial deployment and then after the subsequent Azure Pipelines run of the same BICEP template. The results show 3 attributes that are being updated without being specified in the BICEP template. 

I can only assume its drawing this information from metadata in Azure DevOps Pipelines, then deciding I'm trying to change an immutable attribute and falling over. It's getting far enough to change these attributes, so I'm not sure if its failing on these attributes being different in subsequent runs or if there are additional attributes that it's trying to change and failing upon.

<details><summary>PowerShell</summary>

```terminal
Get-AzStaticWebApp -ResourceGroupName example | ConvertTo-Json
```

</details>

<details><summary>Results on initial run from my CLI</summary>

```json
                                                         
{
  "AllowConfigFileUpdate": true,
  "Branch": null,
  "BuildPropertyApiBuildCommand": null,
  "BuildPropertyApiLocation": null,
  "BuildPropertyAppArtifactLocation": null,
  "BuildPropertyAppBuildCommand": null,
  "BuildPropertyAppLocation": null,
  "BuildPropertyGithubActionSecretNameOverride": null,
  "BuildPropertyOutputLocation": null,
  "BuildPropertySkipGithubActionWorkflowGeneration": null,
  "Capacity": null,
  "ContentDistributionEndpoint": "https://examplehostname.azurestaticapps.net",
  "CustomDomain": [],
  "DefaultHostname": "examplehostname.azurestaticapps.net",
  "Id": "/subscriptions/mysub/resourceGroups/example/providers/Microsoft.Web/staticSites/example",
  "IdentityPrincipalId": null,
  "IdentityTenantId": null,
  "IdentityType": null,
  "IdentityUserAssignedIdentity": {},
  "KeyVaultReferenceIdentity": "SystemAssigned",
  "Kind": null,
  "Location": "West US 2",
  "Name": "example",
  "PrivateEndpointConnection": [],
  "Provider": "None",
  "RepositoryToken": null,
  "RepositoryUrl": null,
  "SkuCapability": null,
  "SkuCapacityDefault": null,
  "SkuCapacityElasticMaximum": null,
  "SkuCapacityMaximum": null,
  "SkuCapacityMinimum": null,
  "SkuCapacityScaleType": null,
  "SkuFamily": null,
  "SkuLocation": null,
  "SkuName": "Free",
  "SkuSize": null,
  "SkuTier": "Free",
  "StagingEnvironmentPolicy": {},
  "Tag": {},
  "TemplatePropertyDescription": null,
  "TemplatePropertyIsPrivate": null,
  "TemplatePropertyOwner": null,
  "TemplatePropertyRepositoryName": null,
  "TemplatePropertyTemplateRepositoryUrl": null,
  "Type": "Microsoft.Web/staticSites",
  "UserProvidedFunctionApp": []
}
```
</details>

<details><summary>Results on subsequent run within Azure Pipelines using the exact same BICEP file.</summary>

Trimmed to only the changed configuration.

```json
{
   ...
    "Branch": "master",
   ...
    "Provider": "DevOps",
   ...
    "RepositoryUrl": "https://github.com/example-gh-org/examplerepo",
    ...
  }
```

Note that this does not occur if repeatedly running from the CLI.


BICEP:

```bicep
@description('A name to give the Static Web App.')
param name string

@description('The Azure region to deploy the Static Web App into. Available regions are: westus2 centralus eastus2 westeurope eastasia')
@allowed([
  'westus2'
  'centralus'
  'eastus2'
  'westeurope'
  'eastasia'
])
param location string

@description('Key/Value pairs of labels to assign to the Static Web App resource.')
param tags object = {}

@description('The type of hosting plan for the Static Web App.')
@allowed([
  'Free'
  'Standard'
])
param planType string = 'Free'

resource swa 'Microsoft.Web/staticSites@2021-01-01' = {
  name: name
  location: location
  tags: tags
  sku: {
    name: planType
  }
  properties: {
    buildProperties: {
      skipGithubActionWorkflowGeneration: true
    }
  }
}
```

</details>

**Comment by miwebst** [comment]
Both of these issues should be fixed now. Can you retry and let us know what you think?

**Comment by aleksandervalle** [comment]
Travelling, will definitely test when I get home. Thanks!

**Comment by mfcollins3** [comment]
@miwebst I ran into this tonight. I was successfully able to run my ARM template the first time, but after that, I get the same error as above.

**Comment by miwebst** [comment]
Hmm, @mfcollins3, do you mind sharing your arm template?

**Comment by mfcollins3** [comment]
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "environment": {
            "type": "string",
            "defaultValue": "dev",
            "metadata": {
                "description": "The type of environment that is being created (dev, test, prod)"
            }
        },
        "githubPersonalAccessToken": {
            "type": "string",
            "metadata": {
                "description": "A personal access token used to access GitHub resources (requires repo, workflow, write:packages scopes)"
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "[resourceGroup().location]",
            "metadata": {
                "description": "Location for all Azure resources"
            }
        }
    },
    "functions": [],
    "variables": {
        "staticWebAppName": "[concat('projectsweb', parameters('environment'))]"
    },
    "resources": [
        {
            "name": "[variables('staticWebAppName')]",
            "type": "Microsoft.Web/staticSites",
            "apiVersion": "2020-12-01",
            "location": "[parameters('location')]",
            "properties": {
                "repositoryUrl": "https://github.com/neudesic/projects-web.git",
                "branch": "main",
                "repositoryToken": "[parameters('githubPersonalAccessToken')]",
                "buildProperties": {
                    "appLocation": "/",
                    "apiLocation": "api",
                    "outputLocation": "dist"
                }
            },
            "sku": {
                "Name": "Free",
                "Tier": "Free"
            }
        }
    ],
    "outputs": {}
}
```

**Comment by miwebst** [comment]
Hey @mfcollins3,

I hit the same issue when deploying your template. To get around this, you can add `"provider": "GitHub"` to the properties of the swa in your template. Subsequent deployments will then work (at least they did for me)

**Comment by aleksandervalle** [comment]
Works after setting `provider: 'GitHub'` in bicep template, although I do get a warning saying the property is read-only.

`WARNING: /github/workspace/staticsite.bicep(8,5) : Warning BCP073: The property "provider" is read-only. Expressions cannot be assigned to read-only properties.`

Many thanks!
