### ISSUE TITLE
[Question] Post authentication redirect to requested URL

### ISSUE THREAD

**Issue by Roger-Sa** [Azure/static-web-apps#502]
Hi, 

I'm using AAD authentication. Let's say I have an app at **myapp.com** and a user wants to access **myapp.com/product?id=123** (which might be bookmarked, for instance). If the user is already logged in this works fine, but if he needs to log in, post authentication redirects the user to **myapp.com** not the requested URL. I know I can configure a post login redirect, but this needs to be a fixed URL. Is it somehow possible for post authentication to redirect the user to where he/she intended to go?

**Comment by anthonychu** [comment]
I don't think this is possible right now, though it's something we should look into supporting. @mkarmark any suggestions?

**Comment by Roger-Sa** [comment]
I am reading [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url) that, due to security implications:
> According to the OAuth 2.0 specification (section 3.1.2 of RFC 6749), a redirection endpoint URI must be an absolute URI.

and:

> If you have several subdomains and your scenario requires that, upon successful authentication, you redirect users to the same page from which they started, using a state parameter might be helpful.

I presume this can be done with custom authentication. I also presume most prefer to just use the built-in authentication. If you (Microsoft) implement this for the built-in authentication, and automatic redirection is out of the question for security reasons, then probably make the requested URL available somehow (some endpoint similar to /.auth/me perhaps?).

**Comment by rellis-of-rhindleton** [comment]
I found this on [Customize sign-ins and sign-outs](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-customize-sign-in-out) — would it be applicable to Static Web Apps as well?

**Comment by brenoalvs** [comment]
Any news on this?
Currently I think the only way to do it is by implementing this kind of logic on the app side which does not make any sense when you are using the built in auth.

**Comment by mishapos** [comment]
We now support adding "post_login_redirect_uri=.referrer" to achieve the behavior of redirecting back to the page before the login flow started. Query parameters and fragments are not supported though.

**Comment by Roger-Sa** [comment]
@mishapos 
What is the correct usage exactly?

Tried this in staticwebapp.config.json:
```
{
   "route": "/login",
   "redirect": "/.auth/login/aad?post_login_redirect_uri=.referrer" 
}
```

But get redirected to **.../.auth/.referrer**

**Comment by msardi23** [comment]
I appended "?post_login_redirect_uri=.referrer" to a page in my site to quickly test this out. However, even with this additional parameter it still dropped me back to my sites home page.  My site is using the AAD authentication provider. Is this new feature still rolling out across Azure regions? Is there any other configuration needed to get this working?

**Comment by anthonychu** [comment]
This is a fairly new feature and we're waiting for query string support to be added, so we haven't documented it yet. You can only use it in a response override:

```json
{
    "routes": [
        {
            "route": "/*",
            "allowedRoles": [
                "authenticated"
            ]
        }
    ],
    "responseOverrides": {
        "401": {
          "statusCode": 302,
          "redirect": "/.auth/login/github?post_login_redirect_uri=.referrer"
        }
      }
}
```

**Comment by Roger-Sa** [comment]
Awesome! It works!

**Comment by msardi23** [comment]
> This is a fairly new feature and we're waiting for query string support to be added, so we haven't documented it yet. You can only use it in a response override:
> 
> ```json
> {
>   "routes": [
>     {
>       "route": "/*",
>       "allowedRoles": [
>         "authenticated"
>       ]
>     }
>   ],
>   "responseOverrides": {
>     "401": {
>       "statusCode": 302,
>       "redirect": "/.auth/login/github?post_login_redirect_uri=.referrer"
>     }
>   }
> }
> ```

This is great and works once changes are pushed back to Azure Static Apps service. 
However, the local auth emulator fails / hangs when the app is run locally with the swa cli. 
Is there a fix in the works for the swa cli or a work around available?

**Comment by manlm** [comment]
> This is a fairly new feature and we're waiting for query string support to be added, so we haven't documented it yet. You can only use it in a response override:
> 
> ```json
> {
>   "routes": [
>     {
>       "route": "/*",
>       "allowedRoles": [
>         "authenticated"
>       ]
>     }
>   ],
>   "responseOverrides": {
>     "401": {
>       "statusCode": 302,
>       "redirect": "/.auth/login/github?post_login_redirect_uri=.referrer"
>     }
>   }
> }
> ```

When I click the link on facebook workplace chat, this does not work. Are there any update on this case?

**Comment by nehaplay** [comment]
> We now support adding "post_login_redirect_uri=.referrer" to achieve the behavior of redirecting back to the page before the login flow started. Query parameters and fragments are not supported though.

@mishapos does this mean the encoding is also not supported (like %20 for space)? I tested and see that redirection works only as long as the URL does not contain a space.


Example:
**This works**: https://something.com/articles/EXTERNAL/README.html
**This does not work**: https://something.com/articles/INTERNAL/Some%20Configuration/Some%20Add%20User/Some%20Add%20User.html

**Comment by gbelenky** [comment]
does it also work in the swa cli during the local development?

**Comment by waterskijubilant** [comment]
This does not work if the link is clicked from another site.

**Comment by niand** [comment]
I am getting the same behaviour as mentioned above. The redirect to a specific subpage works on fresh browser, afterwords I end up on the root url again.

**Comment by MattParkerDev** [comment]
Has there been any progress on supporting query parameters in the post login redirect uri?
