### ISSUE TITLE
Static Web Apps with a .net core 3 functions

### ISSUE THREAD

**Issue by MikeAtETI** [Azure/static-web-apps#504]
Is there a way of getting this up-and-running with a net core 3 functions as backend - following the instructions at https://docs.microsoft.com/en-us/azure/static-web-apps/publish-devops - the VS Code doesn't seem to want to offer me the choice of generating a .net addin

**Comment by anthonychu** [comment]
@MikeAtETI Can you please share a bit more about the steps you took? That tutorial doesn't really focus on code so I'm interested in what you tried in VS Code and where you got stuck.

**Comment by MikeAtETI** [comment]
VS Code isn't my usual dev environment, but I cloned the git repository off azdo

Went to the Azure icon on the LHS, chose Functions - opened up "Local Project", then Functions, then highlighted "Functions" then chose "Create Function" in the toolbar and it created a new js function.

**Comment by MikeAtETI** [comment]
I found the blazor template from https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-blazor worked
