### ISSUE TITLE
Triggers are case-sensitive, but can't be hit because urls are case-insensitive.

### ISSUE THREAD

**Issue by nturinski** [Azure/static-web-apps#507]
Today, the platform allows users to create two HTTP triggers with the exact same name, but with just different casing.  For example:

`HttpTrigger1`
`HTTPTrigger1`

However, when attempting to hit those API triggers, you are unable to hit any specific function trigger because as far as the url is concerned, they're the same since the endpoint seems to be case-insensitive.

So `calmsands.azurestaticapps.net/API/HttpTrigger1` and `calmsands.azurestaticapps.net/API/HtTPTriGGer1` will end up hitting the same endpoint.

The portal displays both triggers, so I assume that the platform is creating both, but I'm not sure how you would be able to specify which one to serve.

See here for more context: https://github.com/microsoft/vscode-azurestaticwebapps/issues/422#issuecomment-869864360

**Comment by miwebst** [comment]
Hey @nturinski , this is not the expected behavior. Url's should be case-sensitive within static web apps.

**Comment by anthonychu** [comment]
I think this is an edge case in Functions that only happens when functions are created on Linux (or a Mac with case sensitivity enabled). Added comment in the linked issue. Static Web Apps is likely doing the right thing.

**Comment by nturinski** [comment]
@anthonychu Do you mean the system creating the SWA app or if the SWA app is a Linux VM?  Because I used a Windows 10 Pro machine to reproduce this behavior.

**Comment by anthonychu** [comment]
I couldn't create a second function with different casing on Windows.

![image](https://user-images.githubusercontent.com/3982077/126554930-73cb931c-9a5d-4b65-b308-5b182bd943c3.png)

But from what I've seen so far, I think this is a Functions/tooling issue. If a customer can somehow create 2 functions with the same name but different casing, the functions host seems to index them fine, but at runtime one route is hiding the other. It doesn't look like there's an issue with how SWA is proxying the call to functions. We should be able to repro this on Functions directly.

I think the fix might end up being in the tooling to prevent functions of the same name from being created.
