### ISSUE TITLE
Include app_location, api_location, and output_location as part of StaticSite metadata

### ISSUE THREAD

**Issue by nturinski** [Azure/static-web-apps#508]
**Is your feature request related to a problem? Please describe.**
Because we work with user's local projects, it would be nice to know when there is a discrepancy with their local `workflow.yml` vs. the `workflow.yml` that is used for the current build.

**Describe the solution you'd like**
If the StaticSite (or StaticSiteBuild) envelope could include these details when you get them from the ARM API, that would be ideal.  It would also be great if it could point to the specific `workflow.yml` file that was used to build the app.

**Describe alternatives you've considered**
We can look for the remote `workflow.yml` and compare it to their local copy to determine whether or not the value is stale.  However, it can be difficult to ascertain which yaml file is actually being used in the build if they have multiple.  We can't rely on the SWA naming convention since users can alter the name of their workflow yaml files.

**Additional context**
If I understand correctly, the Static Web App doesn't actually interact with the `workflow.yml`; that would all be handled by GitHub.  But it does know when there is a new build available and updates accordingly, so would it be possible to update any of those configuration settings in metadata simultaneously?

**Comment by miwebst** [comment]
Unfortunately this information is only available in GitHub today. A user's GitHub token is not saved within the platform and as a result our information would grow out of sync when users update their workflow files. Similarly, for the same reason you described with keying off a users workflow file name, even if we maintained the token its unlikely we could use it to fetch this data.
