### ISSUE TITLE
`staticwebapp.config.json` build error

### ISSUE THREAD

**Issue by iomariani** [Azure/static-web-apps#511]
I'm trying to configure my first Static WebApp using Vue.js app,
but after adding the `staticwebapp.config.json` file it is giving the following build error:

```log
Finished building app with Oryx
Using 'staticwebapp.config.json' file for configuration information, 'routes.json' will be ignored.
Encountered an issue while validating staticwebapp.config.json: Could not read and deserialize the provided routes file.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

I've changed nothing on the .yml file Azure generates,
so my `app_location` is `/` and the config is at the root just as default.
I've configured it just like the [documentation on microsoft website](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#fallback-routes) says.

```json
{
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
  }
}
```

**To Reproduce**
1. `vue create test`
2. `cd test`
3. Add the config file
4. Push the folder content to a rep
4. Create the App on Azure website (changed nothing on the  .yml file, using default)
5. Check deploy on GitHub actions

**Expected behavior**
Apply the navigationFallback from the `staticwebapp.config.json`and proceed with the deploy.

**Comment by iomariani** [comment]
Got it working  now...
Apparently it expects the `routes` to be declared.
Even if the entire app goes through `index.html`, which is pretty common on static vue +  vue-router or vuepress apps...

I've just added a `"routes": []` and it did the trick 🙌🏻

```json
{
  "routes": [],
  "navigationFallback": {
    "rewrite": "/index.html",
    "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
  }
}
```

Leave here my notes, in case someone stumble upon this same issue as well.

**Comment by miwebst** [comment]
Oh interesting, we will take a look. Thanks for reporting this!
