### ISSUE TITLE
docs - incorrect configuration provided for custom AAD authentication

### ISSUE THREAD

**Issue by bartusz01** [Azure/static-web-apps#513]
**Describe the bug**
Managed to get custom AAD authentication working, where I can now assign roles to AAD security groups. However, I tried a slightly different configuration, since the one from the [docs](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#configuration) isn't working. I changed ```registration.clientIdSettingName``` into ```registration.clientId```. See below for the current conf in the docs and how it should be.
```json
{
  "auth": {
    "identityProviders": {
      "azureActiveDirectory": {
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/<TENANT_ID>",
          "clientIdSettingName": "<AAD_CLIENT_ID>",
          "clientSecretSettingName": "<AAD_CLIENT_SECRET>"
        }
      }
    }
  }
}
```
should be
```json
{
  "auth": {
    "identityProviders": {
      "azureActiveDirectory": {
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/<TENANT_ID>",
          "clientId": "<AAD_CLIENT_ID>",
          "clientSecretSettingName": "<AAD_CLIENT_SECRET>"
        }
      }
    }
  }
}
```

**edit: custom Authentication is still not working for me, my goal is to allow specific AAD (security) groups to access the static app**

**Comment by davezuko** [comment]
@bartusz01 I'm running into similar issues with custom AAD configuration and stumbled upon your issue. I'm curious to learn why you closed it; is it truly incorrect in the docs, or did you figure something else out? I've been bashing my head against the wall for the last hour trying to make sense of the documentation and what I could possibly be doing wrong.

**Comment by bartusz01** [comment]
Hi @davezuko, I found out afterwards it was not working as I expected. I have the feeling that both solutions in this issue are fine, the one I suggested (when providing the ```AAD_CLIENT_ID```) and the one in the docs (where you do not specify the ```AAD_CLIENT_ID```, but a reference to the ```AAD_CLIENT_ID``` that is set on your static app settings).  

About the ```TENTANT_ID``` you mentioned. I think here indeed the direct value is required and not a reference. Wich is fine right, as its not really confidential. 

Anyways, overall it seems like the docs are not right or at least incomplete, since we can't get custom AAD authentication to work. Last time I closed this, because it took me too much time and I could not continue with it, but I will reopen it and hopefully someone can provide whats missing in the docs/the correct way to set up custom AAD authentication.

**Comment by davezuko** [comment]
Thanks for the reply, @bartusz01. I was wondering if you had managed to get it work, and it's unfortunate to hear that that's not the case. I'm similarly abandoning my efforts for now.

**Comment by anthonychu** [comment]
Sorry for the confusion. Here's an concrete example that should work:

```json
{
  "auth": {
    "identityProviders": {
      "azureActiveDirectory": {
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/583c845c-54b5-4803-adf6-1d364518f545",
          "clientIdSettingName": "AAD_CLIENT_ID",
          "clientSecretSettingName": "AAD_CLIENT_SECRET"
        }
      }
    }
  }
}
```

The `clientIdSettingName` and `clientSecretSettingName` values should be the names of the app settings that contain the actual client id and secret. I think that's where the confusion is. With the above example, create these app settings:

![image](https://user-images.githubusercontent.com/3982077/127365051-4ef18b1b-73cf-43c0-99a0-5c57f9bba9ef.png)

We'll update the docs to clarify this.

**Comment by davezuko** [comment]
Thanks @anthonychu, clarifying this in the docs will be a huge help to others. I did eventually figure out what the docs meant to say, but nonetheless could not get the SWA to respect my custom AAD configuration. I will try again with the additional `userDetailsClaim` key and see if that produces different results. If it doesn't, would you prefer feedback here or in a separate issue?

**Comment by anthonychu** [comment]
Either in this issue or a new one would be fine. /cc @mkarmark

**Comment by bartusz01** [comment]
@anthonychu Thanks for your reply, but I have tried also your solution before and it did not work for me.  Imagine the following ```staticwebapp.config.json```: 
```json
{
  "routes": [
    {
      "route": "/*",
      "allowedRoles": ["reader"]
    }
  ],
  "responseOverrides": {
    "404": {
    "rewrite": "/404.html"
    },
    "401": {
      "statusCode": 302,
      "redirect": "/.auth/login/aad"
    }
  },
  "auth": {
    "identityProviders": {
      "azureActiveDirectory": {
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/xxx",
          "clientIdSettingName": "AAD_CLIENT_ID",
          "clientSecretSettingName": "AAD_CLIENT_SECRET"
        },
        "userDetailsClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" 
      }
    }
  }
}
```

When I use 'Role Management' on the static app, I can assign the 'reader' role to a single person and everything works as expected. However, I would like to be able to assign access to AAD securitygroups. So on the app registration that is provided in the config above I created the 'reader' appRole, but I have no idea how to link the 'reader' appRole with the 'reader' role provided in the config above. When this appRole is assigned to  a group/person, it will not give them access unfortunately.

**Comment by bartusz01** [comment]
Hi, any update on this? I'm not even sure if its possible to use AAD groups for authentication right now.

**Comment by jon-a-nygaard** [comment]
@bartusz01 I came across the following comment (https://github.com/Azure/static-web-apps/issues/525#issuecomment-887698203) about AAD Roles in SWA, and I assume it is also somewhat related to roles assigned through AAD Groups as well.
No ETA mentioned so far, but maybe there will be an update in the issue thread in the future.

**Comment by bartusz01** [comment]
Thanks @jon-a-nygaard  

Closing this issue as #525 is more clear and more likely to get an update on support for AAD groups/custom app roles.
