### ISSUE TITLE
401 received by authenticated users after some time

### ISSUE THREAD

**Issue by lenniebriscoe** [Azure/static-web-apps#517]
**Describe the bug**
Users have been invited to a Static Web app using the Active Directory security provider link in Role management and successfully registered. After a period of time their access expires and they are no longer able to log into the Static Web App and are always presented with a 401.

**To Reproduce**
1.  I have created invitations using AD as an Authentication provide, given the 'reader' role and used the default expiration.
2.  My users click on the provided link and register. I can then see their role in the Static Website Role Management page.
3.  The users are able to successfully access the secured page by navigating to the URL of the static web app.
4. After a period of time (possibly a week although undetermined) the users are incorrectly no longer able to reach the secured static web app by the domain url and receive a 401. 
5. Removing their role from the Static Website Role Management page and re-inviting them seems to re-allow them access. 

my staticwebapp.config.json has the following:
```
{
    "routes": [
      {
        "route": "/*",
        "allowedRoles": ["authenticated"]
      }
    ]
  }
```
**Expected behavior**
A pre-authenticated user is able to access the site once authenticated without expiry. If login has expired they should be prompted to re-login

**Screenshots**

**Device info (if applicable):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22]  91.0.4472.164 (Official Build) (64-bit)

**Additional context**

**Comment by Zhiyuan-Amos** [comment]
> If login has expired they should be prompted to re-login

I believe this can be done by following this [documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#response-overrides). In summary, add the following code to your `staticwebapp.config.json`.

```json
"401": {
  "statusCode": 302,
  "redirect": "/login"
}
```

**Comment by lenniebriscoe** [comment]
The [documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization) wasn't that clear . For a vanilla AAD login flow you need to put in the provider-specific routes for login/out as well as the redirect:

`{
    "routes": [
        {
            "route": "/login",
            "redirect": "/.auth/login/aad"
        },
        {
            "route": "/logout",
            "redirect": "/.auth/logout"
        },
        {
            "route": "/*",
            "allowedRoles": ["authenticated"]
        }
    ],
    "responseOverrides": {
        "401": {
            "statusCode": 302,
            "redirect": "/login"
          }
      }
  }`
