### ISSUE TITLE
Documentation about how the auth flow works

### ISSUE THREAD

**Issue by brenoalvs** [Azure/static-web-apps#518]
First of all, thanks for this nice service!
I'm using a custom authentication provider and the auth flow is working pretty fine.

Now, my team wants to write some e2e tests but we're struggling with some limitations from CyPress to test cross-origin flows with external auth providers. We also tried other test tools but with no success.

CyPress recommends to do it programmatically and we're using the following guide as reference:
https://docs.cypress.io/guides/testing-strategies/google-authentication#Setting-Google-app-credentials-in-Cypress

But we're not sure how to make our app understand the access tokens that we grab by hand from our auth service.

Can you help us with this? Is there any docs referencing how the auth flow works?

cc: @baguilar-work

**Comment by manekinekko** [comment]
Hey, @brenoalvs I don't personally recommend doing e2e test against real auth providers because auth tokens/data isn't deterministic. I'd rather recommend setting up mocked data for that.

We're using a similar technique with cypress to e2e test our SWA CLI: https://github.com/Azure/static-web-apps-cli.

I hope that'll help.

**Comment by brenoalvs** [comment]
@manekinekko Many thanks for your help!! This helped us a lot in design our tests.
I think the way you encode the cookies to mock worths at least a note in the docs.

But in our case the auth provider is a FusionAuth instance maintained by our company, so we wanted to test it in the flow too.

What we've done:
We created a Selenium setup script that logs in and saves the real cookie from the app into a temp static file.
Then we can use it as a mock in all our Cypress tests.

Kind of hacky but it's working very well!
