### ISSUE TITLE
Static Web App Config - allowed roles for API - case sensitivity - Security concern

### ISSUE THREAD

**Issue by arisabejuela** [Azure/static-web-apps#521]
Feature to allow/ block API request is not working as expected.

**staticwebapp.config.json**
`{
      "route": "/api/getSubscList",
      "allowedRoles": ["contributor", "reader"]
 }`

Upon checking, if I'm unauthenticated and I try to send a GET request to this URL:
https://<auto-generated-url>.azurestaticapps.net/api/getSubscList
I'll get Unauthorized response (expected outcome).

but if I change the URL to:
https://<auto-generated-url>.azurestaticapps.net/api/getsubsclist
or
https://<auto-generated-url>.azurestaticapps.net/api/getSubscLisT
my request will go through even though I don't have the required roles.

**Comment by AverageCakeSlice** [comment]
I'm interested in this issue, does it behave differently if you change the casing of the route parameter to all lowercase?

**Comment by miwebst** [comment]
Thanks for raising this @arisabejuela. We are looking into this!

**Comment by arisabejuela** [comment]
Hi @AverageCakeSlice, it behaves the same (case sensitive).

If you configure staticwebapp.config.json like this:
`{ "route": "/api/**getsubsclist**", "allowedRoles": ["contributor", "reader"] }`

then, unauthenticated, you send GET request to: 
**https://xxxxx.azurestaticapps.net/api/**getsubscLIST****
you'll get a successful response.

**Comment by arisabejuela** [comment]
@miwebst that was quick. Thank you.
Upon checking, issue is already fixed. Great work!
