### ISSUE TITLE
Angular web app routing issue

### ISSUE THREAD

**Issue by AmithaBattul** [Azure/static-web-apps#523]
We have deployed our angular 9 SPA application to azure storage container. When I try to browse the application just with the base address, I am successfully being redirected to the home page. But, when I try https://baseaddress/home, I get 404 - web content not found issue. This issue occurs for all the routes not for the home route alone. When the routing happens through user events like clicking on the hyperlink, the routes work as expected. Public access level is set to Blob (I have tried with the value container also). Please suggest.

**Comment by manekinekko** [comment]
Hey @AmithaBattul this repository is for the Azure Static Web Apps service questions/issues only. Are you able to migrate your app from Blob storage to Azure Static Web Apps?

If you still have to use Blob storage, then you have to use Azure CDN and create a URL rewrite rule: 

1. Add a new rule
1. Condition: URL file extension
  a. Operator: Less than
  b. Extension: 1
  c. Case transform: No transform

1. Action: URL rewrite
  a. Source pattern: /
  b. Destination: /index.html
  c. Preserve unmatched path: No
1. Save rule

Read more from [our docs](https://docs.microsoft.com/en-us/azure/cdn/cdn-standard-rules-engine?WT.mc_id=javascript-0000-wachegha).
