### ISSUE TITLE
Failure during content distribution

### ISSUE THREAD

**Issue by LiserLine** [Azure/static-web-apps#53]
Hi,

Im trying to deploy my static website but the following error occurs in the "Build and Deploy" stage:

_Failure during content distribution_

I added new files/folders in the example repository ([docs](https://docs.microsoft.com/pt-br/azure/static-web-apps/getting-started?tabs=angular#create-a-repository))... I don't know if some files cannot be there (didn't find any info in the docs). I'm missing something?

Here is the example repo [repo](https://github.com/LiserLine/statictest)

**Comment by LiserLine** [comment]
"Solved" the problem by deleting all libraries (**vendor** folder) and using CDNs instead.

Could't find a reason why this works...

**Comment by joslinmicrosoft** [comment]
Hi @LiserLine,

We had a deployment bug that has been identified, and the fix will be applied the next time we upgrade the platform. Thank you for reporting the issue, and for using Static Web Apps!

**Comment by miwebst** [comment]
We've updated the error messages that would have clarified this issue. Closing.
