### ISSUE TITLE
navigationFallback/responseOverrides staticwebapp.config.json settings

### ISSUE THREAD

**Issue by StueyKent** [Azure/static-web-apps#530]
**Describe the bug**
 
Neither the navigationFallback or responseOverrides appear to be working in my app. I have my configuration set so that 404.html should be served if a route could not be found

**To Reproduce**
1. Go to https://blue-dune-04ca69803.azurestaticapps.net/jazz'

```json
{
  "navigationFallback": {
    "rewrite": "/404.html"
  },
  "responseOverrides": {
    "404": {
      "rewrite": "/404.html",
      "statusCode": 200
    }
  },
  "globalHeaders": {
      "content-security-policy": "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' *.gstatic.com data:;"
    },
    "mimeTypes": {
      ".json": "text/json"
    }
}
```

**Expected behavior**
I am expecting the custom [404](https://blue-dune-04ca69803.azurestaticapps.net/404) page i ahve created and not the azure one.

100% this could be down to something I am doing wrong, I tried specifying each individual route but still got the same behaviour. This functionality was working at some point with the current configuration, has something change with SWA?

**Comment by StueyKent** [comment]
**Update**
Looking back through my git history I have found what is causing the 404 to break.

I can't explain it but setting [trailingSlash](https://nextjs.org/docs/api-reference/next.config.js/trailing-slash) in my next.config to true will cause the responseOverrides to stop working.

Their docs suggest that '/jazz' will redirect to '/jazz/', as this route will still not be found why is SWA not using the override set in configuration?

**Comment by anthonychu** [comment]
Looks like the 404 page is located at `/404/index.html`. `/404.html` doesn't exist in the generated site, which is why it's serving the default 404 page. Suggest updating the config to the following:

```json
{
  "responseOverrides": {
    "404": {
      "rewrite": "/404/index.html",
      "statusCode": 404
    }
  },
  "globalHeaders": {
      "content-security-policy": "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self' *.gstatic.com data:;"
    },
    "mimeTypes": {
      ".json": "text/json"
    }
}
```

Looks like this is specifically a custom 404 page scenario, so there's no need to use the navigation fallback rule here. Also, you might want to consider returning status code 404 when a page is not found, instead of 200. Otherwise Google might index the page.

**Comment by StueyKent** [comment]
Nothing wrong with SWA, changing the next.config, changes the output structure of the SSR. 

Amazing quick response.
