### ISSUE TITLE
Static Web App Config with `customOpenIdConnectProviders` returns 404.

### ISSUE THREAD

**Issue by ChuckJonas** [Azure/static-web-apps#532]
**Describe the bug**

According to official [the docs](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad) and other [online resources](https://www.aaron-powell.com/posts/2021-05-13-using-okta-with-static-web-apps/), creating a `staticwebapp.config.json` and configuring it with `customOpenIdConnectProviders` should allow you to login via `/.auth/login/<PROVIDER_NAME_IN_CONFIG>`.

I've tried this many different ways, but no matter what I do, navigating to `/.auth/login/<PROVIDER_NAME_IN_CONFIG>` returns a 404.

**To Reproduce**
1. Fork [this repo](https://github.com/aaronpowell/swa-custom-auth-okta)
2. clone down, delete github actions file, push back up
2. In Azure Portal, create a new SWA from github repo (forked in previous step)
3. Setup Okta as outlined in [this blog ](https://www.aaron-powell.com/posts/2021-05-13-using-okta-with-static-web-apps/)
4. Setup App Settings for clientid & client secret
5. update `wellKnownOpenIdConfiguration` to okta domain
5. Deploy App
6. Navigate to `/.auth/login/okta`
7. Site will return 404

**Expected behavior**
I would expect `/.auth/login/okta` to take me to the login

**Screenshots**
<img width="1531" alt="Azure_Static_Web_Apps_-_404__Not_found" src="https://user-images.githubusercontent.com/5217568/128110646-3b2282df-150a-4058-9745-d2f0dda96592.png">

**Additional context**

I feel like there must be a step missing from both the official documentation and the blog listed above. Has something changed to how `staticwebapp.config.json` are setup?

**Comment by ChuckJonas** [comment]
nvm, it apparently need to be a "standard" tier.

**Comment by anthonychu** [comment]
Sorry about that! @miwebst Is it possible to validate this at deployment time and print an error message?

**Comment by miwebst** [comment]
Yes this is something we can improve upon for sure! Thanks for surfacing!
