### ISSUE TITLE
Failed deploy Vue app to Azure, with package-lock.json generated by npm 7.x

### ISSUE THREAD

**Issue by justinyoo** [Azure/static-web-apps#534]
* I'm following the Microsoft Learn module: https://docs.microsoft.com/learn/modules/publish-static-web-app-authentication/2-exercise-get-started?pivots=vue
* This is the repo: https://github.com/justinyoo/my-static-web-app-authn
* The current `package-lock.json` was generated by npm 7.x
* Oryx has npm 6.x

**Approach 1:**

* Due to the npm issue, I've updated the GitHub Actions workflow by overriding the environment variable:
  https://github.com/justinyoo/my-static-web-app-authn/blob/e05f43bdf8e027d97b297210b2c1b223ed33b5cd/.github/workflows/azure-static-web-apps-calm-dune-008669010.yml#L24-L25

However, I've got the error like: 
![image](https://user-images.githubusercontent.com/1538528/128356679-d4bcb5ae-c6b3-4d2e-ac57-5aac0a9e674e.png)

It's totally working fine on the local machine, but not on GitHub Actions. It's similar to #531 but the Vue app has the `index.html` file in the `public` directory.

**Approach 2:**

* I removed/excluded the existing `package-lock.json` file from the repository
* I removed the environment variable override from the GitHub Actions workflow

Then, it was successfully deployed.

---

Seems that Oryx doesn't like the forced npm version update. 🤔

**Comment by kooljay82** [comment]
It's very weird. `Approach 1`, above, passed course before, very similar to this course. But it fails.

**Comment by anthonychu** [comment]
Related #533 

@arroyc

**Comment by simonaco** [comment]
This should be fixed with the latest version of oryx
