### ISSUE TITLE
Fails to Deploy with any Submodules

### ISSUE THREAD

**Issue by joelbyford** [Azure/static-web-apps#535]
Only 1 change and fails to build.  Can replicate over and over again.  Simply doing a `git submodule init` with a `git submodule update` during the build will fail the deployment with a message of:

`Deployment Failed :(
Deployment Failure Reason: Failure during content distribution.`

This works:
```
      - name: Checkout Repo
        uses: actions/checkout@v2
```

This does not work:
```
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          - submodules: true
```

This also does not work:
```
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Checkout Submodules
        run: git submodule update --init
```

**To Reproduce**
1. Add a submodule to the repo.
2. Add a submodule init and submodule update to the build pipeline
3. Attempt to use the Azure/static-web-apps-deploy@v1 workflow action
4. See it fail.

You're welcome to see the example pipelines here: https://github.com/joelbyford/XmlClassroom.  Nothing complex about it. . .a simple html website with a single submodule (the JavaScript editor widget). 

**Expected behavior**
Publish success.

**Screenshots**
N/A

**Device info (if applicable):**
N/A

**Additional context**

**Comment by anthonychu** [comment]
I can repro this. The main difference between this and apps like Hugo which use submodules and experience no issues is that here we are deploying the entire folder, including the submodule. For Hugo, we're deploying the build output folder, which doesn't include the submodule folder itself.

**Comment by joelbyford** [comment]
Understood, and thanks for looking into it.  Knowing this, I modified the yml file to perform a copy/paste of the needed files to a staging `output` directory and use that directory as the source for static web app publish action.  Perfectly acceptable workaround.  Thanks!
