### ISSUE TITLE
vuepress deployment github action fails with oryx syntax error

### ISSUE THREAD

**Issue by richardw16** [Azure/static-web-apps#54]
Following https://docs.microsoft.com/en-us/azure/static-web-apps/publish-vuepress

Azure Static Web Apps CI/CD / Build and Deploy Job (Azure/static-web-apps-deploy@v0.0.1-preview) fails with SyntaxError:
![vuepress](https://user-images.githubusercontent.com/64897108/84203459-c20c4380-aaa9-11ea-9f24-3241a51bad91.PNG)

**Comment by miwebst** [comment]
@kichalla can you take a look?

**Comment by kichalla** [comment]
@richardw16 Thanks for reporting the issue. On investigation we found that `vuepress` does stuff in a particular way which is currently not compatible with the build engine (Oryx) that Static Web Apps use. We are currently working on to fix this issue. Meanwhile the workaround you can use is to put `vuepress` in `dependencies` node and _not_ in `devDependencies`.

**Comment by kichalla** [comment]
Just FYI...we are making a fix for this in Oryx. I will update this thread once it is available in Static Web Apps. Thanks.

cc @miwebst

**Comment by miwebst** [comment]
Hi @richardw16 , we have updated the version of Oryx running on our Github Action, can you retry and see if you hit the same error?

**Comment by richardw16** [comment]
thank you very much! now it is working:
![azure](https://user-images.githubusercontent.com/64897108/89586194-8985ad80-d83f-11ea-95b7-ba52bd00f84d.PNG)
