### ISSUE TITLE
Securing Static Web Apps + Cosmos DB access

### ISSUE THREAD

**Issue by lucashfreitas** [Azure/static-web-apps#546]
Hello,

I am quite new to Azure and I've got some questions and could not find any docs for them. Sorry in advance if this is duplicated or there are already docs for this. 

1) I want to make sure that my web static apps will be accessible ONLY from connections originated from our external firewall. Are we able to change network settings to allow only a subset of IP addresses? 

The only docs I've found was in the section to deploy using ARM templates (https://docs.microsoft.com/en-us/azure/static-web-apps/configuration):

```
{
  "networking": {
    "allowedIpRanges": [
      "10.0.0.0/24",
      "100.0.0.0/32",
      "192.168.100.0/22"
    ]
  }
}

```

I could not see any related setting in docs/Azure portal.

2) Azure Static Apps/Functions are global. What is the way to go to allow access to Cosmos DB? Basically, I don't want to leave my Cosmos DB accessible for the internet and ONLY by the Azure functions. (Maybe this question is more related to CosmosDB)

**Comment by glaucia86** [comment]
cc: @anthonychu

**Comment by lucashfreitas** [comment]
Hi @miwebst. Thanks :) 

I tried to find more content about it but didn't find. Also make a post on twitter to see if anyone from cosmos db team has any suggestions.

Cheers,

**Comment by lucashfreitas** [comment]
Currently it's not possible to use IAM roles in functions deployed with azure static web apps. We should deploy the function separated and attach it to Static Web app after. 

As mentioned here https://github.com/Azure/static-web-apps/issues/567 this might be available in the future.
