### ISSUE TITLE
Allow : character in configuration

### ISSUE THREAD

**Issue by mumby0168** [Azure/static-web-apps#548]
.NET Core can make use of configuration providers which look for the `:` as a separator such as `RepositoryOptions:CosmosConnectionStirng` but the UI does not let me use a variable containing `:`

![image](https://user-images.githubusercontent.com/23740684/129449719-3447aeab-0f8d-4383-bd5a-dca98805f006.png)

**Comment by anthonychu** [comment]
.NET also supports using double underscore (`__`) instead of `:`. Please try that instead. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#environment-variables

**Comment by mumby0168** [comment]
Ah that is perfect my bad always seemed to use `:` thanks 👍
