### ISSUE TITLE
Azure Static Web App - Github Workflow - Api Deploy is not flexible/doesn't work for custom folder structure

### ISSUE THREAD

**Issue by lucashfreitas** [Azure/static-web-apps#549]
Hello,

Github workflow file allows us to set up an **output_location** for the FRONTEND app but it doesn't specify any output location for the API.  It does allow to set up a build command for the API but how it automatically identifies the API out directory? What if we using mono repository/typescript and have it in a different folder? How can I instruct the workflow to look for a specific folder?

**Comment by anthonychu** [comment]
Do you have a repo with this issue that we can look at?

**Comment by lucashfreitas** [comment]
Hey @anthonychu, thanks for the quick reply.

Unfortunately, the project it's private, but I am happy to spin up a demo if the explanation below is not 100% clear.

Basically, GitHub workflow seems to not be flexible enough regarding the API build & output folder. Depending on your project setup, folder, the API build won't be in the same folder as the frontend build. Let's consider this scenario where you have both frontend and api folder on different locations:

```
frontend-dist
   assets
   static

backend-dist
  host.json
  myFunctionDir

```

The workflow YAML only accepts an `output_location`, so I imagine it expects to see a folder named by API together to the main output location, right? Considering the above scenario how github workflow would "guess" the API folder if there is no option to instruct it?

**Comment by lucashfreitas** [comment]
Another thing: I can't instruct the workflow to skip the API BUILD process and only do the deploy? Currently, the `api_build_command` is empty but it seems the github workflow is still trying to execute `yarn run build` in the API base directory. 

I am following this guide: https://docs.microsoft.com/en-us/azure/static-web-apps/github-actions-workflow but I can't manage to deploy my API as we're using many packages/mono repositories and currently it's not possible to specify a custom folder for the API.

I did a workaround to manually `cp` all the API/Functions JS files to a folder named by API inside the `app_output` dir but the workflow is trying to build the API despite I haven't set up a build command for it.

**Comment by lucashfreitas** [comment]
Update: I managed to manually build & copy the API files and copy it inside the same app `output_folder`, but now the workflow is not able to guess that the project is using nodejs and is returning `The function language detected is unsupported or invalid`. It's a bit strange as the api folder has a package.json, so it's pretty guessable that we're using nodejs. 

It seems the only solution would be to refactor our monorepository/folder structure to satisfy the workflow.

**Comment by anthonychu** [comment]
Can you share more of your workflow? Are you relying on the Static Web Apps deploy action to build the app, or are you added additional steps before it to build the app?

For monorepos, it’s best to set up your own steps to build the app and rely on our action to deploy it. As you’ve noted, there’s no way to just deploy the API output without building. That is tracked in #343 and likely to be addressed in a few months. For now, you might be able to trick it into doing the right thing by running `npm init -y` to create an empty package.json file in the backend-dist folder and pass it as the api_location. The build will run but it should be a no-op and we should detect it as a Node function app.

**Comment by lucashfreitas** [comment]
Hey @anthonychu , thanks! I have completely removed static web apps deploy action and had to do a workaround to manually build and output the frontend/api folder in a way that the static web app expects it. I've also added a package.json in the folder, otherwise, it won't work. 

We're using typescript/monorepository structure and I tried other alternatives but only the above worked. Sorry for being late to reply.

**Comment by lucashfreitas** [comment]
Closing that for now.

**Comment by gorootde** [comment]
> I have completely removed static web apps deploy action and had to do a workaround to manually build and output the frontend/api folder in a way that the static web app expects it. I've also added a package.json in the folder, otherwise, it won't work. 

@lucashfreitas I am blocked by the very same issue. Can you share how you achieved the above?

**Comment by anthonychu** [comment]
We're working on a couple of things. First is to allow you to specify the language (and language version) for the function app. Once that's possible, add support for `skip_api_build` #343. @simonaco @Reshmi-Sriram  can share updates on progress.
