### ISSUE TITLE
Support for x11 in GitHub Action build container

### ISSUE THREAD

**Issue by georgechang** [Azure/static-web-apps#55]
I'm using [Mermaid.js](https://mermaid-js.github.io/) on a Gatsby site and to render the charts, it uses [Puppeteer](https://developers.google.com/web/tools/puppeteer) which has a dependency on the x11 library in Linux. Currently it doesn't look like the container where the static web apps get built has that package installed - is this something that can be included in the standard build container? Thanks!

Here's the error that happens when I try to build the static site:

```
Failed to launch the browser process!
/bin/staticsites/ss-oryx/app-int/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by anthonychu** [comment]
@georgechang As a workaround, does the default GitHub Actions environment allow you to run the build in a separate step instead of relying on the Static Web Apps deploy step to do it?

IMO it'd be nice to support add these dependencies, though I think they add ~250MB to the image.

**Comment by georgechang** [comment]
@anthonychu I don't know why I didn't think of adding steps to just install any dependencies. Thanks for waking my brain up!
