### ISSUE TITLE
Deployment Failed: Failure during content distribution.

### ISSUE THREAD

**Issue by tuube** [Azure/static-web-apps#550]
Hello! Our deployments are suddenly failing with an unclear error message:
![image](https://user-images.githubusercontent.com/19163063/129557409-fd41caf4-ced4-4e4e-ba43-d9962d08a630.png)

Only thing that changed was that there's now much more content than before, now about 350MB.
Any idea what could be causing this?

**Comment by andreaslarssen** [comment]
@tuube Did you figure this one out? I get the same msg

**Comment by tuube** [comment]
Yes we did, forgot to mention here 🤦. 

The trick was to "sanitize" our created pages' paths.

Before we had paths with non-ascii characters like: "/koskâvuotâ/ohtsâškoodán-päikkikuávlu-mun-tiäđám",
which were changed to: "/koskavuota/ohtsaskoodan-paikkikuavlu-mun-tiadam".

After that the deploys started working

**Comment by andreaslarssen** [comment]
@tuube ok, thanks. Seems like there's been an Azure bug that has been fixed lately
