### ISSUE TITLE
Specify a pool of known URLs for pull request previews

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [Azure/static-web-apps#551]
**Is your feature request related to a problem? Please describe.**
A single page app on Static Web Apps that uses in-app authentication (as opposed to the built-in auth, or “easy auth”) needs to know what URL to use for login redirects. For the production instance of the site, this is known. But for the non-production/preview instances that get created from pull requests it is not. There’s no easy way that I can tell to have Azure AD redirect after login to the correct site.

**Describe the solution you'd like**
I wondered if you could let me enter a pool of URLs (or just give me a set) that I can pre-approve in the Azure AD app registration. When you create a new site from a pull request, map it to one of those, instead of one that has never existed (or in addition to it). That way I can have the redirect URL already registered.

**Describe alternatives you've considered**
I’m open to suggestions here :)  Really just need a way to list any login redirect URI in advance, so I don’t have to go enter it after the pull request has been processed.

**Comment by anthonychu** [comment]
There are some related issues such as #22.

We're currently looking into allowing you to have stable staging environments that you deploy to by pushing to its corresponding branch. For instance, you could have a `test` branch that you push to, and it deploys to a staging environment named "test". It would have a stable URL that you can register with your auth providers. Would this work for your scenario here?

**Comment by rellis-of-rhindleton** [comment]
Yes it would.

**Comment by a2441918** [comment]
Or you can also write a powershell script which will add the generated url to the list of redirect uris??

**Comment by Reshmi-Sriram** [comment]
Apologies, we missed on updating this issue thread!
Static Web Apps announced support for [Named Preview Environments ](https://docs.microsoft.com/en-gb/azure/static-web-apps/named-environments?tabs=github-actions) as well as [Stable Staging Preview Environments ](https://docs.microsoft.com/en-us/azure/static-web-apps/preview-environments)in May 2022. This enables one to add a custom prefix to the default generated URL.

Do let us know if this helps solve your problems! :)

**Comment by rellis-of-rhindleton** [comment]
Can't speak for others in this thread, but I think this is good enough for us. Thanks.

**Comment by Reshmi-Sriram** [comment]
Marking as resolved. Feel free to reopen if required!
