### ISSUE TITLE
Content-Disposition header is not returned from a Static Web App Managed Api

### ISSUE THREAD

**Issue by mschoneman** [Azure/static-web-apps#553]
**Describe the bug**

`Content-Disposition` header is not returned from a Static Web App Managed Api

**To Reproduce**
1. Create a static web app with an api
2. Include the following function:
```
        [FunctionName("GetCsv")]
        public async Task<IActionResult> RunGetCsvAsync(
                    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequest req)
        {
            ...Code to generate memory stream omitted...

            return new FileStreamResult(memoryStream, "text/csv")
            {
                FileDownloadName = $"Sample-{DateTime.Today.ToString("yyyy-MM-dd")}.csv",
            };
        }
```
3. Code runs fine in the local dev environment and the `Content-Disposition` header is returned
4. Deploy to Azure Static Web App
5. Access the link "/api/GetCsv"
6. Note that the `Content-Disposition` header is not returned.

**Expected behavior**
`Content-Disposition` header should be returned.

**Comment by danbasszeti** [comment]
Just hit this bug with my content-disposition header being stripped off. Is there any workaround I can do?

**Comment by anthonychu** [comment]
@miwebst @mkarmark Could you please take a look?

**Comment by danbasszeti** [comment]
Hi - for anyone affected by this, if you are using an anchor or button to direct the user to the API url and are trying to use the Content-Disposition header to set the filename etc, then you can achieve this by setting the 'download' attribute on the anchor or button to something with the correct filename. This enabled my users browsers to recognize the downloads as CSV's and open in Excel. Details on this here: https://www.w3schools.com/tags/att_a_download.asp

**Comment by chris-digitise** [comment]
I've noticed this seems to be working now - was it fixed?

**Comment by miwebst** [comment]
Yes we shipped a fix for this recently!
