### ISSUE TITLE
[Bug or incorrect docs] Incorrect type. Expected "integer" for routes status code

### ISSUE THREAD

**Issue by sinedied** [Azure/static-web-apps#554]
**Describe the bug**

The built in validator for `staticwebapp.config.json` file reports this error on route status code when it's defined as a string:
![image](https://user-images.githubusercontent.com/593151/130076854-95819e2c-a61e-4aaf-af73-64008006fda2.png)

But the docs states that a string should be used here, ie: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization#block-an-authorization-provider
And also, it's working when using a string.

I posted the issue on extension repo: https://github.com/microsoft/vscode-azurestaticwebapps/issues/490 but it seems they're not maintaining the validation schema, so it might be the better place here to ask for a clarification 😃 

What is the correct syntax to use here then, is the validation schema wrong or should the docs be fixed?

**Comment by anthonychu** [comment]
Good question. From what I can tell, the service expects int's, but it's able to deserialize correctly if it's a string containing an int.

@mkarmark can you please confirm? If correct, I think we should update docs to use int's.

**Comment by anthonychu** [comment]
Checked and confirmed the service expects ints (though strings work). Updated doc to int. Thanks!

**Comment by sinedied** [comment]
Thanks for the confirmation, I'll update the related Learn modules then
