### ISSUE TITLE
CosmosDb binding

### ISSUE THREAD

**Issue by magnus-hansson** [Azure/static-web-apps#56]
I wonder if it should be possible to create a function with a cosmosDBbinding with Static web apps at the moment?

I get this error message when I try add a cosmosDB binding to a function:

Error in processing api build artifacts: the file 'products-post/function.json' does not specify a valid function with only HTTP triggers and bindings. Please ensure the JSON contains a single httpTrigger input trigger and a single http output binding.

My function.json looks like this:
{ "bindings": [ { "authLevel": "anonymous", "type": "httpTrigger", "direction": "in", "name": "req", "methods": ["post"], "route": "products" }, { "type": "http", "direction": "out", "name": "res" }, { "type": "cosmosDB", "name": "inputDocumentIn", "databaseName": "mydb", "collectionName": "mycol", "connectionStringSetting": "CosmosDBConnectionString", "direction": "in", "sqlQuery": "SELECT * from c" } ] }

**Comment by joslinmicrosoft** [comment]
Hi @magnus-hansson,

This error shouldn't be happening. Are you able to provide the repository URL or the Github Action run that printed this error so we can take a look? Thank you!

**Comment by anthonychu** [comment]
@magnus-hansson Change your GitHub action to use `@latest`, like this: https://github.com/anthonychu/static-web-apps-chat/blob/master/.github/workflows/azure-static-web-apps-nice-grass-061cac810.yml#L21

**Comment by joslinmicrosoft** [comment]
@anthonychu we had fixed this issue a while ago, so using `@v0.0.1-preview` should work fine (I've tested it out on a copy of your site above).

@magnus-hansson can you confirm that your workflow file has the line `uses: Azure/static-web-apps-deploy@v0.0.1-preview`?
