### ISSUE TITLE
Can we use hybrid connections with managed functions?

### ISSUE THREAD

**Issue by michaelmoneypenny** [Azure/static-web-apps#561]
We're currently using managed/integrated functions that deploy with our front end. The issue we've encountered is some of our functions access on premise databases. I know with a standalone function app you can configure hybrid connections in networking but there isn't anything in the static app dashboard regarding this

Is it possible to configure hybrid connections for managed funcs some way? Or could private endpoints help us out? It's fine that everything is only accessible from our internal network

If not - regarding bring your own, our app currently uses out-of-the-box azure AD so the API calls are easily secured as they don't have publicly accessible or direct URLs.

I read that if you link to standalone functions the static app configures CORS etc for you and has "exclusive access" - does this mean AAD would still secure the API endpoints?

Many thanks

**Comment by miwebst** [comment]
Hey @michaelmoneypenny, hybrid connections are not supported with managed functions. For your scenario, are you using easy auth to secure the app using azure AD?

**Comment by michaelmoneypenny** [comment]
Hi - yeah easy auth but hooked up to our AD tenant. I can see with non-managed azure function link the auth works the same and API is still only accessible from the app which is great :)
