### ISSUE TITLE
Static Web App Identity to access Cosmos DB using IAM

### ISSUE THREAD

**Issue by lucashfreitas** [Azure/static-web-apps#567]
Hello,

I have a static web app with several functions that access a cosmo DB instance. In order to improve security, I want to set up cosmos DB access using IAM instead of database keys. 

I have enabled Identity for static web apps but I can't select it under Cosmos DB IAM Role assignment as it doesn't give the option to select Static Web App and it doesn't recognize any static web app functions if we select Functions App.

Is there any way to assign static web app Identity to cosmos DB to allow functions to access using IAM. 

Most of the tutorials seem to use Database Primary Key.

![image](https://user-images.githubusercontent.com/11416392/131269385-23c089f1-041f-4f7a-9f9d-62274d0c2b41.png)

Thanks,

**Comment by anthonychu** [comment]
This is currently not supported. If you need to use managed identity to access Cosmos DB, you will have to to set up a separate function app with managed identity enabled. You can use the [bring your own functions](https://docs.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own) feature to link the function app with your static web app. 

We are aware of this current feature gap and will address it in the future.

**Comment by lucashfreitas** [comment]
Awesome @anthonychu , thanks for the quick reply.
