### ISSUE TITLE
Azure Static web apps role management with custom IdP

### ISSUE THREAD

**Issue by router19** [Azure/static-web-apps#569]
**Describe the bug**
Currently Azure SWA does not have an option to select custom IdP as authentication provider for role management. 

**To Reproduce**
1. Open Azure SWA
2. Click on 'Role Management'
3. Click on "Invite" button.
4. Under authentication provider we can see it list only standard IdPs like AAD, GitHub, twitter. (FB(preview), Google(preview))
I am filing it as a bug rather a feature request because Azure SWA provider an option to configure custom provider as documented at https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad.

**Expected behavior**
An option to provider custom provider config for role management. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63940739/131463995-e39fda8d-3b2a-4f3c-870a-f2e01ed34cf3.png)

**Device info (if applicable):**
 - OS: N/A
 - Browser NA
 - Version NA

**Additional context**
NA

**Comment by router19** [comment]
@mkarmark @anthonychu Any suggestion would be appreciated.

**Comment by adrwh** [comment]
Hi thanks for this article. I am sending custom claims in the openid auth app from Okta. I can access those claims when using Okta SDKs and typical ExpressJS apps, but how can I access them in SWA?

**Comment by simonaco** [comment]
@router19 we've recently added support for assigning roles to users programmatically using serverless functions, see documentation on [role management](https://docs.microsoft.com/azure/static-web-apps/authentication-authorization?tabs=function ) and [Tutorial: Assign custom roles with a function and Microsoft Graph](https://docs.microsoft.com/azure/static-web-apps/assign-roles-microsoft-graph)

**Comment by simonaco** [comment]
@adrwh you can now access claims at <YOUR_SITE_URL>/.auth/me , please let us know if that fits your use case.
