### ISSUE TITLE
HTTP 416 Error with Index.html in a Static Web App

### ISSUE THREAD

**Issue by mcbeev** [Azure/static-web-apps#57]
Content hosted from the Azure Static Web App service seems to have an issue with being validated by [LinkedIn's Post Inspector](https://www.linkedin.com/post-inspector/). Their tool calls out a HTTP 416 response code from any page I test it with. I have used the same exact static html from my ASWA that runs at ([http://symcheck.io/](http://symcheck.io/)) on an IIS site and it works perfectly on the post inspector (200 response code), but with that same exact content being served out via the Azure Static Web App, the tool responds with HTTP 416. 

I have recreated the same HTTP 416 error with a brand new repo at [https://github.com/mcbeev/test416](https://github.com/mcbeev/test416) which is a very simple hello world Index.html file that I then deployed to a brand new Azure Static Web App at [https://happy-wave-09541930f.azurestaticapps.net/Index.html](https://happy-wave-09541930f.azurestaticapps.net/Index.html)

Running that url against [https://www.linkedin.com/post-inspector/](https://www.linkedin.com/post-inspector/) returns a 416 error (and any other page hosted in both of my Azure Static Web Apps. 

Interestingly enough the Facebook and Twitter meta data debug tools work just fine. 

I do think it has something to do with the headers that AWSA are serving out.

Not working from AWSA
![Untitled picture](https://user-images.githubusercontent.com/9918767/84432717-34406d80-abfb-11ea-90a5-ec96be731643.png)

Not working from simple example repo and fresh new AWSA
![Untitled picture2](https://user-images.githubusercontent.com/9918767/84432755-44f0e380-abfb-11ea-887a-d866bd627e77.png)

Working from Local IIS (via ngrok tunnel)(same exact html as above)
![Untitled picture3](https://user-images.githubusercontent.com/9918767/84432772-4cb08800-abfb-11ea-81ce-3b0358eb18bf.png)

**Comment by mkarmark** [comment]
Hi @mcbeev 

First of all, thanks for using Azure Static Web Apps.

We have identified the issue, and are currently working on a fix for it. It should be out soon.

Thanks for bringing this to our attention!

**Comment by miwebst** [comment]
Hi @mcbeev we have rolled out a fix for this, can you confirm and close accordingly?

**Comment by mcbeev** [comment]
Confirmed it is working!  Thank you!

**Comment by alexbjorlig** [comment]
What was the fix for this issue? I'm currently struggling with the 416 error
