### ISSUE TITLE
Is there a way to retrieve the deplyoment token using az staticwebapp?

### ISSUE THREAD

**Issue by plamber** [Azure/static-web-apps#573]
Hello,
I was looking in the documentation for the [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/staticwebapp) if there is a way to retrieve the management deployment token from a script.

![image](https://user-images.githubusercontent.com/18241305/132283297-7100ae0c-585c-4940-8749-212f29b4b063.png)

Thank you for your feedback,
Patrick

**Comment by anthonychu** [comment]
This was recently merged. Should be available in the next Azure CLI release: https://github.com/Azure/azure-cli/issues/16470

**Comment by simonaco** [comment]
closing the issue as this has shipped, @plamber please reopen if needed.
