### ISSUE TITLE
[Bug] Error in ARM typings/docs on `userProvidedFunctionApps` property

### ISSUE THREAD

**Issue by sinedied** [Azure/static-web-apps#576]
**Describe the bug**

I'm trying to use Bicep/ARM to deploy a SWA with user a provided function app.

The ARM template generated by the portal looks like this (omitting the SWA json as it contains nothing special for user provided functions)
```
{
            "type": "Microsoft.Web/staticSites/userProvidedFunctionApps",
            "apiVersion": "2020-12-01",
            "name": "[concat(parameters('staticSites_name'), '/myapp')]",
            "location": "West Europe",
            "dependsOn": [
                "[resourceId('Microsoft.Web/staticSites', parameters('staticSites_name'))]"
            ],
            "properties": {
                "functionAppResourceId": "[parameters('myfunc_id')]",
                "functionAppRegion": "westeurope"
            }
        }
    ]
```

But when I try to use ARM or Bicep to deploy the this template, I get this error: `Cannot register a function app with a preexisting Azure Static Web Apps configuration without setting the isForced flag to true.`
![image](https://user-images.githubusercontent.com/593151/132711738-752c667b-7e7c-4bb4-b71f-0e3a940caaf9.png)

After trying different things, I found out that the `JSON` view in the SWA overview provides a different template for the SWA, which includes a `userProvidedFunctionApps` property that's not in the [template docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.web/staticsites?tabs=json#StaticSiteBuildProperties):

```json
{
    "id": "/subscriptions/123...",
    "name": "myswa",
    "type": "Microsoft.Web/staticSites",
    "location": "West Europe",
    "properties": {
        ...
        "userProvidedFunctionApps": [
            {
                "functionAppResourceId": "/subscriptions/123...",
                "functionAppRegion": "westeurope",
                "createdOn": "2021-09-09T14:52:47.1618939"
            }
        ],
    },
    "sku": {
        "name": "Standard",
        "tier": "Standard"
    }
}
``` 

I tried using this `userProvidedFunctionApps` object in the Bicep template for my SWA instead of the `userProvidedFunctionApps` resource generated by the portal, and it worked!

This property is not in the docs and generates a warning:
![image](https://user-images.githubusercontent.com/593151/132716387-a9cf8c8a-8663-4a4d-870b-6ec48003034b.png)

## Expected behavior

I think that the typing for the `userProvidedFunctionApps` property is incorrect and should be changed as it's currently marked as read-only, so it doesn't generate a warning and can appear in the docs.

## Related
https://github.com/Azure/static-web-apps/issues/575

**Comment by gomete** [comment]
Hi @sinedied,

I had the same issue. I tried to add what you suggested and there is no error if the resource already exists, but when I remove the link and try to recreate it with the template it is not created. Did you have the chance to recreate the resources from scratch? Were they recreated including the link with the backend? I'm afraid the deployment is just ignoring the property `userProvidedFunctionApps` in my case.

Thanks for your time :).

**Comment by ngoquoc** [comment]
Is there any workaround for this? Our entire ARM deployment failed just because of this bug 😳

**Comment by AnjaneyalnDatla** [comment]
Same issue here.

**Comment by miguelEsteban** [comment]
Same here.

**Comment by Rfaering** [comment]
Same here.

**Comment by sokolowskip** [comment]
Same here.

**Comment by itpropro** [comment]
@simonaco any updates on this? The issue is already quite old and it also impacts bicep deployments, as the provider `Microsoft.Web/staticSites/userProvidedFunctionApps@2021-03-01` doesn't seem to be implemented idempotent.

**Comment by annikel** [comment]
Hi everyone, the problem here seems to be that the function app which is being attached has been attached to a different static web app before and so have a not matching Static Web Apps identity provider configured in their Authentication configuration. This can be verified by navigation to the _Function App > Authentication_ 

![image](https://user-images.githubusercontent.com/92825476/177418789-9703f3a9-b26c-4978-804b-42dd79ad2492.png)

Before attaching the resource to a new static web app this identity provider must be removed. Please let me know if after removing this provider you are still experiencing the same issue. 

@sinedied the userProvidedFunctionApps property in the SWA response is a read-only on purpose and can not be used to attach a new user provided function app.

**Comment by itpropro** [comment]
Hi @annikel,
the problem is that the ARM provider doesn't expose the `isForced` parameter that you can use in the REST APIs. It is not connected to the Function App itself or any field on the function app, it is only connected to the `userProvidedFunctionApps` property on the Static Web App object.
The next API version for SWA's has to include a way to provide the `isForced` parameter or the internal implementation needs to be fixed to make the property idempotent. The `userProvidedFunctionApps` should be implemented idempotent, meaning, if the property is already set and the provided one is the same, the provider should just return OK and if the configuration is different, it should either overwrite the configuration or check the `isForced` parameter is set or not to return the specific message.

**Comment by sokolowskip** [comment]
Thanks @annikel 
I tested it and this is the working bicep script:

`resource staticAppBackend 'Microsoft.Web/staticSites/linkedBackends@2022-03-01' = {
  name: '${staticApp.name}/backend'
  properties: {
    backendResourceId: functionApp.id
    region: location
  }
}`

However, there is still one small inconvenience.  I linked the function app to the static app manually from the Azure portal. I run the bicep script and received the following error message: 

`
{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"Code\": \"BadRequest\",\r\n  \"Message\": \"One Static Web App can not have more than one linked backend.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"One Static Web App can not have more than one linked backend.\"\r\n    },\r\n    {\r\n      \"Code\": \"BadRequest\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"ExtendedCode\": \"59363\",\r\n        \"MessageTemplate\": \"One Static Web App can not have more than one linked backend.\",\r\n        \"Parameters\": [],\r\n        \"Code\": \"BadRequest\",\r\n        \"Message\": \"One Static Web App can not have more than one linked backend.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"}]}}
`
In the bicep, I was trying to attach the same function app that was previously linked from the portal. 

After unlinking the manually linked function app, I can run the bicep script many times without any problems.

**Comment by itpropro** [comment]
Thanks for clarifying @annikel! Has there also been an update to the userDefinedFunctionApp endpoint or will that one be deprecated and should not be used in Bicep/ARM anymore?

**Comment by sinedied** [comment]
Thank @annikel, the new linkedBackend resource works perfectly for linking custom functions backends.

I also noticed that the `userDefinedFunctionApp` ARM typing has been fixed in the latest template version, so this issue can be considered as resolved 🙂 .

**Comment by itpropro** [comment]
@sinedied can you link the updated `userDefinedFunctionApp` typing? [This](https://github.com/Azure/azure-rest-api-specs/blob/8ff7d5ef46f43875262110a4b2df7357bdf4369c/specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/StaticSites.json#L1161) looks like the `isForced` parameter is still a uri query parameter.
I think we should only close this issue, if we have verified that the `userDefinedFunctionApp` endpoint is actually idempotent, have you tested a bicep deployment with that yet?

**Comment by sinedied** [comment]
@itpropro I only saw that with version `2021-03-01` the property `userDefinedFunctionApp` is no longer marked as read-only, I did not check the deployment with it as the new `linkedBackends` resource I was able to achieve idempotent deployments.

I might be stretching a bit, but with the new ability of linking backends other than Functions, it would seem that `userDefinedFunctionApp` might be removed in future version and replaced by `linkedBackends` resources. Maybe @annikel could give some insights regarding this?

**Comment by itpropro** [comment]
@sinedied I tested the new APIs, but they are unfortunately not working. It was not possible to deploy a staticSite resource without the error 

```json
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The response for resource had empty or invalid content."
    }
}
```

Even when only deploying the staticSite with only the required `name` parameter, the deployment will fail. With the 2021-03-01 API, everything works, at least for the staticSites endpoint.
So the new API version didn't fix this issue (idempotency of the userDefinedFunctionApp endpoint) and introduced a breaking error on the main endpoint. I don't think we should close this issue, yet...

**Comment by annikel** [comment]
@itpropro Can you give more details about the request that you are experiencing this issue for? I assume this is unrelated to the original issue.

@sinedied yes, our new set of endpoints allows the original _userProvidedFunctionApps_ functionality plus addition backend resource types why there is no need for it in the future. Of course we will continue the support for now.

**Comment by itpropro** [comment]
At the time of writing it was not possible to deploy a staticSite resource at all with the 2022-03-01 API, even with the most minimal parameter set, only providing a name.
I have not tested if it was fixed in the meantime @annikel.

**Comment by sinedied** [comment]
@itpropro You should open a separate issue for this.

I can confirm that the `@2022-03-01` staticSite API seems to be buggy, as the same valid template using `@2021-03-01` deploys just fine, whereas with the `@2022-03-01` I get a deployment error, without any specific issue reported.

However, you can use a `linkedBackends@2022-03-01` resource just fine within a `staticSite@2021-03-01` as a workaround.
