### ISSUE TITLE
Get the original url (before rewriting) in a header when rewriting in staticwebapp.config.json

### ISSUE THREAD

**Issue by flixcor** [Azure/static-web-apps#580]
**Is your feature request related to a problem? Please describe.**
I'm running into the following problem: I'm trying to build a Server Side Rendered app on SWA, using an Azure Function (Node) for the rendering part. Everything is working nicely, except for the very final part: the Function has no way to track down which url the browser originally requested, so that it can decide which client route to render. A `x-ms-original-url` header is present, but this contains the url AFTER the rewrite.

**Describe the solution you'd like**
On every rewrite, add a header containing the originally requested url.

**Describe alternatives you've considered**
An alternative would be if we can use the original url as a variable in the specified rewrite, so we can add it as a query parameter.

**Example:**
Given the following fallback route:
```json
"navigationFallback": {
    "rewrite": "/api/ssr",
    "exclude": [
        "assets/*"
    ]
}
```
The following happens:
- The browser requests the page `contoso.org/about`
- This request is rewritten to `contoso.org/api/ssr`
- The SSR Function is reached, but the `x-ms-original-url` header is `contoso.org/api/ssr`

In this case, a header containing `contoso.org/about` would allow the Function to render the correct route.

**Comment by anthonychu** [comment]
This is a good one. @miwebst @mkarmark Is it possible to add a header for this?

**Comment by smakinson** [comment]
@anthonychu I am also looking for how to pass along the actual original url to a function from a rewrite for a workaround for #196
So close......

**Comment by smakinson** [comment]
@miwebst @mkarmark I apologize for the ping, this one just really hurts with the original url missing. Completely blocks.

**Comment by miwebst** [comment]
This was actually fixed over a month ago (sorry, looks like we missed updating this issue) so now you can do this either through routes like so:
`{
  "routes": [
    {
      "route": "/images/*",
      "rewrite": "/api/ssr"
    }
  ]
}`

Or you can use the navigation fallbacks as shown in @flixcor 's example in the initial post. In both scenarios, the `x-ms-original-url` header will contain the original hostname, path and query string.

**Comment by smakinson** [comment]
That is great news! I'll check it out!

**Comment by smakinson** [comment]
@miwebst  Did a quick check and it looks like `req.headers['x-ms-original-url']` is correct on azure, but not correct yet locally with `swa`. Is that accurate?

**Comment by miwebst** [comment]
`req.originalUrl` is unfortunately not something we can set, so you need to use the `x-ms-original-url ` header. As for support in the local experience, that may be something we need to add. We will look at adding that.

**Comment by anthonychu** [comment]
Created this issue to track in the CLI. @smakinson  if you have more details, please add to that issue: https://github.com/Azure/static-web-apps-cli/issues/337 Thanks

**Comment by flixcor** [comment]
Great, thanks a lot!
