### ISSUE TITLE
DevOps Deploy Static Web App suddenly returning 'Internal Server Error'

### ISSUE THREAD

**Issue by caitlinwillmot** [Azure/static-web-apps#582]
I've been using DevOps 'Deploy Static Web App' (with skip app build turned on) in a Release pipeline to deploy my built React SPA code to my static web app (hobby/personal project tier). Yesterday it was working fine however today I'm now getting the following error:

![image](https://user-images.githubusercontent.com/74575035/133533586-7f9dde91-b241-4870-ab4d-80e9acc70aec.png)

The Release Pipeline has not been updated, and previous releases that had deployed successfully are now failing.

Has there been some kind of change to this way of deployment?

Thanks

**Comment by Greg-Hyliion** [comment]
I am seeing the same issue as of today.

**Comment by joslinmicrosoft** [comment]
Hi, thank you for bringing this up! We have just deployed a fix for this, can you please check if your deployments are succeeding now?

**Comment by caitlinwillmot** [comment]
> 
> 
> Hi, thank you for bringing this up! We have just deployed a fix for this, can you please check if your deployments are succeeding now?

My deployments are succeeding now. Thank you very much for resolving this so quickly :)
