### ISSUE TITLE
The content server has unexpectedly rejected the request with: InternalServerError

### ISSUE THREAD

**Issue by smakinson** [Azure/static-web-apps#585]
**Describe the bug**

I have a SWA that has been running actions/builds successfully. Starting yesterday evening the builds have all been failing.
They run on a schedule via:

```
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
  schedule:
    - cron: "*/60 * * * *"
```

I found this morning if I make a change and push to cause a build manually, it does succeed. So it seems it might be related to the schedule/cron trigger.

Another difference I notice in the logs is that the cron triggered builds have a line (both on the successful & failed builds) that I do not see in the builds that ran from a push. Since it shows in both the successful and failed builds I can't say for sure if it's related, but it might be a clue.

This is what I see in the **failed** cron triggered action/build:
```
Failed to parse GitHub Event Json (/github/workflow/event.json). Proceeding
Could not get event info. Proceeding
The content server has unexpectedly rejected the request with: InternalServerError
```

This is what I see in the **successful** cron triggered action/build:
```
Failed to parse GitHub Event Json (/github/workflow/event.json). Proceeding
Could not get event info. Proceeding
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
Oryx will build app with the following custom override command: yarn run build
---Oryx build logs---
continues...
```

These lines are **NOT** in the logs on the builds triggered from a push (and they succeed):
```
Failed to parse GitHub Event Json (/github/workflow/event.json). Proceeding
Could not get event info. Proceeding
```

Incase its needed (but it looks like it doesn't get this far), the build does this:

`node build/build.js && hugo --ignoreCache && yarn run clean`

The node script grabs a bit of data from an api and writes a file that hugo uses.

**Comment by miwebst** [comment]
Hey @smakinson thanks for bringing this up, we will take a look!

**Comment by joslinmicrosoft** [comment]
Hi @smakinson we just deployed a fix for this. Can you please check if your deployments are succeeding now?

Also linking related issue #582.

**Comment by smakinson** [comment]
@joslinmicrosoft I see they have been succeeding since about 16 hours ago. Thank you for the quick fix!!
