### ISSUE TITLE
Deployment Failure Reason: Failure during content distribution.

### ISSUE THREAD

**Issue by jeromelaban** [Azure/static-web-apps#586]
**Describe the bug**

The deployment of an app started to fail today (it's been working well for the past 45 days, thanks!) with the following message:

```
Function Runtime Information. OS: Windows, Functions Runtime: v3, .NET Core version: 3.1
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.0863025(s)
Status: InProgress. Time: 15.1747632(s)
Status: InProgress. Time: 30.3654083(s)
Status: InProgress. Time: 45.4421333(s)
Status: InProgress. Time: 60.713103(s)
Status: InProgress. Time: 75.7910699(s)
Status: InProgress. Time: 90.9223756(s)
Status: InProgress. Time: 106.0967663(s)
Status: InProgress. Time: 121.1679573(s)
Status: InProgress. Time: 137.0149018(s)
Status: InProgress. Time: 152.1473811(s)
Status: InProgress. Time: 167.3049657(s)
Status: InProgress. Time: 182.4906126(s)
Status: Failed. Time: 197.630691(s)
Deployment Failed :(
Deployment Failure Reason: Failure during content distribution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
```

**To Reproduce**

I don't have any specific steps to reproduce, but here's the [`staticwebapp.config.json`](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/main/Uno/NuGetPackageExplorer.Wasm/wwwroot/staticwebapp.config.json), the [failed build ](https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=33572&view=logs&j=ef19874c-dd89-559a-7822-f5a414b01ba4&t=27d67b36-cf9a-58e4-be8b-2b3a77fd4ed8&l=201) and the azure devops [pipeline associated](https://dev.azure.com/uno-platform/Uno%20Platform/_git/NuGetPackageExplorerCanary?version=GCdd5b4d2c90b4a38519cb5dc8f8c49e20895b289c&path=/pipeline.yml) to it.

**Expected behavior**
The deployment does not fail.

**Screenshots**
None, see logs.

**Device info (if applicable):**

**Additional context**

**Comment by andreaslarssen** [comment]
@jeromelaban Tried to deploy an app for the first time yesterday, and I get the same error msg.

**Comment by miwebst** [comment]
Ouch, sorry for the interruption! Do y'all mind sharing any app names or default hostnames and we can take a deeper look?

**Comment by jeromelaban** [comment]
Looks like one of my deployments succeeded: https://purple-pond-0688d230f.azurestaticapps.net 8 hours ago.

Something was fixed :) I'll try again today.

**Comment by andreaslarssen** [comment]
Yeah, obviously an Azure bug that was fixed.

**Comment by miwebst** [comment]
This was an Azure issue that was fixed. Closing for now as this error code is a generic error we throw if something went wrong during global replication.
