### ISSUE TITLE
Can I prevent API access from external source?

### ISSUE THREAD

**Issue by justinyoo** [Azure/static-web-apps#59]
Hi, Team.

I've added an API endpoint that is accessible from the static web app instance. Now I can call the API endpoint like:

```
/api/hello
```

Now, I want to secure the API endpoint from outside. I only want to call the API from the static web app side. However, I can directly call the API like:

```
https://<my-static-web-app>.azurestaticapps.net/api/hello
```

It's not desirable because the static web app instance shouldn't include the function auth key - meaning the API should allow "anonymous" access.

How can I prevent direct external access to the API endpoint?

**Comment by miwebst** [comment]
So the "static web app" side here means that its your customer's browser making the request. There is no way for the function to differentiate the caller. What is the reason you are trying to lock down access to the api through your static web app domain?

**Comment by anganti** [comment]
@justinyoo can't you just use the "function" authlevel instead of "anonymous". This should work. Am I missing something here?

**Comment by justinyoo** [comment]
@miwebst One of the reasons using the proxy API is to hide sensitive information like API key from the public access. Let's say that I have a static web app instance, `https://snow-piercer-1234.azurestaticapps.net` and its proxy API endpoint of `/api/hello`.

The static web app only calls the proxy API within the browser. It knows nothing about the external API details, which is good. But, WITHIN the proxy API function, it calls an external API like `https://my-external-api.azurewebsites.net/api/lorem?authkey=xyz`. In this case, the authkey of `xyz` comes from the configuration (environment variables), which is fine.

But the problem is that, if I directly send a request to `https://snow-piercer-1234.azurestaticapps.net/api/hello` via Postman, it's still possible. I don't know the auth key of the external API, but I can get the data through this proxy API endpoint, using Postman. I don't think this is the expected behaviour.

The proxy API endpoint should ONLY be open to the static web app, not to anything else; otherwise the proxy API endpoint will be abused.

---

As @anganti suggested, I can set the auth level of the proxy API endpoint from `anonymous` to `function`. Again, if I do this way, the function auth key MUST be exposed to the static web app instance, which SHOULD be avoided, and there's no difference between `anonymous` and `function` with the auth key being exposed.

**Comment by justinyoo** [comment]
If I put API Management between the proxy API and external API, it may solve my concern. But, is this the only way to figure out the issue?

**Comment by MarkXA** [comment]
If the information shouldn't be available to the public, you need to authenticate users via OAuth first (https://docs.microsoft.com/azure/static-web-apps/authentication-authorization) and then your API should validate that they're authorised (https://docs.microsoft.com/en-us/azure/static-web-apps/user-information).

**Comment by justinyoo** [comment]
@MarkXA Yeah, that's one way. But I have a different use case. The static web app itself is public facing, but want to keep the proxy API from being abused. As @miwebst mentioned, if it can't be done on the app instance itself, I should find another way outside the app.

**Comment by MarkXA** [comment]
Well it depends on your definition of "abused", but if for some reason you absolutely have to prevent any access to the API at all, and adding authentication won't prevent the abuse, then Static Web Apps isn't for you and you'll need to use a traditional web server. The whole point of a static app is that there is no web server, the files are just hosted on a CDN and all API access is performed by the client directly.

If by "abuse" you mean you're worried about a denial-of-wallet attack from somebody flooding the API with unauthenticated calls in the hope of landing you with a big bill then I'll leave it to the team to comment on what's in place to prevent that :)

**Comment by justinyoo** [comment]
@MarkXA Yeah, your second paragraph is what I asked originally. ASWA itself can't block the API access. I get that. My ask was different. It's more architectural issue.

Netlify is able to hide the function/proxy from the public visibility: https://docs.netlify.com/functions/configure-and-deploy/#configure-the-functions-folder

> Though we process the files in the functions directory after running your build command, the directory is not visible over the web unless you place it in your site’s publish directory (not recommended).

Netlify uses AWS Lambda for their API proxy feature - meaning their API Gateway does something for it.

It means, our ASWA also can prevent public access to the proxy API part, by implementing some sort of blocking logic.

**Comment by miwebst** [comment]
Ah I see, I think there might be a small disconnect here. @justinyoo the link you posted above is essentially saying if you use Lambda's then the Lambda source code is not accessible unless you include it in your sites published content. 

ASWA works similarly. We build your Azure Functions separately from your static content and as a result then only way for your Function source code to become public is if you include it in the publish directory. No one can ever access the function key's or app settings that you configure for your ASWA functions, these are not exposed to the client.

**Comment by justinyoo** [comment]
Oops. That's what it meant.

Sooo, it's impossible to block random access from public to the proxy API, like everyone says, because it's not what ASWA does for?

**Comment by miwebst** [comment]
So you can't restrict your api calls to just the browser running your application. This is because there isnt really anything unique about your app running in the browser compared to a different http client. You can restrict access by using Roles, but this will restrict the api to a subset of users which may not be your desired solution.

**Comment by ozkary** [comment]
@justinyoo A way to HELP prevent access to the /api routes from other sources (postman, bot) is to create a custom auth-process. Create a hidden login process to produce a toke (JWT). The client application can send the authorization header for every API call. The function can have the logic to read and verify the token or return a 401.  Not 100% secure, but can provide a level of protection.   

**I would love to see aan anonymous login capability similar to Firebase on SWA** This way we could just use routes.json to protect the routes.

Also using a WAF referrer-policy = same-origin can manage it. This however it is not within the 
SWA configuration. 

What approach did you take?

Thanks

**Comment by thomasgauvin** [comment]
Curious to hear how you architected your ASWA and Functions API to be protected against abuse/DDOS @justinyoo 

Is there a documented way to prevent abuse of ASWA Functions API aka denial-of-wallet attack that MarkXA mentioned? @miwebst @annaji-msft Any rate limiting abilities?

From my research, the only solution seems to be to use API management with Bring-your-own functions

**Comment by justinyoo** [comment]
@thomasgauvin To sort out my issue, I simply used `staticwebapp.config.json`.

```json
{
  "routes": [
    {
      "route": "/api/*",
      "allowedRoles": ["authenticated"]
    }
  ]
}
```

But not sure whether this could prevent DDoS attach or not, but at least API is not called anyway. @miwebst @annaji-msft Would you be able to confirm that the `staticwebapp.config.json` file can prevent DDoS attack?

**Comment by anirudhpm** [comment]
@justinyoo 
When you used the route configuration to limit the access to your api to authenticated users, doesn't it beat your purpose of building a public facing frontend/SWA? I'm curious, because i'm in a similar situation.

**Comment by jkim34** [comment]
> @justinyoo When you used the route configuration to limit the access to your api to authenticated users, doesn't it beat your purpose of building a public facing frontend/SWA? I'm curious as i'm in a similar situation.

I'm in a similar situation as well. Wondering if you have figured anything until now.

**Comment by zzulueta** [comment]
Hello, I was wondering if there is a way to prevent the Azure API Management Service to be NOT accessible by POSTMAN. I tried CORS and it will not work

**Comment by casually-creative** [comment]
> Hello, I was wondering if there is a way to prevent the Azure API Management Service to be NOT accessible by POSTMAN. I tried CORS and it will not work

CORS is enforced by trusted browsers like Chrome and Firefox. Your API can define a set of whitelisted domain names, and those browsers will throw errors when a website from another domain tries to call your API.

This means that requests not made from those trusted browsers will still go through. This includes tools like Postman and ill-intention browsers. So bad actors still have ways to flood your API.

On the other hand, it prevents other parties from building websites that consume your API, as those parties most likely want users to access their website through those popular browsers.

---

I'm also looking for a way to protect my API from DDOS attacks and general abuse, while having it accessible from my static web app. I was hoping there was a way to achieve this but I'm getting the feeling there isn't.

I'm going to do some research into API Management Service but don't think it will be able to accomplish this use case. I might end up implementing a token system as /u/[ozkary](https://github.com/ozkary) suggested. Even though it's not foolproof, it will add some level of annoyance for abusers.
