### ISSUE TITLE
Can't reach api in staging environments

### ISSUE THREAD

**Issue by nerblock** [Azure/static-web-apps#592]
**Describe the bug**

Api is unreachable in the staging environment currently. I get this response from all functions, and also when trying to open /api without adding the function name:

`{"code":401,"message":"IDX10205: Issuer validation failed. Issuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'. Did not match: validationParameters.ValidIssuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]' or validationParameters.ValidIssuers: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'."}
`

**To Reproduce**

1. Start a pull request, wait until its finished
2. Try to access a function on the staging url (eg. /api/GetThreads)

**Expected behavior**

Function should respond.

**Additional context**

- I tried with the same code that's currently on the production environment, but it didn't help. So definitely an Azure problem.
- Also this response is definitely not coming from my functions, and I can't see failed requests / exceptions in the live metrics either.
- Deployment log looks normal
- Function type is managed
- Functions are nodejs (typescript)
- No custom authentication
- App is in the Standard plan

**Comment by nerblock** [comment]
Update:

I created a new static web app to investigate the problem further. This is the result:

- Production environment: api calls work - no errors
- Staging environment: api calls fail with the same error as the original site: 
```{"code":401,"message":"IDX10205: Issuer validation failed. Issuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'. Did not match: validationParameters.ValidIssuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]' or validationParameters.ValidIssuers: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'."}```

So at this point I can deduce this is clearly an internal Azure problem with the staging environments.

And the million dollar question is: when can I expect staging envs to work again? Also will you make an announcement about it, so I don't need to waste cloud credits on the constant deployment and undeployment of the staging envs?

Thank you in advance!

**Comment by rwaldin** [comment]
I'm seeing the exact same issue with all newly deployed staging environments as of yesterday. Environments deployed before that continue to work correctly. All environments deployed since yesterday exhibit this behavior.  Any request to /api/<anything> results in: 

> {"code":401,"message":"IDX10205: Issuer validation failed. Issuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'. Did not match: validationParameters.ValidIssuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]' or validationParameters.ValidIssuers: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'."}

**Comment by mkarmark** [comment]
Hi, this was a platform regression to staging environments calling functions such that the function calls exhibited behavior as detailed in this issue. This regression was rolled out 9/23/21 18:05UTC and has been mitigated as of 9/24/21 19:00 UTC, so any apps with managed functions that updated their staging environments in that time window were impacted. Any deployments here on out to the staging environments should restore your functions and they should be made available again. We apologize for the inconvenience.

**Comment by rwaldin** [comment]
> Any deployments here on out to the staging environments should restore your functions and they should be made available again. We apologize for the inconvenience.

Unfortunately, I am still experiencing the exact same behavior as before your reply. I have re-deployed two separate staging environments and I am still getting the same error message when making request to any URL at /api/*:

> {"code":401,"message":"IDX10205: Issuer validation failed. Issuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'. Did not match: validationParameters.ValidIssuer: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]' or validationParameters.ValidIssuers: '[PII is hidden. For more details, see https:\/\/aka.ms\/IdentityModel\/PII.]'."}

**Comment by thomaspurchas** [comment]
I'm also seeing this issue on a branch deployed 1 min ago.

**Comment by nerblock** [comment]
Weird, I just created a new staging env and can confirm it's working fine for me.

**Comment by thomaspurchas** [comment]
https://zealous-moss-01ebaab03-1.westeurope.azurestaticapps.net/api/


<img width="954" alt="Screenshot 2021-09-24 at 21 42 51" src="https://user-images.githubusercontent.com/782311/134737419-584f231b-f102-4e1c-a4f5-d2ecf3a30d98.png">

**Comment by nerblock** [comment]
Have you tried opening a new pull request, or just pushed new commits into the branch?

**Comment by thomaspurchas** [comment]
I've not tried a new PR because @mkarmark wrote

> Any deployments here on out to the staging environments should restore your functions and they should be made available again.

I kinda assumed that ment new deploys would fix existing environments, but maybe not

**Comment by nerblock** [comment]
She probably meant new deployments of the staging environments.

**Comment by nerblock** [comment]
If you guys confirm it's working for you too I'll close this.

**Comment by rwaldin** [comment]
I can confirm that creating a new pull-request generates a new staging environment that no longer has this issue. Redeploying onto an existing staging environment does not solve the problem. Thanks for the quick fix!

**Comment by nerblock** [comment]
Ok thanks everybody, closing this
