### ISSUE TITLE
Unable to change source branch

### ISSUE THREAD

**Issue by alexangas** [Azure/static-web-apps#60]
I recently changed the default branch for my project, and would like to update this in the Static Web App as well. This appears to be easily done in the GitHub Action YAML however I couldn't find anything on the Azure Portal side.

Will I need to delete and recreate it, or change the default branch back to a name that matches the Static Web App? Or is there an option somewhere to update that source branch?

Thanks in advance, and also Static Web Apps is great!

**Comment by miwebst** [comment]
Right now delete and recreate is the only way to go, we are working on improving the flexibility around this! We appreciate your feedback and thanks for trying out the product.

**Comment by alexangas** [comment]
OK, and thanks for getting back to me so fast.

Feel free to keep this issue open if it helps for tracking, otherwise I'll keep an eye out for this in the future!

**Comment by miwebst** [comment]
Just as an update, for newly created apps this is fixed, with the exception that the UI will still link to the old branch.

**Comment by clairernovotny** [comment]
How can we do this for existing apps?

**Comment by miwebst** [comment]
You can reset your api key and update the GH repo secret with the new key. Then you are free to change branches. You can take a look at this issue for instructions on resetting/getting your key:

https://github.com/Azure/static-web-apps/issues/193
