### ISSUE TITLE
Link a normal App Service (Web App / API app) as a BYOF

### ISSUE THREAD

**Issue by shibayan** [Azure/static-web-apps#600]
**Is your feature request related to a problem? Please describe.**

There are cases where you want to use a backend developed with an already existing Web API framework such as ASP.NET Core Web API as a backend for Static Web App.

**Describe the solution you'd like**

I want to use a complex and numerous Web API as a backend (under `/api`) while using Static Web App's route definition to static content, fallback, and advanced authentication.

It is difficult to implement more than 100 APIs in Azure Functions, but it is easy in frameworks that specialize in Web APIs (such as ASP.NET Core Web API).

Since the BYOF mechanism requires the user to be responsible for deployment, it is useful to be able to link Web APIs (not Azure Functions) at the Standard Tier and above.

**Describe alternatives you've considered**

- Migrating existing APIs to Azure Functions was impractical
- Considered routing using Front Door, but could not use Static Web App authentication

**Comment by gdurandrexel** [comment]
I would very much like to have this feature too.
And also the ability to deploy using a Release pipeline only (with approvals and so on).

Basically what I miss in Azure is a hosting solution for SPA:
- that can be handled exactly as a Web App: created with ARM, built with azure-pipelines.yml and deployed with a Release pipeline.
- with any resource as API backend (in my case a Web App, which also serves a mobile client) 
- with the CORS thingy to avoid preflight
- with a way to set some App Settings (for feature flags or api keys for instance, which can vary by environment), served as JSON via an URL relative to the SPA, e.g. /.config. I find App Settings easier to handle (ARM) than injecting them in the artifact during deployment.
- no need for auth, just basic hosting

But that's not what this project is for I guess, so I would appreciate if you could direct me to the proper channel for this kind of request.

**Comment by miwebst** [comment]
This is the right project for hosting SPA's. Today you can do all of the points you listed above with the exception that you currently need to use an Azure Function as the API backend.

@shibayan, this is a good ask and something we will take into consideration.

**Comment by shibayan** [comment]
@miwebst Thanks. For small SPA applications, Azure Functions (HttpTrigger and Event driven) are sufficient, but for feature-rich SPAs, I often want to use the Web API framework.

**Comment by shibayan** [comment]
Resolved https://docs.microsoft.com/en-us/azure/static-web-apps/apis-overview
