### ISSUE TITLE
Blazor WASM 'dotnet-isolated' is unsupported or invalid

### ISSUE THREAD

**Issue by cadelina13** [Azure/static-web-apps#601]
I don't know if I'm in the wrong thread but I can't find any solution on my problem.

I am using Blazor wasm and publish to azure static web with github integration, I have been publishing to github CI/CD for almost a month now then this problem came. 

Function Runtime Information. OS: Windows, Functions Runtime: v3, .NET Core version: 5.0
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
The content server has rejected the request with: BadRequest
Reason: The function language 'dotnet-isolated' is unsupported or invalid. The following languages are valid: node, dotnet, dotnetisolated, python.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

**Comment by anthonychu** [comment]
We will need more information to troubleshoot. Can you share the contents of csproj file for the function app? You can remove any information you don’t want shared.

**Comment by cadelina13** [comment]
> Thanks. I took a look at the broken action run and the successful ones that ran before/after it.
> 
> The repo had an `api_location` configured to a folder containing a .NET 5 ASP.NET Core app. The `api_location` is for defining the location of your Azure Functions app. We do not support ASP.NET Core apps.
> 
> Prior to yesterday, our GitHub Action that builds and deploys apps built and deployed the app with this misconfiguration without returning an error.
> 
> A new version of the GitHub Action was released yesterday that now fails builds with this misconfiguration.
> 
> Your application was later updated to remove the API app from the repo. When this happened, `api_location` now points to a non-existent folder instead of an ASP.NET Core app. The GitHub Action detects that the folder doesn't exist and skips the function app build and deployment, which is why the app builds and deploys again.
> 
> You can set `api_location` to an empty string or remove it entirely from the GitHub workflow file to avoid this from happening again.

thank you so much! i figured it out yesterday and I forgot to update here. I setup my github to ignore my ASP.NET Core API from pushing now it is successfully run on github action. I will close this issue now. God bless!
