### ISSUE TITLE
Azure DevOps yaml doesn't support staging environments?

### ISSUE THREAD

**Issue by IeuanPayne** [Azure/static-web-apps#604]
**Describe the bug**

Hello, 

I have recently started looking at the use of Azure SWA's for my Org and we use Azure DevOps for our source control. I have been looking at the docs to see how I can use environments for deploying staging code for non-prod before promoting to prod (and being available to external customers) 

Im not sure if its due to the lack of knowledge for this system or there is an issue with supporting this functionality form AzDO

Something I have noticed is that in the SWA the "Environments" tab is currently greyed out (don't understand what this could mean but maybe useful for you) 

**Additional context**

I have tried to follow the documentation but it seems as though it focuses on the use of GitHub rather than AzDO...

**Comment by IeuanPayne** [comment]
Just wanted to add my end goal:

So basically I would like to configure a blue green deployment for SWA's

So if the way I'm looking at it currently wont work. I'm open to suggestions.

**Comment by anthonychu** [comment]
What aspects of blue-green deployment are important to you?

Our deployments are atomic, so you should get the instantaneous “swap” behavior that you’d achieve with blue-green.

We don’t support environments in Azure DevOps yet. But that is how we plan on supporting previewing a site before taking it live.

We don’t yet have plans to support quickly swapping in a previously deployed version without deploying, or offer traffic splitting or canary deployments.

Your best bet today is to use two Static Web Apps and something like Azure Front Door to swap traffic between them. Or you can deploy to Azure App Service whose deployment slots feature supports blue-green deployments.

**Comment by RossMurr4y** [comment]
> Our deployments are atomic, so you should get the instantaneous “swap” behavior that you’d achieve with blue-green.

@anthonychu is there any documentation on how this works? I'm trying to track down information on what is actually happening during a deployment. I have the deploy logs but they don't reveal a great deal.

**Comment by anthonychu** [comment]
We don't document how things works exactly. But you should see the existing version being served during deployment, and when the deployment is complete the new version will be served. You should not see a mix of old and new assets being served at the same time.

**Comment by IeuanPayne** [comment]
@anthonychu you previously mentioned putting Azure frontdoor in front of two SWA's to simulate blue/green deployments. Do you happen to have any examples of this being done? Just so I can weigh up my options. Thank you!

**Comment by michalorac** [comment]
Is something new in support staging environments?
We would like to continue using AzureDevOps Environments with approvals for different stages (llike in other projects in which we use Azure Web App).

**Comment by Reshmi-Sriram** [comment]
Hey @michalorac!
We have a PR for supporting Stable Staging environments in DevOps, waiting to be merged [#15981](https://github.com/microsoft/azure-pipelines-tasks/pull/15981). We should be able to see these changes merged and released in another 3-6 weeks.
Hope this helps!

**Comment by michalorac** [comment]
Thanks @Reshmi-Sriram, 
I'll be waiting patiently for the update

**Comment by StephenStrickland** [comment]
@Reshmi-Sriram where is the best place to view/watch for updates?

**Comment by Reshmi-Sriram** [comment]
Hey @StephenStrickland,
I'm afraid I do not have the links to share to track the progress, but given the change is merged, you should be able to see it reflected and released soon :) 
Hope that helps!

**Comment by Reshmi-Sriram** [comment]
Apologies, we missed on updating this issue thread!
Static Web Apps announced support for [Named Preview Environments ](https://docs.microsoft.com/en-gb/azure/static-web-apps/named-environments?tabs=azure-devops)as well as [Stable Staging Preview Environments ](https://docs.microsoft.com/en-us/azure/static-web-apps/preview-environments)in May 2022. This enables one to add a custom prefix to the default generated URL.

Do let us know if this helps solve your problems! :)

**Comment by SchulteMarkus** [comment]
> Apologies, we missed on updating this issue thread! Static Web Apps announced support for [Named Preview Environments ](https://docs.microsoft.com/en-gb/azure/static-web-apps/named-environments?tabs=azure-devops)as well as [Stable Staging Preview Environments ](https://docs.microsoft.com/en-us/azure/static-web-apps/preview-environments)in May 2022. This enables one to add a custom prefix to the default generated URL.
> 
> Do let us know if this helps solve your problems! :)

Already using it for a couple of weeks - awesome!

**Comment by Reshmi-Sriram** [comment]
Closing, resolved.
