### ISSUE TITLE
Cannot set FUNCTIONS_WORKER_RUNTIME

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps#61]
Originally reported by @panesofglass 

Describe the bug
When I try to set a configuration setting for FUNCTIONS_WORKER_RUNTIME to python, I am allowed to save it and see that it saved successfully. However, when I refresh it, the value is removed. This happens in any environment configuration.

To Reproduce

Go to Azure Portal
Go to the Configuration pane
Add a new Configuration Setting
Use FUNCTIONS_WORKER_RUNTIME for the name and python for the value
Save the setting
Refresh and see that the setting has disappeared.
Expected behavior
The configuration setting that saved successfully should be retained.

Additional context
I'm trying to find a way to add an Azure Function using python or dotnet rather than node using a similar approach to that suggested for supporting Jekyll or other static generators by adding additional build steps. I assumed the only thing required would be to specify the FUNCTIONS_WORKER_RUNTIME, but that appears to not be possible b/c the setting keeps disappearing.

**Comment by panesofglass** [comment]
It seems that this is addressed by #62 and #78.

**Comment by anthonychu** [comment]
Let's close this and track using those other issues. Thanks!
