### ISSUE TITLE
Possibility to retrieve auto-generated pre-production URL within Azure DevOps pipeline run

### ISSUE THREAD

**Issue by svdHero** [Azure/static-web-apps#611]
**Is your feature request related to a problem? Please describe.**
This is a feature request that is related to #497.

We are using Azure Pipelines in Azure DevOps for CI/CD and want to implement dynamic deployment of Pull Requests. When using the pipeline task `AzureStaticWebApp@0`, I cannot specify the deployment slot / pre-production URL and I cannot retrieve it from anywhere.

Apparently, with Github Actions this works, as [the documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/review-publish-pull-requests#review-changes) says:

> After the pull request is created, the GitHub Actions deployment workflow runs and deploys your changes to a pre-production environment. Once the workflow has completed building and deploying your app, the GitHub bot adds a comment to your pull request which contains the URL of the pre-production environment. You can click on this link to see your staged changes.
>
> If you take a closer look at the URL, you can see that it's composed like this: https://<SUBDOMAIN-PULL_REQUEST_ID>.<AZURE_REGION>.azurestaticapps.net.

With Azure DevOps the pre-production URL is just some random URL like, e.g., `victorious-monkey-03a201573.azurestaticapps.net`.

**Describe the solution you'd like**
Basically similar behaviour like with Github Actions. More precisely:
- A possibility to save the pre-production URL in some environment variable within my Azure DevOps Pipeline run.
- A possibility to see the pre-production URL somewhere in my DevOps PR comments.
- A possibility to set the pre-production URL via the `AzureStaticWebApp@0` task, e.g. to something like the branch/PR name (compare Github Action example above).

**Describe alternatives you've considered**
There is no alternative for automated PR deployments.

**Additional context**
The pre-production URL is also needed for:
- Dynamically setting the RedirectURI in Azure AD/B2C:
  - Compare
    - #22
    - #551
    - #564
- Dynamically setting the CORS:
  - See #108
  - And https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-rest-api#enable-cors

**Comment by itpropro** [comment]
I think it was already mentioned in the other issue that it is not possible to implement due to platform differences between GitHub and Azure DevOps. So if that is still the case (@mkarmark ?) maybe there is a way to use GitHub for your source code/pipelines instead.
It seems like Azure DevOps will always be behind or not be considered for newer features/fixes not only for SWA, but for many newer (not only Azure) services.

**Comment by mshafiqmk** [comment]
Any updates on this issue ?

**Comment by mshafiqmk** [comment]
I have check docs and it mentioned in the limitation section that it is only possible using GitHub actions.

![image](https://user-images.githubusercontent.com/21343093/145352573-53f8f035-c208-4e6b-9642-6ab1eaa1dccf.png)

https://docs.microsoft.com/en-us/azure/static-web-apps/review-publish-pull-requests

@anthonychu any update when it will be available for devops deployment ?

**Comment by mishapos** [comment]
Hi! We have shipped [Branch Environments](https://docs.microsoft.com/en-us/azure/static-web-apps/branch-environments?tabs=azure-devops) and [Named Environments](https://docs.microsoft.com/en-us/azure/static-web-apps/named-environments?tabs=azure-devops) for GitHub and Azure DevOps which allows you to specify the name of a pre-production environment to deploy to. 

This will allow you to have a predictable URL for your pre-production deployments. Please let us know if this solves your issue, and thank you for using Static Web Apps 😄

**Comment by Reshmi-Sriram** [comment]
Closing this ticket, feel free to re-open if any concerns!
