### ISSUE TITLE
Azure Functions + .NET 6

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [Azure/static-web-apps#619]
Hello! Based on this [documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/apis#constraints):

> The Azure Functions app must either be in Node.js 12, **.NET Core 3.1**, or Python 3.8.

I am aware that Azure Functions 4.0 is in Preview and it supports .NET 6. Do you know if Static Web Apps will support Azure Functions 4.0 (and thus .NET 6) when .NET 6 is released on November 9th?

Thank you!

**Comment by anthonychu** [comment]
You can now deploy .NET 6 function apps (in-process or isolated) to Azure Static Web Apps! See [blog post](https://techcommunity.microsoft.com/t5/apps-on-azure/full-stack-net-6-apps-with-blazor-webassembly-and-azure-static/ba-p/2933428) for more information.
