### ISSUE TITLE
Support more Azure Function languages

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps#62]
Originally reported by @panesofglass
Is your feature request related to a problem? Please describe.
I am surprised only node Azure Functions are supported. The build results are unclear when attempting to use something else, e.g. dotnet or python. In the former case I got an error, and in the latter, Oryx thought the python function app was already built, so it succeeded but without enabling the function host.

Describe the solution you'd like
Support all options supported by Oryx.

Describe alternatives you've considered
I've considered adding additional build steps in the generated workflow as I've done for other custom static site generation.

Additional context
I realize these things are likely already on the roadmap, but I didn't see them in my initial search.

**Comment by 3lrv-ryan** [comment]
Any comments as to priority? I'd love to use this for a current project, but I need Azure Functions with Python and Event Grid support, not just node.js and HTTP. Thanks!

**Comment by anganti** [comment]
we are currently working on supporting both dotnet and python. @dariagrigoriu will be able to shed some light on the timelines.  

we can certainly take a look at enabling Event Grid trigger @joslinmicrosoft. Will revert here.

**Comment by jmarbutt** [comment]
Also watching for the dotnet support.

**Comment by miwebst** [comment]
Announced today, support for C# and Python functions in addition to JS! https://docs.microsoft.com/en-us/azure/static-web-apps/apis
