### ISSUE TITLE
Facebook authentication

### ISSUE THREAD

**Issue by mobiotwin** [Azure/static-web-apps#621]
Hi,

I have an static web app that uses Facebook and Google to login.

I already upgraded my app to Standard plan.
also I already created `staticwebapp.config.json` and add the following

```
{
    "routes": [
        {
            "route": "/*"
        }
    ],
    "navigationFallback": {
        "rewrite": "/index.html"
    },
    "auth": {
        "identityProviders": {
            "facebook": {
                "registration": {
                    "appIdSettingName": "FACEBOOK_APP_ID",
                    "appSecretSettingName": "FACEBOOK_APP_SECRET"
                }
            },
            "google": {
                "registration": {
                    "clientIdSettingName": "GOOGLE_CLIENT_ID",
                    "clientSecretSettingName": "GOOGLE_CLIENT_SECRET"
                }
            }
        }
    }
}
```

Already added the IDs and secrets on the application settings.

Google login works fine 
but Facebook does not work it return the following

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/87389828/140188535-7aa2ce08-9087-440e-8fe3-a3096d54ebe1.png)

**Comment by anthonychu** [comment]
@mkarmark Do you know if there’s any additional config that’s needed to make this work?

**Comment by Gabswim** [comment]
I am experiencing the same issue. 

After upgrading my to `staticwebapp.config.json`:

```json
{
    "routes": [
        {
            "route": "/*"
        }
    ],
    "navigationFallback": {
        "rewrite": "/index.html"
    },
    "auth": {
        "identityProviders": {
            "facebook": {
                "registration": {
                    "appIdSettingName": "FACEBOOK_APP_ID",
                    "appSecretSettingName": "FACEBOOK_APP_SECRET"
                }
            },
            "google": {
                "registration": {
                    "clientIdSettingName": "GOOGLE_CLIENT_ID",
                    "clientSecretSettingName": "GOOGLE_CLIENT_SECRET"
                }
            }
        }
    }
}
```
I am getting the same error. I notice that by default the `email` is not asked for the Facebook login (see image below).  Is this something that I can configure on my end, or it should be configured in Azure static web apps?
<img width="1770" alt="Screen Shot 2021-11-08 at 5 28 32 PM" src="https://user-images.githubusercontent.com/2859712/140828813-eb444d10-9bf8-4283-8760-b81bc7242d89.png">

**Comment by mobiotwin** [comment]
I have fixed it by adding the following
```
...
"facebook": {
                "registration": {
                    "appIdSettingName": "FACEBOOK_APP_ID",
                    "appSecretSettingName": "FACEBOOK_APP_SECRET"
                },
                "login": {
                    "scopes": [
                        "public_profile",
                        "email"
                    ],
                    "loginParameterNames": []
                }
            }
```
