### ISSUE TITLE
Change Node.js version of integrated Function App

### ISSUE THREAD

**Issue by itpropro** [Azure/static-web-apps#623]
I have multiple projects that require Node 14 or Node 16. How can I change the Node version of the integrated Function App in free tier (without using my own Function App)?

**Comment by itpropro** [comment]
Thanks for the update, do you already know, if it will be possible to update existing SWAs? I would then deploy the projects with bring your own function app and switch to the integrated one as soon as its availble.

**Comment by anthonychu** [comment]
Yes. We’ll give you a way to specify what version to use.

**Comment by geoffrich** [comment]
Chiming in with a +1 for this feature. I maintain the Azure SWA adapter for [SvelteKit](https://kit.svelte.dev/), which recently dropped Node 12 support. Until this is supported, people using my adapter will need to pin to an old SvelteKit version.

**Comment by itpropro** [comment]
Also just to make sure, when this feature lands, it will be possible to switch to Node 14 and 16 right? Many technologies I use already require Node 16 for some tasks so it wouldn't make sense to only support Node 14 at this point.

**Comment by anthonychu** [comment]
The current design will allow you to specify the API runtime version in staticwebapp.config.json. We plan to add both Node.js 14 and 16 at the same time. However, Node.js 16 support Azure Functions are still in public preview so we'll offer Node.js 16 as a preview feature as well.

Hope to have news to share on this in January.

**Comment by itpropro** [comment]
Sounds great, thanks for the update and happy holidays to the whole SWA team 🎄

**Comment by tiddydl** [comment]
Hello! any update on this? 😇

**Comment by gordonk** [comment]
Waiting impatiently :)
