### ISSUE TITLE
Azure DevOps Pipelines fails when app directory has a space

### ISSUE THREAD

**Issue by rossmills99** [Azure/static-web-apps#627]
**Describe the bug**

I have a repository with a Docusaurus site at relative path "docsite/My Docs".  When I set "/docsite/My Docs" as the `app_location` I see the error emitted:

```
---Oryx build logs---


Specify --help for a list of available options and commands.
Unrecognized command or argument 'Docs'
```

It looks suspiciously like the call to Oryx passes the app_location path unquoted, so it treats "Docs" as a separate argument.

**To Reproduce**
1. Create repo with static site at a path with a space in it.

**Expected behavior**
Should work even with spaces in the app_location path.

**Comment by anthonychu** [comment]
Yep looks like your suspicions are exactly right. 🙂

/cc @Reshmi-Sriram

**Comment by rossmills99** [comment]
Hey, I've worked around this issue by renaming the folders to remove spaces.  Nevertheless what's going to be the best way to get this fixed?  I'm not familiar enough with the codebase to contribute but it sounds like it should be an easy one... (famous last words)

**Comment by Reshmi-Sriram** [comment]
Hey @rossmills99!
We have an upcoming release which will fix this issue. The [Oryx release](https://github.com/microsoft/Oryx/releases/tag/20220131.3) for this fix is already in place. 
Thank you for reporting this bug! :)
