### ISSUE TITLE
Allow more than one staging environment

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps#63]
Originally reported by @panesofglass

Is your feature request related to a problem? Please describe.
It's nice that Static Apps will generate a staging environment, but limiting it to one and failing builds as a result of having multiple, outstanding PRs is frustrating.

Describe the solution you'd like
Don't fail a build due to limited environments. Post a comment on the successful build noting that a new environment was not created due to no available environments and how to fix it (essentially the same information as is in the failed build message).

Describe alternatives you've considered
Allow unlimited environments, though that's obviously going to cause problems when users get a much larger bill than expected. Possibly allow users to indicate the maximum number of environments they want and an expected price?

**Comment by dariagrigoriu** [comment]
We will consider expanding the number of pre-production environments for future general availability iterations.

**Comment by akzaidi** [comment]
Any timeline for GA? This would be a great feature!

**Comment by miwebst** [comment]
This has been bumped to 3 PR environments per site during preview.
