### ISSUE TITLE
Support node 16.13+ (Official LTS release)

### ISSUE THREAD

**Issue by Strepto** [Azure/static-web-apps#634]
**Is your feature request related to a problem? Please describe.**

The latest node lts release was officially released a few weeks ago as v16.13.0. 

<https://nodejs.org/en/blog/release/v16.13.0/>

We have dependencies that have transitioned to require at least the 16.13.+ release. 

The latest release supported by Azure Static Web Apps Github Action is 16.8.0. 

Are there any plans to upgrade the Github action to support the LTS release? 

**Describe the solution you'd like**

The official node 16 lts release version (16.13.0) available in the github action. 

**Describe alternatives you've considered**

Can I install node in a previous build step and use that version in the Static Web App build job with any magic?

Alternative is to manually build, and then have SWA github action just upload stuff, but thats not so easy.

**Comment by anthonychu** [comment]
Thanks for pointing this out. Created an issue in Oryx to track. microsoft/Oryx#1161

**Comment by dean-dot-git** [comment]
I second this!

**Comment by anthonychu** [comment]
Updated to 16.13.1.
