### ISSUE TITLE
workflow failure (unprovoked?): Failed to deploy the Azure Functions

### ISSUE THREAD

**Issue by sig9** [Azure/static-web-apps#638]
**Describe the bug**

The Build and Deploy step of our githoub action is failing. Started yesterday when we opened a PR. Re-run all jobs continues to fail today. 

This has been working reliably until now. The log messages are not helpful, not sure where else to look for clues.  seems like an infrastructure/hosting/service issue from what we can see here.  The PR doesn't have any changes to the api functions.

**To Reproduce**
1. Open a PR
2. Wait for failed Build and Deploy Job with message - Failed to deploy the Azure Functions
3. re-run all jobs
4. Wait for failed Build and Deploy Job with message - Failed to deploy the Azure Functions

![image](https://user-images.githubusercontent.com/2271605/142660288-696a7457-d487-4f57-b2a0-0bce692044fd.png)

screenshot of the workflow yaml
![image](https://user-images.githubusercontent.com/2271605/142660650-76490a81-9adc-4018-adb7-eaade029b5e1.png)

**Comment by riverar** [comment]
Seeing same issue, hard to get any diagnostic information. @anthonychu

**Comment by kbarnes3** [comment]
I'm seeing the same issue on two separate projects that use Azure Functions. I have other projects that use Static Web Apps to deploy just an Angular frontend with no Azure Functions associated and these continue to work fine.

**Comment by miwebst** [comment]
We are tracking this here. There is an issue with Azure Functions: https://github.com/Azure/static-web-apps/issues/632

**Comment by miwebst** [comment]
Sorry wrong link, this is the correct one: https://github.com/Azure/static-web-apps/issues/622
