### ISSUE TITLE
Error when deleting preview site before deleting PR

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps#64]
Originally reported by @MarkXA

Describe the bug
If you delete a PR preview site in the portal and then close the PR, the CD pipeline fails when it tries to remove the (now non-existent) preview.

To Reproduce

Create a PR in GitHub.
When the preview site has been created, delete it in the portal.
Close the PR in GitHub.
The deployment pipeline fails with an error:
The content server has rejected the request with: BadRequest
Reason: No matching static site environment was found.
Expected behavior
The deployment should ignore the BadRequest response in this situation.

Additional context
The rest of the preview experience works well 👍

**Comment by miwebst** [comment]
This has been fixed!
