### ISSUE TITLE
Restrict access to Application Gateway always returns 503

### ISSUE THREAD

**Issue by lukasvice** [Azure/static-web-apps#641]
**Describe the bug**

When I restrict networking with the service tag "GatewayManager", so that the Static Web App is only accessible via the Application Gateway, a 502 error is always returned.

**To Reproduce**
1. Configure the App Gateway Backend with the SWA's FQDN
2. Configure the access restriction to the App Gateway in the staticwebapp.config.json file
3. Open the SWA with the configured Gateway URL
4. Get a 503 Bad Gateway error

staticwebapp.config.json file:
```json
{
  "networking": {
    "allowedIpRanges": [
      "GatewayManager"
    ]
  },
  "forwardingGateway": {
    "allowedForwardedHosts": [
      "app-gateway-site-fqdn.example.com"
    ]
  }
}
```

**Expected behavior**

The SWA should be reachable only through the App Gateway and not return a 503.

**Additional context**

If I call the SWA directly using my private IP, it returns a 403, which should be correct. If I add my IP to the allowed ranges, the direct call works.
If I remove the networking restriction, i can open the SWA via the App Gateway. So the configuration of the App Gateway and SWA should be correct.

**Comment by anthonychu** [comment]
I'm not very familiar with setting up App Gateway. But I think the `GatewayManager` service tag might not be for regular traffic from App Gateway. In the [docs](https://docs.microsoft.com/azure/virtual-network/service-tags-overview#available-service-tags), it's described as `Management traffic for deployments dedicated to Azure VPN Gateway and Application Gateway.`.

I think you might need to put the App Gateway in a VNET, then use a [private endpoint](https://docs.microsoft.com/azure/static-web-apps/private-endpoint) to securely connect to the static web app.

**Comment by lukasvice** [comment]
Oh, I see, thanks for pointing that out. I will give it a try and let you know.

**Comment by lukasvice** [comment]
It works with the Private Endpoint. Thanks again!
