### ISSUE TITLE
Azure Pipelines task uses the deprecated Node 6 handler

### ISSUE THREAD

**Issue by srmagura** [Azure/static-web-apps#642]
**Is your feature request related to a problem? Please describe.**
Running `AzureStaticWebApp@0` in a pipeline (`ubuntu-latest`) prints a deprecation warning:

> This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**Describe the solution you'd like**
Upgrade the task to the latest Node execution handler.

**Comment by anthonychu** [comment]
This should be fixed in the latest task. Not sure if it's fully rolled out yet. Can you please check your logs and share what version of AzureStaticWebApp@0 was used?

**Comment by srmagura** [comment]
Good to know. My pipeline runs from earlier today used version 0.187.2.

**Comment by wilwer** [comment]
Hi, we have several pipelines failing at the moment with the same issue, same version (0.187.2). Is there any news?

**Comment by anthonychu** [comment]
@wilwer this should be a warning. Can you confirm that this is showing as an error for you and it’s causing the build to fail?

**Comment by anthonychu** [comment]
@anatolybolshakov Can you please confirm that this warning should not fail a build? And do you know if there is an ETA for the release of the latest AzureStaticWebApp task?

**Comment by anatolybolshakov** [comment]
@anthonychu yes, since this is a warning message - it should not cause build failure. The roll out process has already been started - usually it takes about 2-3 weeks to be completed (so it should be rolled out during 197 sprint per [calendar](https://whatsprintis.it/)).

**Comment by simonaco** [comment]
@srmagura @wilwer we recently released task 0.194.2 which should address this issue.
