### ISSUE TITLE
keyvault references in standard static web apps not working + request for tick/wrong marking

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/static-web-apps#645]
**Describe the bug**

This is feature request. But there is some probability of this also being a bug - same as #428, but on bring your own functions/standard plan/production environment.

@Microsoft.KeyVault references are not working in static web apps (swa) with bring your own functions also (in standard plan/production environment). I have followed this [microsoft doc](https://docs.microsoft.com/en-us/azure/static-web-apps/key-vault-secrets), enabled system identity, added access policy in keyvault and added application setting as in screenshot. 

More importantly, unlike web/function app settings, in swa, we don't have a way to verify if the keyvault reference is good or bad with the red/green tick marks as in attached screenshot. Is there a way to debug why the references are not working?

**To Reproduce**
For [custom authentication](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad) in swa, I added parameters AAD_CLIENT_ID and AAD_CLIENT_KEY as keyvault references (screenshot).

**Expected behavior**
In Azure portal, static web app key vault references should have tick or wrong marks like in Web apps or function apps keyvault references

**Screenshots**
![swa_error](https://user-images.githubusercontent.com/1491933/143376612-689b8cd6-418b-4250-8e5f-ae45ad898d27.png)

**Device info (if applicable):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96

**Additional context**
Or is it like keyvault references are allowed only for linked function application and not for the static web app itself? If that is the case, where should we save AAD_CLIENT_ID and AAD_CLIENT_KEY ?

**Comment by kiranpradeep** [comment]
Closing as not an issue. But the suggestion of tick/wrong mark remains.

**Comment by sonamm19** [comment]
Any update on this one?

**Comment by kiranpradeep** [comment]
For completeness

1. For me, this issue happened only after around 3 months from deployment. All worked well for around initial 3 months after which it started failing. If you face the issue on day 1, then this issue is different from what you are facing.
2. I raised Azure support ticket (#2208050030000788) and after long, I got below reply and the issue was fixed.

>  Upon investigation, engineers discovered that due to a day 0 bug in the renewal logic, Managed Identity certificates were not getting renewed as expected. Because of that, we were using expired managed identity certificates to access Key Vault secrets, so Key Vault was correctly rejecting our attempts at resolving the app settings. We mitigated the issue by deploying a fix in the Managed Identity certificate renewal logic so that the sites with expired certificates were able to fetch fresh certificates and resolve key vault references.


For static web apps, I suggest you raise your issue in Azure Support portal. It appears this repo gets little attention. Closing.
