### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by mellson** [Azure/static-web-apps#650]
Is it possible to configure a static web app with IPv6 support when it's hosted on Azure?

**Comment by simonaco** [comment]
@mellson can you provide more context on your use case?

**Comment by mellson** [comment]
@simonaco sure, thanks for the comment. My primary use case is to make our site as available as possible. Our site is a B2B application targeting primarily businesses in Denmark. And the government in Denmark has put up this site https://xn--sikkerpnettet-vfb.dk/ which checks how "safe" a website is. Some of the tests they run are to check if your site can be reached using IPv6 addresses. So when it can't you get a worse score which is not ideal for us.

**Comment by simonaco** [comment]
@mellson we recently released the public preview of enterprise-grade edge which adds IPv6 support to static web apps. [Enterprise-grade edge](https://docs.microsoft.com/azure/static-web-apps/enterprise-edge?tabs=azure-portal)

**Comment by mellson** [comment]
@simonaco that sounds great - thanks for the update. I'll try the preview later this week.
