### ISSUE TITLE
GitHub actions

### ISSUE THREAD

**Issue by springcomp** [Azure/static-web-apps#656]
**Describe the bug**

From a working SWA project with a .net core 3.1 function app as a backend API, I’m trying to switch the function app to .net 6.0.
However, this fails in the GitHub actions deployment.

GitHub actions’ [Build and Deploy Job](https://github.com/springcomp/my-app/runs/4467961865?check_suite_focus=true) error.

**Screenshots**

![image](https://user-images.githubusercontent.com/8488398/145364829-cc4a0371-b0d8-47a3-b3e2-eda467610512.png)

**Comment by anthonychu** [comment]
Did you try building the app locally? The [framework version](https://github.com/springcomp/my-app/blob/edca0bebc7b4f82632468095792433053c0671be/api/api.csproj#L3) is incorrect. You should be using `net6.0` as indicated by this [list](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#latest-versions).

**Comment by springcomp** [comment]
@anthonychu

Yes, indeed, I tested this with success locally inside the SWA emulator.

My Azure Function [.csproj](https://github.com/springcomp/my-app/blob/feature/net6.0/api/api.csproj#L3) file targets .net 6.0.

**Comment by anthonychu** [comment]
Please use the documented target framework moniker of `net6.0` in your csproj (not `net60`).

**Comment by springcomp** [comment]
@anthonychu, thanks for pointing this out.

So obvious in hindsight. 🤦‍♂️
