### ISSUE TITLE
Option to add extra HTTP response headers

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps#66]
Originally reported by @liprec

Is your feature request related to a problem? Please describe.
Currently there is no option to set additional HTTP response headers like CSP headers or X-Content-Type-Options. Scanning via https://securityheaders.com/ or WebHint (https://webhint.io/docs/user-guide/hints/hint-x-content-type-options/) results in several security remarks.

Describe the solution you'd like
Some option to add HTTP response headers. Could be either via an extra configuration setting with the service or maybe via a json file in the root that contains the extra HTTP response headers inline with the routes.json option.

More context: the idea here would be that on any static assets that are served you'd like these headers to be added as well

**Comment by miwebst** [comment]
https://github.com/Azure/static-web-apps/issues/2

**Comment by miwebst** [comment]
We have added the ability to add DefaultHeaders to responses, you can find the documentation here: https://docs.microsoft.com/en-us/azure/static-web-apps/routes#default-headers

For now this is part of the routes.json, in the future this file is likely to change to something more generic.
