### ISSUE TITLE
Securing Azure SQL used by SWA API Azure Function

### ISSUE THREAD

**Issue by jpalo** [Azure/static-web-apps#668]
When accessing Azure SQL from SWA API (managed Azure Function), I assume I need to open the SQL to the world firewall-wise? Should I move to "Bring your own Function" model if I'd like to limit access to SQL using VNET & private endpoints only for my Azure Function?

**Comment by miwebst** [comment]
"Bring your own function" is the only way to do this today. You will need to make sure your Function is accessible publicly too.
