### ISSUE TITLE
Add alternative domain validation for custom domain

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps#67]
Originally reported by @liprec

Is your feature request related to a problem? Please describe.
To add a custom domain to the Azure Static Web App service you need to add a CNAME record for the custom (sub)domain that points to the *.azurestaticapps.net URL to validate the ownership of the domain.
If you want to move your current production site to the Azure Static Web App service this validation and assignment step will need downtime of your website due to the DNS change.

Describe the solution you'd like
An option to validate the custom domain via an alternative way so the move of the site can only triggered by an DNS update. Alternative validation can be done via a TXT record or via an alternative CNAME record (see e.g. the CDN option: https://docs.microsoft.com/en-us/azure/cdn/cdn-map-content-to-custom-domain#map-the-temporary-cdnverify-subdomain)

**Comment by liprec** [comment]
Someone of the team can close this issue as this option is available. Thanks and congratulations with the GA 🎉!
