### ISSUE TITLE
Deployment without index.html?

### ISSUE THREAD

**Issue by biltongza** [Azure/static-web-apps#671]
I'm using SvelteKit and trying to publish a site with server side rendering enabled. My root page has dynamic content, so I can't prerender it to just a plain html file and publish that because the contents get written at build time and then never updated. 

Trying to use oryx to deploy without an index.html fails, telling me that it is required. So I tried creating a dummy index.html and using a rewrite rule for index.html, instead sending them to `/api/__render` which is the api endpoint that gets created for server side rendering. This works just fine in the emulator, but doesn't seem to work in the deployed site, and I just get my dummy index.html file content instead.

Is this a supported scenario at all?

**Comment by anthonychu** [comment]
Yes. You should be able to add the dummy index.html plus these 2 route rules in staticwebapp.config.json to make this work:

```json
[
  {
    "route": "/index.html",
    "rewrite": "/api/__render"
  },
  {
    "route": "/",
    "rewrite": "/api/__render"
  }
]
```

We're hesitant to remove the index.html check as this catches a significant number of workflow misconfigurations, so you'll need to use this workaround for now.

**Comment by biltongza** [comment]
Awesome, that works perfectly. Thanks!
