### ISSUE TITLE
Angular apps with Routing fail when navigating

### ISSUE THREAD

**Issue by SheldonHage** [Azure/static-web-apps#675]
I have a few Angular apps ranging from drop-dead simple to highly complex each using Angular Routing.

I've successfully enabled **VS Code** --> **Github** --> **Actions** --> **Deploy to Static Web App** for a few of them.

When any of the apps navigate from WITHIN the app, the navigation works fine.   So this is ok.

To reproduce using a **simple app with basic routing**:
1.  Build and deploy an Angular app that has routing
2.  Access the web app like:  https:/<static-web-url>.azurestaticapps.net/
3.  Refresh the browser.   This should work.
4.  Navigate away from the root to whatever route you setup.
      ex:  https:/<static-web-url>.azurestaticapps.net/home.  <--
5.  Refresh the browser.
6. Encounter a 404 error

 To reproduce using an **Angular app w/ routing that uses MSAL / Azure AD B2C** (mine uses a tenant):
1.   Follow steps 1 & 2 about.
2.  Since Azure B2C will redirect after AuthN, encounter 404 error here. 

**Expected behavior**
Obviously I would expect Static Web Apps to support Angular with routing.   Even the most basic apps use it.

**Screenshots**
Video attached.  Hopefully it comes through.

https://user-images.githubusercontent.com/49240336/147826695-7a8982aa-e1a3-40a5-8387-49823bea7696.mp4

**Comment by miwebst** [comment]
Have you configured a navigation fallback via the staticwebapp.config.json: https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#fallback-routes

**Comment by SheldonHage** [comment]
I have not.   This could be the issue; will verify.

**Comment by SheldonHage** [comment]
This did solve it.
