### ISSUE TITLE
Deleting Static Web App from within VS Code leaves behind Azure Resource Groups

### ISSUE THREAD

**Issue by SheldonHage** [Azure/static-web-apps#676]
**Deleting Static Web App from within VS Code leaves behind Azure Resource Groups**

**To Reproduce**
1.   Use VS Code to checkin code to Github with action to deploy to new Azure Static Web App
2.   After successful build and deployment...
3.   Go to Azure Portal and see that a dedicated resource group was created for the static web app
4.   In VS Code, use the Static Web App plugin to **delete** the Static Web App
5.   Go back to Azure portal and see that the dedicated resource group remains.

**Expected behavior**
I think this should be handled differently.   Basically what I saw after a number of trial and error failed deployments and deleting the static web apps from within VS Code, my Azure portal had many resource groups with auto-incremented names.  In practice these would leave a person unsure which was still in use and which weren't

**Comment by Reshmi-Sriram** [comment]
Hey @SheldonHage, 
Thank you for raising this issue! Since it is concerned with VSCode, I'm transferring the issue to the VSCode Staticwebapps issues (https://github.com/microsoft/vscode-azurestaticwebapps/issues)
Feel free to re-open it here later if needed!
