### ISSUE TITLE
How does the Globally Distributed static content work with other features?

### ISSUE THREAD

**Issue by rhalaly** [Azure/static-web-apps#678]
In your docs you say that one of the key features you have in Azure Static Web Apps is:
> Globally distributed static content, putting content closer to your users.

I don't understand how it can work with other features like authentication.
If I have this `staticwebapp.json`:
```json
{
  "routes": [
    {
      "route": "/*",
      "allowedRoles": ["authenticated"]
    }
  ]
}
```

I don't have any code in my HTML+JS that enforces the authentication, but still, something enforces that rule.

On one hand, you claim that the static content is globally distributed. 
On the other hand, you claim that the Azure Functions (managed) are deployed to one region:
> Azure Static Web Apps is a global service. Your app's static assets are globally distributed. When you create your app, you select a region where the managed Azure Functions app is deployed.

So, the backend that enforces the other features cannot be Azure Functions since it is deployed to one region.

So, how does Azure Static Web Apps enforces such features and still allow globally distributed static content?

**Comment by miwebst** [comment]
Azure Static Web Apps globally distributes your static content. All requests are routed to our edge nodes where various logic is applied such as routing rules. The various features in the config file are independent of any serverless functions you add to your project.

**Comment by rhalaly** [comment]
Not sure I understand the flow.

What is the flow of a user that want to navigate to any page with the config from my first comment?

There is a lot of logic happening before the static content...
Your servers need to reads the config file, authorize the user with the context cookie, and if authorize, return the static content.

Is this server logic global distributed?

**Comment by miwebst** [comment]
Our edge nodes how to interpret the config file and your rules are applied before static content is served. This happens at our globally distributed edge nodes.

**Comment by gterminator** [comment]
Means in the end the "global distribution" is a lie when you just "route it".
I've tested it now. Makes me really mad, because it is a lie in the documentation and have now find another way to distribute the content.
