### ISSUE TITLE
Reuse of existing GitHub workflows/secrets

### ISSUE THREAD

**Issue by simonaco** [Azure/static-web-apps#68]
Originally reported by @liprec

Is your feature request related to a problem? Please describe.
Created multiple times an Azure Static Web App and linked it to the same GitHub repo due to #18, and each time copy + pasted the old workflow definition to the new one and replace the secret variable to get it working.

Describe the solution you'd like
During the configuration of the Azure Static Web App add an extra option to choose the GitHub objects (workflow yaml/ secret).
Could also used to provide your own name regarding the workflow file name and secret.

Describe alternatives you've considered
None.

**Comment by Reshmi-Sriram** [comment]
Closing due to no traction.
