### ISSUE TITLE
Returning 301 status from API shows 500 page

### ISSUE THREAD

**Issue by geoffrich** [Azure/static-web-apps#680]
**Describe the bug**

Returning a 301 status from the API shows an Azure "500: Internal Server Error" page and does not perform the redirect. Interestingly, returning a 302 works as expected and _does_ successfully perform the redirect.

**To Reproduce**
1. Create a fresh Azure SWA project with just an `index.html`
2. Add an HTTP triggered function called "redirect" with the following implementation. Note that the status defaults to 301, but can be overridden by a query param to help with testing.
```js
module.exports = async function (context, req) {
    const status = req.query.status || 301;
    
    context.res = {
        status,
        headers: {
            location: "/"
        }
    }
}
```
3. Deploy the function and navigate to `/api/redirect`. A 500 page is shown. Going to `/api/redirect?status=302` will make the function return a 302 instead and correctly perform the redirect.

Live demo: https://lemon-water-0ee4dc01e.azurestaticapps.net/api/redirect
Repo: https://github.com/geoffrich/azure-swa-redirect-issue

**Expected behavior**
A 301 is returned instead of a 500.

**Screenshots**
n/a

**Device info (if applicable):**
n/a

**Additional context**
This is causing an issue with my [SvelteKit adapter](https://github.com/geoffrich/svelte-adapter-azure-swa) for Azure SWA. If the SvelteKit app returns a 301, Azure SWA shows an error instead of performing the redirect.

I added App Insights to a different app showing this issue and did not see any error or exception logged when the 500 was returned, which is strange.

**Comment by miwebst** [comment]
Thanks for reporting this, we will get this fixed.

**Comment by miwebst** [comment]
This should be fixed now!

**Comment by geoffrich** [comment]
Great, thanks! Seems like the fix is working on my end.
