### ISSUE TITLE
Undocumented not allowed parameter for functions

### ISSUE THREAD

**Issue by paule96** [Azure/static-web-apps#684]
**Describe the bug**

If you write a function that accepts as a query parameter `code` it will throw a 500 http error.
This error can't be reproduced local so I think it's an issue in the static web apps repo. It only happens after deployment.

You can see the issue and the fix in this [Commit](https://github.com/codez-one/CZ.Azure.FileExchange/commit/fd246b8c62baee5f5604828131b4b13ebf856c13).

**To Reproduce**
1. Create with dotnet a new function project (I used dotnet 6)
2. In the default template of a http function there is requesting a name with the query parameter `name`
3. change this parameter to `code`
4. deploy
5. try to call the function with the query parameter `code`
6. Get an 500 HTTP error

**Expected behavior**
The would be no error or it would be at least documented. It would be also nice if the server error would return a message like: `it's not allowed to use a query parameter ``code`` `

**Comment by miwebst** [comment]
Repeat of this longstanding issue, please use that issue for tracking: https://github.com/Azure/static-web-apps/issues/165
