### ISSUE TITLE
The portal doesn't always warn for unsaved data in Application Settings

### ISSUE THREAD

**Issue by aelgasser** [Azure/static-web-apps#69]
I was working with Application Settings and found that it doesn't persist them until you click **Save** (see my other issue in the docs section https://github.com/MicrosoftDocs/azure-docs/issues/57341).

Although when clicking on **Refresh** (once I saw that toolbar on top :-) ) it shows this warning, which is a good thing:

![image](https://user-images.githubusercontent.com/3692722/85016467-11b5d380-b16a-11ea-806a-aae1b439feb0.png)

But if you click away on any other link, in the left sidebar, for example, it just goes away without warning and without saving.

It should either warn the user that items aren't saved or save automatically when an item is added.

Thank you

**Comment by takyyon** [comment]
Thanks for this! We have made the necessary changes on our end which should be deployed in a couple of weeks.
