### ISSUE TITLE
Custom Domain Setup with GoDaddy dosent work

### ISSUE THREAD

**Issue by v2kiran** [Azure/static-web-apps#696]
**Describe the bug**

Hi

I am trying to add a custom domain to a azure static web site and I keep getting this error message:

```
An unknown error has occurred while adding your custom domain. Please try again later.
```

**To Reproduce**

- Bought a domain via Godaddy
- create azure static web app in Azure
- azure generates a random domain name - test it in browser and made sure it works
- create subdomain (blog) in godaddy ( CNAME pointing to random domain generated by azure)
- wait for 72 hrs for dns propagation.
- tested subdomain name resolution --> blog.xyz.com resolves to "white-tiger123" (azure random domain)

try to add the subdomain(blog.xyz.com) to the static web app in Azure portal - it validates fine but after clicking close the status says "failed" and then the error message posted at the beginning of this post shows up.

tried with another CNAME "www" - same behavior.

**Expected behavior**
Be able to browse the web app with the custom domain (blog.xyz.com)

**Screenshots**
![image](https://user-images.githubusercontent.com/7691373/151182359-90138929-69ed-4c85-b593-2cbbbdca3423.png)

Godaddy DNS settings
![image](https://user-images.githubusercontent.com/7691373/151183252-0940297f-4737-447b-9abd-b1f464de2974.png)

**Additional context**
The Azure generated random domain is below:
```
white-wave-023dce200.azurestaticapps.net
```

**Comment by miwebst** [comment]
Hi @v2kiran , this custom domain was flagged but we have since gotten it unblocked. Can you try again?

**Comment by v2kiran** [comment]
Hi @miwebst - thanks for unblocking the domain . yes just re-added and it went through 🙂

Thanks for the help
regards
Kiran

**Comment by miwebst** [comment]
Great to hear!

**Comment by The-Smallest** [comment]
@miwebst Hi, also keep on getting `An unknown error has occurred while adding your custom domain. Please try again later.` trying to add custom domain `mirporter.ru`. (DNS is hosted Azure). 
I even bought another domain and I have no problems adding it to static site.
How can I check if my domain `mirporter.ru` is flagged?

**Comment by bartoszlisiecki** [comment]
@miwebst Hi, I have same problem with it `An unknown error has occurred while adding your custom domain. Please try again later.`.  CNAME is set and propagated. What should i do with it?
