### ISSUE TITLE
The Application Settings page is sometimes unresponsive

### ISSUE THREAD

**Issue by aelgasser** [Azure/static-web-apps#70]
The Application Settings page often becomes unresponsive after loading the initial settings. As you see below my settings are loaded (blurred the sensitive ones) but I can't click on **Add**, **Show values** or **Advanced edit**.

![image](https://user-images.githubusercontent.com/3692722/85017100-3c545c00-b16b-11ea-9b4f-0bdf7ba13881.png)

I just traced the network activity on the tab (running Edge Chromium Version 83.0.478.45 (Official build) (64-bit)) and found this: 

![image](https://user-images.githubusercontent.com/3692722/85017604-02378a00-b16c-11ea-9549-b6a540f2bf01.png)

![image](https://user-images.githubusercontent.com/3692722/85017773-58a4c880-b16c-11ea-926a-59d9a6c66bba.png)

![image](https://user-images.githubusercontent.com/3692722/85017802-635f5d80-b16c-11ea-87a2-865b73cc041d.png)

The timing here looks like it is reaching a timeout after about 30 seconds.

Can you look into this.

Thank you.

**Comment by aelgasser** [comment]
This issue as most likely confirmed to have been caused by an outage on Azure Functions in West Europe as described by https://github.com/Azure/static-web-apps/issues/71#issuecomment-646808818

I'm leaving the issue open as a reminder to improve the experience on the portal if it occurs again (see https://github.com/Azure/static-web-apps/issues/71#issuecomment-646814188)

**Comment by takyyon** [comment]
Thank you for the suggestion @aelgasser! I think it makes sense to handle the UX in such a scenario. I can include that update  in the next deployment. Closing this issue for now.
