### ISSUE TITLE
Deployment failed with err ELIFECYCLE

### ISSUE THREAD

**Issue by Shruti700** [Azure/static-web-apps#707]
**Describe the bug**

I have been trying to deploy a simple react based web app to the Azure static web app via Github actions , but it failed several times responding with error code ELIFECYCLE. As said in official documents and google searches, I have tried deleting package-lock.json and reinstalling npm as well, but it didn't worked. 

**To Reproduce**
1. Go to my github repository : https://github.com/Shruti700/betterbuys
2. Click on 'Actions/ Build and deploy job'
3. Scroll down

Azure workflow file:
`name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_BUSH_0A3A34510 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_BUSH_0A3A34510 }}
          action: "close"`

**Expected behavior**
It should have deployed without error
![Screenshot 2022-01-29 224905](https://user-images.githubusercontent.com/63151043/151670574-f15a5a69-43a2-453c-a6f5-a8d502a4d1b2.png)

**Screenshots**

**Device info (if applicable):**

**Additional context**

**Comment by miwebst** [comment]
Looks like it failed to compile? It is important that in the CI environment, warnings are treated as errors. You can manually switch this to false to allow warnings if you'd like.

Relevant logs from your action run:

```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.

src/components/CheckoutForm/AddressForm.jsx
  Line 41:6:  React Hook useEffect has a missing dependency: 'checkoutToken.id'. Either include it or remove the dependency array                          react-hooks/exhaustive-deps
  Line 49:6:  React Hook useEffect has missing dependencies: 'checkoutToken.id' and 'shippingCountry'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

src/components/CheckoutForm/Checkout/Checkout.jsx
  Line 36:6:  React Hook useEffect has missing dependencies: 'activeStep' and 'history'. Either include them or remove the dependency array  react-hooks/exhaustive-deps

src/components/CheckoutForm/PaymentForm.jsx
  Line 19:20:  'paymentMethod' is assigned a value but never used  no-unused-vars

src/components/Navbar/Navbar.jsx
  Line 2:42:  'MenuItem' is defined but never used  no-unused-vars
  Line 2:51:  'Menu' is defined but never used      no-unused-vars
```

**Comment by mkarmark** [comment]
@Shruti700 Hi! Just wanted to follow up on this issue to see if Mitch's reply helped unblock you or if you are still blocked, since I didn't see much action on this thread!

**Comment by Shruti700** [comment]
Hello @mkarmark I did tried to according to Mitch's comment but unfortunately it didn't work. Eventually I switched and directly deployed it through the azure  app services via azure portal. Presently my application is up and running. Thank you and also sorry for my delayed response.
