### ISSUE TITLE
Improper scope requested when calling /.auth/login/twitter

### ISSUE THREAD

**Issue by FrankBurmo** [Azure/static-web-apps#708]
When a user logins with their Twitter-account, way to much access to the twitter-account is requested by the SWA.

**To Reproduce**
1. Go to a link in your SWA that points to "/.auth/login/twitter"
2. Then the user gets a prompt from twitter to grant way to much permissions to their twitter-account, see screenshot.

(Screenshot is in Norwegian, but in summary the permissions requested in addional to "normal" ones: "Follow and de-follow users", "Post and delete tweets", "Hide, block and rapport accounts on behalf of you"++++++). 

**Expected behavior**
A prompt from twitter where minimal permissions are presented to the user, eg. plain user-information.

**Screenshots**
![image](https://user-images.githubusercontent.com/2544148/151671735-f67d4dd2-a444-41bf-8d3a-9a78fbf27ece.png)

**Comment by mkarmark** [comment]
Hi @FrankBurmo, thanks for bringing this to our attention. We have now adjusted our settings on our end for Twitter to request far fewer permissions from the user logging in. Give logging in a try and let us know if things are now sufficient for you! Thanks!
