### ISSUE TITLE
Static files not served compressed

### ISSUE THREAD

**Issue by johnknoop** [Azure/static-web-apps#714]
## Expected result

From what I've found in the documentation and other Github issues, static files like images are supposed to be served in compressed form (using brotli) if the browser supports it (determined by the `accept-encoding` header.

## Observed result

Even though my browser passes this value in the `accept-encoding` header:

![image](https://user-images.githubusercontent.com/3394270/152500552-9b32022d-7713-44db-b9e8-c014dba83b29.png)

The images served by my Azure Static WebApp seem to be returned uncompressed (outlined with red pen) while content from other domains (Facebook for example) are brotly-compressed (outlined in green):

![image](https://user-images.githubusercontent.com/3394270/152501169-36e61b2d-559e-4c0f-aae2-5962b19dd784.png)

**Comment by anthonychu** [comment]
Only certain mime types are automatically compressed. You can include compressed versions of files that are not automatically compressed. https://docs.microsoft.com/en-us/azure/static-web-apps/faq#how-do-i-enable-gzip-or-brotli-compression-

@miwebst Is there a list of types that are automatically compressed?

**Comment by johnknoop** [comment]
@anthonychu 

Thanks!
