### ISSUE TITLE
Add claims to local emulator login screen and /.auth/me local endpoint

### ISSUE THREAD

**Issue by hags1975** [Azure/static-web-apps#717]
Can't provide claims in local emulator.

Provide an array input of claims similar to what you see in a live static web app site in the local login form.

![image](https://user-images.githubusercontent.com/22360470/152892622-827e5abc-d75d-44b4-b1f7-8183a49515d1.png)

Link to documenation:
https://docs.microsoft.com/en-us/azure/static-web-apps/local-development

**Comment by aaronpowell** [comment]
@AndreasHaggren I'd suggest raising the issue directly on the CLI repo - https://github.com/Azure/static-web-apps-cli/issues

**Comment by hags1975** [comment]
Raised it here instead:
 https://github.com/Azure/static-web-apps-cli/issues
