### ISSUE TITLE
Route containing plus sign '+' returns 404

### ISSUE THREAD

**Issue by shawntoffel** [Azure/static-web-apps#72]
One of my hugo generated blogs currently hosted in Azure blob storage allows authors to specify their own tags for grouping posts. One of the tags happens to be "A+" which results in a URL such as https://contoso.com/tags/A+/

Hosted via Azure Static Web Apps this URL returns a 404 HTTP status code with content: "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

Using a URL encoded plus sign "%2B" has the same result.

**Comment by miwebst** [comment]
Hi @shawntoffel thanks for reporting this! We will take a look and get back to you.

**Comment by miwebst** [comment]
Hi @shawntoffel we have found the issue and are working on a fix, it will roll out with our next update.

**Comment by shawntoffel** [comment]
Excellent. Thank you!

**Comment by miwebst** [comment]
Just an update here, the problem is actually more complex than we originally thought it was. We are still working on a solution to this but it will take more time than our next release. I apologize for the inconvenience!

**Comment by araemo** [comment]
I think I am running into the same problem.  I spotted this in the application logs for my web service (so, I'm not sure if this counts as a static web app, even though I'm only doing static file hosting):
```
<h3>HTTP Error 404.11 - Not Found</h3><h4>The request filtering module is configured to deny a request that contains a double escape sequence.</h4>
```
So... I tried to use a web.config to set ```<requestFiltering allowDoubleEscaping="true" />``` as I have seen as fixes to the above message, but that caused my site to stop serving any files with a 500 error instead.

**Comment by IT-CASADO** [comment]
I'm running into the same problem and didn't find a way to make it work...

**Comment by miwebst** [comment]
We are about 2 weeks away from having this fixed. I'll update this thread when it is.

**Comment by thomastvedt** [comment]
We're getting 404 on url's containing `@` and `#`. I guess this could be related? Are there any (temporary) workarounds?

**Comment by miwebst** [comment]
Do you have an example for the `#`?  I believe this is the same problem for the `@`

**Comment by miwebst** [comment]
This should be fixed now for the `+` case. Thank you for your patience! @thomastvedt can you check if your scenarios are now fixed too?

**Comment by thomastvedt** [comment]
Example url: https://myapp.azurestaticapps.net/en/path/123/50802202220573Z/mail@customer.no#0f654e0811aa02651002b92cdc4

routes.json:
```
  "routes": [
    {
      "route": "/*",
      "serve": "/index.html",
      "statusCode": 200
    }
  ],
```

This path should be redirected to our SPA, but resulted in 404. I did a quick test now, and this still results in 404 :( I'll test some more tomorrow 👍🏼

**Comment by thomastvedt** [comment]
Happy new year!  🚀
Any news on this one? 😄

**Comment by miwebst** [comment]
Hey @thomastvedt,

Happy new year! Sorry for the long delay. We have something in the works that will address this. I will follow-up here when that is public and ready for use!

**Comment by aDotNetDeveloper** [comment]
Hi,

Any update on this?

I have this Static Wed App configuration

    {
        "route": "/blog",
        "redirect": "/#blog"
    },  

so www.mydomain.com/blog should redirect to the #blog anchor on the root page

but it gets encoded along the way to www.mydomain.com/%23blog
resulting in a 404

**Comment by thomastvedt** [comment]
We switched from azure static web apps to kubernetes partly because of this. You often need fine grained control of routing / nginx (?)

**Comment by stephane-vanraes** [comment]
Is there any news on this ?

We are hosting a SvelteKit app on azure and their latest routing system generates file like `+layout-123456.css`, the plus sign in the name causes those assets to have a 404, making azure static web apps unusable for that framework.

**Comment by manishranjanthakur123** [comment]
It doesn't work .(dot) as well, as someone already mentioned above, which is generic use case fx containing jwt token in url. any update please?

**Comment by minimumphalcon** [comment]
We have a problem with . (dot) as well. A workaround was to change `site.com/action/abc.d` to `site.com/action?abc.d` but have not gotten around `site.com/.well-known/apple-app-site-association`

**Comment by riverar** [comment]
@anthonychu Hit this too, this issue is 3 years old. Is this repository dead? Who's triaging this?

**Comment by austincrft** [comment]
I am also hitting the dot issue

**Comment by lakswin** [comment]
> This should be fixed now for the `+` case. Thank you for your patience! @thomastvedt can you check if your scenarios are now fixed too?

Are there any resolution already for '+' in Azure? It still exists! @miwebst

**Comment by thomastvedt** [comment]
> > This should be fixed now for the `+` case. Thank you for your patience! @thomastvedt can you check if your scenarios are now fixed too?
> 
> Are there any resolution already for '+' in Azure? It still exists! @miwebst

I would recommend using something else 🙈

**Comment by shawntoffel** [comment]
Hello,

I can confirm the original problem that this issue was opened for has indeed been resolved for some time.

As a reminder, the original issue was that my static site has a directory on disk /tags/A+. When navigating to /tags/A+ in the browser a 404 was returned instead of the expected index.html in that directory. This hasn't occurred since the fix.

I tested '+', '#', '@', and '.', all still work properly on my site. I believe this issue can be closed as resolved. Perhaps there is a different issue folks are encountering?
