### ISSUE TITLE
Azure Static Web redirect the user to authenticated requested page after successful login 

### ISSUE THREAD

**Issue by shobhitkasliwal-onbe** [Azure/static-web-apps#738]
Hello, 
I am using the static web app and have all pages that starts with route /internal/* needs authentication.  It works all okay when user starts with home page. The issue I am facing is when I am sharing the link  for a specific internal page and when user is clicking the link it takes them to login page and then to home page after successful login. I would like the user to see the requested authenticated internal page after successful login. 
Can anyone please suggest how can I accomplish this ?

{
      "route": "/internal/*",
      "allowedRoles": ["authenticated"]
    }

**Comment by mkarmark** [comment]
With the behavior you are detailing, you probably have a response override that looks something like this:
```json
"responseOverrides": {
    "401": {
      "redirect": "/.auth/login/aad",
      "statusCode": 302
    }
  }
```

In order to alter that to end the login flow at the origin path, adjust the redirect path to include the post_login_redirect_uri query string parameter with value .referrer

```json
"responseOverrides": {
    "401": {
      "redirect": "/.auth/login/aad?post_login_redirect_uri=.referrer",
      "statusCode": 302
    }
  }
```

**Comment by shobhitkasliwal-onbe** [comment]
Thank you @mkarmark  !! 
This is working as expected now.
