### ISSUE TITLE
all environments down

### ISSUE THREAD

**Issue by nerblock** [Azure/static-web-apps#740]
I'm getting this error message when trying to access my staging environment:

> HTTP Error 500.30 - ANCM In-Process Start Failure
> Common solutions to this issue:
> The application failed to start
> The application started but then stopped
> The application started but threw an exception during startup
> Troubleshooting steps:
> Check the system event log for error messages
> Enable logging the application process' stdout messages
> Attach a debugger to the application process and inspect
> For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028265

**Comment by nerblock** [comment]
So the situation is getting worse, the production environment went down too. Anyone else experiencing this problem?

**Comment by michaeltoft** [comment]
Yep, we're down aswell. Anyone know of a good service status page? Getting a little annoyed with azure in general lately.

**Comment by niels-ws** [comment]
We are facing the same problem.

**Comment by fudoki22** [comment]
Also seeing this in prod.

**Comment by AlexSapple** [comment]
Hi all - same for us, down on all environments. Not sure when this started, but only noticed in the last half hour or so.

**Comment by tobiaskohlbau** [comment]
We're affected as well, I've tried to open a support ticket to get more information. We noticed around 8 AM CET.

**Comment by ArrigeAnders** [comment]
All of our environments also went down. We noticed this half an hour ago.

**Comment by asmailov** [comment]
We have the same issue. We noticed our website down at: `2022-02-24T09:45:00.000Z`

**Comment by nerblock** [comment]
In the meantime here is something to read: https://azure.microsoft.com/en-us/support/legal/sla/app-service-static/v1_0/

**Comment by ArrigeAnders** [comment]
Our apps are still accessible from South Korea it seems. Maybe this is specifically a problem in Europe?

**Comment by Peter-Juhasz** [comment]
Same here

**Comment by Jarod1662** [comment]
I'm experiencing the same issue - Azure seems to be having a lot of issues recently....

**Comment by kush-acacium** [comment]
Down :(

**Comment by AlexSapple** [comment]
there is acknowledgement from MS here (at the top of the page) -> https://status.azure.com/en-us/status

**Comment by xwellingtonx** [comment]
Sam here, all non-production environment down. I have never been happier than now for letting PROD in AppService due to the SWA being way more expensive in terms of BandWidth.

**Comment by AlexSapple** [comment]
I've got services back in the last few minutes.

**Comment by kush-acacium** [comment]
Great! thanks for the notification @AlexSapple, looks like ours are back too.

**Comment by nerblock** [comment]
frontend is ok, but api still throws internal server error 500 on all envs

**Comment by niels-ws** [comment]
> frontend is ok, but api still throws internal server error 500 on all envs

same here :(

**Comment by ArrigeAnders** [comment]
> frontend is ok, but api still throws internal server error 500 on all envs

Same here.

**Comment by nerblock** [comment]
the api is back online 👍

**Comment by nerblock** [comment]
Unfortunately I spoke too early. We are back to HTTP Error 500.30 - ANCM In-Process Start Failure.

**Comment by Jarod1662** [comment]
> Unfortunately I spoke too soon. We are back to HTTP Error 500.30 - ANCM In-Process Start Failure.

They have mentioned that the issue has been mitigated but I'm still seeing issues.

**Comment by nerblock** [comment]
Status page now shows "This incident is now mitigated.", but all of my sites are still down. ¯\_(ツ)_/¯

**Comment by javier-romera** [comment]
The are down again.

**Comment by nerblock** [comment]
Maybe @mkarmark can help with this?

**Comment by Peter-Juhasz** [comment]
Our sites are still down as well.

**Comment by mkarmark** [comment]
Hi, sorry for the inconvenience called by this issue. This issue has been mitigated for a few hours now, and your sites should be back up. Let me know if you still experience an outage on your site.

**Comment by stilbu** [comment]
@mkarmark Unfortunately our production site is down again as of just now, 500.30 - ANCM In-Process Start Failure

**Comment by miwebst** [comment]
Hey @stilbu, we have been applying temporary mitigations while we rollout a permanent fix for the issue. At this point, we've rolled out the permanent fix to the primary nodes that were affected in Europe. You should see mitigation and we will continue to monitor the situation in case any site begins to hit the 500.30's again.

One additional option you have is to temporarily enable enterprise-grade edge which will shift your app off of the affected nodes and onto a distinct set of nodes managed by Azure Front Door. This shouldn't be necessary given the fix is rolling out but is a potential action for anyone that wants extra certainty.

Sorry again for the inconvenience. Appreciate your patience.

**Comment by nerblock** [comment]
Problem is resolved so I'm closing the issue.

**Comment by Peter-Juhasz** [comment]
Sites are down again! Timeouts, invalid certs, "Our service are not available right now."

**Comment by miwebst** [comment]
@Peter-Juhasz, please create a new issue for this. This thread was related to an outage with a known cause. Please provide details in a separate thread.
