### ISSUE TITLE
Next.js server side rendering - possible with SWA?

### ISSUE THREAD

**Issue by dfberry** [Azure/static-web-apps#749]
If I'm bringing my Next.js apps (a catalog of various apps) to Azure and they make use of server-side rendering, is it possilbe to use SWA/Functions somehow or do I need to move them to App Service?

**Comment by TomJD** [comment]
I have a similar question as we are rewriting some legacy stuff into NextJS with SSR. 
Is there an OOB way to deploy onto Azure as AWS has, or is this part of the wait? Can't find clear documentation on the deployment part.

**Comment by superhp** [comment]
> Hi @dfberry! As of today, Static Web Apps only supports [static rendering of Next.js Apps](https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs). However, the team is currently working on supporting Server-side rendering in Static Web Apps and you should be seeing a public preview of the same in the coming couple of months!🎉 CC// @simonaco @pvbchak

Do you have any updates on the progress? This feature sounds really good and we would like to test it as soon as the preview is available :)

**Comment by nerblock** [comment]
I agree, it would be nice to have an update on this.

**Comment by lawrenceong001** [comment]
hi @Reshmi-Sriram -- you mentioned support Azure Static Web Apps -- would this include other static generators such as Gatsby?

**Comment by superhp** [comment]
@Reshmi-Sriram could you give us some updates on what is the status of Next.js SSR support and when it should be available at least as a public preview?

**Comment by doorman02** [comment]
Hi, @Reshmi-Sriram is there any approximate timeframe when the public preview will be available? I am considering if I should wait or use Azure Web Apps. Since SSR is very common when using nextjs I guess this is a highly wanted feature. Thanks!

**Comment by Reshmi-Sriram** [comment]
Hi All,
We're expecting the public preview to be out by October. There have been a couple of blockers and hence a slight delay in the planned release. Apologies for the wait, stay tuned for more updates!
cc// @sulabh-msft

**Comment by alexkyse1** [comment]
Hello @Reshmi-Sriram !

Any development updates related to SSR? How is it going?

**Comment by ShanonJackson** [comment]
https://github.com/ShanonJackson/nextjs-azure

If you're looking for SSR please It would be good to have some people try out the library so I can start to get a feel for what's still outstanding.

Very close to production ready, and the initial results are that it's around 30-50% faster than Vercel.

This library can be plug-and-played with static-web-apps but I'd recommend using the infrastructure setup within the project.

Very happy to support anyone in any way on hosting NextJS setups on Azure just reach out to me, happy to walk someone through "do it youself", "do it on static web apps" or do it with "nextjs-azure".

**Comment by thomasgauvin** [comment]
Work in progress! We're just as excited to see NextJS SSR on SWA!

**Comment by schemburkar** [comment]
@thomasgauvin I received an email from Azure (App Service recommendation) stating "Post mid-September, Azure Static Web Apps will support Server-Side Rendering (SSR) for Next.js applications." 

![image](https://user-images.githubusercontent.com/3159347/189851518-e928bea3-c144-42be-afce-564b6dbe8313.png)

Does that mean that we no longer need to `export` our Next.js app and it will also support SSG? Is there any way to try the new behavior in preview ?

**Comment by Reshmi-Sriram** [comment]
> Does that mean that we no longer need to `export` our Next.js app and it will also support SSG? Is there any way to try the new behavior in preview ?

@schemburkar  - in case you prefer to use the statically exported Next.js files, you will still have the option to do so using the `is_static_export` flag in your existing app. In case you would like to use SSR/ ISR/ SSG, you can do so using the new feature change. 
Let me know if this helps!

**Comment by berik** [comment]
@Reshmi-Sriram, how can we try a new behaviour SSR/ISR/SSG? Is [ISR on demand](https://github.com/leerob/on-demand-isr)?

**Comment by schemburkar** [comment]
> In case you would like to use SSR/ ISR/ SSG, you can do so using the new feature change.

Thanks @Reshmi-Sriram  I'm aware of the `is_static_export`. How do i enable the SSG for my existing app. I tried publishing without the `export` option but the deploy fails, so need to know any setting or feature flag that needs to be enabled ?

**Comment by erwinsmit** [comment]
@schemburkar Will azure static web apps also support pages/api routes? 

With a custom nextjs server, these are not working, currently, I work around that issue by creating azure functions for the API routes.

**Comment by ShanonJackson** [comment]
@erwinsmit 
https://github.com/ShanonJackson/nextjs-azure

This will give. you ```npx nextjs-azure``` which will transform .next folder into a 3 folders one of which is "api" which should be an azure function compatible folder with your entire pages/api folder built in the most optimized way.

Basically just wraps your nextjs output in an azure function compatibility layer.

**Comment by Reshmi-Sriram** [comment]
**Update**! You should now be able to try out Next.js SSR public preview support in Static Web Apps! 
Check out [this](https://github.com/Azure/static-web-apps/discussions/921) discussion to learn more :)

**Comment by Reshmi-Sriram** [comment]
Closing this issue.
