### ISSUE TITLE
Can I have outbound IP addresses of a static web app instance?

### ISSUE THREAD

**Issue by justinyoo** [Azure/static-web-apps#75]
This is an extended question from #59.

So, basically I can't restrict the proxy API access from public, as @miwebst mentioned in the previous issue thread.

But I still want to prevent access from public, by implementing the access restriction feature on API Management or Azure App Service instance like:

* [Azure App Service access restrictions](https://docs.microsoft.com/azure/app-service/app-service-ip-restrictions?WT.mc_id=devkimchicom-github-juyoo)
* [API Management access restriction policies](https://docs.microsoft.com/azure/api-management/api-management-access-restriction-policies?WT.mc_id=devkimchicom-github-juyoo)

However, I need to know the IP addresses to apply this access policy. As I don't know how to get a list of outbound IP addresses for ASWA, I wonder if this is possible or not?

**Comment by miwebst** [comment]
Its not possible right now, we are continuously adding more points of presence so we don't want people taking dependencies on these and then having their apps break when we begin using a new IP address.

**Comment by justinyoo** [comment]
Thanks for confirmation!

**Comment by cspadmin** [comment]
my third party is seeing external ip what is not listed in my web app outbound IP?  per checking the ip that they are seeing, its part of the mcirosoft data center public ip. but why they are seeing that but its not listed in the portal?

**Comment by cspadmin** [comment]
> Its not possible right now, we are continuously adding more points of presence so we don't want people taking dependencies on these and then having their apps break when we begin using a new IP address.

my third party is seeing external ip what is not listed in my web app outbound IP? per checking the ip that they are seeing, its part of the mcirosoft data center public ip. but why they are seeing that but its not listed in the portal?

**Comment by miwebst** [comment]
As described above, we do not have any external IP guarantee's right now. Can you describe the use case? I'm assuming they want to add some rules based on ip address?

**Comment by cspadmin** [comment]
> As described above, we do not have any external IP guarantee's right now. Can you describe the use case? I'm assuming they want to add some rules based on ip address?

Thanks for your reply. are u saying that outbound IP cannot be whitelisted by our third party provider?  The issue here. .. is our third party provider is seeing an external IP of our web app that is not listed in Outbound IP in Azure....

**Comment by cspadmin** [comment]
so i  guess , as long as the IP advertised belongs to Microsoft. you can whitelist it.

**Comment by miwebst** [comment]
I see. Yes these IP addresses will always be owned by Microsoft. We are not currently publishing a set of these as they may expand overtime.

**Comment by sijucm** [comment]
I would also like to get the possible outboundIps of an Azure Static Web app. My use case is so that I can add that to the firewall of my CosmosDB. Now I have to open it up for every network and I'm not very comfortable doing that. 
Due to these kind of restrictions (not able to do oauth flows as another example) makes me wonder why will I use the static web app for long instead of separating into a storage account based SPA and Azure functions. I did really like the Azure static web app easiness of managing everything together, but then microsoft should not restrict it so much that is becomes unusable after the initial fast deployment.

**Comment by anthonychu** [comment]
@sijucm We are looking into ways to give you more control over the function app. We’ll keep this scenario in mind and see if we can address it in the process.

**Comment by chenxizhang** [comment]
@anthonychu  Do you have any update on this feature? I also want to know the ip list of the function app, because some external system require the information to whitelist them.

**Comment by mickey-stringer** [comment]
@anthonychu Is there an update on this, or is it being planned/tracked elsewhere?

**Comment by zzulueta** [comment]
> Hey folks! To restrict your backends to Static Web Apps, you should use backend integration https://learn.microsoft.com/en-us/azure/static-web-apps/apis-overview. This will ensure that only the proxied API calls via Static Web Apps will have access to your backends. This will be configured differently depending on your backend type, but you will be able to notice that some type of authentication is added to prevent public access to backends automatically

- I wish this was true. My issue here is that any developer can look at the html code and look for the link that calls the backend. From there, he/she would just run it via Postman and see whatever information is there

**Comment by PeerQu** [comment]
I would also like to know how to obtain a static IP for the azure static web app. 

My client ui are getting a bloburl and are prepending the sastoken <BlobUrl><SasToken> these information can be read in the headers. Therefore I need to whitelist by IP

Do you have a alternative solution for this if its not possible to obtain a static IP for the Azure static webapp
Best regards

**Comment by amaniel15** [comment]
This is an old post but for anyone still curious, you can get all the outbound IP addresess by following https://learn.microsoft.com/en-us/azure/app-service/overview-inbound-outbound-ips#find-outbound-ips. Once you run the command, you'll get an output similar to this: 

possibleOutboundIpAddresses": IP address 1, IP address 2 and etc

**Comment by zdanovich89** [comment]
> This is an old post but for anyone still curious, you can get all the outbound IP addresess by following https://learn.microsoft.com/en-us/azure/app-service/overview-inbound-outbound-ips#find-outbound-ips. Once you run the command, you'll get an output similar to this:
> 
> possibleOutboundIpAddresses": IP address 1, IP address 2 and etc

Static web application doesn't have this option, just web application and function application
