### ISSUE TITLE
BYO Function - Authorized Requests X-MS-CLIENT-PRINCIPAL Header is missing

### ISSUE THREAD

**Issue by StiviiK** [Azure/static-web-apps#751]
Hi, we are experiencing the Issue that for authorised requests the `X-MS-CLIENT-PRINCIPAL` header is missing on the API side. We have deployed a Azure Static Web App and a linked BYO Azure Function.

The `x-ms-client-principal` header is never available (when the request arrives at the api) if we call the API through our static web app `SWAURL.azurestaticapps.net/api/...`.    

For the authorisation we configured Azure Active Directory Version 2 (https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#azure-active-directory-version-2). The User is authenticated and the auth cookie will be correctly send to the SWA as we can see in the request inspector from the browser.
![image](https://user-images.githubusercontent.com/8115642/157075815-32eca267-fca5-4e75-944a-50a62e5bd5d3.png)

Are we missing something in our static web app configuration?
```json
{
  "auth": {
    "rolesSource": "/api/v1/StaticWebAppConfiguration/roles",
    "identityProviders": {
      "azureActiveDirectory": {
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/***/v2.0",
          "clientIdSettingName": "AZURE_CLIENT_ID",
          "clientSecretSettingName": "AZURE_CLIENT_SECRET"
        }
      }
    }
  },
  "navigationFallback": {
    "rewrite": "/index.html"
  },
  "routes": [
    {
      "route": "/api*",
      "allowedRoles": ["authenticated"]
    },
    {
      "route": "/logout",
      "redirect": "/.auth/logout"
    }
  ],
  "responseOverrides": {
    "401": {
      "statusCode": 302,
      "redirect": "/.auth/login/aad"
    }
  }
}
```

The following (custom/special, apart of the normal) headers are passed to our api:
`disguised-host,x-ms-auth-token,x-ms-request-id,x-ms-original-url,x-forwarded-tlsversion,x-appservice-proto,x-forwarded-proto,x-arr-ssl,x-forwarded-for,x-original-url,was-default-hostname,x-site-deployment-id,x-arr-log-id,x-waws-unencoded-url,Cookie=StaticWebAppsAuthCookie=,Cookie=AppServiceAuthSession=,Cookie=AppServiceAuthSession1=,Cookie=Nonce=`

**Comment by StiviiK** [comment]
I have found a workaround, the client principal is contained within the claims of the token from `x-ms-auth-token` header.

**Comment by mkarmark** [comment]
Hi, do you mind sharing your app details so that we can investigate what is going on? If you don't feel comfortable sharing the details with us here, feel free to open a support case and we can help there.

**Comment by StiviiK** [comment]
Closed, no longer relevant for me.
