### ISSUE TITLE
Blazor WASM App + Azure Static Website + CosmosDB binding + Github Actions = 'cosmosDB' with missing or invalid direction

### ISSUE THREAD

**Issue by PoisnFang** [Azure/static-web-apps#764]
### Bug Report
I used the Github action file that Azure auto generates with. I am using `"Microsoft.NET.Sdk.Functions" Version="4.1.0"`
My code:
```csharp
        [FunctionName("ProductsGet")]
        public static IActionResult GetAllProducts(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "products")] HttpRequest req,
    [CosmosDB(
        databaseName: "productsdb",
        collectionName: "products",
        ConnectionStringSetting = "CosmosDBConnection")]
        IEnumerable<Product> products,
    ILogger log)
        {
            log.LogInformation("Getting products");
            return new OkObjectResult(products);
        }
```
It run fines locally, but when it gets to the Build and Deploy stage of the Github action it throws this error:
> ---End of Oryx build logs---
Function Runtime Information. OS: windows, Functions Runtime: ~4, dotnet version: 6.0
Finished building function app with Oryx
Error in processing api build artifacts: the file 'ProductsGet/function.json' specifies a binding of type 'cosmosDB' with missing or invalid direction ''. Visit https://github.com/Azure/azure-functions-host/wiki/function.json for more information.
For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

The project is like [this one](https://docs.microsoft.com/en-us/learn/modules/publish-app-service-static-web-app-api-dotnet/1-introduction), except I tried to integrate CosmosDB

**Comment by rickvdbosch** [comment]
I'm running into a similar issue using the new beta package `Microsoft.Azure.WebJobs.Extensions.Tables` which generates this message for a table binding to a `TableClient`. 

The code below (simplified) works fine locally, but errors out after building on Oryx.

```csharp
[FunctionName("FUNCTION-NAME")]
public IActionResult Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequest req,
    [Table("ENTITIES")] TableClient tableClient, ILogger log)
{
    return new OkObjectResult(tableClient.Query<ENTITY>().ToList());
}

```

The actual message:
>Error in processing api build artifacts: the file 'FUNCTION-NAME/function.json' specifies a binding of type 'table' with missing or invalid direction ''. Visit https://github.com/Azure/azure-functions-host/wiki/function.json for more information.

**Comment by uxsoft** [comment]
I have the same issue with importing SignalR
```
Function Runtime Information. OS: windows, Functions Runtime: ~4, dotnet version: 6.0
Finished building function app with Oryx
Error in processing api build artifacts: the file 'Negotiate/function.json' specifies a binding of type 'signalRConnectionInfo' with missing or invalid direction ''. Visit https://github.com/Azure/azure-functions-host/wiki/function.json for more information.
```
[Repository](https://github.com/uxsoft/swa-test/runs/5807868761?check_suite_focus=true)

**Comment by sig9** [comment]
I am running into the same issue with CosmosDB after updating my .csproj to Target Framework net6.0 and Azure Functions Version v4. The Oryx build fails in a PR github action. 
These are all the csproj changes I made. 
![image](https://user-images.githubusercontent.com/2271605/164253641-073846e8-d8a3-4f1a-91e7-f8b240403af4.png)

The Error I see is:
![image](https://user-images.githubusercontent.com/2271605/164253909-43b25559-74b3-413c-846b-83b87493ba9a.png)

I don't understand why function.json is mentioned. These should be inproc.

**Comment by anthonychu** [comment]
I think this might be an issue introduced by `Microsoft.NET.Sdk.Functions` 4.1.0. Can you try using 4.0.1 to see if the issue persists?

**Comment by rickvdbosch** [comment]
Thank you @anthonychu, that does the trick!
Downgraded the mentioned package `Microsoft.NET.Sdk.Functions` from version 4.1.0 to 4.0.1 and the build error on my GitHub actions workflow disappeared.

**Comment by tkamesh** [comment]
Issue is fixed and rolled out. Please let us know, if you still run into the same issue.
