### ISSUE TITLE
Azure Functions with AuthorizationLevel.Function return 401 errors

### ISSUE THREAD

**Issue by StacyCash** [Azure/static-web-apps#766]
Since today all of my Static Web Apps across multiple subscriptions and active directories have started to return 401 errors when the API was requested.

After changing the AuthorizationLevel for the functions from AuthorizationLevel.Function to AuthorizationLevel.Anonymous they started to work again.

An example repo with two functions (one working, one not) can be found [here](https://github.com/StacyCash/function-401-reproduction)

A working API (using AuthorizationLevel.Anonymous)
https://thankful-island-0d9de2403.1.azurestaticapps.net/api/workingfunction
A not working API (using AuthorizationLevel.Function)
https://thankful-island-0d9de2403.1.azurestaticapps.net/api/notworkingfunction

Until yesterday both of these options worked.

**Comment by miwebst** [comment]
Both of these are working for me? Can you share what you are seeing?

**Comment by StacyCash** [comment]
Yesterday I was getting a 200 response with the working function (returning: "Function: WorkingFunction"), and 401 response from the NotWorking function on all machines I tested with.

This morning both work... I've closed the issue, but will keep the repo in case it reoccurs

**Comment by TroyWitthoeft** [comment]
Just saw this on multiple SWAs in our environment. 
All APIs were running fine with function-level auth set.  At midnight EST all apis started returning 401 unauthorized.  Had to convert to anonymous to fix.

**Comment by JackBeaudry** [comment]
> Just saw this on multiple SWAs in our environment. All APIs were running fine with function-level auth set. At midnight EST all apis started returning 401 unauthorized. Had to convert to anonymous to fix.

I'm seeing the same. Two weeks ago two of my production apps in one subscription stopped working. The client would get a 401 when calling the Azure function API. Nothing had changed in the code!  Another app in another subscription worked fine. Now that app has the same problem. 

Changing the Azure function authlevel to anonymous is a workaround to get it to work, but relatively unsecure and a poor solution. 

What changed?
