### ISSUE TITLE
Newbie Trouble with Development Environment after integrating a test function

### ISSUE THREAD

**Issue by PhilLepanto** [Azure/static-web-apps#77]
I'm sorry if this is not the right place for this type of issue. I'm relatively new to GitHub and React/SPA development. I've been trying to follow along in the Quick Starts to set up a React Site and then add in functions.  I'm using VS Code for Windows. The site seems to be up and running on Azure, but when I tried to run >yarn start this morning, I got this message:
`Error: [BABEL] C:\Users\yyyy\Documents\WORK\reactSandbox\xxxxx\node_modules\object-is\index.js: Could not find plugin "proposal-class-properties". Ensure there is an entry in ./available-plugins.js for it. (While processing: "C:\\Users\\yyyy\\Documents\\WORK\\reactSandbox\\xxxxx\\node_modules\\babel-preset-react-app\\dependencies.js$0")
    at Array.map (<anonymous>)
    at Generator.next (<anonymous>)
    at Generator.next (<anonymous>)`

Trying to get my function to work, I know I had to change the version of node that I was using from 13X to 12.18.1, and I know I added 
`,
    "liveServer.settings.proxy": {
        "enable": true,
        "baseUri": "/api",
        "proxyUri": "http://127.0.0.1:7071/api"
     }`

I am really not sure how to proceed to try and fix this. If anyone can point me in the right direction, or help me understand the sequencing I need to do in terms of starting the debugging locally and then running yarn start. Finally, apologies if this is the wrong type of forum for this.

**Comment by miwebst** [comment]
Hey @PhilLepanto sorry for the delay on this. So I'd encourage you to try out the VS Code extension for Static Web Apps: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestaticwebapps 

It streamlines running the functions and project side-by-side so it may simplify the local development challenges you are facing.

**Comment by anthonychu** [comment]
We're working on a Static Web Apps CLI that will have an emulator that should simplify this experience.

**Comment by miwebst** [comment]
You can find more details on the SWA cli here: https://github.com/Azure/static-web-apps-cli
