### ISSUE TITLE
Devops pipeline failed with timeout error

### ISSUE THREAD

**Issue by ashisn001** [Azure/static-web-apps#777]
**Describe the bug**

Devops pipeline just started failing today. It was working as expected before. The project consists of some xml and html files.

**To Reproduce**
1. Commit and push a change to bit bucket
2. Build pipeline will be triggered
3. See the logs for the error

**Azure Pipelines YAML File**
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: ''
      output_location: ''
    env:
      azure_static_web_apps_api_token: $(deployment_token)`

**Expected behavior**
Build should succeed without error

**Screenshots**
![image](https://user-images.githubusercontent.com/94908647/161890110-eed2bbc4-ab4b-44f3-86e1-8098b8559858.png)

**Comment by miwebst** [comment]
Same as this issue. Lets use the earlier one to track: https://github.com/Azure/static-web-apps/issues/776

**Comment by ashisn001** [comment]
@miwebst : still this issue exists, we are getting the same error as before
