### ISSUE TITLE
Show error when creating configuration settings that are blocked

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#78]
In the portal, creating a setting named `FUNCTIONS_WORKER_RUNTIME` or `AzureWebJobsStorage` are not allowed, but the configuration editor accepts the values. Things appear to be okay, but the values are actually not saved and the user is not alerted.

Related #61

**Comment by jon-a-nygaard** [comment]
Hi @anthonychu, I believe this issue can be closed. See https://github.com/Azure/static-web-apps/issues/374#issuecomment-920729015 🙂
