### ISSUE TITLE
Redirect with post_login_redirect_uri=.referrer cuts of trailing slash, breaks *every* relative link

### ISSUE THREAD

**Issue by fabge** [Azure/static-web-apps#785]
We are redirecting users to the requested page after they have successfully authenticated like so:

```bash
"responseOverrides": {
        "401": {
            "statusCode": "302",
            "redirect": "/.auth/login/aad?post_login_redirect_uri=.referrer"
        }
}
```
The URL the user is redirected to differs from the initial request URL. As an example, this is the URL the user enters:
https://docs.example.com/docs/concepts/roles-and-tasks/
And this is the URL the user is redirected to:
https://docs.example.com/docs/concepts/roles-and-tasks

Notice the missing trailing slash. The problem with the missing trailing slash is, that this breaks **every relative link** on the website.
E.g. `<a href="../definitions/">definitions</a>` points to 
https://docs.example.com/docs/definitions/
instead of 
https://docs.example.com/docs/concepts/definitions/

**Expected behavior**
We expect the `post_login_redirect_uri=.referrer` to redirect to the **exact** URL, without trimming the trailing slash.

**Comment by rapopescu16** [comment]
Hi @fabge, thank you very much for the details! 
I will add here the link to the documentation where it is mentioned how we can configure the trailing slash with Static Web Apps: https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#trailing-slash just for future references. 
Thanks a lot!
