### ISSUE TITLE
Deployments failing intermittently (timeout?)

### ISSUE THREAD

**Issue by anthonychu** [Azure/static-web-apps#79]
Sometimes my deployments will fail, but if I retry enough times, it'll work. Wonder if it's timing out...

![image](https://user-images.githubusercontent.com/3982077/85934253-5857ac00-b895-11ea-8560-5875787266a1.png)

**Comment by anganti** [comment]
we are currently experiencing intermittent issues with functions deployments in US geo. Will keep you posted when issue gets resolved.
