### ISSUE TITLE
Deploy from Azure DevOps to SWA failed on resource creation

### ISSUE THREAD

**Issue by diberry** [Azure/static-web-apps#790]
**Describe the bug**

Tried this 3 times with same repo so not an issue with the service. I can deploy through pipelines to Azure App Service. Trying to convert that project to SWA since it is just a react app. No idea if the issue is my config of the deployment, app route and where to find the files for yml or if it is a permission problem with the internal FTE AzDo.

**To Reproduce**
1. Created a new resource in azure portal
2. selected Azure DevOps, and the org/project/repo
3. selected 'create' to begin the process
4. failed with 

  ```
  {
    "code": "DeploymentFailed",
    "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
    "details": [
      {
        "code": "InternalServerError",
        "message": "There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 1870e6aa-6f65-4daa-8b42-d92b1ed0f9db"
      }
    ]
  }
  ```
5. PAT between AzDo and SWA was created - I did get that email. 

**Expected behavior**
Expect an error message that helps me resolve the issue. 

**Screenshots**

**Device info (if applicable):**
 - Win 10/Google Chrome/Azure portal

**Additional context**

Happy to share AzDo with internal FTE to resolve.

**Comment by INNVTV** [comment]
I am getting the exact same issue with my Azure DevOps repository using a Blazor WASM application.

**Comment by diberry** [comment]
The only way I deployed at resource creation time was to create a new repo with nothing in it. Create the resource successfully. Move code into new repo, then deploy again.

**Comment by rupareddy5-21** [comment]
We are working on this issue and bug fix will be rolled out soon. Sorry for the inconvenience!

**Comment by rupareddy5-21** [comment]
Hi @oZakari 
The PR for this issue has been merged and it will be released by 10th June. Thanks for your patience.

**Comment by rupareddy5-21** [comment]
Hi @oZakari,
The changes are rolled out now. Please check and let me know if things are still looking unhealthy.

**Comment by oZakari** [comment]
Thanks, will do!
