### ISSUE TITLE
GitHub Orgs not populating properly

### ISSUE THREAD

**Issue by FirstCraftyBrother** [Azure/static-web-apps#8]
When trying to use the App Service Static Web Apps through the Azure portal. It seems that after signing into GitHub the organizations that populate are not complete. I asked at Build what organizations should populate and was told that Admin access was required on the repository in order for it to create the Static Web App. This makes sense to me and I agree, but not all the repositories that I am admin or owner on are available.

When I sign in using this account, the only visible org to select in the drop down is [FirstCraftyBrother](https://github.com/FirstCraftyBrother) as in my personal repositories. I expect to be able to see the [4CraftyBrothers](https://github.com/4CraftyBrothers) org as well as I am the owner and admin to that org which has public repositories in it that I am also the owner of.

**Comment by miwebst** [comment]
It sounds like something may have gone wrong in the auth flow. Can you try removing the OAuth registration and try again? Here are the steps from removing the Azure Static Web App app registration: 

On Github, click on the user drop down in the top right. Then click settings, then applications, and finally Authorized OAuth Apps. Here you will see an Azure Static Web App registration that you can delete.

Let us know if that fixes things!

**Comment by FirstCraftyBrother** [comment]
This was the issue, thank you!
