### ISSUE TITLE
Cookie value set from API is URL Encoded twice from deployed SWA

### ISSUE THREAD

**Issue by jwarner00** [Azure/static-web-apps#800]
When setting a cookie in a C# API, cookie value is URL encoded twice from an SWA deployed to Azure, but once (as expected) when running locally. Problem observed running in Microsoft Edge. This causes a problem for reading the cookie from the API - namely that the API must conditionally URL decode the cookie value.

**To Reproduce**
1. See sample repository for code: https://github.com/jwarner00/swa-cookie-repro
2. Alternativly, create a API function that sets a cookie, and an API funciton that reads that cookie:

set function - see https://github.com/jwarner00/swa-cookie-repro/blob/main/api/CookeFunctions.cs
```
// ... 
var payload = new SamplePOCO()
{
    Name = "Bob Smith",
    Age = 32
};

var cookieText = JsonConvert.SerializeObject(payload);

req.HttpContext.Response.Cookies.Append(CookieName, cookieText, new CookieOptions()
{
    Expires = DateTime.Now.AddMinutes(60)
});
// ...
```

get function - see https://github.com/jwarner00/swa-cookie-repro/blob/main/api/CookeFunctions.cs
```
// ...
try
{
    var foundCookie = req.Cookies.TryGetValue(CookieName, out var cookieText);
    if (!foundCookie)
    {
        return new OkObjectResult($"Could not find cookie with name {CookieName}");
    }

    log.LogInformation(cookieText);
    var cookieObj = JsonConvert.DeserializeObject<SamplePOCO>(cookieText);

    return new OkObjectResult(cookieObj);
}
catch (Exception ex)
{
    log.LogError(ex, "Unhandled error in GetCookie");
    return new OkObjectResult($"Error: Unhandled exception in GetCookie: {ex.ToString()}");
}
// ...
```

4.  Run the application locally. Navigate to /api/setcookie to set the cookie. Navigate to /api/getcookie to read the cookie. You should get an OK response with the text "{"name":"Bob Smith","age":32}"
5. Deploy the application to a new Azure Static Web App. Use deployment task that follows or see https://github.com/jwarner00/swa-cookie-repro/blob/main/pipelines/deploy.yml
```
      - task: AzureStaticWebApp@0
        inputs:
          skip_app_build: true
          api_location: 'api/'
          app_location: 'src/'
          azure_static_web_apps_api_token: $(dev_deployment_token)
```
6. Once the application is deployed, navigate to the deployed application at /api/setcookie to set the cookie. Navigate to /api/getcookie. 

Expected: See "{"name":"Bob Smith","age":32}" as in local development
Actual: Exception was thrown. Sample code generates this output: 

> Error: Unhandled exception in GetCookie: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: %. Path '', line 0, position 0.
>    at Newtonsoft.Json.JsonTextReader.ParseValue()
>    at Newtonsoft.Json.JsonTextReader.Read()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Repro.Function.CookeFunctions.GetCookie(HttpRequest req, ILogger log) in /working_dir/api/CookeFunctions.cs:line 66

8. Compare cookie from running locally and in deployed code in browser dev tools. Note that if you URL decode the cookie that is set by the deployed function, you get the value of the cookie set by the local function. Deployed funciton appears to be URL Encoding the value again somewhere.

Source Repository: https://github.com/jwarner00/swa-cookie-repro

**Device info (if applicable):**
Issue tested in browsers: Microsoft Edge, Firefox

**Comment by annikel** [comment]
Hi @jwarner00, we located the problem and the issue will be fixed with the next release.
