### ISSUE TITLE
Setting AD B2C as custom OpenId Connect Provider not working.

### ISSUE THREAD

**Issue by kamgasimo-nano** [Azure/static-web-apps#818]
**Describe the bug**

Setting AD B2C as custom OpenId Connect Provider not working.

**To Reproduce**
1. Create a Static Web App
2. Create a B2C Tenant
3. Use B2C as custom provider with the following config.
4. Navigate to /.auth/login/b2c
5. Get a 404

**Expected behavior**
Redirect to btc login form.

**Screenshots**
![Screen Shot 2022-05-29 at 14 37 50](https://user-images.githubusercontent.com/96853909/170871774-0a8fe7d6-be48-4178-923a-bd852f7f80e1.png)

**Device info (if applicable):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 102.0.5005.61

**Config**
```json
{
  "routes": [
      {
          "route": "/.auth/login/aad",
          "statusCode": 404
      },
      {
          "route": "/.auth/login/apple",
          "statusCode": 404
      },
      {
          "route": "/.auth/login/facebook",
          "statusCode": 404
      },
      {
          "route": "/.auth/login/github",
          "statusCode": 404
      },
      {
          "route": "/.auth/login/google",
          "statusCode": 404
      },
      {
          "route": "/.auth/login/twitter",
          "statusCode": 404
      }
  ],
  "auth": {
      "identityProviders": {
          "customOpenIdConnectProviders": {
              "b2c": {
                  "registration": {
                      "clientIdSettingName": "B2C_CLIENT_ID",
                      "clientCredential": {
                          "clientSecretSettingName": "B2C_CLIENT_SECRET"
                      },
                      "openIdConnectConfiguration": {
                          "wellKnownOpenIdConfiguration": "https://nanolaval.b2clogin.com/nanolaval.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_LOGIN"
                      }
                  },
                  "login": {
                      "nameClaimType": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
                      "scopes": [
                        "openid"
                       ],
                      "loginParameterNames": []
                  }
              }
          }
      }
  }
}

**Comment by Reshmi-Sriram** [comment]
Hi @kamgasimo-nano,
We'll investigate on this issue, but meanwhile could you please confirm a couple of things?

- Did you check our [official documentation](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=openid-connect) explaining how to configure Custom Auth in SWA?
- Are you using a Standard SKU?

They are just to narrow down on the error. Thanks!

**Comment by kamgasimo-nano** [comment]
HI @Reshmi-Sriram Thanks for reply. I have followed the official documentation.
I'm using a Free SKU.

**Comment by kamgasimo-nano** [comment]
I have upgraded to Standard SKU but still not working.
