### ISSUE TITLE
StaticWebApp Deployment Error: Could not find the .NET Core project file.

### ISSUE THREAD

**Issue by pallabiroutfnf** [Azure/static-web-apps#820]
I am using AzureStaticWebApp@0 task and trying to deploy to a React app with Node Js. 
Required package.json and staticwebapp.config.json file is already present there in source code. 

But the task is recognizing the source code as .Net Core and trying to find the project file it seems, which is giving below error.

Detecting platforms...
Error: Could not find the .NET Core project file.

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
##[error]Error: The process '/usr/bin/bash' failed with exit code 1

**Comment by tkamesh** [comment]
It's cross post from https://github.com/microsoft/Oryx/issues/1404 
closing the issue as it already resolved in the other post.
