### ISSUE TITLE
Azure/static-web-apps-deploy@v1: Fails to build Node builds with Node 18.2

### ISSUE THREAD

**Issue by Strepto** [Azure/static-web-apps#830]
**Describe the bug**

Since yesterday Oryx seems to pick a version of node it cannot install.

```
DeploymentId: 89e1ec1c-a952-415a-8c5b-2db444660483
App Directory Location: '/' was found.
No Api directory specified. Azure Functions will not be created.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues
Oryx Version: 0.2.20220401.1, Commit: afed4f696a08bfd4c8e4109704a082bf9fb20515, ReleaseTagName: 20220401.1
Build Operation ID: |BElYoJjZkpw=.8737adea_
Repository Commit : f8d3ac9af01579577d671feb627f19e0ac0c5f72
Detecting platforms...
Detected following platforms:
  nodejs: 18.2.0
Version '18.2.0' of platform 'nodejs' is not installed. Generating script to install it...
Detected the following frameworks: Typescript
Source directory     : /github/workspace
Destination directory: /bin/staticsites/ss-oryx/app
Downloading and extracting 'nodejs' version '18.2.0' to '/opt/nodejs/18.2.0'...
Downloaded in 1 sec(s).
Verifying checksum...
Extracting contents...
performing sha512 checksum for: nodejs...
Done in 2 sec(s).
Removing existing manifest file
Creating directory for command manifest file if it does not exist
Creating a manifest file...
Node Build Command Manifest file created.
Using Node version:
node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by node)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
---End of Oryx build logs---
Oryx has failed to build the solution.
```

**Expected behavior**

Not fail build

**Comment by akarray** [comment]
I get the same error. It's no more possible de build and deploy for us.

**Comment by qianz2** [comment]
Hi @[Strepto](https://github.com/Strepto), we've removed node 18 SDKs from the prod storage account and the builds would not be automatically selecting node 18 from now on. Please try it again, thanks!

**Comment by Strepto** [comment]
This seems to work fine now. Closing.

**Comment by oldmanfleming** [comment]
@qianz2 is there a timeline for supporting node 18? Its already current and is going to be LTS in 3 days: https://github.com/nodejs/Release

**Comment by ardyaryan** [comment]
> You can hack it to work by limiting the node version in pakage.json if you are able to use older node versions
> 
> ```json
> package.json
> ...
>  "engines": {
>      "node": ">=16.0.0 <18"
>  },
> ...
> ```

thank you!

**Comment by graybushlabs** [comment]
I was getting a similar error with an Angular projects deploying to Azure static web app. The work around worked for me too but I had to specify a different range.
```
"engines": {
    "node": ">18"
  }
```

**Comment by lwurzbacher** [comment]
When deploying via Azure DevOps using the AzureStaticWebApp@0 task it always defaults to node 16.x. I tried changing package.json to contain engines node 18 - same issue (as if it was not honoring that change); I'm guessing this is a feature that works on github actions. 

Kudos to this post that led me down the path to getting the app to build & deploy using node 20. 

Ideally, there should be an option on the AzureStaticWebApp for nodeVersion: XX

https://github.com/microsoft/Oryx/issues/2369#issuecomment-1984892230

**Comment by nivnoimanharmonie** [comment]
Amazing, Thanks :)
