### ISSUE TITLE
Route matching appears to ignore methods

### ISSUE THREAD

**Issue by pschaeflein** [Azure/static-web-apps#831]
**Describe the bug**

I am attempting to use routes and files to simulate API calls.

The [documentation for application configuration](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration) contains the following rule for Routes:

>  Rule evaluation stops at the first match. A match occurs when the route property and a value in the methods array (if specified) match the request. Each request can match at most one rule.

 When I have the same route with different methods configured, the second one is never considered, resulting in a 405 Method not allowed response

**To Reproduce**

Configuration:

```json
{
  "routes": [
    {
      "route": "/items",
      "methods": [ "GET" ],
      "rewrite": "/getItems.json"
    },
    {
      "route": "/items",
      "methods": [ "POST" ],
      "rewrite": "/newItem.json",
      "headers": {
        "Location": "/items/f2906fe1-f647-4ce0-81fd-1de4884c4cca"
      }
    }
]
```

Calls to `GET /items` work.
```
GET https://<snip>.azurestaticapps.net/items HTTP/1.1

HTTP/1.1 200 OK
```

Calls to `POST /items` do not work
```
POST https://<snip>.azurestaticapps.net/items HTTP/1.1

HTTP/1.1 405 Method Not Allowed
```

**Expected behavior**

The POST call should return the contents at the configured rewrite location with the configured headers.

**Comment by lwpinion** [comment]
Hi, was this ever updated on the docs? We have been trying to make POST calls to an endpoint on our Nuxt app and could not figure out why it wasn't working until now.

Based on [this article](https://learn.microsoft.com/en-us/azure/static-web-apps/apis-overview), it sounds like `/api` is the only place that POST calls can be made. If this is true, then your documentation on Nuxt _sorely_ needs to be updated accordingly. Likewise, if we want to host a Nuxt app on Azure that has the ability to accept POST requests outside of `/api` what other options do we have? Just a node.js app service?

Thank you for your time!
