### ISSUE TITLE
Is it possible to set Container Apps as API with ARM/Bicep?

### ISSUE THREAD

**Issue by MarcelWouters** [Azure/static-web-apps#835]
I deploy a Static Web App with Bicep. It's working fine except how to set a Container App as API endpoint with Bicep/ARM?

I can do this with the Azure Portal.

**Comment by annikel** [comment]
Hi @MarcelWouters, here is an example [ARM template](https://github.com/annikel/arm-examples/blob/main/linked-backends) for adding an API to a static web app. It works very similar to attaching a user provided function only that the naming is slightly different and the API's region will only need to be specified if the app is a Web or Function App

**Comment by thomasgauvin** [comment]
@MarcelWouters @annikel Can we close this issue as resolved? To add on to @annikel's reference, here is the Bicep/ARM guidance from MS Docs for SWA https://docs.microsoft.com/en-us/azure/templates/microsoft.web/staticsites/linkedbackends?pivots=deployment-language-bicep

**Comment by MarcelWouters** [comment]
@thomasgauvin Yes can be closed
