### ISSUE TITLE
Standard Plan custom AAD login showing 404

### ISSUE THREAD

**Issue by cylin2000** [Azure/static-web-apps#836]
**Describe the bug**

Hi Team,

I followed below document
https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#azure-active-directory-version-1 and enabled AAD login, however the login page showing 404 not found error. 

**To Reproduce**
1. Fork static web app from https://github.com/cylin2000/vanilla-basic
2. Create a Static Web App with standard plan and use this vanilla-basic repository
3. Navigate to login page, e.g. https://ashy-cliff-0b3d94f10.1.azurestaticapps.net/.auth/login/aad 
4. See error 404

Note: If I removed the "auth" section from staticwebapp.config.json, or just remove this file, it will work. 
Or if I change the Plan to Free Plan, it will work also. 

**Expected behavior**
I should see the login page and redirect to AAD login, please help check, thanks a lot.

**Screenshots**
![image](https://user-images.githubusercontent.com/2646632/176356508-f7759616-7a0f-41d5-bff8-2b18056e6353.png)

**Device info (if applicable):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [102.0.5005.115 (Official Build) (64-bit)]

**Additional context**

**Comment by mishapos** [comment]
Hi @cylin2000 the docs you listed are for custom authentication which is only available on the Standard plan. It's for when you want to create your own AAD App Registration or some other custom authentication provider. 

If using the built-in Static Web Apps Azure Active Directory is sufficient for you, then you don't need to configure anything. Simply route your users to `/.auth/login/aad` and they will be taken to the login page and remove the `auth` portion from your `staticwebapp.config.json` file

If you do want to create your own Azure Active Directory App Registration, you have to also make sure to add the associated App Settings for ClientID and Client Secret, as described here: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#configure-a-custom-identity-provider

**Comment by cylin2000** [comment]
Hi @mishapos , thank you for the review. I have followed the document you mentioned  https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#configure-a-custom-identity-provider , and I configured AAD Settings for ClientID and Client Secret, you could refer my configuration at https://github.com/cylin2000/vanilla-basic/blob/main/src/staticwebapp.config.json , when I deployed the code, it's showing 404 error. I checked the configuration, it's correct.

**Comment by mishapos** [comment]
Hi @cylin2000 our logs currently show that we are unable to find your App Setting `AAD_CLIENT_SECRET`. Could you please check in portal if you see this setting (and its associated value)? 

And be sure to hit the save button at the top. 😃 Thanks!

https://docs.microsoft.com/en-us/azure/static-web-apps/application-settings#configure-application-settings

**Comment by cylin2000** [comment]
Hi @mishapos , My bad, I used  AAD_CLIENT_SECRET in code, but configured AZURE_CLIENT_SECRET in portal, thank you very much for the help, I have no more questions, kindly close the issue, thanks.
