### ISSUE TITLE
Unable to configure API link to Web App for Container (Linux) from Azure Portal

### ISSUE THREAD

**Issue by shibayan** [Azure/static-web-apps#838]
**Describe the bug**

API link configuration to Docker Container based App Service (Web App) cannot be performed from Azure Portal.

Container-based Web App did not appear in the drop-down of the API link dialog as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/1356444/176634072-709d0bf8-da67-47f4-a24e-c0e7eaea5075.png)

There are actually two additional Web Apps in this subscription, both of which are container-based.

![image](https://user-images.githubusercontent.com/1356444/176634093-ab4b2630-7066-4526-a89a-4910ad8fb611.png)

**Expected behavior**

Web App for Container (Linux) enabled as API link from Azure Portal.

**Comment by mishapos** [comment]
Hi @shibayan , thank you so much for using Static Web Apps! This is indeed a bug, and we are working on a fix right away. Unfortunately, there currently isn't a workaround for using Docker Web Apps (other Web Apps should work just fine), but I will update this thread once the fix is deployed.

**Comment by thomasgauvin** [comment]
Closing this issue as this has been fixed! 🎉

Please reopen if needed
