### ISSUE TITLE
Cannot link a BYOF Azure Web App that is a container as a SWA API

### ISSUE THREAD

**Issue by axc450** [Azure/static-web-apps#843]
**Describe the bug**

I have an API that runs in a docker image as part of Azure Web App. I cannot link this as an API for a SWA however I can link normal Azure Web Apps.

**To Reproduce**
1. Create an Azure Web app that is a container
2. Create an Azure SWA (standard tier)
3. Attempt to link the Web App to the SWA as part of a SWA BYOF API. It does not show in the list of apps to choose from (Web App)

**Expected behavior**
The web app should show up in the list. I assume there is a dodgy filter somewhere and not showing all valid app services **OR** container web apps are not valid targets (and this is not a bug)... in which case there should be some documentation around this.

**Comment by mkarmark** [comment]
Hi @axc450, thanks for bringing this to our attention. We are determining the scale of the bug and will keep this issue posted on when we can deploy the fix. For now, would using Container Apps as your backend type work for you?

**Comment by axc450** [comment]
Hey @mkarmark !

I think this may be a duplicate of #838 so I may be better to track it there.
I cant really move my API container to container apps at the moment, it has to live in an app service for containers :)

**Comment by thomasgauvin** [comment]
Closing this issue as this has been fixed! 🎉

Please reopen if needed
