### ISSUE TITLE
GitHub Action appears to be incompatible with Docusaurus

### ISSUE THREAD

**Issue by paynecrl97** [Azure/static-web-apps#85]
I'm having trouble getting the GitHub action to work with a repository where the build is dependent on some files that lie outside of the `app_location`. More specifically, it's a [Docusaurus](https://docusaurus.io/en/) v1 site.

This is the structure of a basic Docusaurus site:

```
root-directory
├── Dockerfile
├── README.md
├── docker-compose.yml
├── docs
│   ├── doc1.md
│   ├── doc2.md
│   ├── doc3.md
│   ├── exampledoc4.md
│   └── exampledoc5.md
└── website
    ├── blog
    │   ├── 2016-03-11-blog-post.md
    │   ├── 2017-04-10-blog-post-two.md
    │   ├── 2017-09-25-testing-rss.md
    │   ├── 2017-09-26-adding-rss.md
    │   └── 2017-10-24-new-version-1.0.0.md
    ├── core
    │   └── Footer.js
    ├── package.json
    ├── pages
    ├── sidebars.json
    ├── siteConfig.js
    └── static
```

At one point during the Docusaurus build script, it checks for the presence of the `docs` folder relative from the `website` folder, and this is the step that fails (it throws the exception at line 226 on this PR: https://github.com/facebook/docusaurus/pull/111/commits/7330ee74c19b46184caf76371ed36d0b893a5de3).

I've tried various different values for the `Azure/static-web-apps-deploy` GitHub Action, but I think it boils down to this problem:

1. I must use `app_location: "/website"` (or else the `app_build_command` never seems to be executed)
1. Files and folders outside the `app_location` do not appear to be available to build scripts (maybe not checked out?)
1. Doucsaurus tries to traverse up out of the `website` folder to find the `docs` folder (line 225 of the linked PR above), which isn't there, then throws.

**Comment by paynecrl97** [comment]
There is a workaround available:

Build the site in a separate step before the static web apps step:
```
      - name: Build
        run: "yarn install && yarn run build"
        working-directory: "website/"
```

Then use the output of that step as the app location, eg: ` app_location: "/website/build/docs"`

**Comment by miwebst** [comment]
We are working on a solution to this so in the future you can avoid doing the build beforehand! I will update this issue once that work has rolled out.

**Comment by miwebst** [comment]
Hi @paynecrl97, can you retry this? This should be fixed now.
