### ISSUE TITLE
Special characters not served - Blazor WebAssembly .NET6 using MudBlazor 

### ISSUE THREAD

**Issue by sinisteralex** [Azure/static-web-apps#852]
**Norwegian characters  Æ-Ø-Å is not served on a .NET6 Blazor WebAssembly app deployed with Azure Static Web App**

On Localhost special characters are served, when deployed to Azure Static Web App they are not showing correctly.

**To Reproduce**
1. Createa new Blazor WebAssembly-app in .NET6 with Norwegian Characters  Æ-Ø-Å in HTML with UTF-8 in index.html
2. Publish repo to Github
3. Deploy to Azure Static Web App 

Index.html 

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>My Project</title>
    <base href="/" />

    <link href="_content/MudBlazor/MudBlazor.min.css" rel="stylesheet" />
    <link href="Client.Pages.Components.EventTable.css" />
    <link href="app.css" rel="stylesheet" />
</head>

<body>
    <div id="app">

        Loading...
    </div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.webassembly.js"></script>

    <script src="_content/MudBlazor/MudBlazor.min.js"></script>

</body>

**Expected behavior**
Expect norwegian characteres  Æ-Ø-Å to be served and not ? served in place of special characters

**Screenshots**
Screenshot Localhost

![Special Characters Localhost](https://user-images.githubusercontent.com/53612147/179232988-78b97f6c-c541-47be-8b93-ab2f125a3319.png)

Screenshot Azure Static Web App
![Special Characters](https://user-images.githubusercontent.com/53612147/179232213-b8ce68aa-95b5-4607-ae82-a8e7200abb82.png)

**Comment by mishapos** [comment]
Hi, @sinisteralex could you please share the default hostname of your Static Web App?

**Comment by sinisteralex** [comment]
> Hi, @sinisteralex could you please share the default hostname of your Static Web App?

I would be happy too if you can PM me :)

SinisterAlex

**Comment by sinisteralex** [comment]
> Hi, @sinisteralex could you please share the default hostname of your Static Web App?

https://mango-grass-01beb5403.1.azurestaticapps.net/ - This is the one
