### ISSUE TITLE
Azure Static Webapp step fails with upload timeout error

### ISSUE THREAD

**Issue by donipudi** [Azure/static-web-apps#853]
In the pipeline, the build passes but the static web app step fails with below error
![image](https://user-images.githubusercontent.com/59617506/179264608-d72a4d8e-5149-4c13-808d-88706db77b46.png)

**Comment by panchosoft** [comment]
The same issue is happening to us since yesterday evening:

![image](https://user-images.githubusercontent.com/415730/179270212-c359eb44-f162-4cb9-8480-d74ccd02fc1b.png)

**Comment by topher1086** [comment]
I'm seeing the same issue as well.
![image](https://user-images.githubusercontent.com/57721193/179270689-5adaa159-448c-483a-aae3-81f2f91c08e5.png)

**Comment by AKaudinov** [comment]
Yeah, same issue here:
![image](https://user-images.githubusercontent.com/12226282/179272270-deb81313-726e-4204-a26f-94454362322f.png)

**Comment by mishapos** [comment]
Hi, we are aware of an issue related to Static Web Apps deployments intermittently failing. We have identified a fix and are in the process of rolling it out. Deployments should now be going through more reliably.

**Comment by AKaudinov** [comment]
Thanks @mishapos ! The deployments have started to stabilize on our end.

**Comment by MaxWilson** [comment]
I am still intermittently seeing this issue, October 13, 2022. https://github.com/MaxWilson/POCDungeonDraw/actions/runs/3246742217

**Comment by dligthart** [comment]
We are still experiencing this issue.
