### ISSUE TITLE
platformErrorOverrides preventing swa start from working

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/static-web-apps#855]
**Describe the bug**
I loaded up a repo that I hadn't changed for a few months, and found when I ran swa start this error was produced:
WARNING: Failed to read staticwebapp.config.json configuration

The following error was encountered: The property "platformErrorOverrides" is not allowed.

After I removed: 
[swa] 56:     "platformErrorOverrides": [
[swa] 57:         {
[swa] 58:             "errorType": "Unauthenticated",
[swa] 59:             "serve": "/login"
[swa] 60:         }
[swa] 61:     ]

from the file, swa start worked as expected.

**Device info (if applicable):**
 - OS: GitHub Codespace
 - Browser: chrome
 - Version: 103.0.5060.114 (Official Build) (64-bit)
 - Azure Static Web Apps CLI: 1.0.2

**Comment by anthonychu** [comment]
`platformErrorOverrides` is not a valid property in the file. See the [documentation here](https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#example-configuration-file).

**Comment by irwinwilliams** [comment]
Word @anthonychu , I guess it's not anymore. I deployed with it fine when I started  my site last year.
