### ISSUE TITLE
Too many redirects with Cloudflare

### ISSUE THREAD

**Issue by peterkarman1** [Azure/static-web-apps#858]
When enabling Cloudflare proxy in front of the app, you get the error too many redirects. I have  the following config file

`{
  "forwardingGateway": {
    "allowedForwardedHosts": ["myapp.com", "www.myapp.com"]
  }
}`

And in cloudflare i have added a rule to automatically inject the X-Forwarded-Host header with no luck. 

Expected behavior:
It goes to the site

**Comment by peterkarman1** [comment]
User error. Fix for future people

I would like to inform you that, If you’re receiving the ERR_TOO_MANY_REDIRECTS error when accessing your HTTPS-enabled site that is being proxied through Cloudflare, it’s likely that you have SSL set to Flexible. This should be set to Full (strict), which will ensure connections to your site are fully encrypted end-to-end.

The SSL setting can be found under the SSL/TLS tab.

**Comment by codejoey** [comment]
it's due to https://developers.cloudflare.com/ssl/troubleshooting/too-many-redirects/#flexible-encryption-mode 
basically, origin server automatically redirects all HTTP requests to HTTPS  making a loop.
