### ISSUE TITLE
InternalServerError for bicep deployment with Provider: 'None'

### ISSUE THREAD

**Issue by th3ragex** [Azure/static-web-apps#861]
I am trying to deploy a SWA with 'Other' as source provider via bicep. It creates the SWA but the response from the deployment task i am getting is:

```json
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [{
                "code": "InternalServerError",
                "message": "{\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The response for resource had empty or invalid content.\"\r\n  }\r\n}"
            }
        ]
    }
}
```

Using the portal works without any issue and would look like this:
![image](https://user-images.githubusercontent.com/15040273/180409442-87594bde-189e-41eb-8398-4155f24ce4f9.png)

My bicep:
```bicep
param location string = resourceGroup().location
resource staticWebPageDeviceRegistration 'Microsoft.Web/staticSites@2022-03-01' = {
  name: 'test-swa'
  location: location
  sku:{
    name: 'Standard'
    tier: 'Standard'
  }
  properties:{
     provider: 'None'
  }
}

```
I was not able to find any documentation on the 'None' parameter. I exported the ARM template of a manually deployed SWA to get this information.

1. Deploy bicep 
2. See error in console
2. See error in deployments

**Expected behavior**
- A better error message which helps me to find a solution
- Documentation of the provider parameter and expected other parameter values.

**Device info:**
 - OS: Windows 10 21H2
- Bicep CLI version 0.8.9 (33a85174de)
- Az Region: West Europe

If i export the ARM template from the portal it looks like this:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "staticSites_test_swa_name": {
            "defaultValue": "test-swa",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Web/staticSites",
            "apiVersion": "2021-03-01",
            "name": "[parameters('staticSites_test_swa_name')]",
            "location": "West Europe",
            "sku": {
                "name": "Standard",
                "tier": "Standard"
            },
            "properties": {
                "stagingEnvironmentPolicy": "Enabled",
                "allowConfigFileUpdates": true,
                "provider": "None",
                "enterpriseGradeCdnStatus": "Disabled"
            }
        }
    ]
}
```

**Comment by tkamesh** [comment]
`provider` is not mandatory property. consider having empty properties.

**Comment by sinedied** [comment]
I get the same error when having empty properties:
```bicep
resource staticWebApp 'Microsoft.Web/staticSites@2022-03-01' = {
  name: 'swa-${projectName}-${environment}-${uid}'
  location: location
  tags: commonTags
  sku: {
    name: 'Standard'
    tier: 'Standard'
  }
  properties: {
  }
}
```

When switching to the older `@2021-03-01` api, no errors.

**Comment by th3ragex** [comment]
@sinedied Thank you! Using the `2021-03-01` version works for me as well. 

Btw: The region i am testing on is "West Europe"

**Comment by annikel** [comment]
Hi @th3ragex and @sinedied, we will be rolling out the fix for the create static sites operation for the 2022-03-01 api-version soon. Until then please use the version 2021-03-01. Thank you!
