### ISSUE TITLE
Ability to use deployment_environment in Gitlab CI/CD pipeline

### ISSUE THREAD

**Issue by PaulIvanov** [Azure/static-web-apps#867]
Is there an ability to use the `deployment_environment` variable within the gitlab version of the static-web-app configuration?

**Describe the solution you'd like**
Id like to be able to deploy named branches to staging branches on my static web app service

**Describe alternatives you've considered**
Using a different service than azure to host my applications

**Comment by joslinmicrosoft** [comment]
Hi @PaulIvanov I'm discussing with the team to add this option for GitLab, we'll let you know as soon as we have an update.

**Comment by joslinmicrosoft** [comment]
Hi @PaulIvanov, we've extended support for using the `DEPLOYMENT_ENVIRONMENT` variable in GitLab as now documented here: https://gitlab.com/static-web-apps/azure-static-web-apps-deploy#other-optional-paramters. Please let us know if that works for you. Thanks!
