### ISSUE TITLE
Update wording in domain configuration blade to include subdomains

### ISSUE THREAD

**Issue by burkeholland** [Azure/static-web-apps#87]
Originally reported [here](https://github.com/MicrosoftDocs/azure-docs/issues/57930).

The issue is that we don't specify that "www" could be any subdomain, and that confuses people. The request is that we update the blade to show that you can use any subdomain, not just "www". I tried mocking this up, but I'm not sure happy with this. It seems even more confusing. 

![custom](https://user-images.githubusercontent.com/686963/86655282-37393e80-bfac-11ea-822c-7f3431db7437.png)

**Comment by refortie** [comment]
That is a good suggestion. I have created a work item and added to our queue to be fix

**Comment by btardif** [comment]
I think we need to review this with our copy editor. @burkeholland I'll add you to the meeting hopefully we can land on something  👍

**Comment by btardif** [comment]
@dariagrigoriu can you get me admin access so that I can triage and tag myself?

**Comment by burkeholland** [comment]
Tracking on DevOps UX as 7945735

**Comment by miwebst** [comment]
Looks like it is updated now
