### ISSUE TITLE
Specifying a custom index document

### ISSUE THREAD

**Issue by teekay** [Azure/static-web-apps#870]
I would like to be able to specify a custom index document for a given route.

For example: I have a route `/blog/rss/`. The default document should be `index.xml`, not `index.html`, since the content type is XML.

From the docs It's not obvious to me that I can do that today, and I suspect I cannot.

I could work around this by using a redirect but that would be sub-optimal.

Please kindly consider adding this feature. Thank you.

**Comment by anthonychu** [comment]
I think you might be able achieve this with a rewrite instead of a redirect. https://docs.microsoft.com/en-us/azure/static-web-apps/configuration#defining-routes

**Comment by teekay** [comment]
Thank you!
