### ISSUE TITLE
Redirect to an external URL

### ISSUE THREAD

**Issue by teekay** [Azure/static-web-apps#871]
I would like to be able to define an external redirect URL for certain routes.

Example: I have a blob that I used to host on my website, and now I moved it to Azure Blob Storage. For compatibility reasons, I want to redirect clients asking for the blob to the new location. Like this:

```json
{
      "route": "/apps/cabeceo/releases/CabeceoSetup.exe",
      "redirect": "https://tomaskohlcomstgacc.blob.core.windows.net/cabeceo/CabeceoSetup.exe",
      "statusCode": 301
 }
```

I have noticed that while redirects that point to an internal URL work, when I hit the route that has an external redirect URL, I receive a `404` instead.

**Comment by annikel** [comment]
Hi @teekay, I was trying to reproduce the issue but it does work fine for me - as it is supposed to since we do support external redirect URLs. Could you please ensure your file is accessible under that URL. Thanks!

**Comment by teekay** [comment]
@annikel yes, you are right. Sorry. I had an issue in my build script and the external redirects were not generated.
