### ISSUE TITLE
Unable to switch to nodejs 16. Build fails.

### ISSUE THREAD

**Issue by Danish-Mentorange** [Azure/static-web-apps#879]
**Describe the bug**

When using the `Azure/static-web-apps-deploy@v1` the build is failing because it is detecting and installing nodejs 14. We are using nodejs 16. I also added the following line but it still detects node 14.

```
- uses: actions/setup-node@v3
      with:
        node-version: 16
```

**Expected behavior**
I should be able to use `Azure/static-web-apps-deploy@v1` for nodejs 16.

**Comment by vivekjilla** [comment]
Hi @Danish-Mentorange, 
I will check with our team to see if we can/should change the default node version.

But meanwhile, to specify custom nodejs version, can you try this approach and see if it helps - https://blog.johnnyreilly.com/2022/05/28/azure-static-web-apps-node-16-oryx

**Comment by Danish-Mentorange** [comment]
That did the trick. Thank you.
