### ISSUE TITLE
Package.json guidance for dependencies versus devDependencies

### ISSUE THREAD

**Issue by diberry** [Azure/static-web-apps#882]
I see in some SWA apps that all dependencies including strictly dev dependencies such as TypeScript types are all in the dependencies node. Is this required or recommended for SWA? If yes, why. 

```
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.47",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.7.4",
    "web-vitals": "^2.1.4"
  },
```

**Comment by vivekjilla** [comment]
Afaik, this is not required by SWA. Can you please let us know if you faced any issues when you added strictly dev-dependencies to only the devDependencies section instead of dependencies?

**Comment by diberry** [comment]
@vivekjilla  Not issues, but wondering what to say in docs about how to think about dependencies and devDependencies when structuring a project in the pipeline.

**Comment by vivekjilla** [comment]
@diberry as far as I can see, we're not doing any special handling there. So, standard operating procedure is fine.
