### ISSUE TITLE
blazor - trying to log in => sorry, there is nothing at this address

### ISSUE THREAD

**Issue by drma-dev** [Azure/static-web-apps#883]
![image](https://user-images.githubusercontent.com/12803050/184451594-2032181a-c257-4ba8-9f83-a60b74bdbcb3.png)
this error has been happening for a while, both when trying to log in and to log out. I found that deleting the 'index.html' file from the cache resolves and the targeting for that endpoint works again.

`const offlineAssetsExclude = [/^service-worker\.js$/, /^routes\.json$/, /^index\.html$/];`
removing the 'index.html' from the 'service-worker.published.js' file temporarily solved this problem.

I've opened this item before, but it was ignored. I'm reposting.

**Comment by vivekjilla** [comment]
Hi @drma-dev, in your service-work.published.js: https://github.com/drma-dev/VerusDate/blob/master/src/VerusDate.Web/wwwroot/service-worker.published.js#L43
I see we have a logic to serve index.html for all the GET requests and if the index.html is cached, the request will not hit the server. I guess this might be happening with `/.auth...` urls as well. 

And when you removed the `index.html` from cache, the request is reaching the server where StaticWebApp was able to take the appropriate action.

If this is correct, can you try setting `shouldServeIndexHtml` as `false` for auth routes where request path has `/.auth/....` (in the above file) and then adding index.html back to cache, and see if it works.

Please let us know if that helps or if we need to dig further into this. Thanks!

**Comment by drma-dev** [comment]
`const shouldServeIndexHtml = event.request.mode === 'navigate' && !event.request.url.includes('/.auth/');`

@vivekjilla I made it. takes both login and logout.

but shouldn't this be like that by default in the template or at least be in the documentation?

**Comment by vivekjilla** [comment]
@drma-dev glad that it worked! 

I thought that was a custom code. 

Can you please point me to the template where this logic was picked from. 
I will check with my team and see if we can fix it there.

**Comment by drma-dev** [comment]
@vivekjilla 
![image](https://user-images.githubusercontent.com/12803050/184500905-e3d97b59-cee8-4713-bbe9-1ddc75736e43.png)

**Comment by vivekjilla** [comment]
@drma-dev Thanks for referencing the template. This issue is due to the combination of blazor app and static web apps. I'll check with my team to see  if we can update our docs to reflect this. 

Thanks for reporting, and apologies for the inconvenience caused. :)

**Comment by Reshmi-Sriram** [comment]
cc// @craigshoemaker

**Comment by vivekjilla** [comment]
Closing this issue as the original issue has been resolved. Tracking the doc fix separately

**Comment by Tillman32** [comment]
Was the documentation updated? I'm running into the same issue just using the out of the box template.

**Comment by brandonchastain** [comment]
+1 this also impacted me just now, after enabling PWA on a Blazor WASM app which I host on Static Web Apps. I think I started with the latest .net 9 templates but still had to go fix this issue in the service-worker.published.js.
