### ISSUE TITLE
Blazor - .auth routes show Sorry, there is nothing at this address.

### ISSUE THREAD

**Issue by bmaruyama** [Azure/static-web-apps#884]
**Describe the bug**

I tried to add AAD B2C as a custom auth provider to a deployed Blazor Azure SWA.  All .auth routes, including the new aadb2c route, return a 401.

**To Reproduce**
1. Add AAD B2C as a custom auth provider as per https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-azure-static-app
2. As part of that, add the auth section to the configuration file.
3. Navigate to .auth routes, page shows "Sorry, there is nothing at this address", blazor.webassembly.js gives the following errors in developer Console: Info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
5. Remove the auth section of the config file.
6. Verify that the non-custom auth routes (e.g. AAD) display a login prompt.

**Expected behavior**
That .auth routes do not require an authenticated user.

**Device info (if applicable):**
 - macOS
 - Chrome & Safari

**Additional context**
I have run into a similar issue before which was resolved by removing old PWA files from wwwroot.  #883 is similar to this previous issue. ~~This SWA is based on very early templates, so it is possible that some of the files (js, etc.) are out of date.~~ It is very possible that the changes for AAD B2C were not done properly, but I would have expected different errors.

**Comment by vivekjilla** [comment]
@bmaruyama can you please provide the static site endpoint, so that we can look into this further, and also, if possible, can you please provide the Blazor example repo used.

**Comment by bmaruyama** [comment]
@vivekjilla  I have supplied the endpoint via email.  Thanks for your help.

**Comment by vivekjilla** [comment]
@bmaruyama Thanks for sharing the endpoint.
Looks like the custom auth AAD B2C is not enabled for your app now.
Can you add it back, so that we can repro the issue and dig into the details further.
Right now, the default auth providers like aad is working fine and aadb2c is returning "There is nothing at the address" as expected

**Comment by bmaruyama** [comment]
@vivekjilla My apologies, the config file has been updated and deployed.  The Login link uses the aadb2c provider.

**Comment by hugoforte** [comment]
I'm having a similar issue - should I open a new ticket?

I edited this project to enable aad b2c: https://github.com/MicrosoftDocs/mslearn-staticwebapp-authentication
I'm unable to get to the .auth/login/aadb2c endpoint (get 404 error) - aad, twitter, and github logins are working

I followed the same article: https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-azure-static-app.

Here's the endpoint: 
https://gentle-flower-02ac39b0f.1.azurestaticapps.net/

I attached the code as well
[my-static-web-app-authn-main.zip](https://github.com/Azure/static-web-apps/files/9367399/my-static-web-app-authn-main.zip)

**Comment by vivekjilla** [comment]
@hugoforte Yes, can you please open a new issue for your usecase, as it seems to be different from what's happening in this issue.

**Comment by vivekjilla** [comment]
@bmaruyama Can you please check if you added the app settings in your app as per step 3 here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-azure-static-app#step-3-configure-the-azure-static-app

I guess, we need to add these settings instead of adding the values directly to the config file (incase you did this).
![image](https://user-images.githubusercontent.com/6436807/185299770-cb53cfca-0060-41af-a009-9ef795892127.png)


Can you please try this and let us know if it worked

**Comment by hugoforte** [comment]
> @hugoforte Yes, can you please open a new issue for your usecase, as it seems to be different from what's happening in this issue.

@vivekjilla 
Thanks - I created it here: https://github.com/Azure/static-web-apps/issues/890

**Comment by bmaruyama** [comment]
Vivek,

Yes, it looks like I missed that step. I was concerned that I had run into another variation of the bug I fixed previously.  Thank you so much for your assistance, I am grateful for such a fast response.

Brett
