### ISSUE TITLE
Failed to create Personal Access Token in Azure DevOps deployment

### ISSUE THREAD

**Issue by aaronpowell** [Azure/static-web-apps#887]
Sparked from https://twitter.com/jacksorjacksor/status/1559495716401287168?s=20&t=Mijqwm0p17MRAoHb2_J7hg, I'm trying to setup a pipeline using Azure DevOps and I'm hitting an error:

![Error message](https://user-images.githubusercontent.com/434140/185297505-a85a5f38-79f9-453a-b4f0-4bbfa4558caf.png)
 
The process I've gone through is:

1. Logged into Azure DevOps 
1. Created a new project and initialized a repo
2. Uploaded a file, index.html to the repo
3. Opened Azure and created a new SWA resource
4. Selected Azure DevOps as the deployment source (then filled out the config)
5. Navigated to the Review + Create screen and selected Create
6. Received error as above

Here's the settings provided when creating the resource in Azure:

![SWA create settings](https://user-images.githubusercontent.com/434140/185297620-791e8703-b420-4bf0-8178-a095a44d107b.png)

**Comment by jacksorjacksor** [comment]
AH I think I've found why.

For me this issue was resolved when I connected my Azure DevOps account to Azure Active Directory. When logged into the associated Azure Portal I was then able to deploy directly from Azure DevOps to a newly created SWA instance.

**Comment by thetitan** [comment]
Thank you @jacksorjacksor. This did the trick for me. For anyone with the same issue, the connection is done in DevOps, under Organization Settings, on the Azure AD tab.

**Comment by rupareddy5-21** [comment]
Thanks for the workaround @jacksorjacksor. We're closing the issue. Please feel free to raise concerns if you're facing any issues.

**Comment by nattui** [comment]
To build on top of [jacksorjacksor](https://github.com/jacksorjacksor) helpful instructions

---

Here are my 2024 Instructions:

1. Go to your organization's Azure DevOps (https://dev.azure.com/<YOUR_ORG_NAME>)
2. Bottom left there is "Organization settings"
3. Click on "Microsoft Entra" on the sidebar
4. Click on the "Connect directory" button
