### ISSUE TITLE
The custom domain has not been resolving to your static web app and has expired

### ISSUE THREAD

**Issue by TrplM** [Azure/static-web-apps#888]
**Describe the bug**

I have multiple Statics Apps **proxied** through Cloudflare with a custom domain name. Today I see all the apps returning the Azure 404 holding page.

The Azure portal shows the custom domain as _**"Validation failed"**_ and **_"The custom domain has not been resolving to your static web app and has expired"_**

I don't see this behaviour documented anywhere? What is the solution to prevent this in the future - TXT verification?

![Picture1r](https://user-images.githubusercontent.com/3910679/185305847-9f342529-440f-45b9-b9be-90cc89124737.png)

![Picture2r](https://user-images.githubusercontent.com/3910679/185305871-89546092-0c78-4167-9c5a-8ee7315500d6.png)

**Comment by sachin-rathor** [comment]
Hi @TrplM ,

Could you please share the default hostname?

Thanks!

**Comment by TrplM** [comment]
> Hi @TrplM ,
> 
> Could you please share the default hostname?
> 
> Thanks!

This is one of them (red-sea-08fb6fc03.1.azurestaticapps.net), but I have already disconnected and reconnected the custom domains

**Comment by vivekjilla** [comment]
@TrplM Thanks for reverifying. And apologies for the inconvenience caused.

For auto renewal, we use http-token method. 
And for that to work, please make sure the `.well-known/pki-validation/fileauth.txt` endpoint on your custom domain is accessible to public internet, so that digicert can validate the domain.

We're working on improving the docs and notification flows in this area.
Please let us know if you need anything else.

**Comment by TrplM** [comment]
@vivekjilla 

Couple of clarification questions:

The contents of the file should be the _validationToken_ generated when using TXT verification?

How do I obtain the _validationToken_? Do I need to delete and reconnect the domains?
`az staticwebapp hostname` returns no _validationToken_ even for domains I reconnected this morning with the TXT method.
If I try and generate the token (portal and cli) for already validated domains, it returns nothing.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/3910679/185371018-2988a796-b3f4-4e03-8011-14d66223e86b.png">

**Comment by vivekjilla** [comment]
Hi @TrplM the validation token gets generated when the certificate is nearing expiry and for renewal, Digicert + SWA will automatically take care of generating the token and returning it when the fileauth.txt endpoint is accessed, when it's nearing expiry.

As you created the certificates today, they won't expire for next 6 months.

So, what we need to make sure is that the request is actually reaching the Static Web App when accessing the `.well-known/pki-validation/fileauth.txt` endpoint, and it's not restricted by any proxies or caching or auth restrictions etc by CDN or anything else.

**Comment by TrplM** [comment]
> Hi @TrplM the validation token gets generated when the certificate is nearing expiry and for renewal, Digicert + SWA will automatically take care of generating the token and returning it when the fileauth.txt endpoint is accessed, when it's nearing expiry.
> 
> As you created the certificates today, they won't expire for next 6 months.
> 
> So, what we need to make sure is that the request is actually reaching the Static Web App when accessing the `.well-known/pki-validation/fileauth.txt` endpoint, and it's not restricted by any proxies or caching or auth restrictions etc by CDN or anything else, for automatic renewal to work.

Happy to take this offline or over to a support ticket if required?

But still a little unclear as to the root cause, and what I would need to do to resolve. If the file exists there should be no issues accessing the file through the custom domain with Cloudflare proxying the request.

I've uploaded a test file, and get some strange behaviour. Still investigating whether it is an issue with Cloudflare or the Static App

Using the default hostname, I can reach the file correctly
<img width="544" alt="image" src="https://user-images.githubusercontent.com/3910679/185390756-b39c6527-8b72-46e9-af98-8059016b8a6d.png">

If I access via the custom domain , I get a 404 from Azure
<img width="937" alt="image" src="https://user-images.githubusercontent.com/3910679/185391079-cc3d1d4a-6844-4e96-8a85-0f968777967c.png">

**Comment by vivekjilla** [comment]
@TrplM This seems like it has something to do with configuration in Cloudflare. I don't have much context on that. Can you check if the cloudflare is actually proxying the request to the same endpoint with default hostname or if it's doing something else?

**Comment by TrplM** [comment]
@vivekjilla Will feedback as soon as I have narrowed it down. All other routes work, just the /.well-known is returning 404

**Comment by vivekjilla** [comment]
@TrplM Hey, just wanted to share one more thing I just realized. Sorry for the delay.

This could very well be expected behavior. Only when the cert renewal is in progress, would we see some the token response back on that endpoint otherwise we would get the 404.

Also the response for this endpoint depends on which hostname we're using to call it, and as default hostnames are completely managed by us, I think we just return that fixed string called "test-token" when hitting that endpoint.

Hope that clears things up now.

**Comment by mosoftwareenterprises** [comment]
@TrplM I just bumped into this myself, and like you recreated my custom domain. Did you find the cause?
I cannot see anything at cloudflare to indicate the issue.

**Comment by mosoftwareenterprises** [comment]
I think I have solved my issue. It still was not validating the domain, but then i re-read the docs, and I noticed I had not setup the apex domain required by Azure.
https://learn.microsoft.com/en-us/azure/static-web-apps/apex-domain-external
Adding this, has allowed it to validate:
Cloudflare:
![image](https://user-images.githubusercontent.com/71320282/202737931-ab5913e2-ae58-4a22-b956-cf65700bd312.png)
Azure:
![image](https://user-images.githubusercontent.com/71320282/202737988-40759aaa-386c-4d52-8500-0198a5d80b79.png)

**Comment by thomasgauvin** [comment]
@mosoftwareenterprises are you using the CNAME flattening of Cloudflare in this case? Before adding this, what record was added that resolved your domain to your Static Web App? Was it another CNAME/ALIAS record?

**Comment by mosoftwareenterprises** [comment]
I am not using cname flattening.
It was a cname record before to the blog subdomain.

**Comment by thomasgauvin** [comment]
Ok I see, so you are currently using a CNAME record (with host `blog`) to route traffic from https://blog.markoliver.website/ to your Static Web App correct? If that is the case, the SSL cert renewal should have worked without the need to add APEX domain, so perhaps it's worth investigating this a bit more

**Comment by thomasgauvin** [comment]
@TrplM are you using Always Use HTTPS on your proxy? It seems that this is a common issue with Proxied Cloudflare sites https://community.cloudflare.com/t/let-lets-encrypt-bot-bypass-always-use-https/200274

**Comment by TrplM** [comment]
> @TrplM are you using Always Use HTTPS on your proxy? It seems that this is a common issue with Proxied Cloudflare sites https://community.cloudflare.com/t/let-lets-encrypt-bot-bypass-always-use-https/200274

Yes that seemed to be our issue. Static Apps requires the `/.well-known/` directory to be accessible and as we were proxying everything through Cloudflare this route was getting blocked. We've made some updates to our Cloudflare configuration and it seems to be resolved for now.

**Comment by thomasgauvin** [comment]
Excellent, I'm glad that resolved your issue @TrplM, @mosoftwareenterprises any chance this was also you issue for the renewal of your blog subdomain website?

**Comment by mosoftwareenterprises** [comment]
> Ok I see, so you are currently using a CNAME record (with host `blog`) to route traffic from https://blog.markoliver.website/ to your Static Web App correct? 

Correct.
> If that is the case, the SSL cert renewal should have worked without the need to add APEX domain, so perhaps it's worth us investigating this a bit more. 

ok.

> Are you using HTTPS only and/or using the Proxy option?
If you mean this option in CloudFlare, then yes, it is turned on:
![image](https://user-images.githubusercontent.com/71320282/204534583-80729551-7ebd-4879-a4b0-442751b81ad9.png)

**Comment by abouroubi** [comment]
> 

Hello, can you share the config used in Cloudflare to avoid this ?

**Comment by TrplM** [comment]
> > 
> 
> Hello, can you share the config used in Cloudflare to avoid this?

Ours were due to custom firewall rules and worker routes. Out of the box, I don't think any additional configuration is needed on Cloudflare, even when proxying.

**Comment by abouroubi** [comment]
Yeah I think the issue is manly because of Always Use HTTPS, it's more of a CloudFlare issue than Azure.

**Comment by nutmix** [comment]
.well-known/pki-validation/fileauth.txt

how does this work? What should be in the txt file?  What domain should host it?

We have the same issue that we cannot renew the certs, and you cant upload custom certs, its a catch 22.

Our particular problem is that we use the static hosting for our sites "down" pages, so most of the time our URL (e.g. www.mysite.com) resolves, via traffic manger, to our main hosting.  when our main hosting is down, we flip the switch in traffic manger to point www.mysite.com to the static web app, only to find its cert ran out!

We desperately need a way to get certs, or renew certs on static web apps, when the custom domain url is not currently pointing to the static web app.

**Comment by naskew** [comment]
I came across this because I just set up a couple of Azure SWA's with their own custom domains. Setting this up was incredibly simple, I just created the SWA and then added the custom domain in Azure and went to my DNS provider (Argeweb) to add a CNAME. Note that my apex is not with Azure but these subdomains are and if all goes well then I'll shift the apex too.

But the reason for my question is just that the custom domains for the SWAs I've created on Azure show an expiry date of roughly 6 months from now and I'm curious what this actually means. Reading the above it seems that @mosoftwareenterprises @TrplM had some issues past the 6 month date and it's not clear what I need to do to prevent this. Is there some Azure documentation that covers this now?

**Comment by mosoftwareenterprises** [comment]
Hey @naskew . I believe the certificates run out and are automatically renewed ever 6 months.
My current cert:
![image](https://github.com/user-attachments/assets/526cb6a2-630c-455e-94c1-e7ccf02122eb)

 I fixed mine in 2022 and had no issues since. Check out my investigation here: https://blog.markoliver.website/Azure-Static-Web-App-Invalid-SSL-Certificate

**Comment by naskew** [comment]
Thanks for the reply Mark. I hope you are right :-) I'm planning to move my apex to an SWA and the expiry dates are just after I need to give notice to my current host that I'm moving. I'll take a look at the blog. Thanks again.

**Comment by naskew** [comment]
One quick thing. I'm using a separate site to monitor my apex site because my current hosts have been pretty poor over the years. I use "uptrends" but there are a number of such services that try to get a url to respond and if that fails then you get an email.  Having seen your experience, I think I'll add checks to my SWAs so I know quickly if one fails.

**Comment by TrplM** [comment]
> But the reason for my question is just that the custom domains for the SWAs I've created on Azure show an expiry date of roughly 6 months from now and I'm curious what this actually means. Reading the above it seems that @mosoftwareenterprises @TrplM had some issues past the 6 month date and it's not clear what I need to do to prevent this. Is there some Azure documentation that covers this now?

In our case, there were some incorrect firewall rules blocking access to the sites `.well-known` directory causing the cert renewal to fail. No issues since then
