### ISSUE TITLE
Static Web Apps should generate an Allow header for 405 errors for better debugging

### ISSUE THREAD

**Issue by danbasszeti** [Azure/static-web-apps#895]
**Is your feature request related to a problem? Please describe.**
I was building a react app that sent a POST request to the bundled function app with Azure Static Web Apps and it kept replying with a 405 error, Method Not Allowed. It took me a while but I eventually worked out that I had dropped off the /api at the start of my request, so it was trying to hit the static server rather than the function app, and I presume that only supports GET's. 

According to MDN (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405) the server 'must' generate an Allow header with the allowed verbs on it. It currently does not do this, and doesn't provide any other information at all: 
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/75691669/185927072-3bf66cbf-b9ca-4729-a7d4-2e0750dfa214.png">

**Describe the solution you'd like**
I'd like an Allow header with GET on it - that would have made me hit a 404 in my case which would have made me realise my mistake much faster. Perhaps also a message suggesting that you might be intending to call an API and therefore might be missing the root path for that? Not sure how much can be given away without security issues. 

**Describe alternatives you've considered**
A message that is more explicit about the problem, but only shows in the static web apps CLI to avoid security problems. 

**Additional context**

**Comment by mishapos** [comment]
Hi, thank you for using Static Web Apps and for the great suggestion! We have a fix rolling out soon that will add the Allow header to 405 responses.

**Comment by mishapos** [comment]
@danbasszeti The fix has been rolled out. Do you mind checking that the Allow header now appears for you and close the issue if it's resolved? Thanks!
