### ISSUE TITLE
Support Apple as authentication provider

### ISSUE THREAD

**Issue by wes566** [Azure/static-web-apps#9]
The auth experience on iPhones with "Sign in with Apple" is pretty great and it would be great if my app built on SWA supported that.

**Comment by antonioberetini** [comment]
Yes please

**Comment by mkarmark** [comment]
Thank you for using Azure Static Web Apps!

For preview, using the five offered providers (Azure Active Directory, Facebook, GitHub, Google, and Twitter) is the only option for authentication/authorization.

Supporting Apple as an authentication provider is something we plan to offer in the future.

Thank you for your feedback. Keep them coming.

**Comment by miwebst** [comment]
This is available through custom auth, you can try it here https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=apple
