### ISSUE TITLE
Manage roles in app

### ISSUE THREAD

**Issue by DarqueWarrior** [Azure/static-web-apps#91]
If I wanted another person on my team to have the permission to assign roles do I have to give them access to my Azure Subscription? Is there an API under .Auth so that invites / role assignments can be done from my app not only from the portal? I would hate to grant people access to my Subscription and teach them enough about Azure to move around safely just so they can assign permissions to people.

**Comment by miwebst** [comment]
Interesting idea! This is not currently supported but certainly good feedback :) Today the only way to do this is to go through the Portal or use azCli: https://docs.microsoft.com/en-us/cli/azure/staticwebapp?view=azure-cli-latest you can see the user update at the bottom

**Comment by DarqueWarrior** [comment]
I used to run a site where I would assign a "Club Admin" that person could then assign permissions to whoever they wanted under their Club. I can't give all those people access to my subscription. It was simply part of the Web App. The security and permissions were managed from the site. I was evaluating if I could move that site to static web apps. But at this time that would be an issue for me.

**Comment by GaryParr** [comment]
I actually just posted a [quesiton](https://github.com/Azure/static-web-apps/issues/200) related to this as I hadn't thought to search on "roles" in the issues list yet. Anyway, managing roles is only part of the API equation as you also need a programmatic method of sending and revoking invitations.

**Comment by simonaco** [comment]
this should be addressed by the recent feature allowing users to write a serverless function to manage roles.
