### ISSUE TITLE
Custom domain error: Request Envelope is invalid.

### ISSUE THREAD

**Issue by zachsents** [Azure/static-web-apps#925]
Trying to add a custom domain is giving an error. I have the domain in NameCheap and a DNS zone created on Azure for it. The nameservers are pointing to the correct place, as verified by
`Resolve-DnsName synbiosuite.org -Type NS`

When I try to add the custom domain in the portal, I get "domainName is invalid.  The domain name given was not found." 

When I try to add the domain with the CLI with the command:
`az staticwebapp hostname set -n SynBioSuite --hostname synbiosuite.org --validation-method dns-txt-token`
I get "Request Envelope is invalid.  Please ensure the custom domain is not linked to another site." I am not using the domain on any other site, and everything has had plenty of time to propogate. This has been an issue for weeks.

Any ideas?

**Comment by joslinmicrosoft** [comment]
Hi @zachsents we've noticed on our end that the domain was linked earlier today; can you confirm if that was you and if you are now unblocked?

**Comment by zachsents** [comment]
Hey, just got off with Azure support and they cleared it up. Not sure what the issue was; didn't require any action on my end.
