### ISSUE TITLE
Task fails with Didn't find Oryx manifest file under location: /ss-oryx/app-manifest/oryx-manifest.toml error for static export

### ISSUE THREAD

**Issue by kantipenko** [Azure/static-web-apps#929]
**Describe the bug**

Using Azure DevOps task and ubuntu latest image we receive following error on AzureStaticWebApp@0 task
Verbose logging enabled
Build timeout not specified, defaulting to 15 minutes
App Directory Location: './app/dist/' was found.
Looking for event info
Event info parsed from action options.
Skipping step to build /working_dir/./app/dist with Oryx
No Api directory specified. Azure Functions will not be created.
Found staticwebapp.config.json file: 'app/dist/21894/staticwebapp.config.json'
**Didn't find Oryx manifest file under location: /ss-oryx/app-manifest/oryx-manifest.toml
**Failed to find a default file in the app artifacts folder (./app/dist). Valid default files: index.html,Index.html.**
If your application contains purely static content, please verify that the variable 'app_location' in your deployment configuration file points to the root of your application.
If your application requires build steps, please validate that a default file exists in the build output directory.

**App is Not Oryx and we have index.html in ./app/dist folder**

**To Reproduce**
Task used to deploy static webapp
      - task: AzureStaticWebApp@0
        enabled: true #requires linux agent, so new stage needed and artefact should be exported in this one
        displayName: "Deploy Dev01"
        name: DeployDev01
        inputs:
            app_location: './app/dist/'
            output_location: '/dist'
            skip_app_build: true
            skip_api_build: true
            verbose: true
            is_static_export: true
            azure_static_web_apps_api_token:  $(Dev01DT)

_If possible, please provide the following information if relevant (do not include sensitive content):_
Can not be provided due to sensitive nature

**Expected behavior**
Static Website got deployed by Azure DevOps task

**Screenshots**

**Device info (if applicable):**
NA
**Additional context**

**Comment by joslinmicrosoft** [comment]
Hi @kantipenko just to check, are you sure `app/dist` is the root folder of your app contents, with the `index.html`? From the log about `staticwebapp.config.json`, is it possible that `app/dist/21894` is the root?

To also clarify, there's no error with Oryx (that is a warning message that only appears on `verbose: true` meant to be informational in this case). Also, `is_static_export` is meant to be used with Next.js apps, is that the case for you?

**Comment by kantipenko** [comment]
Thanks @joslinmicrosoft ! Great catch!
Updated task to the inputs below and it worked. Issue can be closed.
            - task: AzureStaticWebApp@0
        enabled: true #requires linux agent, so new stage needed and artefact should be exported in this one
        displayName: "Deploy Dev01"
        name: DeployDev01
        inputs:
            app_location: './app/dist/$(Build.BuildId)/'
            output_location: '/dist/'
            skip_app_build: true
            skip_api_build: true
            verbose: true
            #is_static_export: true
            azure_static_web_apps_api_token:  $(Dev01DT)
