### ISSUE TITLE
403 Forbidden with Custom Authentication

### ISSUE THREAD

**Issue by jaylinclinycare** [Azure/static-web-apps#943]
I am using Identity Server 4 as the custom IDP, it's able to redirect to my login UI and fill in the username / password, however, it redirects back to 403 Forbidden page after successful login.

I tried the different settings for login.nameClaimType in staticwebapp.config.json:

1. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
2. given_name
3. email
5. even get rid of the whole nameClaimType

Here is my staticwebapp.config.json
```
{
  "navigationFallback": {
    "rewrite": "index.html",
    "exclude": ["/images/*.{png,jpg,gif}", "/css/*"]
  },
  "auth": {
    "identityProviders": {
      "customOpenIdConnectProviders": {
        "idsvr": {
          "registration": {
            "clientIdSettingName": "IS4_ClientId",
            "clientCredential": {
              "clientSecretSettingName": "IS4_ClientSecret"
            },
            "openIdConnectConfiguration": {
              "wellKnownOpenIdConfiguration": "https://2b36-1-145-110-180.au.ngrok.io/.well-known/openid-configuration"
            }
          },
          "login": {
            "nameClaimType": "email",
            "scopes": ["openid", "profile"]
          }
        }
      }
    }
  }
}

```

![image](https://user-images.githubusercontent.com/111974628/194823484-0fcbb693-8e26-4cd5-83a7-e88f9543b5cf.png)

I am wondering what /.auth/complete tries to validate? IdToken? Or AccessToken?

**Comment by jaylinclinycare** [comment]
It turned out that my id-token did not contain any claims, once the claims are returned back, I managed to login to the SWA.

**Comment by MonicaExplan** [comment]
Hi

what "once the claims are returned back". How did you solve it?
Thanks a lot
Monica

**Comment by hawkzey** [comment]
> It turned out that my id-token did not contain any claims, once the claims are returned back, I managed to login to the SWA.

did you do additional config to return claims
