### ISSUE TITLE
Azure DevOps - Release Pipeline - updated appsettings.json is ignored after publish

### ISSUE THREAD

**Issue by TeguSolutions** [Azure/static-web-apps#947]
I plan to deploy a pure static web app (without functions) with some hosting-specific (non-sensitive) details using the appsettings.json file.
I want to update the parameters on a Release Pipeline scope using the pipeline variables.

On the build pipeline: The project is built, and the artifact is created as single files (no zipping)
The release pipeline looks like the following:
![image](https://user-images.githubusercontent.com/20848629/195292267-986952b5-d117-4f1e-af35-9fb0baab8dcb.png)

I use PowerShell scripts to print the modified appsettings.json file at every step. It gives the expected result.
The simplified result is:
```
{
  ..other settings..
  "ThemeId": "1",
  "ThemeName": "DefaultTheme"
}
```

But the deployed appsettings.json remains the default one:
```
{
  ..other settings..
  "ThemeId": "#{ThemeId}#",
  "ThemeName": "#{ThemeName}#"
}
```

Other information:

- I tried to check/uncheck the 'Skip App Build' - I prefer not to rebuild the app again. It is done by the build pipeline.
- staticwebapp.config.json: I use the default version, I tried to change the MimeType from "text/json" to "application/json"
- I checked the log files 100x times, but everything looks fine, except the outcome.

Can you tell me what the issue is? Is it a bug, or am I missing anything?
Please let me know if any more information is required.

**Comment by vivekjilla** [comment]
@TeguSolutions Can you please try this work-around and see if it unblocks you: 
1. Use a different name for appsettings.json file in your repo, like `_appsettings.json` or `appsettings.template.json`
2. In your "Replace tokens" step, along with changing the contents, also update/create the file name back to `appsettings.json`

One possibility for the behavior you're observing is, the ADO task for "publish to static web app" pulls the code from repo and it overwrites already modified files. 

Sorry for the inconvenience caused and please let us know if the workaround works. 
If yes, we will take a look at this issue and see if we can avoid it.

**Comment by TeguSolutions** [comment]
@vivekjilla thank you, I appreciate the hints.

In the meantime, I could make it work.

As I figured out, I faced multiple 'issues' simultaneously with the appsettings.json approach to pass configuration value for Azure Static Web App.

Please let me show my workaround; it may help others too.

1, The appsettings.json modifications are ignored.

I deleted the appsettings.json from the repo, and I created this file on the fly in the release pipelines.
As a first step, I use the PowerShell task to create and fill the file (Release pipelines scoped variables):

```
New-Item $(System.DefaultWorkingDirectory)/.../wwwroot/appsettings.json

Set-Content $(System.DefaultWorkingDirectory)/.../wwwroot/appsettings.json '{
  "ApiRoute": "$(ApiRoute)",
  "ThemeId": "$(ThemeId)",
  "ThemeName": "$(ThemeName)"
}'
```

Publish to Static Web App task:
The app location is the wwwroot folder, and the Skip app build is checked (the app is already built).


2, The populated appsettings.json is ignored by the web app.

It's pretty tough to realise, but it may make sense.

In local development, the appsettings.development.json is automatically picked up at startup and converted to WebAssemblyHostConfiguration (or IConfiguration). It can be injected anywhere, and the values can be used.

Although it's not the case with the static web app.
In the production environment, I manually make this process as the first step right after the builder is created.

```
        using var httpClient = new HttpClient();
        httpClient.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
        var stream = await httpClient.GetStreamAsync("/appsettings.json");
        builder.Configuration.AddJsonStream(stream);
```

That's so simple :)
