### ISSUE TITLE
Oryx Pipeline Timeout

### ISSUE THREAD

**Issue by AscaL** [Azure/static-web-apps#949]
I've been building a SWA with Nuxt 3.
Since yesterday my pipelines have started failing for timeout on oryx (preset azure), even ones that previously ran to completion.
They all end the same way:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/8880943/195529381-4bd9661a-de5e-4d0e-9795-5804c4d89a68.png">

- Azure Pipelines workflow YAML file
<img width="186" alt="image" src="https://user-images.githubusercontent.com/8880943/195529901-e1f0d733-9ad0-44f0-9e43-2f9832d0f7dc.png">

- staticwebapp.config.json file
<img width="187" alt="image" src="https://user-images.githubusercontent.com/8880943/195530238-2ad769eb-6c80-4b98-a5d5-8c04c53cffe5.png">

**Expected behavior**
Pipeline does not timeout

**Comment by reedsutliff** [comment]
im encounting the same issue, deployment seems to be flaky

**Comment by AscaL** [comment]
@reedsutliff Did you manage to deploy anything or it just keeps timing out? I've run the pipeline ten times hoping one would pass... it doesn't.

**Comment by valstu** [comment]
I came to write similar issue but noticed this so I'll continue on this one. I'm exactly the same issue and I am using Github Actions, the build actually gets deployed but polling the deployment timeouts for some reason.

**Comment by reedsutliff** [comment]
@AscaL I am having the same experience as @valstu - the polling fails and then after some time the resource in portal shows the deployment succeeded and i can see the updates on my site

**Comment by valstu** [comment]
Most likely related issue #942

**Comment by boy-incerta** [comment]
At our company we are encountering the same issue. The polling for deployment was already taking longer for a few weeks (but never this long!) and since today regular time-outs on this polling.
![Schermafbeelding 2022-10-13 om 15 13 23](https://user-images.githubusercontent.com/97019812/195606122-98d93ea6-6b54-43e2-b11c-14ccc2aa9bbe.png)

**Comment by ksdaniel** [comment]
+1 

Having the same issue. No deploy possible for a couple of hours now.

`
Upload Timed Out. Unsure if deployment was successful or not.
`

No service issues in the portal, though.

**Comment by mjsprengers** [comment]
+1 Same issues. Although, after 3 retries, one deployment was successful.

**Comment by honeymustard** [comment]
Had the same issue today with a fairly new app, assumed it was intermittent. It worked occasionally though ..

**Comment by valstu** [comment]
Don't know what happened but one build seemed to work now.

**Comment by MaxWilson** [comment]
Came here to say the same thing. I have a fairly basic Azure SWA which has begun timing out intermittently during the deploy step. Example failure: https://github.com/MaxWilson/POCDungeonDraw/actions/runs/3246697020/jobs/5325750402

Typically, three or four runs fail in a row, and then an hour or so later the next build succeeds.

**Comment by adam-javelin** [comment]
Having the same issue. Here is my error log: https://pipelines.actions.githubusercontent.com/serviceHosts/583c118f-1d9a-4ddc-862e-67a8e673d75e/_apis/pipelines/1/runs/1258/signedlogcontent/2?urlExpires=2022-10-14T02%3A18%3A10.5877322Z&urlSigningMethod=HMACV1&urlSignature=r038Sm4waknUQMjEtil0wTBx4PKBWIYL0zNCGX16cV4%3D

![image](https://user-images.githubusercontent.com/79462674/195748451-a912268d-62ce-445a-a1d0-07ce6681aa5c.png)

**Comment by vivekjilla** [comment]
Hi everyone, sorry for the inconvenience caused. We identified the issue and working on the fix. Will update here once the issue is resolved.

**Comment by adam-javelin** [comment]
@vivekjilla I was finally able to build. Thank you!

**Comment by AscaL** [comment]
Solved, closing the issue. Thanks everyone.

Cheers

**Comment by camila-akqa** [comment]
@vivekjilla we are having same issue.

![image](https://user-images.githubusercontent.com/67367750/211975038-dc257a54-36aa-44b3-a54a-604847b0df26.png)

It timeouts uploading and the status on the Azure Static web app remains as "uploading "

![image](https://user-images.githubusercontent.com/67367750/211974831-b3c651bd-54b3-49e1-a212-38460b6e584c.png)

Would you be able to help us with this?

**Comment by dhyanikd** [comment]
Facing the time outs again

**Comment by xania** [comment]
> Solved, closing the issue. Thanks everyone.
> 
> Cheers

@vivekjilla solved how, 2026 still the same issue, consistent failure, even retry previously succesful deploys are now failing
