### ISSUE TITLE
Oryx version/tag in docker image

### ISSUE THREAD

**Issue by jochenjonc** [Azure/static-web-apps#955]
I would like to know when the Oryx version in the docker image that is used by the GitHub action is being updated. I've noticed that GitHub Action, which is relying on the mcr.microsoft.com/appsvc/staticappsclient:stable Docker image, is using Oryx [20220621.1](https://github.com/microsoft/Oryx/releases/tag/20220621.1).

`Oryx Version: 0.2.20220621.1, Commit: 82ed84f0f3fd3a25ded3029f137601f54e7a1d05, ReleaseTagName: 20220621.1`

But I'm actually waiting for a fix that was part of Oryx [20220718.1](https://github.com/microsoft/Oryx/releases/tag/20220718.1) and now a few months later I'm still waiting for this fix to make it to the Docker image.

**Comment by vivekjilla** [comment]
You should see new tag now. We updated our client. Thanks!
