### ISSUE TITLE
Nuxt 3 PWA - manifest.json replaced on build

### ISSUE THREAD

**Issue by AscaL** [Azure/static-web-apps#958]
Hi, I'm trying to deploy a SPA to SWA. I'm using Nuxt 3 with the Nitro preset `Azure`.
The issue is that my `manifest.json` file, which is correctly loaded in dev, seems to be replaced by oryx when building and deploying.
The file is found in the `.output/public` dir after running `pnpm buld`.
<img width="439" alt="image" src="https://user-images.githubusercontent.com/8880943/196954213-751870de-ab4d-4d6a-9f6d-1132b08c598a.png">

And here you can see it gets replaced (I think, not 100% sure):
<img width="251" alt="image" src="https://user-images.githubusercontent.com/8880943/196954917-02f4cccd-97c6-4353-9f69-59e995b51887.png">
<img width="487" alt="image" src="https://user-images.githubusercontent.com/8880943/196955091-8cd0d51a-2936-44b5-9dcd-4d208e582eed.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/8880943/196955182-f4b066d1-858f-4e13-9bab-435c272b0e87.png">

And I end up with this manifest:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/8880943/196955517-4360410b-79ba-4078-8498-b0d9f01219ad.png">
which seems to have some routes and imports inside, but nothing about my PWA
<img width="522" alt="image" src="https://user-images.githubusercontent.com/8880943/196955759-bd824739-6151-4bee-af41-3494c21858bc.png">

**Expected behavior**
Keep my manifest.json file for the PWA

**Comment by rupareddy5-21** [comment]
Hi @AscaL, sorry for the inconvenience caused. If you have already built your app before, can you try using [skip_app_build](https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=github-actions#skip-building-front-end-app) so that oryx won't build your app and replace your manifest file.

**Comment by AscaL** [comment]
Hi @rupareddy5-21 , thanks for the tip. I've tried but unsuccessfully. 

Upon further investigation I've discovered that the manifest deployed seems to be the one in `.output/server/functions/chunks/` instead of the one (that i expect) in `.output/public/`
I really do not know why

**Comment by AscaL** [comment]
Don't know how or why but it's working at the moment. Closing
