### ISSUE TITLE
Support Node 18

### ISSUE THREAD

**Issue by oldmanfleming** [Azure/static-web-apps#961]
**Is your feature request related to a problem? Please describe.**
Azure static-web-apps does not support Node 18 

**Describe the solution you'd like**
Azure static-web-apps should support Node 18. It is already current and will be LTS in 3 days.

**Describe alternatives you've considered**
Lower Node versions can be used for now.

**Additional context**
Most users wan't to develop on the same versions of tooling that is used in build environments. Many users use Node 18 and many more will once it becomes long term stable. This Action should support building with Node 18.

**Comment by johnnyreilly** [comment]
Would love to see this also https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/317

**Comment by Reshmi-Sriram** [comment]
Hi @oldmanfleming and @johnnyreilly,
The support work for Node 18 is in progress, please expect an announcement soon. Thanks! :)

**Comment by Reshmi-Sriram** [comment]
Node 18 support is now in Public preview -https://azure.microsoft.com/en-us/updates/public-preview-azure-static-web-apps-now-supports-node-18/
