### ISSUE TITLE
The Node.js version is wrong and not corresponding to the one configured in package.json

### ISSUE THREAD

**Issue by MiguelMinoldo** [Azure/static-web-apps#969]
Hello dear support,

I'm facing the following issue: When deploying the next.js app to the static app, it first picks the proper node version. On a next step (Starting to build function app with Oryx) it picks up an old version that is not working properly.

Steps to reproduce:
1. Fork the repo: https://github.com/MiguelMinoldo/xm-cloud-foundation
2. Deploy to Azure Static App (app_location: "/src/sxastarter")
4. See error:

![image](https://user-images.githubusercontent.com/14338387/198575033-dae7a4e2-0c62-42d5-9138-992b39786ee0.png)

- GitHub Actions workflow YAML file: https://github.com/MiguelMinoldo/xm-cloud-foundation/blob/main/.github/workflows/azure-static-web-apps-white-desert-00fe9d903.yml
- Source repository: https://github.com/MiguelMinoldo/xm-cloud-foundation

Thanks in advance!

**Comment by vivekjilla** [comment]
Hi @MiguelMinoldo the repo you specified is not accessible. But today we support node version 12, 14 and 16 for NextJS as it will be deployed as a managed function. Can you please make sure to choose one of those versions in package.json, for the build to pick it up correctly. For discussion on similar issue, please refer to https://github.com/Azure/static-web-apps/discussions/921#discussioncomment-3886942

**Comment by MiguelMinoldo** [comment]
Setting it to v16 fixed it. Thanks a lot!
