### ISSUE TITLE
Unable to deploy Next.js app to Static App: "Failed to deploy the Azure Functions"

### ISSUE THREAD

**Issue by MiguelMinoldo** [Azure/static-web-apps#971]
Hello dear support:

I'm trying to deploy my Next.js App to the Static App, it fails without any reason at the end of the deployment process.
Error message points to "Failed to deploy Azure functions"
 
```
Deployment Failed :(
Deployment Failure Reason: Failed to deploy the Azure Functions.
```

1. Go to Github and clone/fork: https://github.com/MiguelMinoldo/xm-cloud-foundation
2. Go to actions and run the Azure Static Web Apps CI/CD action
3. See error

- GitHub Actions or Azure Pipelines workflow YAML file: https://github.com/MiguelMinoldo/xm-cloud-foundation/blob/main/.github/workflows/azure-static-web-apps-white-desert-00fe9d903.yml
- source repository: https://github.com/MiguelMinoldo/xm-cloud-foundation

Please check the screenshot
![image](https://user-images.githubusercontent.com/14338387/199033484-c88e5195-8652-451f-b991-acaf447e9e95.png)

Thanks in advance

**Comment by vivekjilla** [comment]
@MiguelMinoldo are you passing `USERNAME` as an app setting for this app. Azure function is failing as USERNAME is not allowed appsetting name. Can you please check and see if you can remove or change it to some other name and try. Thanks!

**Comment by MiguelMinoldo** [comment]
Hi @vivekjilla, thanks for the quick reply. Unfortunately, I've removed this app setting but the issue persists, is there any way to check logs to know why the Azure function is failing?

Thanks!

**Comment by vivekjilla** [comment]
Hey @MiguelMinoldo I still see it's failing with same error for USERNAME. Can you please check once again if the app settings are removed from the portal as shown in the screenshot at https://learn.microsoft.com/en-us/azure/static-web-apps/application-settings#use-the-azure-portal

Sorry for the inconvenience wrt logs visibility. We're working on improving that feature but there's no way right now afaik.

**Comment by MiguelMinoldo** [comment]
Hi @vivekjilla, it worked now, thanks! Apologies for the misunderstansing I thought you were refering to the workflow yml file.
Thanks!
