### ISSUE TITLE
Question: .Net 7 Support for APIs?

### ISSUE THREAD

**Issue by jesseryoung** [Azure/static-web-apps#974]
I'm seeing some issues getting .NET 7 azure functions project running in Static Web Apps. [Azure Functions seems to support .NET 7](https://devblogs.microsoft.com/dotnet/dotnet-7-comes-to-azure-functions/) however I haven't been able to find any public documentation or GitHub issues that states that it should work with APIs in Azure Static Web Apps.

Before I do further troubleshooting, should .NET 7 APIs be working with SWAs right now?

**Comment by cmriachi** [comment]
Hello @jesseryoung, we are working on support for .NET 7 APIs with static web apps; expect an announcement coming soon. Thank you :)

**Comment by philvessey** [comment]
Hi @cmriachi  - is this close for deployment? Hitting similar issue with build logs stating only 3.1 and 6.0 are supported / available.

**Comment by thomasgauvin** [comment]
We announced support for .NET 7 here 🎉 https://azure.microsoft.com/en-us/updates/generally-available-azure-static-web-apps-now-fully-supports-net-7/
