### ISSUE TITLE
Azure Static Web App - Gatsby

### ISSUE THREAD

**Issue by zrodman** [Azure/static-web-apps#982]
I'm attempting to deploy Gatsby Static Web App via Azure Static Web App, although am encountering an issue deploying because of the version of Node.js use.

Is there any way to override this, or alter configuration to deploy successfully?

![image](https://user-images.githubusercontent.com/50938683/201243288-0c7fce85-cd67-475f-a90a-98882f37d7c1.png)

**Comment by vivekjilla** [comment]
@zrodman  you can specify the custom node version using the `engines` property in `package.json` More details at https://edi.wang/post/2022/1/27/how-to-specify-nodejs-version-when-building-azure-static-web-app

**Comment by zrodman** [comment]
Perfect. That worked!
