### ISSUE TITLE
Oryx ignoring app_build_command in react-native SWA

### ISSUE THREAD

**Issue by doctor-ew** [Azure/static-web-apps#987]
While we are working through a React Native legacy upgrade, we need to run `npx npm i --force && npx npm run build`. 

Up until 08 November, we were able to build our static web app with the app_build_command:

> app_build_command: 'npx npm i --force && npx npm run build'

Wondering if something changed in Oryx as this no longer is the case:

Went from

> 
> Using Node version:
> v16.18.0
> 
> Using Npm version:
> 8.19.2
> 
> Running 'npm install --unsafe-perm'...
>
> npm WARN using --force I sure hope you know what you are doing.
>

to:

> 
> Using Node version:
> v16.18.0
> 
> Using Npm version:
> 8.19.2
> 
> Running 'npm install --unsafe-perm'...
> 
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> 

Please advise!

**Comment by tipleavalentin** [comment]
Same issue here, instead of:
...
steps:
        with:
          node-version: '18.x'
      - run: npm install --no-package-lock --legacy-peer-deps
....
It runs "npm install --unsafe-perm"

**Comment by cormacpayne** [comment]
@doctor-ew @FullofQuarks @tipleavalentin -- Hey folks, sorry about the inconvenience here; if someone wouldn't mind, I could take a look at logs from a public GitHub Action workflow, or logs posted in a follow-up comment from an execution of the SWA Azure DevOps Task, and investigate why Oryx is failing when provided with this argument to the SWA action or task. If you have logs from a previously successful execution of an action or task (from > 7 days ago), that would be great to check out as well while we investigate the issue occurring here.

**Comment by doctor-ew** [comment]
@cormacpayne Here you go: https://www.doctorew.com/shuttlebay/logs_85.zip And Thank you for taking a look!

**Comment by davide-bergamini-sevenit** [comment]
There is the exact same problem in **GitLab**.
It was fixed on BitBucket last month:
[](https://bitbucket.org/microsoft/azure-static-web-apps-deploy/commits/3631f7b673a52603c38d1cdf36e9495cfbe9cb5c)

**Comment by cormacpayne** [comment]
@doctor-ew thanks for providing these logs -- if you are able to, would you mind trying the following: in you're app's `package.json` file, set the `engines.node` field to the following:

```json
{
  "name": "...",
  "version": "...",
  ...
  "engines": {
    "node": "14.x"
  }
}
```

The previous version of Static Web Apps was using node 14, and the default version being used now is node 16, which may be causing the issues you're seeing. This change to the `engines.node` field will force Oryx to use the latest version of node 14 supported, which, I'm hoping, will resolve the issue that you're facing.

**Comment by doctor-ew** [comment]
Oh yeah! @cormacpayne that worked! Thank you!!

**Comment by doctor-ew** [comment]
I take it back @cormacpayne -- was working till this evening! 

Last good build (2 hours ago): https://www.doctorew.com/shuttlebay/logs_115.zip

Failed build: https://www.doctorew.com/shuttlebay/logs_119.zip 

Please do your magic again!

**Comment by doctor-ew** [comment]
I tell a lie. Looks like this one is on us -- a bad package-lock.json cleanup broke the build.

We removed fsevent which was needed? But the code built and ran locally. So, ::shrug::
