### ISSUE TITLE
Failed to find a default file in the app artifacts folder (.next) for Hybrid next.js deployment to Azure Static App from Azure Pipelines

### ISSUE THREAD

**Issue by camila-akqa** [Azure/static-web-apps#993]
**Describe the bug**

I am getting the following error when trying to deploy a SSR-supported next.js application to Azure Static App from Azure Pipelines

![image](https://user-images.githubusercontent.com/67367750/202894977-5125aa3a-e893-432b-8a3b-9cc0ba5527be.png)

The structure of the project is very straight forward , the package.json file is on the root folder, the .next folder gets generated under the root folder as well , the folders inside the root look like the image below, please notice that the pages folder sits under /src/pages:

![image](https://user-images.githubusercontent.com/67367750/202895017-6fd7be77-0abf-410e-ba45-6a681a448252.png)

I added a buildAz task, so to create an empty node_modules under the generated .next folder after the build, following the approach detailed on this [thread](https://github.com/Azure/static-web-apps/discussions/921#discussioncomment-4045378), but the issue seems unrelated: 

This is how the azure pipelines looks like:
![image](https://user-images.githubusercontent.com/67367750/202895076-16343b23-b4e1-4f0f-b65f-04c6bdfd1ce7.png)

**Expected behavior**

Being able to deploy to Azure Static Web apps our existing next.js project without losing the SSR capabilities of next.js as it is now supported  https://aka.ms/swa-nextjs-ssr-blog

**Comment by vivekjilla** [comment]
@camila-akqa Thanks for sharing the logs and package.json. 

As you don't want the `html export` feature of the NextJS, can you please remove the `&& next export` from the `build` command in your package.json and try again.

Please let me know if it helps. Thanks!

**Comment by camila-akqa** [comment]
Hi @vivekjilla 

Thanks again for looking into this. I am already doing that, so in Az Pipelines I've these field:

```
app_build_command: 'yarn **buildAz**'
is_static_export: false
api_location: "" 
output_location: ""
```

and In the package.json I've defined a task that looks like next: 

`"buildAz": "cross-env IGNORE_TYPESCRIPT_ERRORS=true next build --no-lint",`

Please notice that I tried deploying the same project as static, eg. including "&& next export" in the build command and with the following fields in Azure pipelines , and the site is deployed correctly:

```
is_static_export: true
api_location: "" 
output_location: "out"
```

I've made some changes since the last time I posted last message (eg. reducing the size of the node_modules) , so I can reattach the logs if needed. 

Really appreciate all help you can provide! thanks. 
Camila

**Comment by camila-akqa** [comment]
Oh @vivekjilla 

I actually changed had this 2 tasks on my package.json

```
 "build": "yarn generate && cross-env IGNORE_TYPESCRIPT_ERRORS=true next build --no-lint && next export",
    "buildAz": "yarn generate && cross-env IGNORE_TYPESCRIPT_ERRORS=true next build --no-lint",
```

After your previous comment I anyway changed to be 

```
"build": "cross-env IGNORE_TYPESCRIPT_ERRORS=true next build --no-lint",
    "buildStatic": "yarn generate && cross-env IGNORE_TYPESCRIPT_ERRORS=true next build --no-lint && next export",
```

And updated the pipeline to use yarn build instead of yarn buildAz, eg:

`app_build_command: 'yarn build'`

And it is now working!!!!!!!

Thanks a lot for your help!!
